// файл генерируется автоматически скриптом protected/maintenance/export_consts_to_js.pl
;window.CONSTS = {};var ADDRESS_STREET_PREFIXES = window.CONSTS.ADDRESS_STREET_PREFIXES = "",
    ALLOW_BANNER_LETTERS = window.CONSTS.ALLOW_BANNER_LETTERS = "abcdefghijklmonpqrstuvwxyzABCDEFGHIJKLMONPQRSTUVWXYZабвгдеёжзийклмнопрстуфхцчшщъыьэюяАБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯЄЇєїҐґ'Ўў'ІіҰҒғӨҢҚҺҮұөңқһүҖҲҳҗӘәÄäßẞğĞşŞçÇıİ̇âÂîÎûÛéüÜöÖʻҲҳʼÁáÀàẢảÃãẠạĂăẮắẰằẲẳẴẵẶặẤấẦầẨẩẪẫẬậĐđÉÈèẺẻẼẽẸẹÊêẾếỀềỂểỄễỆệÍíÌìỈỉĨĩỊịÓóÒòỎỏÕõỌọÔôỐốỒồỔổỖỗỘộƠơỚớỜờỞởỠỡỢợÚúÙùỦủŨũỤụƯưỨứỪừỬửỮữỰựÝýỲỳỶỷỸỹỴỵáéíñóúÁÉÍÑÓÚáàâãéèêíïóôõöúçñÁÀÂÃÉÈÊÍÏÓÔÕÖÚÇÑáčďéěíňóřšťúůýžÁČĎÉĚÍŇÓŘŠŤÚŮÝŽąćęłńóśźżĄĆĘŁŃÓŚŹŻ\\[\\]0123456789.-+,. \"¡!¿?\\()%$€;:/&'*_=#№«» –—−™®©’°⁰¹²³⁴⁵⁶⁷⁸⁹₽",
    ALLOW_LETTERS = window.CONSTS.ALLOW_LETTERS = "abcdefghijklmonpqrstuvwxyzABCDEFGHIJKLMONPQRSTUVWXYZабвгдеёжзийклмнопрстуфхцчшщъыьэюяАБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯЄЇєїҐґ'Ўў'ІіҰҒғӨҢҚҺҮұөңқһүҖҲҳҗӘәÄäßẞğĞşŞçÇıİ̇âÂîÎûÛéüÜöÖʻҲҳʼÁáÀàẢảÃãẠạĂăẮắẰằẲẳẴẵẶặẤấẦầẨẩẪẫẬậĐđÉÈèẺẻẼẽẸẹÊêẾếỀềỂểỄễỆệÍíÌìỈỉĨĩỊịÓóÒòỎỏÕõỌọÔôỐốỒồỔổỖỗỘộƠơỚớỜờỞởỠỡỢợÚúÙùỦủŨũỤụƯưỨứỪừỬửỮữỰựÝýỲỳỶỷỸỹỴỵáéíñóúÁÉÍÑÓÚáàâãéèêíïóôõöúçñÁÀÂÃÉÈÊÍÏÓÔÕÖÚÇÑáčďéěíňóřšťúůýžÁČĎÉĚÍŇÓŘŠŤÚŮÝŽąćęłńóśźżĄĆĘŁŃÓŚŹŻ\\[\\]0123456789.",
    AUDIO_GOALS_AUDITORY_TYPES = window.CONSTS.AUDIO_GOALS_AUDITORY_TYPES = [
        "start",
        "first_quartile",
        "midpoint",
        "third_quartile",
        "complete"
    ],
    BANNER_TYPE_MULTIPLIER_TYPES = window.CONSTS.BANNER_TYPE_MULTIPLIER_TYPES = [
        "cpm_banner"
    ],
    BEL_NATIVE_LETTERS = window.CONSTS.BEL_NATIVE_LETTERS = "Ўў",
    BRAND_SURVEY_BUDGET_THRESHOLD = window.CONSTS.BRAND_SURVEY_BUDGET_THRESHOLD = 0,
    BRAND_SURVEY_BUDGET_THRESHOLD_DAILY = window.CONSTS.BRAND_SURVEY_BUDGET_THRESHOLD_DAILY = 0,
    BSAUCTION_PLACE_LAYOUT = window.CONSTS.BSAUCTION_PLACE_LAYOUT = {
        "10" : {
            "index" : 0,
            "type" : "premium"
        },
        "11" : {
            "index" : 1,
            "type" : "premium"
        },
        "12" : {
            "index" : 2,
            "type" : "premium"
        },
        "13" : {
            "index" : 3,
            "type" : "premium"
        },
        "20" : {
            "index" : 0,
            "type" : "guarantee"
        },
        "21" : {
            "index" : 1,
            "type" : "guarantee"
        },
        "22" : {
            "index" : 2,
            "type" : "guarantee"
        },
        "23" : {
            "index" : 3,
            "type" : "guarantee"
        }
    },
    BS_EXT_PHRASE_SINCE_DATE = window.CONSTS.BS_EXT_PHRASE_SINCE_DATE = 20160515,
    BS_SEARCH_QUERIES_LAST_DAYS = window.CONSTS.BS_SEARCH_QUERIES_LAST_DAYS = 180,
    BS_SEARCH_QUERIES_SINCE_DATE = window.CONSTS.BS_SEARCH_QUERIES_SINCE_DATE = 20160723,
    BUSINESS_TYPES = window.CONSTS.BUSINESS_TYPES = {
        "auto" : {
            "name" : "Автомобили",
            "value" : "auto"
        },
        "flights" : {
            "name" : "Авиабилеты",
            "value" : "avia"
        },
        "hotels" : {
            "name" : "Отели",
            "value" : "hotels"
        },
        "news" : {
            "name" : "Новости",
            "value" : "news"
        },
        "other" : {
            "name" : "Другой бизнес",
            "value" : "other"
        },
        "pharm" : {
            "name" : "Фармацевтика",
            "value" : "pharm"
        },
        "realty" : {
            "name" : "Недвижимость",
            "vale" : "realty"
        },
        "retail" : {
            "name" : "Розничная торговля",
            "value" : "retail"
        }
    },
    CAMPAIGN_MINUS_WORDS_LIMIT = window.CONSTS.CAMPAIGN_MINUS_WORDS_LIMIT = 20000,
    DEFAULT_AUTOBUDGET = window.CONSTS.DEFAULT_AUTOBUDGET = 50,
    DEFAULT_CREATIVE_COUNT_LIMIT = window.CONSTS.DEFAULT_CREATIVE_COUNT_LIMIT = 50,
    DEMOGRAPHY_MULTIPLIER_AGES = window.CONSTS.DEMOGRAPHY_MULTIPLIER_AGES = [
        "0-17",
        "18-24",
        "25-34",
        "35-44",
        "45-54",
        "55-",
        "45-",
        "unknown"
    ],
    DEMOGRAPHY_MULTIPLIER_GENDERS = window.CONSTS.DEMOGRAPHY_MULTIPLIER_GENDERS = [
        "male",
        "female"
    ],
    DE_NATIVE_LETTERS = window.CONSTS.DE_NATIVE_LETTERS = "Ääßẞ",
    ENGAGED_SESSION_GOAL_ID = window.CONSTS.ENGAGED_SESSION_GOAL_ID = 12,
    ENTRY_PLACES = window.CONSTS.ENTRY_PLACES = {
        "GUARANTEE" : 23,
        "PREMIUM" : 13
    },
    GOALS_MAX_NUM = window.CONSTS.GOALS_MAX_NUM = 10,
    GROUP_MINUS_WORDS_LIMIT = window.CONSTS.GROUP_MINUS_WORDS_LIMIT = 4096,
    INDOOR_GOALS_AUDITORY_TYPES = window.CONSTS.INDOOR_GOALS_AUDITORY_TYPES = [
        "start"
    ],
    INVENTORY_MULTIPLIER_TYPES = window.CONSTS.INVENTORY_MULTIPLIER_TYPES = [
        "instream_web",
        "inpage",
        "interstitial",
        "inbanner",
        "rewarded"
    ],
    KAZ_LETTERS = window.CONSTS.KAZ_LETTERS = "ҰҒғӨҢҚҺҮұөңқһүҖҲҳҗӘә",
    MAX_AUTOBUDGET = window.CONSTS.MAX_AUTOBUDGET = 10000000,
    MAX_AUTOBUDGET_BID = window.CONSTS.MAX_AUTOBUDGET_BID = 840,
    MAX_AUTOBUDGET_CLICKS_BUNDLE = window.CONSTS.MAX_AUTOBUDGET_CLICKS_BUNDLE = 1000000000,
    MAX_BODY_LENGTH = window.CONSTS.MAX_BODY_LENGTH = 81,
    MAX_BODY_LENGTH_CONTENT_PROMOTION = window.CONSTS.MAX_BODY_LENGTH_CONTENT_PROMOTION = 200,
    MAX_BODY_LENGTH_MOBILE = window.CONSTS.MAX_BODY_LENGTH_MOBILE = 75,
    MAX_BODY_UNINTERRUPTED_LENGTH = window.CONSTS.MAX_BODY_UNINTERRUPTED_LENGTH = 23,
    MAX_CALLOUTS_COUNT_ON_BANNER = window.CONSTS.MAX_CALLOUTS_COUNT_ON_BANNER = 50,
    MAX_CALLOUT_LENGTH = window.CONSTS.MAX_CALLOUT_LENGTH = 25,
    MAX_CALLOUT_LENGTH_ON_BANNER = window.CONSTS.MAX_CALLOUT_LENGTH_ON_BANNER = 66,
    MAX_DISPLAY_HREF_LENGTH = window.CONSTS.MAX_DISPLAY_HREF_LENGTH = 20,
    MAX_DOMAIN_LENGTH = window.CONSTS.MAX_DOMAIN_LENGTH = 35,
    MAX_MONEY_WARNING_VALUE = window.CONSTS.MAX_MONEY_WARNING_VALUE = 50,
    MAX_NUMBER_OF_NARROW_CHARACTERS = window.CONSTS.MAX_NUMBER_OF_NARROW_CHARACTERS = 15,
    MAX_OPEN_FOR_EDIT_BANNERS = window.CONSTS.MAX_OPEN_FOR_EDIT_BANNERS = 500,
    MAX_PHRASE_LENGTH = window.CONSTS.MAX_PHRASE_LENGTH = 4096,
    MAX_PHRASE_RANK_WARNING = window.CONSTS.MAX_PHRASE_RANK_WARNING = 7000,
    MAX_PRICE = window.CONSTS.MAX_PRICE = 840,
    MAX_RETARGETINGS_ON_CLIENT = window.CONSTS.MAX_RETARGETINGS_ON_CLIENT = 2000,
    MAX_RETARGETING_GOALS_IN_GROUP = window.CONSTS.MAX_RETARGETING_GOALS_IN_GROUP = 250,
    MAX_RETARGETING_GOAL_TIME_DAYS = window.CONSTS.MAX_RETARGETING_GOAL_TIME_DAYS = 90,
    MAX_RETARGETING_GROUPS = window.CONSTS.MAX_RETARGETING_GROUPS = 50,
    MAX_RF = window.CONSTS.MAX_RF = 1000,
    MAX_RF_RESET = window.CONSTS.MAX_RF_RESET = 30,
    MAX_TAGS_FOR_BANNER = window.CONSTS.MAX_TAGS_FOR_BANNER = 30,
    MAX_TAGS_FOR_CAMPAIGN = window.CONSTS.MAX_TAGS_FOR_CAMPAIGN = 200,
    MAX_TAG_LENGTH = window.CONSTS.MAX_TAG_LENGTH = 25,
    MAX_TITLE_EXTENSION_LENGTH = window.CONSTS.MAX_TITLE_EXTENSION_LENGTH = 30,
    MAX_TITLE_LENGTH = window.CONSTS.MAX_TITLE_LENGTH = 35,
    MAX_TITLE_LENGTH_CONTENT_PROMOTION = window.CONSTS.MAX_TITLE_LENGTH_CONTENT_PROMOTION = 200,
    MAX_TITLE_LENGTH_MOBILE = window.CONSTS.MAX_TITLE_LENGTH_MOBILE = 35,
    MAX_TITLE_UNINTERRUPTED_LENGTH = window.CONSTS.MAX_TITLE_UNINTERRUPTED_LENGTH = 22,
    MAX_URL_LENGTH = window.CONSTS.MAX_URL_LENGTH = 1024,
    MAX_WORDS_IN_KEYPHRASE = window.CONSTS.MAX_WORDS_IN_KEYPHRASE = 7,
    MAX_WORD_LENGTH = window.CONSTS.MAX_WORD_LENGTH = 35,
    MEANINGFUL_GOALS_OPTIMIZATION_GOAL_ID = window.CONSTS.MEANINGFUL_GOALS_OPTIMIZATION_GOAL_ID = 13,
    MIN_AUTOBUDGET = window.CONSTS.MIN_AUTOBUDGET = 10,
    MIN_AUTOBUDGET_AVG_CPA = window.CONSTS.MIN_AUTOBUDGET_AVG_CPA = 0.03,
    MIN_AUTOBUDGET_AVG_CPI = window.CONSTS.MIN_AUTOBUDGET_AVG_CPI = 0.03,
    MIN_AUTOBUDGET_AVG_PRICE = window.CONSTS.MIN_AUTOBUDGET_AVG_PRICE = 0.03,
    MIN_AUTOBUDGET_BID = window.CONSTS.MIN_AUTOBUDGET_BID = 0.01,
    MIN_AUTOBUDGET_CLICKS_BUNDLE = window.CONSTS.MIN_AUTOBUDGET_CLICKS_BUNDLE = 100,
    MIN_GOALS_ON_CAMPAIGN = window.CONSTS.MIN_GOALS_ON_CAMPAIGN = 40,
    MIN_PHRASE_RANK_WARNING = window.CONSTS.MIN_PHRASE_RANK_WARNING = 2,
    MIN_PRICE = window.CONSTS.MIN_PRICE = 0.01,
    MOBILE_MULTIPLIER_OS_TYPES = window.CONSTS.MOBILE_MULTIPLIER_OS_TYPES = [
        "ios",
        "android"
    ],
    MOBILE_OS_VERSIONS = window.CONSTS.MOBILE_OS_VERSIONS = {
        "Android" : [
            1.0,
            1.1,
            1.5,
            1.6,
            2.0,
            2.1,
            2.2,
            2.3,
            3.0,
            3.1,
            3.2,
            4.0,
            4.1,
            4.2,
            4.3,
            4.4,
            5.0,
            5.1,
            6.0,
            7.0,
            7.1,
            8.0,
            8.1,
            9.0,
            10.0,
            11.0
        ],
        "iOS" : [
            1.0,
            2.0,
            3.0,
            3.1,
            4.0,
            4.1,
            4.2,
            5.0,
            5.1,
            6.0,
            6.1,
            7.0,
            7.1,
            8.0,
            8.1,
            8.2,
            8.3,
            8.4,
            9.0,
            9.1,
            9.2,
            9.3,
            10.0,
            10.1,
            10.2,
            10.3,
            11.0,
            11.1,
            11.2,
            11.3,
            11.4,
            12.0,
            12.1,
            12.2,
            12.3,
            12.4,
            13.0,
            13.1,
            13.2,
            13.3,
            13.4,
            13.5,
            13.6,
            13.7,
            14.0,
            14.1
        ]
    },
    NARROW_SYMBOLS = window.CONSTS.NARROW_SYMBOLS = ".,!:;\"",
    NEWS_ARCHIVE_URL = window.CONSTS.NEWS_ARCHIVE_URL = "https://yandex.<tld>/adv/news?tag=<tag>",
    NEW_MAX_TITLE_LENGTH = window.CONSTS.NEW_MAX_TITLE_LENGTH = 56,
    NEW_MAX_TITLE_LENGTH_MOBILE = window.CONSTS.NEW_MAX_TITLE_LENGTH_MOBILE = 56,
    ONE_SITELINK_DESC_MAX_LENGTH = window.CONSTS.ONE_SITELINK_DESC_MAX_LENGTH = 60,
    ONE_SITELINK_MAX_LENGTH = window.CONSTS.ONE_SITELINK_MAX_LENGTH = 30,
    OPENSTAT_LABEL = window.CONSTS.OPENSTAT_LABEL = "dGVzdDsxOzE7",
    OUTDOOR_GOALS_AUDITORY_TYPES = window.CONSTS.OUTDOOR_GOALS_AUDITORY_TYPES = [
        "start"
    ],
    PAY_FOR_CONVERSION_AVG_CPA_WARNING_RATIO_DEFAULT_VALUE = window.CONSTS.PAY_FOR_CONVERSION_AVG_CPA_WARNING_RATIO_DEFAULT_VALUE = 3,
    PAY_FOR_CONVERSION_SUM_TO_AVG_CPA_MIN_RATIO = window.CONSTS.PAY_FOR_CONVERSION_SUM_TO_AVG_CPA_MIN_RATIO = 20,
    POSITION_CTR_CORRECTION_BY_PLACE = window.CONSTS.POSITION_CTR_CORRECTION_BY_PLACE = {
        "10" : 100,
        "11" : 85,
        "12" : 73,
        "13" : 62,
        "20" : 9,
        "21" : 7,
        "22" : 7,
        "23" : 5
    },
    PRICE_PLACES = window.CONSTS.PRICE_PLACES = {
        "FIRST" : 2,
        "GARANT" : 1,
        "GUARANTEE1" : 20,
        "GUARANTEE2" : 21,
        "GUARANTEE3" : 22,
        "GUARANTEE4" : 23,
        "PREMIUM" : 3,
        "PREMIUM1" : 10,
        "PREMIUM2" : 11,
        "PREMIUM3" : 12,
        "PREMIUM4" : 13,
        "ROTATION" : 0
    },
    RECOMMENDATION_SUM_MAX = window.CONSTS.RECOMMENDATION_SUM_MAX = 0,
    RECOMMENDATION_SUM_MID = window.CONSTS.RECOMMENDATION_SUM_MID = 0,
    RECOMMENDATION_SUM_MIN = window.CONSTS.RECOMMENDATION_SUM_MIN = 0,
    RECOMMENDATION_SUM_WARN = window.CONSTS.RECOMMENDATION_SUM_WARN = 0,
    ROLE_NAMES = window.CONSTS.ROLE_NAMES = {
        "agency" : "агентство",
        "client" : "клиент",
        "internal_ad_admin" : "администратор внутренней рекламы",
        "internal_ad_manager" : "менеджер внутренней рекламы",
        "internal_ad_superreader" : "суперсмотритель внутренней рекламы",
        "limited_support" : "саппорт с ограниченным доступом",
        "manager" : "менеджер",
        "media" : "медиапланер",
        "placer" : "вешальщик",
        "subclient" : "субклиент",
        "super" : "супер-пользователь",
        "superreader" : "суперсмотритель",
        "supersubclient" : "супер-субклиент",
        "superteamleader" : "начальник отдела",
        "support" : "саппорт",
        "teamleader" : "тимлидер"
    },
    RUS_LETTERS = window.CONSTS.RUS_LETTERS = "абвгдеёжзийклмнопрстуфхцчшщъыьэюяАБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ",
    SITELINKS_MAX_LENGTH = window.CONSTS.SITELINKS_MAX_LENGTH = 66,
    SITELINKS_NUMBER = window.CONSTS.SITELINKS_NUMBER = 4,
    TR_NATIVE_LETTERS = window.CONSTS.TR_NATIVE_LETTERS = "ğĞşŞçÇıİ̇âÂîÎûÛé",
    UKR_NATIVE_LETTERS = window.CONSTS.UKR_NATIVE_LETTERS = "ЄЇєїҐґ",
    VIDEO_GOALS_AUDITORY_TYPES = window.CONSTS.VIDEO_GOALS_AUDITORY_TYPES = [
        "start",
        "first_quartile",
        "midpoint",
        "third_quartile",
        "complete"
    ],
    WEATHER_MULTIPLIER_CONDITION_TYPES = window.CONSTS.WEATHER_MULTIPLIER_CONDITION_TYPES = [
        "temp",
        "cloudness",
        "prec_type",
        "prec_strength"
    ],
    WEATHER_MULTIPLIER_CONSTRAINTS = window.CONSTS.WEATHER_MULTIPLIER_CONSTRAINTS = {
        "cloudness" : {
            "values" : [
                0,
                25,
                50,
                75,
                100
            ]
        },
        "prec_strength" : {
            "values" : [
                0,
                25,
                50,
                75,
                100
            ]
        },
        "prec_type" : {
            "values" : [
                0,
                1,
                3
            ]
        },
        "temp" : {
            "range" : [
                "-50",
                50
            ]
        }
    },
    WEATHER_MULTIPLIER_MAX_CONDITION_COUNT = window.CONSTS.WEATHER_MULTIPLIER_MAX_CONDITION_COUNT = 20,
    currencies = window.CONSTS.currencies = {
        "BYN" : {
            "AUCTION_STEP" : 0.01,
            "AUTOBUDGET_AVG_CPA_WARNING" : 940,
            "AUTOBUDGET_AVG_PRICE_WARNING" : 9,
            "AUTOBUDGET_CLICKS_BUNDLE_WARNING" : 10000000,
            "AUTOBUDGET_MAX_PRICE_WARNING" : 9,
            "AUTOBUDGET_PAY_FOR_CONVERSION_AVG_CPA_WARNING" : 160,
            "AUTOBUDGET_PAY_FOR_CONVERSION_AVG_CPA_WARNING_INCREASED" : 480,
            "AUTOBUDGET_SUM_WARNING" : 31000,
            "BALANCE_CURRENCY_NAME" : "BYN",
            "BIG_RATE" : 9,
            "BRAND_SURVEY_BUDGET_THRESHOLD" : 8500,
            "BRAND_SURVEY_BUDGET_THRESHOLD_DAILY" : 584,
            "DEFAULT_AUTOBUDGET" : 47,
            "DEFAULT_AVG_CPV" : 0.07,
            "DEFAULT_CPM_PRICE" : 3.5,
            "DEFAULT_PRICE" : 0.1,
            "DIRECT_DEFAULT_PAY" : 47,
            "ISO_NUM_CODE" : 933,
            "LIST_ORDER" : 6,
            "MAX_AUTOBUDGET" : 9400000,
            "MAX_AUTOBUDGET_BID" : 780,
            "MAX_AUTOBUDGET_CLICKS_BUNDLE" : 940000000,
            "MAX_AUTOPAY_CARD" : null,
            "MAX_AUTOPAY_REMAINING" : null,
            "MAX_AUTOPAY_YAMONEY" : null,
            "MAX_AVG_CPV" : 0.2,
            "MAX_CLIENT_ARCHIVE" : 100,
            "MAX_CPM_PRICE" : 100,
            "MAX_DAILY_BUDGET_AMOUNT" : 1000000000,
            "MAX_DAILY_BUDGET_FOR_PERIOD" : 100000000,
            "MAX_PRICE" : 780,
            "MAX_SHOW_BID" : 158,
            "MAX_TOPAY_SUGGEST" : 470,
            "MIDDLE_AVG_CPV" : 0.12,
            "MIN_AUTOBUDGET" : 9,
            "MIN_AUTOBUDGET_AVG_CPA" : 0.03,
            "MIN_AUTOBUDGET_AVG_CPM" : 0.15,
            "MIN_AUTOBUDGET_AVG_PRICE" : 0.03,
            "MIN_AUTOBUDGET_BID" : 0.01,
            "MIN_AUTOBUDGET_CLICKS_BUNDLE" : 100,
            "MIN_AUTOPAY" : null,
            "MIN_AVG_CPV" : 0.01,
            "MIN_CPC_CPA_PERFORMANCE" : 0.03,
            "MIN_CPM_FRONTPAGE_PRICE" : 0.78,
            "MIN_CPM_PRICE" : 0.15,
            "MIN_DAILY_BUDGET_FOR_PERIOD" : 9,
            "MIN_DAY_BUDGET" : 9,
            "MIN_IMAGE_PRICE" : 0.01,
            "MIN_PAY" : 30,
            "MIN_PRICE" : 0.01,
            "MIN_PRICE_FOR_MFA" : 0.05,
            "MIN_SUM_INTERPRETE_AS_PAYMENT" : 9,
            "MIN_TRANSFER_MONEY" : 30,
            "MIN_WALLET_DAY_BUDGET" : 30,
            "MONEYMETER_MAX_MIDDLE_SUM" : null,
            "MONEYMETER_MIDDLE_PRICE_MIN" : null,
            "MONEYMETER_TYPICAL_MIDDLE_SUM_INTERVAL_BEGIN" : null,
            "MONEYMETER_TYPICAL_MIDDLE_SUM_INTERVAL_END" : null,
            "MONEY_OUT_LIMIT" : 1,
            "PAY_FOR_CONVERSION_MIN_RESERVED_SUM_DEFAULT_VALUE" : 170,
            "PAY_WITH_CASH_LIMIT" : 0,
            "PRECISION_DIGIT_COUNT" : 4,
            "RECOMMENDATION_SUM_MAX" : 1000,
            "RECOMMENDATION_SUM_MID" : 400,
            "RECOMMENDATION_SUM_MIN" : 150,
            "RECOMMENDATION_SUM_WARN" : 0,
            "RECOMMENDED_SUM_TO_PAY" : 120,
            "TOUCH_WEEK_BUDGET_SUM_FIRST" : 42,
            "TOUCH_WEEK_BUDGET_SUM_SECOND" : 69,
            "TOUCH_WEEK_BUDGET_SUM_THIRD" : 103,
            "UC_DEFAULT_CONVERSION_VALUE" : 5,
            "UC_DEFAULT_WEEK_BUDGET" : 75,
            "YABS_RATIO" : 100,
            "currency_sign" : "Br",
            "full_name" : "белорусские рубли",
            "name" : "BYN"
        },
        "CHF" : {
            "AUCTION_STEP" : 0.01,
            "AUTOBUDGET_AVG_CPA_WARNING" : 1000,
            "AUTOBUDGET_AVG_PRICE_WARNING" : 10,
            "AUTOBUDGET_CLICKS_BUNDLE_WARNING" : 10000000,
            "AUTOBUDGET_MAX_PRICE_WARNING" : 10,
            "AUTOBUDGET_PAY_FOR_CONVERSION_AVG_CPA_WARNING" : 170,
            "AUTOBUDGET_PAY_FOR_CONVERSION_AVG_CPA_WARNING_INCREASED" : 510,
            "AUTOBUDGET_SUM_WARNING" : 34000,
            "BALANCE_CURRENCY_NAME" : "CHF",
            "BIG_RATE" : 10,
            "BRAND_SURVEY_BUDGET_THRESHOLD" : 0,
            "BRAND_SURVEY_BUDGET_THRESHOLD_DAILY" : 0,
            "DEFAULT_AUTOBUDGET" : 50,
            "DEFAULT_AVG_CPV" : 0.07,
            "DEFAULT_CPM_PRICE" : 1.5,
            "DEFAULT_PRICE" : 0.1,
            "DIRECT_DEFAULT_PAY" : 50,
            "ISO_NUM_CODE" : 756,
            "LIST_ORDER" : 8,
            "MAX_AUTOBUDGET" : 10000000,
            "MAX_AUTOBUDGET_BID" : 600,
            "MAX_AUTOBUDGET_CLICKS_BUNDLE" : 1000000000,
            "MAX_AUTOPAY_CARD" : null,
            "MAX_AUTOPAY_REMAINING" : null,
            "MAX_AUTOPAY_YAMONEY" : null,
            "MAX_AVG_CPV" : 0.2,
            "MAX_CLIENT_ARCHIVE" : 100,
            "MAX_CPM_PRICE" : 50,
            "MAX_DAILY_BUDGET_AMOUNT" : 1000000000,
            "MAX_DAILY_BUDGET_FOR_PERIOD" : 100000000,
            "MAX_PRICE" : 600,
            "MAX_SHOW_BID" : 120,
            "MAX_TOPAY_SUGGEST" : 500,
            "MIDDLE_AVG_CPV" : 0.12,
            "MIN_AUTOBUDGET" : 10,
            "MIN_AUTOBUDGET_AVG_CPA" : 0.03,
            "MIN_AUTOBUDGET_AVG_CPM" : 0.08,
            "MIN_AUTOBUDGET_AVG_PRICE" : 0.03,
            "MIN_AUTOBUDGET_BID" : 0.01,
            "MIN_AUTOBUDGET_CLICKS_BUNDLE" : 100,
            "MIN_AUTOPAY" : null,
            "MIN_AVG_CPV" : 0.01,
            "MIN_CPC_CPA_PERFORMANCE" : 0.03,
            "MIN_CPM_FRONTPAGE_PRICE" : 0.35,
            "MIN_CPM_PRICE" : 0.08,
            "MIN_DAILY_BUDGET_FOR_PERIOD" : 5,
            "MIN_DAY_BUDGET" : 10,
            "MIN_IMAGE_PRICE" : 0.01,
            "MIN_PAY" : 15,
            "MIN_PRICE" : 0.01,
            "MIN_PRICE_FOR_MFA" : 0.05,
            "MIN_SUM_INTERPRETE_AS_PAYMENT" : 10,
            "MIN_TRANSFER_MONEY" : 15,
            "MIN_WALLET_DAY_BUDGET" : 15,
            "MONEYMETER_MAX_MIDDLE_SUM" : 400,
            "MONEYMETER_MIDDLE_PRICE_MIN" : 5,
            "MONEYMETER_TYPICAL_MIDDLE_SUM_INTERVAL_BEGIN" : 20,
            "MONEYMETER_TYPICAL_MIDDLE_SUM_INTERVAL_END" : 40,
            "MONEY_OUT_LIMIT" : 0.1,
            "PAY_FOR_CONVERSION_MIN_RESERVED_SUM_DEFAULT_VALUE" : 0,
            "PAY_WITH_CASH_LIMIT" : 0,
            "PRECISION_DIGIT_COUNT" : 6,
            "RECOMMENDATION_SUM_MAX" : 500,
            "RECOMMENDATION_SUM_MID" : 200,
            "RECOMMENDATION_SUM_MIN" : 80,
            "RECOMMENDATION_SUM_WARN" : 0,
            "RECOMMENDED_SUM_TO_PAY" : 150,
            "TOUCH_WEEK_BUDGET_SUM_FIRST" : 20,
            "TOUCH_WEEK_BUDGET_SUM_SECOND" : 31,
            "TOUCH_WEEK_BUDGET_SUM_THIRD" : 47,
            "UC_DEFAULT_CONVERSION_VALUE" : 1,
            "UC_DEFAULT_WEEK_BUDGET" : 30,
            "YABS_RATIO" : 1,
            "currency_sign" : "₣",
            "full_name" : "швейцарские франки",
            "name" : "CHF"
        },
        "EUR" : {
            "AUCTION_STEP" : 0.01,
            "AUTOBUDGET_AVG_CPA_WARNING" : 1000,
            "AUTOBUDGET_AVG_PRICE_WARNING" : 10,
            "AUTOBUDGET_CLICKS_BUNDLE_WARNING" : 10000000,
            "AUTOBUDGET_MAX_PRICE_WARNING" : 10,
            "AUTOBUDGET_PAY_FOR_CONVERSION_AVG_CPA_WARNING" : 170,
            "AUTOBUDGET_PAY_FOR_CONVERSION_AVG_CPA_WARNING_INCREASED" : 510,
            "AUTOBUDGET_SUM_WARNING" : 34000,
            "BALANCE_CURRENCY_NAME" : "EUR",
            "BIG_RATE" : 10,
            "BRAND_SURVEY_BUDGET_THRESHOLD" : 7000,
            "BRAND_SURVEY_BUDGET_THRESHOLD_DAILY" : 490,
            "DEFAULT_AUTOBUDGET" : 50,
            "DEFAULT_AVG_CPV" : 0.07,
            "DEFAULT_CPM_PRICE" : 1.5,
            "DEFAULT_PRICE" : 0.1,
            "DIRECT_DEFAULT_PAY" : 50,
            "ISO_NUM_CODE" : 978,
            "LIST_ORDER" : 5,
            "MAX_AUTOBUDGET" : 10000000,
            "MAX_AUTOBUDGET_BID" : 500,
            "MAX_AUTOBUDGET_CLICKS_BUNDLE" : 1000000000,
            "MAX_AUTOPAY_CARD" : null,
            "MAX_AUTOPAY_REMAINING" : null,
            "MAX_AUTOPAY_YAMONEY" : null,
            "MAX_AVG_CPV" : 0.2,
            "MAX_CLIENT_ARCHIVE" : 100,
            "MAX_CPM_PRICE" : 44,
            "MAX_DAILY_BUDGET_AMOUNT" : 1000000000,
            "MAX_DAILY_BUDGET_FOR_PERIOD" : 100000000,
            "MAX_PRICE" : 500,
            "MAX_SHOW_BID" : 100,
            "MAX_TOPAY_SUGGEST" : 500,
            "MIDDLE_AVG_CPV" : 0.12,
            "MIN_AUTOBUDGET" : 10,
            "MIN_AUTOBUDGET_AVG_CPA" : 0.03,
            "MIN_AUTOBUDGET_AVG_CPM" : 0.07,
            "MIN_AUTOBUDGET_AVG_PRICE" : 0.03,
            "MIN_AUTOBUDGET_BID" : 0.01,
            "MIN_AUTOBUDGET_CLICKS_BUNDLE" : 100,
            "MIN_AUTOPAY" : null,
            "MIN_AVG_CPV" : 0.01,
            "MIN_CPC_CPA_PERFORMANCE" : 0.03,
            "MIN_CPM_FRONTPAGE_PRICE" : 0.31,
            "MIN_CPM_PRICE" : 0.07,
            "MIN_DAILY_BUDGET_FOR_PERIOD" : 4.2,
            "MIN_DAY_BUDGET" : 10,
            "MIN_IMAGE_PRICE" : 0.01,
            "MIN_PAY" : 15,
            "MIN_PRICE" : 0.01,
            "MIN_PRICE_FOR_MFA" : 0.05,
            "MIN_SUM_INTERPRETE_AS_PAYMENT" : 10,
            "MIN_TRANSFER_MONEY" : 15,
            "MIN_WALLET_DAY_BUDGET" : 15,
            "MONEYMETER_MAX_MIDDLE_SUM" : 350,
            "MONEYMETER_MIDDLE_PRICE_MIN" : 5,
            "MONEYMETER_TYPICAL_MIDDLE_SUM_INTERVAL_BEGIN" : 20,
            "MONEYMETER_TYPICAL_MIDDLE_SUM_INTERVAL_END" : 40,
            "MONEY_OUT_LIMIT" : 0.1,
            "PAY_FOR_CONVERSION_MIN_RESERVED_SUM_DEFAULT_VALUE" : 64,
            "PAY_WITH_CASH_LIMIT" : 0,
            "PRECISION_DIGIT_COUNT" : 6,
            "RECOMMENDATION_SUM_MAX" : 500,
            "RECOMMENDATION_SUM_MID" : 200,
            "RECOMMENDATION_SUM_MIN" : 80,
            "RECOMMENDATION_SUM_WARN" : 0,
            "RECOMMENDED_SUM_TO_PAY" : 150,
            "TOUCH_WEEK_BUDGET_SUM_FIRST" : 18,
            "TOUCH_WEEK_BUDGET_SUM_SECOND" : 29,
            "TOUCH_WEEK_BUDGET_SUM_THIRD" : 44,
            "UC_DEFAULT_CONVERSION_VALUE" : 2,
            "UC_DEFAULT_WEEK_BUDGET" : 30,
            "YABS_RATIO" : 1,
            "currency_sign" : "€",
            "full_name" : "евро",
            "name" : "евро"
        },
        "GBP" : {
            "AUCTION_STEP" : 0.01,
            "AUTOBUDGET_AVG_CPA_WARNING" : 1000,
            "AUTOBUDGET_AVG_PRICE_WARNING" : 10,
            "AUTOBUDGET_CLICKS_BUNDLE_WARNING" : 10000000,
            "AUTOBUDGET_MAX_PRICE_WARNING" : 10,
            "AUTOBUDGET_PAY_FOR_CONVERSION_AVG_CPA_WARNING" : 170,
            "AUTOBUDGET_PAY_FOR_CONVERSION_AVG_CPA_WARNING_INCREASED" : 510,
            "AUTOBUDGET_SUM_WARNING" : 34000,
            "BALANCE_CURRENCY_NAME" : "GBP",
            "BIG_RATE" : 10,
            "BRAND_SURVEY_BUDGET_THRESHOLD" : 5000,
            "BRAND_SURVEY_BUDGET_THRESHOLD_DAILY" : 350,
            "DEFAULT_AUTOBUDGET" : 50,
            "DEFAULT_AVG_CPV" : 0.07,
            "DEFAULT_CPM_PRICE" : 1.5,
            "DEFAULT_PRICE" : 0.1,
            "DIRECT_DEFAULT_PAY" : 50,
            "ISO_NUM_CODE" : 826,
            "LIST_ORDER" : 5,
            "MAX_AUTOBUDGET" : 10000000,
            "MAX_AUTOBUDGET_BID" : 500,
            "MAX_AUTOBUDGET_CLICKS_BUNDLE" : 1000000000,
            "MAX_AUTOPAY_CARD" : null,
            "MAX_AUTOPAY_REMAINING" : null,
            "MAX_AUTOPAY_YAMONEY" : null,
            "MAX_AVG_CPV" : 0.2,
            "MAX_CLIENT_ARCHIVE" : 100,
            "MAX_CPM_PRICE" : 44,
            "MAX_DAILY_BUDGET_AMOUNT" : 1000000000,
            "MAX_DAILY_BUDGET_FOR_PERIOD" : 100000000,
            "MAX_PRICE" : 500,
            "MAX_SHOW_BID" : 100,
            "MAX_TOPAY_SUGGEST" : 500,
            "MIDDLE_AVG_CPV" : 0.12,
            "MIN_AUTOBUDGET" : 10,
            "MIN_AUTOBUDGET_AVG_CPA" : 0.03,
            "MIN_AUTOBUDGET_AVG_CPM" : 0.07,
            "MIN_AUTOBUDGET_AVG_PRICE" : 0.03,
            "MIN_AUTOBUDGET_BID" : 0.01,
            "MIN_AUTOBUDGET_CLICKS_BUNDLE" : 100,
            "MIN_AUTOPAY" : null,
            "MIN_AVG_CPV" : 0.01,
            "MIN_CPC_CPA_PERFORMANCE" : 0.03,
            "MIN_CPM_FRONTPAGE_PRICE" : 0.31,
            "MIN_CPM_PRICE" : 0.07,
            "MIN_DAILY_BUDGET_FOR_PERIOD" : 4.2,
            "MIN_DAY_BUDGET" : 10,
            "MIN_IMAGE_PRICE" : 0.01,
            "MIN_PAY" : 15,
            "MIN_PRICE" : 0.01,
            "MIN_PRICE_FOR_MFA" : 0.05,
            "MIN_SUM_INTERPRETE_AS_PAYMENT" : 10,
            "MIN_TRANSFER_MONEY" : 15,
            "MIN_WALLET_DAY_BUDGET" : 15,
            "MONEYMETER_MAX_MIDDLE_SUM" : 350,
            "MONEYMETER_MIDDLE_PRICE_MIN" : 5,
            "MONEYMETER_TYPICAL_MIDDLE_SUM_INTERVAL_BEGIN" : 20,
            "MONEYMETER_TYPICAL_MIDDLE_SUM_INTERVAL_END" : 40,
            "MONEY_OUT_LIMIT" : 0.1,
            "PAY_FOR_CONVERSION_MIN_RESERVED_SUM_DEFAULT_VALUE" : 64,
            "PAY_WITH_CASH_LIMIT" : 0,
            "PRECISION_DIGIT_COUNT" : 6,
            "RECOMMENDATION_SUM_MAX" : 500,
            "RECOMMENDATION_SUM_MID" : 200,
            "RECOMMENDATION_SUM_MIN" : 80,
            "RECOMMENDATION_SUM_WARN" : 0,
            "RECOMMENDED_SUM_TO_PAY" : 150,
            "TOUCH_WEEK_BUDGET_SUM_FIRST" : 18,
            "TOUCH_WEEK_BUDGET_SUM_SECOND" : 29,
            "TOUCH_WEEK_BUDGET_SUM_THIRD" : 44,
            "UC_DEFAULT_CONVERSION_VALUE" : 2,
            "UC_DEFAULT_WEEK_BUDGET" : 30,
            "YABS_RATIO" : 1,
            "currency_sign" : "£",
            "full_name" : "фунты стерлингов",
            "name" : "GBP"
        },
        "KZT" : {
            "AUCTION_STEP" : 1,
            "AUTOBUDGET_AVG_CPA_WARNING" : 130000,
            "AUTOBUDGET_AVG_PRICE_WARNING" : 1300,
            "AUTOBUDGET_CLICKS_BUNDLE_WARNING" : 10000000,
            "AUTOBUDGET_MAX_PRICE_WARNING" : 1300,
            "AUTOBUDGET_PAY_FOR_CONVERSION_AVG_CPA_WARNING" : 30000,
            "AUTOBUDGET_PAY_FOR_CONVERSION_AVG_CPA_WARNING_INCREASED" : 90000,
            "AUTOBUDGET_SUM_WARNING" : 4300000,
            "BALANCE_CURRENCY_NAME" : "KZT",
            "BIG_RATE" : 1300,
            "BRAND_SURVEY_BUDGET_THRESHOLD" : 1500000,
            "BRAND_SURVEY_BUDGET_THRESHOLD_DAILY" : 107000,
            "DEFAULT_AUTOBUDGET" : 6500,
            "DEFAULT_AVG_CPV" : 1.6,
            "DEFAULT_CPM_PRICE" : 600,
            "DEFAULT_PRICE" : 10,
            "DIRECT_DEFAULT_PAY" : 6500,
            "ISO_NUM_CODE" : 398,
            "LIST_ORDER" : 7,
            "MAX_AUTOBUDGET" : 1300000000,
            "MAX_AUTOBUDGET_BID" : 130000,
            "MAX_AUTOBUDGET_CLICKS_BUNDLE" : 1300000000,
            "MAX_AUTOPAY_CARD" : null,
            "MAX_AUTOPAY_REMAINING" : null,
            "MAX_AUTOPAY_YAMONEY" : null,
            "MAX_AVG_CPV" : 6,
            "MAX_CLIENT_ARCHIVE" : 13000,
            "MAX_CPM_PRICE" : 18000,
            "MAX_DAILY_BUDGET_AMOUNT" : 1000000000,
            "MAX_DAILY_BUDGET_FOR_PERIOD" : 100000000,
            "MAX_PRICE" : 130000,
            "MAX_SHOW_BID" : 26000,
            "MAX_TOPAY_SUGGEST" : 65000,
            "MIDDLE_AVG_CPV" : 3.6,
            "MIN_AUTOBUDGET" : 1300,
            "MIN_AUTOBUDGET_AVG_CPA" : 3,
            "MIN_AUTOBUDGET_AVG_CPM" : 29,
            "MIN_AUTOBUDGET_AVG_PRICE" : 3,
            "MIN_AUTOBUDGET_BID" : 1,
            "MIN_AUTOBUDGET_CLICKS_BUNDLE" : 100,
            "MIN_AUTOPAY" : null,
            "MIN_AVG_CPV" : 0.3,
            "MIN_CPC_CPA_PERFORMANCE" : 3,
            "MIN_CPM_FRONTPAGE_PRICE" : 138.89,
            "MIN_CPM_PRICE" : 29,
            "MIN_DAILY_BUDGET_FOR_PERIOD" : 1700,
            "MIN_DAY_BUDGET" : 1300,
            "MIN_IMAGE_PRICE" : 1,
            "MIN_PAY" : 5000,
            "MIN_PRICE" : 1,
            "MIN_PRICE_FOR_MFA" : 5,
            "MIN_SUM_INTERPRETE_AS_PAYMENT" : 1300,
            "MIN_TRANSFER_MONEY" : 5000,
            "MIN_WALLET_DAY_BUDGET" : 5000,
            "MONEYMETER_MAX_MIDDLE_SUM" : 65000,
            "MONEYMETER_MIDDLE_PRICE_MIN" : 650,
            "MONEYMETER_TYPICAL_MIDDLE_SUM_INTERVAL_BEGIN" : 4000,
            "MONEYMETER_TYPICAL_MIDDLE_SUM_INTERVAL_END" : 8000,
            "MONEY_OUT_LIMIT" : 30,
            "PAY_FOR_CONVERSION_MIN_RESERVED_SUM_DEFAULT_VALUE" : 30000,
            "PAY_WITH_CASH_LIMIT" : 0,
            "PRECISION_DIGIT_COUNT" : 6,
            "RECOMMENDATION_SUM_MAX" : 200000,
            "RECOMMENDATION_SUM_MID" : 70000,
            "RECOMMENDATION_SUM_MIN" : 28000,
            "RECOMMENDATION_SUM_WARN" : 0,
            "RECOMMENDED_SUM_TO_PAY" : 20000,
            "TOUCH_WEEK_BUDGET_SUM_FIRST" : 7158,
            "TOUCH_WEEK_BUDGET_SUM_SECOND" : 11930,
            "TOUCH_WEEK_BUDGET_SUM_THIRD" : 17962,
            "UC_DEFAULT_CONVERSION_VALUE" : 500,
            "UC_DEFAULT_WEEK_BUDGET" : 11500,
            "YABS_RATIO" : 100,
            "currency_sign" : "₸",
            "full_name" : "казахстанские тенге",
            "name" : "тенге"
        },
        "RUB" : {
            "AUCTION_STEP" : 0.1,
            "AUTOBUDGET_AVG_CPA_WARNING" : 30000,
            "AUTOBUDGET_AVG_PRICE_WARNING" : 300,
            "AUTOBUDGET_CLICKS_BUNDLE_WARNING" : 10000000,
            "AUTOBUDGET_MAX_PRICE_WARNING" : 300,
            "AUTOBUDGET_PAY_FOR_CONVERSION_AVG_CPA_WARNING" : 5000,
            "AUTOBUDGET_PAY_FOR_CONVERSION_AVG_CPA_WARNING_INCREASED" : 15000,
            "AUTOBUDGET_SUM_WARNING" : 1000000,
            "BALANCE_CURRENCY_NAME" : null,
            "BIG_RATE" : 300,
            "BRAND_SURVEY_BUDGET_THRESHOLD" : 1000000,
            "BRAND_SURVEY_BUDGET_THRESHOLD_DAILY" : 70000,
            "DEFAULT_AUTOBUDGET" : 1500,
            "DEFAULT_AVG_CPV" : 0.6,
            "DEFAULT_CPM_PRICE" : 100,
            "DEFAULT_PRICE" : 3,
            "DIRECT_DEFAULT_PAY" : 1500,
            "ISO_NUM_CODE" : 643,
            "LIST_ORDER" : 2,
            "MAX_AUTOBUDGET" : 300000000,
            "MAX_AUTOBUDGET_BID" : 25000,
            "MAX_AUTOBUDGET_CLICKS_BUNDLE" : 1000000000,
            "MAX_AUTOPAY_CARD" : 49999.99,
            "MAX_AUTOPAY_REMAINING" : 999999.99,
            "MAX_AUTOPAY_YAMONEY" : 15000,
            "MAX_AVG_CPV" : 2,
            "MAX_CLIENT_ARCHIVE" : 3000,
            "MAX_CPM_PRICE" : 3000,
            "MAX_DAILY_BUDGET_AMOUNT" : 1000000000,
            "MAX_DAILY_BUDGET_FOR_PERIOD" : 100000000,
            "MAX_PRICE" : 25000,
            "MAX_SHOW_BID" : 5000,
            "MAX_TOPAY_SUGGEST" : 15000,
            "MIDDLE_AVG_CPV" : 1.2,
            "MIN_AUTOBUDGET" : 300,
            "MIN_AUTOBUDGET_AVG_CPA" : 0.9,
            "MIN_AUTOBUDGET_AVG_CPM" : 5,
            "MIN_AUTOBUDGET_AVG_PRICE" : 0.9,
            "MIN_AUTOBUDGET_BID" : 0.3,
            "MIN_AUTOBUDGET_CLICKS_BUNDLE" : 100,
            "MIN_AUTOPAY" : 300,
            "MIN_AVG_CPV" : 0.1,
            "MIN_CPC_CPA_PERFORMANCE" : 1,
            "MIN_CPM_FRONTPAGE_PRICE" : 25,
            "MIN_CPM_PRICE" : 5,
            "MIN_DAILY_BUDGET_FOR_PERIOD" : 300,
            "MIN_DAY_BUDGET" : 300,
            "MIN_IMAGE_PRICE" : 0.3,
            "MIN_PAY" : 300,
            "MIN_PRICE" : 0.3,
            "MIN_PRICE_FOR_MFA" : 1.5,
            "MIN_SUM_INTERPRETE_AS_PAYMENT" : 300,
            "MIN_TRANSFER_MONEY" : 300,
            "MIN_WALLET_DAY_BUDGET" : 1000,
            "MONEYMETER_MAX_MIDDLE_SUM" : 13000,
            "MONEYMETER_MIDDLE_PRICE_MIN" : 150,
            "MONEYMETER_TYPICAL_MIDDLE_SUM_INTERVAL_BEGIN" : 800,
            "MONEYMETER_TYPICAL_MIDDLE_SUM_INTERVAL_END" : 1600,
            "MONEY_OUT_LIMIT" : 5,
            "PAY_FOR_CONVERSION_MIN_RESERVED_SUM_DEFAULT_VALUE" : 5000,
            "PAY_WITH_CASH_LIMIT" : 12500,
            "PRECISION_DIGIT_COUNT" : 4,
            "RECOMMENDATION_SUM_MAX" : 35000,
            "RECOMMENDATION_SUM_MID" : 12500,
            "RECOMMENDATION_SUM_MIN" : 5000,
            "RECOMMENDATION_SUM_WARN" : 49999,
            "RECOMMENDED_SUM_TO_PAY" : 4000,
            "TOUCH_WEEK_BUDGET_SUM_FIRST" : 1200,
            "TOUCH_WEEK_BUDGET_SUM_SECOND" : 2000,
            "TOUCH_WEEK_BUDGET_SUM_THIRD" : 3000,
            "UC_DEFAULT_CONVERSION_VALUE" : 100,
            "UC_DEFAULT_WEEK_BUDGET" : 2300,
            "YABS_RATIO" : 100,
            "currency_sign" : "₽",
            "full_name" : "российские рубли",
            "name" : "руб."
        },
        "TRY" : {
            "AUCTION_STEP" : 0.01,
            "AUTOBUDGET_AVG_CPA_WARNING" : 1700,
            "AUTOBUDGET_AVG_PRICE_WARNING" : 17,
            "AUTOBUDGET_CLICKS_BUNDLE_WARNING" : 10000000,
            "AUTOBUDGET_MAX_PRICE_WARNING" : 17,
            "AUTOBUDGET_PAY_FOR_CONVERSION_AVG_CPA_WARNING" : 450,
            "AUTOBUDGET_PAY_FOR_CONVERSION_AVG_CPA_WARNING_INCREASED" : 1350,
            "AUTOBUDGET_SUM_WARNING" : 57000,
            "BALANCE_CURRENCY_NAME" : "TRY",
            "BIG_RATE" : 17,
            "BRAND_SURVEY_BUDGET_THRESHOLD" : 0,
            "BRAND_SURVEY_BUDGET_THRESHOLD_DAILY" : 0,
            "DEFAULT_AUTOBUDGET" : 85,
            "DEFAULT_AVG_CPV" : 0.07,
            "DEFAULT_CPM_PRICE" : 6,
            "DEFAULT_PRICE" : 0.1,
            "DIRECT_DEFAULT_PAY" : 100,
            "ISO_NUM_CODE" : 949,
            "LIST_ORDER" : 9,
            "MAX_AUTOBUDGET" : 17000000,
            "MAX_AUTOBUDGET_BID" : 1500,
            "MAX_AUTOBUDGET_CLICKS_BUNDLE" : 1700000000,
            "MAX_AUTOPAY_CARD" : null,
            "MAX_AUTOPAY_REMAINING" : null,
            "MAX_AUTOPAY_YAMONEY" : null,
            "MAX_AVG_CPV" : 0.2,
            "MAX_CLIENT_ARCHIVE" : 170,
            "MAX_CPM_PRICE" : 178,
            "MAX_DAILY_BUDGET_AMOUNT" : 1000000000,
            "MAX_DAILY_BUDGET_FOR_PERIOD" : 100000000,
            "MAX_PRICE" : 1500,
            "MAX_SHOW_BID" : 300,
            "MAX_TOPAY_SUGGEST" : 1000,
            "MIDDLE_AVG_CPV" : 0.12,
            "MIN_AUTOBUDGET" : 17,
            "MIN_AUTOBUDGET_AVG_CPA" : 0.03,
            "MIN_AUTOBUDGET_AVG_CPM" : 0.3,
            "MIN_AUTOBUDGET_AVG_PRICE" : 0.03,
            "MIN_AUTOBUDGET_BID" : 0.01,
            "MIN_AUTOBUDGET_CLICKS_BUNDLE" : 100,
            "MIN_AUTOPAY" : null,
            "MIN_AVG_CPV" : 0.01,
            "MIN_CPC_CPA_PERFORMANCE" : 0.03,
            "MIN_CPM_FRONTPAGE_PRICE" : 1.89,
            "MIN_CPM_PRICE" : 0.3,
            "MIN_DAILY_BUDGET_FOR_PERIOD" : 18,
            "MIN_DAY_BUDGET" : 17,
            "MIN_IMAGE_PRICE" : 0.01,
            "MIN_PAY" : 50,
            "MIN_PRICE" : 0.01,
            "MIN_PRICE_FOR_MFA" : 0.05,
            "MIN_SUM_INTERPRETE_AS_PAYMENT" : 17,
            "MIN_TRANSFER_MONEY" : 50,
            "MIN_WALLET_DAY_BUDGET" : 50,
            "MONEYMETER_MAX_MIDDLE_SUM" : 850,
            "MONEYMETER_MIDDLE_PRICE_MIN" : 10,
            "MONEYMETER_TYPICAL_MIDDLE_SUM_INTERVAL_BEGIN" : 50,
            "MONEYMETER_TYPICAL_MIDDLE_SUM_INTERVAL_END" : 100,
            "MONEY_OUT_LIMIT" : 1,
            "PAY_FOR_CONVERSION_MIN_RESERVED_SUM_DEFAULT_VALUE" : 495,
            "PAY_WITH_CASH_LIMIT" : 0,
            "PRECISION_DIGIT_COUNT" : 6,
            "RECOMMENDATION_SUM_MAX" : 3200,
            "RECOMMENDATION_SUM_MID" : 1200,
            "RECOMMENDATION_SUM_MIN" : 500,
            "RECOMMENDATION_SUM_WARN" : 0,
            "RECOMMENDED_SUM_TO_PAY" : 200,
            "TOUCH_WEEK_BUDGET_SUM_FIRST" : 114,
            "TOUCH_WEEK_BUDGET_SUM_SECOND" : 189,
            "TOUCH_WEEK_BUDGET_SUM_THIRD" : 285,
            "UC_DEFAULT_CONVERSION_VALUE" : 10,
            "UC_DEFAULT_WEEK_BUDGET" : 250,
            "YABS_RATIO" : 1,
            "currency_sign" : "₺",
            "full_name" : "турецкие лиры",
            "name" : "TL"
        },
        "UAH" : {
            "AUCTION_STEP" : 0.01,
            "AUTOBUDGET_AVG_CPA_WARNING" : 8000,
            "AUTOBUDGET_AVG_PRICE_WARNING" : 80,
            "AUTOBUDGET_CLICKS_BUNDLE_WARNING" : 10000000,
            "AUTOBUDGET_MAX_PRICE_WARNING" : 80,
            "AUTOBUDGET_PAY_FOR_CONVERSION_AVG_CPA_WARNING" : 1300,
            "AUTOBUDGET_PAY_FOR_CONVERSION_AVG_CPA_WARNING_INCREASED" : 3900,
            "AUTOBUDGET_SUM_WARNING" : 250000,
            "BALANCE_CURRENCY_NAME" : "UAH",
            "BIG_RATE" : 80,
            "BRAND_SURVEY_BUDGET_THRESHOLD" : 0,
            "BRAND_SURVEY_BUDGET_THRESHOLD_DAILY" : 0,
            "DEFAULT_AUTOBUDGET" : 400,
            "DEFAULT_AVG_CPV" : 0.16,
            "DEFAULT_CPM_PRICE" : 45,
            "DEFAULT_PRICE" : 0.8,
            "DIRECT_DEFAULT_PAY" : 360,
            "ISO_NUM_CODE" : 980,
            "LIST_ORDER" : 3,
            "MAX_AUTOBUDGET" : 74000000,
            "MAX_AUTOBUDGET_BID" : 9000,
            "MAX_AUTOBUDGET_CLICKS_BUNDLE" : 925000000,
            "MAX_AUTOPAY_CARD" : null,
            "MAX_AUTOPAY_REMAINING" : null,
            "MAX_AUTOPAY_YAMONEY" : null,
            "MAX_AVG_CPV" : 0.6,
            "MAX_CLIENT_ARCHIVE" : 800,
            "MAX_CPM_PRICE" : 1360,
            "MAX_DAILY_BUDGET_AMOUNT" : 1000000000,
            "MAX_DAILY_BUDGET_FOR_PERIOD" : 100000000,
            "MAX_PRICE" : 9000,
            "MAX_SHOW_BID" : 1800,
            "MAX_TOPAY_SUGGEST" : 2500,
            "MIDDLE_AVG_CPV" : 0.36,
            "MIN_AUTOBUDGET" : 80,
            "MIN_AUTOBUDGET_AVG_CPA" : 0.3,
            "MIN_AUTOBUDGET_AVG_CPM" : 2.25,
            "MIN_AUTOBUDGET_AVG_PRICE" : 0.3,
            "MIN_AUTOBUDGET_BID" : 0.08,
            "MIN_AUTOBUDGET_CLICKS_BUNDLE" : 100,
            "MIN_AUTOPAY" : null,
            "MIN_AVG_CPV" : 0.03,
            "MIN_CPC_CPA_PERFORMANCE" : 0.24,
            "MIN_CPM_FRONTPAGE_PRICE" : 9.96,
            "MIN_CPM_PRICE" : 2.25,
            "MIN_DAILY_BUDGET_FOR_PERIOD" : 135,
            "MIN_DAY_BUDGET" : 80,
            "MIN_IMAGE_PRICE" : 0.08,
            "MIN_PAY" : 250,
            "MIN_PRICE" : 0.08,
            "MIN_PRICE_FOR_MFA" : 0.4,
            "MIN_SUM_INTERPRETE_AS_PAYMENT" : 80,
            "MIN_TRANSFER_MONEY" : 250,
            "MIN_WALLET_DAY_BUDGET" : 250,
            "MONEYMETER_MAX_MIDDLE_SUM" : 3400,
            "MONEYMETER_MIDDLE_PRICE_MIN" : 50,
            "MONEYMETER_TYPICAL_MIDDLE_SUM_INTERVAL_BEGIN" : 200,
            "MONEYMETER_TYPICAL_MIDDLE_SUM_INTERVAL_END" : 400,
            "MONEY_OUT_LIMIT" : 2,
            "PAY_FOR_CONVERSION_MIN_RESERVED_SUM_DEFAULT_VALUE" : 0,
            "PAY_WITH_CASH_LIMIT" : 0,
            "PRECISION_DIGIT_COUNT" : 5,
            "RECOMMENDATION_SUM_MAX" : 0,
            "RECOMMENDATION_SUM_MID" : 0,
            "RECOMMENDATION_SUM_MIN" : 0,
            "RECOMMENDATION_SUM_WARN" : 0,
            "RECOMMENDED_SUM_TO_PAY" : 1000,
            "TOUCH_WEEK_BUDGET_SUM_FIRST" : 466,
            "TOUCH_WEEK_BUDGET_SUM_SECOND" : 776,
            "TOUCH_WEEK_BUDGET_SUM_THIRD" : 1168,
            "UC_DEFAULT_CONVERSION_VALUE" : 35,
            "UC_DEFAULT_WEEK_BUDGET" : 850,
            "YABS_RATIO" : 10,
            "currency_sign" : "₴",
            "full_name" : "украинские гривны",
            "name" : "грн"
        },
        "USD" : {
            "AUCTION_STEP" : 0.01,
            "AUTOBUDGET_AVG_CPA_WARNING" : 1000,
            "AUTOBUDGET_AVG_PRICE_WARNING" : 10,
            "AUTOBUDGET_CLICKS_BUNDLE_WARNING" : 10000000,
            "AUTOBUDGET_MAX_PRICE_WARNING" : 10,
            "AUTOBUDGET_PAY_FOR_CONVERSION_AVG_CPA_WARNING" : 170,
            "AUTOBUDGET_PAY_FOR_CONVERSION_AVG_CPA_WARNING_INCREASED" : 510,
            "AUTOBUDGET_SUM_WARNING" : 34000,
            "BALANCE_CURRENCY_NAME" : "USD",
            "BIG_RATE" : 10,
            "BRAND_SURVEY_BUDGET_THRESHOLD" : 7000,
            "BRAND_SURVEY_BUDGET_THRESHOLD_DAILY" : 490,
            "DEFAULT_AUTOBUDGET" : 50,
            "DEFAULT_AVG_CPV" : 0.07,
            "DEFAULT_CPM_PRICE" : 1.5,
            "DEFAULT_PRICE" : 0.1,
            "DIRECT_DEFAULT_PAY" : 50,
            "ISO_NUM_CODE" : 840,
            "LIST_ORDER" : 4,
            "MAX_AUTOBUDGET" : 10000000,
            "MAX_AUTOBUDGET_BID" : 700,
            "MAX_AUTOBUDGET_CLICKS_BUNDLE" : 1000000000,
            "MAX_AUTOPAY_CARD" : null,
            "MAX_AUTOPAY_REMAINING" : null,
            "MAX_AUTOPAY_YAMONEY" : null,
            "MAX_AVG_CPV" : 0.2,
            "MAX_CLIENT_ARCHIVE" : 100,
            "MAX_CPM_PRICE" : 52,
            "MAX_DAILY_BUDGET_AMOUNT" : 1000000000,
            "MAX_DAILY_BUDGET_FOR_PERIOD" : 100000000,
            "MAX_PRICE" : 700,
            "MAX_SHOW_BID" : 140,
            "MAX_TOPAY_SUGGEST" : 500,
            "MIDDLE_AVG_CPV" : 0.12,
            "MIN_AUTOBUDGET" : 10,
            "MIN_AUTOBUDGET_AVG_CPA" : 0.03,
            "MIN_AUTOBUDGET_AVG_CPM" : 0.08,
            "MIN_AUTOBUDGET_AVG_PRICE" : 0.03,
            "MIN_AUTOBUDGET_BID" : 0.01,
            "MIN_AUTOBUDGET_CLICKS_BUNDLE" : 100,
            "MIN_AUTOPAY" : null,
            "MIN_AVG_CPV" : 0.01,
            "MIN_CPC_CPA_PERFORMANCE" : 0.03,
            "MIN_CPM_FRONTPAGE_PRICE" : 0.36,
            "MIN_CPM_PRICE" : 0.08,
            "MIN_DAILY_BUDGET_FOR_PERIOD" : 5,
            "MIN_DAY_BUDGET" : 10,
            "MIN_IMAGE_PRICE" : 0.01,
            "MIN_PAY" : 15,
            "MIN_PRICE" : 0.01,
            "MIN_PRICE_FOR_MFA" : 0.05,
            "MIN_SUM_INTERPRETE_AS_PAYMENT" : 10,
            "MIN_TRANSFER_MONEY" : 15,
            "MIN_WALLET_DAY_BUDGET" : 15,
            "MONEYMETER_MAX_MIDDLE_SUM" : 500,
            "MONEYMETER_MIDDLE_PRICE_MIN" : 5,
            "MONEYMETER_TYPICAL_MIDDLE_SUM_INTERVAL_BEGIN" : 30,
            "MONEYMETER_TYPICAL_MIDDLE_SUM_INTERVAL_END" : 60,
            "MONEY_OUT_LIMIT" : 0.1,
            "PAY_FOR_CONVERSION_MIN_RESERVED_SUM_DEFAULT_VALUE" : 72,
            "PAY_WITH_CASH_LIMIT" : 0,
            "PRECISION_DIGIT_COUNT" : 6,
            "RECOMMENDATION_SUM_MAX" : 500,
            "RECOMMENDATION_SUM_MID" : 200,
            "RECOMMENDATION_SUM_MIN" : 80,
            "RECOMMENDATION_SUM_WARN" : 0,
            "RECOMMENDED_SUM_TO_PAY" : 150,
            "TOUCH_WEEK_BUDGET_SUM_FIRST" : 20,
            "TOUCH_WEEK_BUDGET_SUM_SECOND" : 32,
            "TOUCH_WEEK_BUDGET_SUM_THIRD" : 48,
            "UC_DEFAULT_CONVERSION_VALUE" : 2,
            "UC_DEFAULT_WEEK_BUDGET" : 30,
            "YABS_RATIO" : 1,
            "currency_sign" : "$",
            "full_name" : "доллары США",
            "name" : "долл."
        },
        "YND_FIXED" : {
            "AUCTION_STEP" : 0.01,
            "AUTOBUDGET_AVG_CPA_WARNING" : 1000,
            "AUTOBUDGET_AVG_PRICE_WARNING" : 10,
            "AUTOBUDGET_CLICKS_BUNDLE_WARNING" : 10000000,
            "AUTOBUDGET_MAX_PRICE_WARNING" : 10,
            "AUTOBUDGET_PAY_FOR_CONVERSION_AVG_CPA_WARNING" : 160,
            "AUTOBUDGET_PAY_FOR_CONVERSION_AVG_CPA_WARNING_INCREASED" : 480,
            "AUTOBUDGET_SUM_WARNING" : 34000,
            "BALANCE_CURRENCY_NAME" : null,
            "BIG_RATE" : 10,
            "BRAND_SURVEY_BUDGET_THRESHOLD" : 0,
            "BRAND_SURVEY_BUDGET_THRESHOLD_DAILY" : 0,
            "DEFAULT_AUTOBUDGET" : 50,
            "DEFAULT_AVG_CPV" : null,
            "DEFAULT_CPM_PRICE" : null,
            "DEFAULT_PRICE" : 0.1,
            "DIRECT_DEFAULT_PAY" : 50,
            "ISO_NUM_CODE" : null,
            "LIST_ORDER" : 1,
            "MAX_AUTOBUDGET" : 10000000,
            "MAX_AUTOBUDGET_BID" : 840,
            "MAX_AUTOBUDGET_CLICKS_BUNDLE" : 1000000000,
            "MAX_AUTOPAY_CARD" : null,
            "MAX_AUTOPAY_REMAINING" : null,
            "MAX_AUTOPAY_YAMONEY" : null,
            "MAX_AVG_CPV" : 0.2,
            "MAX_CLIENT_ARCHIVE" : 100,
            "MAX_CPM_PRICE" : 100,
            "MAX_DAILY_BUDGET_AMOUNT" : 1000000000,
            "MAX_DAILY_BUDGET_FOR_PERIOD" : 100000000,
            "MAX_PRICE" : 840,
            "MAX_SHOW_BID" : 168,
            "MAX_TOPAY_SUGGEST" : 500,
            "MIDDLE_AVG_CPV" : 0.12,
            "MIN_AUTOBUDGET" : 10,
            "MIN_AUTOBUDGET_AVG_CPA" : 0.03,
            "MIN_AUTOBUDGET_AVG_CPM" : 0.17,
            "MIN_AUTOBUDGET_AVG_PRICE" : 0.03,
            "MIN_AUTOBUDGET_BID" : 0.01,
            "MIN_AUTOBUDGET_CLICKS_BUNDLE" : 100,
            "MIN_AUTOPAY" : null,
            "MIN_AVG_CPV" : 0.01,
            "MIN_CPC_CPA_PERFORMANCE" : 0.1,
            "MIN_CPM_FRONTPAGE_PRICE" : 0.17,
            "MIN_CPM_PRICE" : 0.17,
            "MIN_DAILY_BUDGET_FOR_PERIOD" : 10,
            "MIN_DAY_BUDGET" : 10,
            "MIN_IMAGE_PRICE" : 0.01,
            "MIN_PAY" : 15,
            "MIN_PRICE" : 0.01,
            "MIN_PRICE_FOR_MFA" : 0.05,
            "MIN_SUM_INTERPRETE_AS_PAYMENT" : 10,
            "MIN_TRANSFER_MONEY" : 15,
            "MIN_WALLET_DAY_BUDGET" : 15,
            "MONEYMETER_MAX_MIDDLE_SUM" : 500,
            "MONEYMETER_MIDDLE_PRICE_MIN" : 5,
            "MONEYMETER_TYPICAL_MIDDLE_SUM_INTERVAL_BEGIN" : 30,
            "MONEYMETER_TYPICAL_MIDDLE_SUM_INTERVAL_END" : 60,
            "MONEY_OUT_LIMIT" : 0.2,
            "PAY_FOR_CONVERSION_MIN_RESERVED_SUM_DEFAULT_VALUE" : null,
            "PAY_WITH_CASH_LIMIT" : 0,
            "PRECISION_DIGIT_COUNT" : 6,
            "RECOMMENDATION_SUM_MAX" : 0,
            "RECOMMENDATION_SUM_MID" : 0,
            "RECOMMENDATION_SUM_MIN" : 0,
            "RECOMMENDATION_SUM_WARN" : 0,
            "RECOMMENDED_SUM_TO_PAY" : 150,
            "TOUCH_WEEK_BUDGET_SUM_FIRST" : 40,
            "TOUCH_WEEK_BUDGET_SUM_SECOND" : 67,
            "TOUCH_WEEK_BUDGET_SUM_THIRD" : 100,
            "UC_DEFAULT_CONVERSION_VALUE" : null,
            "UC_DEFAULT_WEEK_BUDGET" : null,
            "YABS_RATIO" : 1,
            "currency_sign" : "y.e.",
            "full_name" : "условные единицы",
            "name" : "у.е."
        }
    },
    currencies_order = window.CONSTS.currencies_order = [
        "YND_FIXED",
        "RUB",
        "UAH",
        "USD",
        "EUR",
        "GBP",
        "BYN",
        "KZT",
        "CHF",
        "TRY"
    ],
    currency_texts_description = window.CONSTS.currency_texts_description = {
        "account_currency_convert_finished" : {
            "BYN" : "Перевод аккаунта в белорусские рубли завершен",
            "CHF" : "Перевод аккаунта в швейцарские франки завершен",
            "EUR" : "Перевод аккаунта в евро завершен",
            "GBP" : "Перевод аккаунта в фунты стерлингов завершен",
            "KZT" : "Перевод аккаунта в тенге завершен",
            "RUB" : "Перевод аккаунта в российские рубли завершен",
            "TRY" : "Перевод аккаунта в турецкие лиры завершен",
            "UAH" : "Перевод аккаунта в украинские гривны завершен",
            "USD" : "Перевод аккаунта в доллары США завершен",
            "YND_FIXED" : null
        },
        "account_currency_convert_finished_detailed" : {
            "BYN" : "Перевод вашего аккаунта %s в валюту белорусские рубли успешно завершен",
            "CHF" : "Перевод вашего аккаунта %s в валюту швейцарские франки успешно завершен",
            "EUR" : "Перевод вашего аккаунта %s в валюту евро успешно завершен",
            "GBP" : "Перевод вашего аккаунта %s в валюту фунты стерлингов успешно завершен",
            "KZT" : "Перевод вашего аккаунта %s в валюту тенге успешно завершен",
            "RUB" : "Перевод вашего аккаунта %s в валюту российские рубли успешно завершен",
            "TRY" : "Перевод вашего аккаунта %s в валюту турецкие лиры успешно завершен",
            "UAH" : "Перевод вашего аккаунта %s в валюту украинские гривны успешно завершен",
            "USD" : "Перевод вашего аккаунта %s в валюту доллары США успешно завершен",
            "YND_FIXED" : null
        },
        "account_currency_convert_finished_short" : {
            "BYN" : "Аккаунт %s переведен в белорусские рубли",
            "CHF" : "Аккаунт %s переведен в швейцарские франки",
            "EUR" : "Аккаунт %s переведен в евро",
            "GBP" : "Аккаунт %s переведен в фунты стерлингов",
            "KZT" : "Аккаунт %s переведен в тенге",
            "RUB" : "Аккаунт %s переведен в российские рубли",
            "TRY" : "Аккаунт %s переведен в турецкие лиры",
            "UAH" : "Аккаунт %s переведен в украинские гривны",
            "USD" : "Аккаунт %s переведен в доллары США",
            "YND_FIXED" : null
        },
        "api_locked_during_currency_converted" : {
            "BYN" : "Доступ к кампаниям закрыт на время перехода в белорусские рубли",
            "CHF" : "Доступ к кампаниям закрыт на время перехода в швейцарские франки",
            "EUR" : "Доступ к кампаниям закрыт на время перехода в евро",
            "GBP" : "Доступ к кампаниям закрыт на время перехода в фунты стерлингов",
            "KZT" : "Доступ к кампаниям закрыт на время перехода в тенге",
            "RUB" : "Доступ к кампаниям закрыт на время перехода в российские рубли",
            "TRY" : "Доступ к кампаниям закрыт на время перехода в турецкие лиры",
            "UAH" : "Доступ к кампаниям закрыт на время перехода в украинские гривны",
            "USD" : "Доступ к кампаниям закрыт на время перехода в доллары США",
            "YND_FIXED" : null
        },
        "click_price_after_convert" : {
            "BYN" : "Цена клика после перехода в белорусские рубли",
            "CHF" : "Цена клика после перехода в швейцарские франки",
            "EUR" : "Цена клика после перехода в евро",
            "GBP" : "Цена клика после перехода в фунты стерлингов",
            "KZT" : "Цена клика после перехода в тенге",
            "RUB" : "Цена клика после перехода в российские рубли",
            "TRY" : "Цена клика после перехода в турецкие лиры",
            "UAH" : "Цена клика после перехода в украинские гривны",
            "USD" : "Цена клика после перехода в доллары США",
            "YND_FIXED" : null
        },
        "client_new_campaigns_in" : {
            "BYN" : "Новые кампании клиента в белорусских рублях",
            "CHF" : "Новые кампании клиента в швейцарских франках",
            "EUR" : "Новые кампании клиента в евро",
            "GBP" : "Новые кампании клиента в фунтах стерлингов",
            "KZT" : "Новые кампании клиента в тенге",
            "RUB" : "Новые кампании клиента в российских рублях",
            "TRY" : "Новые кампании клиента в турецких лирах",
            "UAH" : "Новые кампании клиента в украинских гривнах",
            "USD" : "Новые кампании клиента в долларах США",
            "YND_FIXED" : "Новые кампании клиента в у.е."
        },
        "convert_all_campaigns_into" : {
            "BYN" : "Перевести все кампании в белорусские рубли",
            "CHF" : "Перевести все кампании в швейцарские франки",
            "EUR" : "Перевести все кампании в евро",
            "GBP" : "Перевести все кампании в фунты стерлингов",
            "KZT" : "Перевести все кампании в тенге",
            "RUB" : "Перевести все кампании в российские рубли",
            "TRY" : "Перевести все кампании в турецкие лиры",
            "UAH" : "Перевести все кампании в украинские гривны",
            "USD" : "Перевести все кампании в доллары США",
            "YND_FIXED" : null
        },
        "convert_finished_successfully" : {
            "BYN" : "Перевод на белорусские рубли успешно завершен",
            "CHF" : "Перевод на швейцарские франки успешно завершен",
            "EUR" : "Перевод на евро успешно завершен",
            "GBP" : "Перевод на фунты стерлингов успешно завершен",
            "KZT" : "Перевод на тенге успешно завершен",
            "RUB" : "Перевод на российские рубли успешно завершен",
            "TRY" : "Перевод на турецкие лиры успешно завершен",
            "UAH" : "Перевод на украинские гривны успешно завершен",
            "USD" : "Перевод на доллары США успешно завершен",
            "YND_FIXED" : null
        },
        "convert_from_conv_units_into" : {
            "BYN" : "Конвертация из «у.е.» в белорусские рубли",
            "CHF" : "Конвертация из «у.е.» в швейцарские франки",
            "EUR" : "Конвертация из «у.е.» в евро",
            "GBP" : "Конвертация из «у.е.» в фунты стерлингов",
            "KZT" : "Конвертация из «у.е.» в тенге",
            "RUB" : "Конвертация из «у.е.» в российские рубли",
            "TRY" : "Конвертация из «у.е.» в турецкие лиры",
            "UAH" : "Конвертация из «у.е.» в украинские гривны",
            "USD" : "Конвертация из «у.е.» в доллары США",
            "YND_FIXED" : null
        },
        "convert_start_at" : {
            "BYN" : null,
            "CHF" : null,
            "EUR" : null,
            "GBP" : null,
            "KZT" : null,
            "RUB" : "Перевод всех кампаний в рубли начнется автоматически после %s",
            "TRY" : null,
            "UAH" : null,
            "USD" : null,
            "YND_FIXED" : null
        },
        "multicurrency_teaser_title" : {
            "BYN" : "Ведите ваши кампании в белорусских рублях",
            "CHF" : "Ведите ваши кампании в швейцарских франках",
            "EUR" : "Ведите ваши кампании в евро",
            "GBP" : "Ведите ваши кампании в фунтах стерлингов",
            "KZT" : "Ведите ваши кампании в тенге",
            "RUB" : "Ведите ваши кампании в рублях",
            "TRY" : "Ведите ваши кампании в турецких лирах",
            "UAH" : "Ведите ваши кампании в украинских гривнах",
            "USD" : "Ведите ваши кампании в долларах США",
            "YND_FIXED" : null
        },
        "my_new_campaigns_in" : {
            "BYN" : "Мои новые кампании в белорусских рублях",
            "CHF" : "Мои новые кампании в швейцарских франках",
            "EUR" : "Мои новые кампании в евро",
            "GBP" : "Мои новые кампании в фунтах стерлингов",
            "KZT" : "Мои новые кампании в тенге",
            "RUB" : "Мои новые кампании в российских рублях",
            "TRY" : "Мои новые кампании в турецких лирах",
            "UAH" : "Мои новые кампании в украинских гривнах",
            "USD" : "Мои новые кампании в долларах США",
            "YND_FIXED" : "Мои новые кампании в у.е."
        },
        "new_campaign_in" : {
            "BYN" : "Новая кампания в белорусских рублях",
            "CHF" : "Новая кампания в швейцарских франках",
            "EUR" : "Новая кампания в евро",
            "GBP" : "Новая кампания в фунтах стерлингов",
            "KZT" : "Новая кампания в тенге",
            "RUB" : "Новая кампания в российских рублях",
            "TRY" : "Новая кампания в турецких лирах",
            "UAH" : "Новая кампания в украинских гривнах",
            "USD" : "Новая кампания в долларах США",
            "YND_FIXED" : null
        },
        "now_converting_from_conv_units_into" : {
            "BYN" : "Идёт переход из «у.е.» в белорусские рубли",
            "CHF" : "Идёт переход из «у.е.» в швейцарские франки",
            "EUR" : "Идёт переход из «у.е.» в евро",
            "GBP" : "Идёт переход из «у.е.» в фунты стерлингов",
            "KZT" : "Идёт переход из «у.е.» в тенге",
            "RUB" : "Идёт переход из «у.е.» в российские рубли",
            "TRY" : "Идёт переход из «у.е.» в турецкие лиры",
            "UAH" : "Идёт переход из «у.е.» в украинские гривны",
            "USD" : "Идёт переход из «у.е.» в доллары США",
            "YND_FIXED" : null
        },
        "now_you_use_new_currency" : {
            "BYN" : "Теперь для ведения всех ваших рекламных кампаний будут использоваться белорусские рубли",
            "CHF" : "Теперь для ведения всех ваших рекламных кампаний будет использоваться швейцарские франки",
            "EUR" : "Теперь для ведения всех ваших рекламных кампаний будет использоваться евро",
            "GBP" : "Теперь для ведения всех ваших рекламных кампаний будут использоваться фунты стерлингов",
            "KZT" : "Теперь для ведения всех ваших рекламных кампаний будут использоваться казахстанские тенге",
            "RUB" : "Теперь для ведения всех ваших рекламных кампаний будут использоваться российские рубли",
            "TRY" : "Теперь для ведения всех ваших рекламных кампаний будут использоваться турецкие лиры",
            "UAH" : "Теперь для ведения всех ваших рекламных кампаний будут использоваться украинские гривны",
            "USD" : "Теперь для ведения всех ваших рекламных кампаний будут использоваться доллары США",
            "YND_FIXED" : null
        },
        "pay_in" : {
            "BYN" : "Оплатить в белорусских рублях",
            "CHF" : "Оплатить в швейцарских франках",
            "EUR" : "Оплатить в евро",
            "GBP" : "Оплатить в фунтах стерлингов",
            "KZT" : "Оплатить в тенге",
            "RUB" : "Оплатить в российских рублях",
            "TRY" : "Оплатить в турецких лирах",
            "UAH" : "Оплатить в украинских гривнах",
            "USD" : "Оплатить в долларах США",
            "YND_FIXED" : "Оплатить"
        },
        "pay_specific" : {
            "BYN" : "Особенности платежей в белорусских рублях",
            "CHF" : "Особенности платежей в швейцарских франках",
            "EUR" : "Особенности платежей в евро",
            "GBP" : "Особенности платежей в фунтах стерлингов",
            "KZT" : "Особенности платежей в тенге",
            "RUB" : "Особенности платежей в российских рублях",
            "TRY" : "Особенности платежей в турецких лирах",
            "UAH" : "Особенности платежей в украинских гривнах",
            "USD" : "Особенности платежей в долларах США",
            "YND_FIXED" : null
        },
        "work_specific" : {
            "BYN" : "Особенности работы в %sбелорусских рублях%s",
            "CHF" : "Особенности работы в %sшвейцарских франках%s",
            "EUR" : "Особенности работы в %sевро%s",
            "GBP" : "Особенности работы в %sфунтах стерлингов%s",
            "KZT" : "Особенности работы в %sтенге%s",
            "RUB" : "Особенности работы в %sроссийских рублях%s",
            "TRY" : "Особенности работы в %sтурецких лирах%s",
            "UAH" : "Особенности работы в %sукраинских гривнах%s",
            "USD" : "Особенности работы в %sдолларах США%s",
            "YND_FIXED" : null
        },
        "your_client_currency_convert_finished" : {
            "BYN" : "Перевод Вашего клиента %s (%s) в белорусские рубли завершен",
            "CHF" : "Перевод Вашего клиента %s (%s) в швейцарские франки завершен",
            "EUR" : "Перевод Вашего клиента %s (%s) в евро завершен",
            "GBP" : "Перевод Вашего клиента %s (%s) в фунты стерлингов завершен",
            "KZT" : "Перевод Вашего клиента %s (%s) в тенге завершен",
            "RUB" : "Перевод Вашего клиента %s (%s) в российские рубли завершен",
            "TRY" : "Перевод Вашего клиента %s (%s) в турецкие лиры завершен",
            "UAH" : "Перевод Вашего клиента %s (%s) в украинские гривны завершен",
            "USD" : "Перевод Вашего клиента %s (%s) в доллары США завершен",
            "YND_FIXED" : null
        },
        "your_client_currency_convert_successfully_finished" : {
            "BYN" : "Перевод Вашего клиента %s (%s) в белорусские рубли успешно завершен",
            "CHF" : "Перевод Вашего клиента %s (%s) в швейцарские франки успешно завершен",
            "EUR" : "Перевод Вашего клиента %s (%s) в евро успешно завершен",
            "GBP" : "Перевод Вашего клиента %s (%s) в фунты стерлингов успешно завершен",
            "KZT" : "Перевод Вашего клиента %s (%s) в тенге успешно завершен",
            "RUB" : "Перевод Вашего клиента %s (%s) в российские рубли успешно завершен",
            "TRY" : "Перевод Вашего клиента %s (%s) в турецкие лиры успешно завершен",
            "UAH" : "Перевод Вашего клиента %s (%s) в украинские гривны успешно завершен",
            "USD" : "Перевод Вашего клиента %s (%s) в доллары США успешно завершен",
            "YND_FIXED" : null
        }
    },
    fixed_currency_rates = window.CONSTS.fixed_currency_rates = {
        "YND_FIXED" : {
            "BYN" : {
                "0" : {
                    "with_nds" : 0.8,
                    "without_nds" : 0.8
                }
            },
            "CHF" : {
                "0" : {
                    "with_nds" : 0.77,
                    "without_nds" : 0.77
                },
                "20141201" : {
                    "with_nds" : 0.57,
                    "without_nds" : 0.53
                },
                "20150401" : {
                    "with_nds" : 0.41,
                    "without_nds" : 0.41
                }
            },
            "EUR" : {
                "0" : {
                    "with_nds" : 0.65,
                    "without_nds" : 0.65
                },
                "20141201" : {
                    "with_nds" : 0.45,
                    "without_nds" : 0.45
                },
                "20150401" : {
                    "with_nds" : 0.39,
                    "without_nds" : 0.39
                }
            },
            "GBP" : {
                "0" : {
                    "with_nds" : 0.65,
                    "without_nds" : 0.65
                },
                "20141201" : {
                    "with_nds" : 0.45,
                    "without_nds" : 0.45
                },
                "20150401" : {
                    "with_nds" : 0.39,
                    "without_nds" : 0.39
                }
            },
            "KZT" : {
                "0" : {
                    "with_nds" : 145.6,
                    "without_nds" : 130
                },
                "20141201" : {
                    "with_nds" : 112,
                    "without_nds" : 100
                },
                "20150401" : {
                    "with_nds" : 84,
                    "without_nds" : 75
                },
                "20150701" : {
                    "with_nds" : 112,
                    "without_nds" : 100
                },
                "20151001" : {
                    "with_nds" : 117.6,
                    "without_nds" : 105
                }
            },
            "RUB" : {
                "0" : {
                    "with_nds" : 30,
                    "without_nds" : 25.4237288135593
                }
            },
            "TRY" : {
                "0" : {
                    "with_nds" : 2,
                    "without_nds" : 1.7
                },
                "20141201" : {
                    "with_nds" : 1.42,
                    "without_nds" : 1.2
                },
                "20150401" : {
                    "with_nds" : 1.26,
                    "without_nds" : 1.07
                }
            },
            "UAH" : {
                "0" : {
                    "with_nds" : 6,
                    "without_nds" : 5
                },
                "20121201" : {
                    "with_nds" : 8.1,
                    "without_nds" : 6.75
                },
                "20140901" : {
                    "with_nds" : 12,
                    "without_nds" : 10
                }
            },
            "USD" : {
                "0" : {
                    "with_nds" : 0.85,
                    "without_nds" : 0.85
                },
                "20141201" : {
                    "with_nds" : 0.56,
                    "without_nds" : 0.56
                },
                "20150401" : {
                    "with_nds" : 0.41,
                    "without_nds" : 0.41
                }
            }
        }
    };