#!/bin/sh

#DEBHELPER#

# Enable vertis-nodejs vhost
vertis-nodejs-service enable --silent yandex-sovetnik-redir

# Enable nginx vhost
# [ -f /etc/nginx/sites-available/302-yandex-sovetnik-stats.conf ] && ln -sf /etc/nginx/sites-available/302-yandex-sovetnik-stats.conf /etc/nginx/sites-enabled/302-yandex-sovetnik-stats.conf || echo 'WARNING ! ! ! NO NGINX VHOST FOUND ! ! !'

exit 0
