#!/bin/sh

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
yav-deploy --rsa-login robot-direct-yav-np --rsa-private-key /etc/direct-tokens/ssh-rsa_robot-direct-yav-np || printf '\n\npostinst FAILED, run yav-deploy manually\n\n'
