CREATE TABLE TEST_QRTZ_LOG (
  ID IDENTITY,
  JOB_NAME VARCHAR2(255) NOT NULL,
  JOB_GROUP VARCHAR2(255) NOT NULL,
  TRIGGER_FIRE_TIME TIMESTAMP NOT NULL,
  JOB_FINISHED_TIME TIMESTAMP,
  JOB_STATUS VARCHAR2(255),
  HOST_NAME VARCHAR2(255) NOT NULL,
  FULL_JOB_STATUS CLOB,
  TRACE_ID VARCHAR2(255)
);