#!/usr/bin/perl

### BEGIN INIT INFO
# Provides:          yandex-hbf-agent
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
### END INIT INFO

use Ubic::Run;
