package ru.yandex.crm.tests.delivery;

import java.io.*;
import java.util.*;

public class autoGeneratedTests
{
    public static void main(String [] args) throws IOException
    {   List cmdAndArgs = Arrays.asList("cmd", "/k", "start", "mrules.bat");
        File dir = new File("C:/work/crm-support/tests/rulesCheckGenerator/");
        ProcessBuilder pb = new ProcessBuilder(cmdAndArgs);
        pb.directory(dir);
        Process p = pb.start();
    }
}
