#!/bin/sh
### BEGIN INIT INFO
# Provides:          disable-transparent-hugepages
# Required-Start:    $local_fs
# Required-Stop:
# X-Start-Before:    mongod mongodb-mms-automation-agent
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Disable Linux transparent huge pages
# Description:       Disable Linux transparent huge pages, to improve
#                    database performance.
### END INIT INFO

if [ -d /sys/kernel/mm/transparent_hugepage ]; then
    thp_path=/sys/kernel/mm/transparent_hugepage
elif [ -d /sys/kernel/mm/redhat_transparent_hugepage ]; then
    thp_path=/sys/kernel/mm/redhat_transparent_hugepage
else
    exit 0
fi  

case $1 in
  start|restart|reload)
    echo "* Starting (disabling) THP now"
    echo 'never' > ${thp_path}/enabled
    echo 'never' > ${thp_path}/defrag
    exit 0
    ;;

  status)
    if grep -q '\[never\]' ${thp_path}/enabled && grep -q '\[never\]' ${thp_path}/defrag ; then
        echo "* Disable THP is running (THP disabled)"
        exit 0
    else
        echo "* Disable THP is not running (THP enabled)"
        exit 3
    fi

    ;;

  stop)
    echo "* Stopping (enabling) THP now"
    echo 'always' > ${thp_path}/enabled
    echo 'always' > ${thp_path}/defrag
    exit 0
    ;;

  *)
    echo "Usage: $0 {start|stop|status|restart|reload}" >&2
    
    ;;

esac

exit 1

