#!/bin/sh

### BEGIN INIT INFO
# Provides:          report-testing-assistant
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Report Testing Assistant daemon
# Description:       RTA helps to manage several independent Report instances
### END INIT INFO

DAEMON=/usr/local/bin/rta-daemon
DAEMON_NAME=report-testing-assistant
DAEMON_ARGUMENTS="-c /etc/yandex/$DAEMON_NAME.cfg"
DAEMON_LOG=/var/log/$DAEMON_NAME.log
DAEMON_USER=thoughteer
PIDFILE=/var/run/$DAEMON_NAME.pid

. /lib/lsb/init-functions

do_start () {
    log_daemon_msg "Starting system $DAEMON_NAME daemon"
    start-stop-daemon --start --background --pidfile $PIDFILE --make-pidfile --user $DAEMON_USER --chuid $DAEMON_USER --startas /bin/bash -- -c "exec $DAEMON $DAEMON_ARGUMENTS >> $DAEMON_LOG 2>&1"
    log_end_msg $?
}

do_stop () {
    log_daemon_msg "Stopping system $DAEMON_NAME daemon"
    pkill -TERM -P $(cat $PIDFILE)
    start-stop-daemon --stop --pidfile $PIDFILE --retry 10
    log_end_msg $?
}

case "$1" in
    start|stop)
        do_${1}
        ;;
    restart|reload|force-reload)
        do_stop
        do_start
        ;;
    status)
        status_of_proc "$DAEMON_NAME" "$DAEMON" && exit 0 || exit $?
        ;;
    *)
        echo "Usage: /etc/init.d/$DAEMON_NAME {start|stop|restart|status}"
        exit 1
        ;;
esac

exit 0
