import {
    createRecipe,
    createFilter,
    createFilterValue,
    createProduct,
    mergeState,
} from '@yandex-market/kadavr/mocks/Report/helpers';
import {getCatalogerMock} from './helpers';

export default {
    guruLight: {
        description: 'Тип "Гуру Лайт"',
        type: 'guruLight',
        routeParams: {
            'nid': 57743,
            'slug': 'parketnaia-doska',
            'local-offers-first': 0,
            'onstock': 1,
        },
        mocks: {
            'Cataloger.tree': getCatalogerMock({
                'category': {
                    'entity': 'category',
                    'fullName': 'Товары для строительства и ремонта',
                    'id': 91597,
                    'isLeaf': false,
                    'modelsCount': 591594,
                    'name': 'Строительство и ремонт',
                    'nid': 54503,
                    'offersCount': 4738408,
                    'type': 'gurulight',
                    'viewType': 'list',
                },
                'childrenType': 'mixed',
                'entity': 'navnode',
                'fullName': 'Строительство и ремонт',
                'hasPromo': false,
                'id': 54503,
                'isLeaf': false,
                'link': {
                    'params': {
                        'hid': [
                            '91597',
                        ],
                        'nid': [
                            '54503',
                        ],
                    },
                    'target': 'department',
                },
                'name': 'Строительство и ремонт',
                'navnodes': [{
                    'category': {
                        'entity': 'category',
                        'fullName': 'Строительные и отделочные материалы',
                        'id': 1618979,
                        'isLeaf': false,
                        'modelsCount': 21198,
                        'name': 'Материалы',
                        'nid': 55168,
                        'offersCount': 1779963,
                        'type': 'gurulight',
                        'viewType': 'list',
                    },
                    'childrenType': 'mixed',
                    'entity': 'navnode',
                    'fullName': 'Строительные и отделочные материалы',
                    'hasPromo': false,
                    'id': 55168,
                    'isLeaf': false,
                    'link': {
                        'params': {
                            'hid': [
                                '1618979',
                            ],
                            'nid': [
                                '55168',
                            ],
                        },
                        'target': 'catalog',
                    },
                    'name': 'Материалы',
                    'navnodes': [{
                        'category': {
                            'entity': 'category',
                            'fullName': 'Напольные покрытия',
                            'id': 12333619,
                            'isLeaf': false,
                            'modelsCount': 6,
                            'name': 'Напольные покрытия',
                            'nid': 60957,
                            'offersCount': 133817,
                            'type': 'gurulight',
                            'viewType': 'list',
                        },
                        'childrenType': 'mixed',
                        'entity': 'navnode',
                        'fullName': 'Напольные покрытия',
                        'hasPromo': false,
                        'id': 60957,
                        'isLeaf': false,
                        'link': {
                            'params': {
                                'hid': [
                                    '12333619',
                                ],
                                'nid': [
                                    '60957',
                                ],
                            },
                            'target': 'catalog',
                        },
                        'name': 'Напольные покрытия',
                        'navnodes': [{
                            'category': {
                                'entity': 'category',
                                'fullName': 'Паркетная доска',
                                'id': 91637,
                                'isLeaf': true,
                                'modelsCount': 0,
                                'name': 'Паркетная доска',
                                'nid': 57743,
                                'offersCount': 17973,
                                'type': 'gurulight',
                                'viewType': 'list',
                            },
                            'childrenType': 'gurulight',
                            'entity': 'navnode',
                            'fullName': 'Паркетная доска',
                            'hasPromo': false,
                            'id': 57743,
                            'isLeaf': true,
                            'link': {
                                'params': {
                                    'hid': [
                                        '91637',
                                    ],
                                    'nid': [
                                        '57743',
                                    ],
                                },
                                'target': 'catalog',
                            },
                            'name': 'Паркетная доска',
                            'rootNavnode': {
                                'entity': 'navnode',
                                'id': 54503,
                            },
                            'slug': 'parketnaia-doska',
                            'type': 'category',
                        }],
                        'rootNavnode': {
                            'entity': 'navnode',
                            'id': 54503,
                        },
                        'slug': 'napolnye-pokrytiia',
                        'type': 'category',
                    }],
                    'rootNavnode': {
                        'entity': 'navnode',
                        'id': 54503,
                    },
                    'slug': 'stroitelnye-i-otdelochnye-materialy',
                    'type': 'category',
                }],
                'rootNavnode': {
                    'entity': 'navnode',
                    'id': 54503,
                },
                'slug': 'stroitelstvo-i-remont',
                'type': 'category',
            }),
            'report': mergeState([
                createProduct({slug: 'product'}, 1),
            ]),
        },
    },
    guruLightWithRecipe: {
        description: 'Тип "Гуру Лайт с рецептом"',
        type: 'guruLightWithRecipe',
        routeParams: {
            'nid': 57736,
            'slug': 'laminat-quick-step',
            'local-offers-first': 0,
            'glfilter': '7893318:10716686',
            'onstock': 1,
        },
        params: {
            breadcrumbsText: [
                'Строительство и ремонт',
                'Строительные и отделочные материалы',
                'Напольные покрытия',
                'Ламинат',
                'Ламинат Quick-Step',
            ],
        },
        mocks: {
            'report': mergeState([
                createProduct({slug: 'product'}, '1'),
                createRecipe({
                    'entity': 'recipe',
                    'id': 11243,
                    'header': 'Ламинат Quick-Step',
                    'name': 'Ламинат Quick-Step',
                    'slug': 'laminat-quick-step',
                    'shortName': 'Quick-Step',
                    'category': {
                        'id': 91640,
                        'navigationId': 57736,
                    },
                    'popularity': 79551,
                    'buttonIndex': 0,
                    'filters': [{
                        'id': '7893318',
                        'type': 'enum',
                        'name': 'Производитель',
                        'xslname': 'vendor',
                        'subType': '',
                        'kind': 1,
                        'position': 1,
                        'valuesCount': 1,
                        'values': [{
                            'initialFound': 0,
                            'checked': true,
                            'found': 0,
                            'value': 'Quick-Step',
                            'vendor': {
                                'name': 'Quick-Step',
                                'entity': 'vendor',
                                'id': 10716686,
                            },
                            'id': '10716686',
                        }],
                        'valuesGroups': [{
                            'type': 'all',
                            'valuesIds': [
                                '10716686',
                            ],
                        }],
                    }],
                }, '11243'),
            ]),
            'Cataloger.tree': getCatalogerMock({
                'category': {
                    'entity': 'category',
                    'fullName': 'Товары для строительства и ремонта',
                    'id': 91597,
                    'isLeaf': false,
                    'modelsCount': 596277,
                    'name': 'Строительство и ремонт',
                    'nid': 54503,
                    'offersCount': 4847871,
                    'type': 'gurulight',
                    'viewType': 'list',
                },
                'childrenType': 'mixed',
                'entity': 'navnode',
                'fullName': 'Строительство и ремонт',
                'hasPromo': false,
                'id': 54503,
                'isLeaf': false,
                'link': {
                    'params': {
                        'hid': [
                            '91597',
                        ],
                        'nid': [
                            '54503',
                        ],
                    },
                    'target': 'department',
                },
                'name': 'Строительство и ремонт',
                'navnodes': [{
                    'category': {
                        'entity': 'category',
                        'fullName': 'Строительные и отделочные материалы',
                        'id': 1618979,
                        'isLeaf': false,
                        'modelsCount': 21441,
                        'name': 'Материалы',
                        'nid': 55168,
                        'offersCount': 1797900,
                        'type': 'gurulight',
                        'viewType': 'list',
                    },
                    'childrenType': 'mixed',
                    'entity': 'navnode',
                    'fullName': 'Строительные и отделочные материалы',
                    'hasPromo': false,
                    'id': 55168,
                    'isLeaf': false,
                    'link': {
                        'params': {
                            'hid': [
                                '1618979',
                            ],
                            'nid': [
                                '55168',
                            ],
                        },
                        'target': 'catalog',
                    },
                    'name': 'Материалы',
                    'navnodes': [{
                        'category': {
                            'entity': 'category',
                            'fullName': 'Напольные покрытия',
                            'id': 12333619,
                            'isLeaf': false,
                            'modelsCount': 6,
                            'name': 'Напольные покрытия',
                            'nid': 60957,
                            'offersCount': 136559,
                            'type': 'gurulight',
                            'viewType': 'list',
                        },
                        'childrenType': 'mixed',
                        'entity': 'navnode',
                        'fullName': 'Напольные покрытия',
                        'hasPromo': false,
                        'id': 60957,
                        'isLeaf': false,
                        'link': {
                            'params': {
                                'hid': [
                                    '12333619',
                                ],
                                'nid': [
                                    '60957',
                                ],
                            },
                            'target': 'catalog',
                        },
                        'name': 'Напольные покрытия',
                        'navnodes': [{
                            'category': {
                                'entity': 'category',
                                'fullName': 'Ламинат',
                                'id': 91640,
                                'isLeaf': true,
                                'modelsCount': 3,
                                'name': 'Ламинат',
                                'nid': 57736,
                                'offersCount': 56134,
                                'type': 'gurulight',
                                'viewType': 'list',
                            },
                            'childrenType': 'gurulight',
                            'entity': 'navnode',
                            'fullName': 'Ламинат',
                            'hasPromo': false,
                            'id': 57736,
                            'isLeaf': true,
                            'link': {
                                'params': {
                                    'hid': [
                                        '91640',
                                    ],
                                    'nid': [
                                        '57736',
                                    ],
                                },
                                'target': 'catalog',
                            },
                            'name': 'Ламинат',
                            'rootNavnode': {
                                'entity': 'navnode',
                                'id': 54503,
                            },
                            'slug': 'laminat',
                            'type': 'category',
                        }],
                        'rootNavnode': {
                            'entity': 'navnode',
                            'id': 54503,
                        },
                        'slug': 'napolnye-pokrytiia',
                        'type': 'category',
                    }],
                    'rootNavnode': {
                        'entity': 'navnode',
                        'id': 54503,
                    },
                    'slug': 'stroitelnye-i-otdelochnye-materialy',
                    'type': 'category',
                }],
                'rootNavnode': {
                    'entity': 'navnode',
                    'id': 54503,
                },
                'slug': 'stroitelstvo-i-remont',
                'type': 'category',
            }),
        },
    },
    guru: {
        description: 'Тип "Гуру"',
        type: 'guru',
        routeParams: {
            'nid': 54726,
            'slug': 'mobilnye-telefony',
            'local-offers-first': 0,
            'onstock': 1,
        },
        mocks: {
            'Cataloger.tree': getCatalogerMock({
                'category': {
                    'entity': 'category',
                    'fullName': 'Электроника',
                    'id': 198119,
                    'isLeaf': false,
                    'modelsCount': 124572,
                    'name': 'Электроника',
                    'slug': 'elektronika',
                    'nid': 54440,
                    'offersCount': 1418191,
                    'type': 'gurulight',
                    'viewType': 'list',
                },
                'childrenType': 'mixed',
                'entity': 'navnode',
                'fullName': 'Электроника',
                'hasPromo': false,
                'id': 54440,
                'isLeaf': false,
                'link': {
                    'params': {
                        'hid': [
                            '198119',
                        ],
                        'nid': [
                            '54440',
                        ],
                    },
                    'target': 'department',
                },
                'name': 'Электроника',
                'navnodes': [{
                    'category': {
                        'entity': 'category',
                        'fullName': 'Телефоны и аксессуары к ним',
                        'slug': 'telefony-i-aksessuary-k-nim',
                        'id': 91461,
                        'isLeaf': false,
                        'modelsCount': 16660,
                        'name': 'Телефоны',
                        'nid': 54437,
                        'offersCount': 766969,
                        'type': 'gurulight',
                        'viewType': 'list',
                    },
                    'childrenType': 'mixed',
                    'entity': 'navnode',
                    'fullName': 'Телефоны и аксессуары к ним',
                    'hasPromo': false,
                    'id': 54437,
                    'isLeaf': false,
                    'link': {
                        'params': {
                            'hid': [
                                '91461',
                            ],
                            'nid': [
                                '54437',
                            ],
                        },
                        'target': 'catalog',
                    },
                    'name': 'Телефоны',
                    'navnodes': [{
                        'category': {
                            'entity': 'category',
                            'fullName': 'Мобильные телефоны',
                            'slug': 'mobilnye-telefony',
                            'id': 91491,
                            'isLeaf': true,
                            'modelsCount': 2763,
                            'name': 'Мобильные телефоны',
                            'nid': 54726,
                            'offersCount': 81728,
                            'type': 'guru',
                            'viewType': 'grid',
                        },
                        'childrenType': 'mixed',
                        'entity': 'navnode',
                        'fullName': 'Мобильные телефоны',
                        'hasPromo': false,
                        'id': 54726,
                        'isLeaf': true,
                        'link': {
                            'params': {
                                'hid': [
                                    '91491',
                                ],
                                'nid': [
                                    '54726',
                                ],
                            },
                            'target': 'catalogleaf',
                        },
                        'name': 'Мобильные телефоны',
                        'rootNavnode': {
                            'entity': 'navnode',
                            'id': 54440,
                        },
                        'slug': 'mobilnye-telefony',
                        'type': 'category',
                    }],
                    'rootNavnode': {
                        'entity': 'navnode',
                        'id': 54440,
                    },
                    'slug': 'telefony-i-aksessuary-k-nim',
                    'type': 'category',
                }],
                'rootNavnode': {
                    'entity': 'navnode',
                    'id': 54440,
                },
                'slug': 'elektronika',
                'type': 'category',
            }),
            'report': mergeState([
                createProduct({slug: 'product'}, 1),
            ]),
        },
    },
    guruWithParametrizedHeader: {
        description: 'Тип "Гуру с параметрическим заголовком"',
        type: 'guruWithParametrizedHeader',
        routeParams: {
            'nid': 56199,
            'slug': 'fotoapparaty-s-podderzhkoi-raw',
            'local-offers-first': 0,
            'glfilter': '4892381:1',
            'onstock': 1,
        },
        params: {
            breadcrumbsText: [
                'Электроника',
                'Фото- и видеокамеры',
                'Фотоаппараты',
            ],
        },
        mocks: {
            'report': mergeState([
                createProduct({slug: 'product'}, '1'),
                createFilter({
                    type: 'boolean',
                    name: 'Поддержка RAW',
                }, '4892381'),
                createFilterValue({value: '1', checked: true}, '4892381', '1'),
                createFilterValue({value: '0'}, '4892381', '0'),
            ]),
            'Cataloger.tree': getCatalogerMock({
                'category': {
                    'entity': 'category',
                    'fullName': 'Электроника',
                    'id': 198119,
                    'isLeaf': false,
                    'modelsCount': 124572,
                    'name': 'Электроника',
                    'nid': 54440,
                    'offersCount': 1418191,
                    'type': 'gurulight',
                    'viewType': 'list',
                },
                'childrenType': 'mixed',
                'entity': 'navnode',
                'fullName': 'Электроника',
                'hasPromo': false,
                'id': 54440,
                'isLeaf': false,
                'link': {
                    'params': {
                        'hid': [
                            '198119',
                        ],
                        'nid': [
                            '54440',
                        ],
                    },
                    'target': 'department',
                },
                'name': 'Электроника',
                'navnodes': [{
                    'category': {
                        'entity': 'category',
                        'fullName': 'Фото и видеокамеры',
                        'id': 90607,
                        'isLeaf': false,
                        'modelsCount': 14383,
                        'name': 'Фото и видеокамеры',
                        'nid': 54778,
                        'offersCount': 181040,
                        'type': 'gurulight',
                        'viewType': 'list',
                    },
                    'childrenType': 'mixed',
                    'entity': 'navnode',
                    'fullName': 'Фото- и видеокамеры',
                    'hasPromo': false,
                    'id': 54778,
                    'isLeaf': false,
                    'link': {
                        'params': {
                            'hid': [
                                '90607',
                            ],
                            'nid': [
                                '54778',
                            ],
                        },
                        'target': 'catalog',
                    },
                    'name': 'Фото- и видеокамеры',
                    'navnodes': [{
                        'category': {
                            'entity': 'category',
                            'fullName': 'Фотоаппараты',
                            'id': 91148,
                            'isLeaf': true,
                            'modelsCount': 618,
                            'name': 'Фотоаппараты',
                            'nid': 56199,
                            'offersCount': 33589,
                            'type': 'guru',
                            'viewType': 'grid',
                        },
                        'childrenType': 'guru',
                        'entity': 'navnode',
                        'fullName': 'Фотоаппараты',
                        'hasPromo': false,
                        'id': 56199,
                        'isLeaf': false,
                        'link': {
                            'params': {
                                'hid': [
                                    '91148',
                                ],
                                'nid': [
                                    '56199',
                                ],
                            },
                            'target': 'catalogleaf',
                        },
                        'name': 'Фотоаппараты',
                        'rootNavnode': {
                            'entity': 'navnode',
                            'id': 54440,
                        },
                        'slug': 'fotoapparaty',
                        'type': 'category',
                    }],
                    'rootNavnode': {
                        'entity': 'navnode',
                        'id': 54440,
                    },
                    'slug': 'foto-i-videokamery',
                    'type': 'category',
                }],
                'rootNavnode': {
                    'entity': 'navnode',
                    'id': 54440,
                },
                'slug': 'elektronika',
                'type': 'category',
            }),
        },
    },
    guruWithRecipe: {
        description: 'Тип "Гуру" c рецептом',
        type: 'guruWithRecipe',
        routeParams: {
            nid: 54726,
            slug: 'smartfony',
            glfilter: '4940921:13475069',
        },
        params: {
            breadcrumbsText: [
                'Электроника',
                'Телефоны и аксессуары к ним',
                'Мобильные телефоны',
                'Смартфоны',
            ],
        },
        mocks: {
            'report': mergeState([
                createProduct({slug: 'product'}, '1'),
                createRecipe({
                    'entity': 'recipe',
                    'id': 407126144,
                    'header': 'Смартфоны',
                    'name': 'Смартфоны',
                    'slug': 'smartfony',
                    'shortName': 'Смартфоны',
                    'category': {
                        'id': 91491,
                        'navigationId': 54726,
                    },
                    'popularity': 5760877,
                    'buttonIndex': 0,
                    'filters': [{
                        'id': '4940921',
                        'type': 'enum',
                        'name': 'Тип',
                        'xslname': 'Type',
                        'subType': '',
                        'kind': 1,
                        'position': 3,
                        'valuesCount': 1,
                        'values': [{
                            'initialFound': 0,
                            'checked': true,
                            'found': 0,
                            'value': 'смартфон',
                            'id': '13475069',
                        }],
                        'valuesGroups': [{
                            'type': 'all',
                            'valuesIds': [
                                '13475069',
                            ],
                        }],
                    }],
                }, '407126144'),
            ]),
            'Cataloger.tree': getCatalogerMock({
                'category': {
                    'entity': 'category',
                    'fullName': 'Электроника',
                    'id': 198119,
                    'isLeaf': false,
                    'modelsCount': 106301,
                    'name': 'Электроника',
                    'nid': 54440,
                    'offersCount': 710787,
                    'type': 'gurulight',
                    'viewType': 'list',
                },
                'childrenType': 'mixed',
                'entity': 'navnode',
                'fullName': 'Электроника',
                'hasPromo': false,
                'id': 54440,
                'isLeaf': false,
                'link': {
                    'params': {
                        'hid': [
                            '198119',
                        ],
                        'nid': [
                            '54440',
                        ],
                    },
                    'target': 'department',
                },
                'name': 'Электроника',
                'navnodes': [{
                    'category': {
                        'entity': 'category',
                        'fullName': 'Телефоны и аксессуары к ним',
                        'id': 91461,
                        'isLeaf': false,
                        'modelsCount': 14603,
                        'name': 'Телефоны',
                        'nid': 54437,
                        'offersCount': 384303,
                        'type': 'gurulight',
                        'viewType': 'list',
                    },
                    'childrenType': 'mixed',
                    'entity': 'navnode',
                    'fullName': 'Телефоны и аксессуары к ним',
                    'hasPromo': false,
                    'id': 54437,
                    'isLeaf': false,
                    'link': {
                        'params': {
                            'hid': [
                                '91461',
                            ],
                            'nid': [
                                '54437',
                            ],
                        },
                        'target': 'catalog',
                    },
                    'name': 'Телефоны',
                    'navnodes': [{
                        'category': {
                            'entity': 'category',
                            'fullName': 'Мобильные телефоны',
                            'id': 91491,
                            'isLeaf': true,
                            'modelsCount': 2469,
                            'name': 'Мобильные телефоны',
                            'nid': 54726,
                            'offersCount': 41407,
                            'type': 'guru',
                            'viewType': 'grid',
                        },
                        'childrenType': 'mixed',
                        'entity': 'navnode',
                        'fullName': 'Мобильные телефоны',
                        'hasPromo': false,
                        'id': 54726,
                        'isLeaf': true,
                        'link': {
                            'params': {
                                'hid': [
                                    '91491',
                                ],
                                'nid': [
                                    '54726',
                                ],
                            },
                            'target': 'catalogleaf',
                        },
                        'name': 'Мобильные телефоны',
                        'rootNavnode': {
                            'entity': 'navnode',
                            'id': 54440,
                        },
                        'slug': 'mobilnye-telefony',
                        'type': 'category',
                    }],
                    'rootNavnode': {
                        'entity': 'navnode',
                        'id': 54440,
                    },
                    'slug': 'telefony-i-aksessuary-k-nim',
                    'type': 'category',
                }],
                'rootNavnode': {
                    'entity': 'navnode',
                    'id': 54440,
                },
                'slug': 'elektronika',
                'type': 'category',
            }),
        },
    },
    clustered: {
        description: 'Тип "Кластеризованная"',
        type: 'clustered',
        routeParams: {
            'nid': 57254,
            'slug': 'zhenskie-kolgotki-i-chulki',
            'local-offers-first': 0,
            'onstock': 1,
        },
        mocks: {
            'Cataloger.tree': getCatalogerMock({
                'category': {
                    'entity': 'category',
                    'fullName': 'Одежда, обувь и аксессуары',
                    'id': 7877999,
                    'isLeaf': false,
                    'modelsCount': 217875,
                    'name': 'Одежда, обувь и аксессуары',
                    'nid': 54432,
                    'offersCount': 1941366,
                    'type': 'gurulight',
                    'viewType': 'list',
                },
                'childrenType': 'mixed',
                'entity': 'navnode',
                'fullName': 'Одежда, обувь и аксессуары',
                'hasPromo': false,
                'id': 54432,
                'isLeaf': false,
                'link': {
                    'params': {
                        'hid': [
                            '7877999',
                        ],
                        'nid': [
                            '54432',
                        ],
                    },
                    'target': 'department',
                },
                'name': 'Одежда и обувь',
                'navnodes': [{
                    'category': {
                        'entity': 'category',
                        'fullName': 'Женская одежда',
                        'id': 7811873,
                        'isLeaf': false,
                        'modelsCount': 0,
                        'name': 'Женская одежда',
                        'nid': 54602,
                        'offersCount': 506268,
                        'type': 'gurulight',
                        'viewType': 'list',
                    },
                    'childrenType': 'mixed',
                    'entity': 'navnode',
                    'fullName': 'Женская одежда',
                    'hasPromo': false,
                    'id': 54602,
                    'isLeaf': false,
                    'link': {
                        'params': {
                            'hid': [
                                '7811873',
                            ],
                            'nid': [
                                '54602',
                            ],
                        },
                        'target': 'catalog',
                    },
                    'name': 'Женская одежда',
                    'navnodes': [{
                        'category': {
                            'entity': 'category',
                            'fullName': 'Женское нижнее белье и купальники',
                            'id': 7811892,
                            'isLeaf': false,
                            'modelsCount': 0,
                            'name': 'Белье и купальники',
                            'nid': 55657,
                            'offersCount': 63502,
                            'type': 'gurulight',
                            'viewType': 'list',
                        },
                        'childrenType': 'clusters',
                        'entity': 'navnode',
                        'fullName': 'Женское нижнее белье и купальники',
                        'hasPromo': false,
                        'id': 55657,
                        'isLeaf': false,
                        'link': {
                            'params': {
                                'hid': [
                                    '7811892',
                                ],
                                'nid': [
                                    '55657',
                                ],
                            },
                            'target': 'catalog',
                        },
                        'name': 'Белье и купальники',
                        'navnodes': [{
                            'category': {
                                'entity': 'category',
                                'fullName': 'Женские колготки и чулки',
                                'id': 7811933,
                                'isLeaf': true,
                                'modelsCount': 0,
                                'name': 'Колготки и чулки',
                                'nid': 57254,
                                'offersCount': 24709,
                                'type': 'clusters',
                                'viewType': 'grid',
                                'warnings': [{
                                    'type': 'goods_return_rules',
                                    'value': {
                                        'full': 'Товар не подлежит возврату или обмену',
                                        'short': 'Товар не подлежит возврату или обмену',
                                    },
                                }],
                            },
                            'childrenType': 'clusters',
                            'entity': 'navnode',
                            'fullName': 'Женские колготки и чулки',
                            'hasPromo': false,
                            'id': 57254,
                            'isLeaf': true,
                            'link': {
                                'params': {
                                    'hid': [
                                        '7811933',
                                    ],
                                    'nid': [
                                        '57254',
                                    ],
                                },
                                'target': 'catalog',
                            },
                            'name': 'Колготки и чулки',
                            'rootNavnode': {
                                'entity': 'navnode',
                                'id': 54432,
                            },
                            'slug': 'zhenskie-kolgotki-i-chulki',
                            'type': 'category',
                        }],
                        'rootNavnode': {
                            'entity': 'navnode',
                            'id': 54432,
                        },
                        'slug': 'zhenskoe-nizhnee-bele-i-kupalniki',
                        'type': 'category',
                    }],
                    'rootNavnode': {
                        'entity': 'navnode',
                        'id': 54432,
                    },
                    'slug': 'zhenskaia-odezhda',
                    'type': 'category',
                }],
                'rootNavnode': {
                    'entity': 'navnode',
                    'id': 54432,
                },
                'slug': 'odezhda-obuv-i-aksessuary',
                'type': 'category',
            }),
            'report': mergeState([
                createProduct({slug: 'product'}, 1),
            ]),
        },
    },
    clusteredWithRecipe: {
        description: 'Тип "Кластеризованная с рецептом"',
        type: 'clusteredWithRecipe',
        routeParams: {
            'nid': 69476,
            'slug': 'zhenskie-dzhinsy-diesel',
            'local-offers-first': 0,
            'glfilter': '7893318:2638554',
            'onstock': 1,
        },
        params: {
            breadcrumbsText: [
                'Одежда, обувь и аксессуары',
                'Женщинам',
                'Женская одежда',
                'Женские джинсы',
                'Женские джинсы Diesel',
            ],
        },
        mocks: {
            'report': mergeState([
                createRecipe({
                    'entity': 'recipe',
                    'id': 9944,
                    'header': 'Женские джинсы Diesel',
                    'name': 'Женские джинсы Diesel',
                    'slug': 'zhenskie-dzhinsy-diesel',
                    'shortName': 'Diesel',
                    'category': {
                        'id': 7811907,
                        'navigationId': 57290,
                    },
                    'popularity': 220,
                    'buttonIndex': 0,
                    'filters': [{
                        'id': '7893318',
                        'type': 'enum',
                        'name': 'Производитель',
                        'xslname': 'vendor',
                        'subType': '',
                        'kind': 1,
                        'position': 1,
                        'valuesCount': 1,
                        'values': [{
                            'initialFound': 0,
                            'checked': true,
                            'found': 0,
                            'value': 'DIESEL',
                            'vendor': {
                                'name': 'DIESEL',
                                'entity': 'vendor',
                                'id': 2638554,
                            },
                            'id': '2638554',
                        }],
                        'valuesGroups': [{
                            'type': 'all',
                            'valuesIds': [
                                '2638554',
                            ],
                        }],
                    }],
                }, '9944'),
            ]),
            'Cataloger.tree': getCatalogerMock({
                'category': {
                    'entity': 'category',
                    'fullName': 'Одежда, обувь и аксессуары',
                    'id': 7877999,
                    'isLeaf': false,
                    'modelsCount': 217875,
                    'name': 'Одежда, обувь и аксессуары',
                    'nid': 54432,
                    'offersCount': 1941366,
                    'type': 'gurulight',
                    'viewType': 'list',
                },
                'childrenType': 'mixed',
                'entity': 'navnode',
                'fullName': 'Одежда, обувь и аксессуары',
                'hasPromo': false,
                'id': 54432,
                'isLeaf': false,
                'link': {
                    'params': {
                        'hid': [
                            '7877999',
                        ],
                        'nid': [
                            '54432',
                        ],
                    },
                    'target': 'department',
                },
                'name': 'Одежда и обувь',
                'navnodes': [{
                    'childrenType': 'mixed',
                    'entity': 'navnode',
                    'fullName': 'Женщинам',
                    'hasPromo': false,
                    'id': 68790,
                    'isLeaf': false,
                    'link': {
                        'params': {
                            'nid': [
                                '68790',
                            ],
                        },
                        'target': 'catalog',
                    },
                    'name': 'Женщинам',
                    'navnodes': [{
                        'category': {
                            'entity': 'category',
                            'fullName': 'Женская одежда',
                            'id': 7811873,
                            'isLeaf': false,
                            'modelsCount': 0,
                            'name': 'Женская одежда',
                            'nid': 69470,
                            'offersCount': 506268,
                            'type': 'gurulight',
                            'viewType': 'list',
                        },
                        'childrenType': 'mixed',
                        'entity': 'navnode',
                        'fullName': 'Женская одежда',
                        'hasPromo': false,
                        'id': 69470,
                        'isLeaf': false,
                        'link': {
                            'params': {
                                'hid': [
                                    '7811873',
                                ],
                                'nid': [
                                    '69470',
                                ],
                            },
                            'target': 'catalog',
                        },
                        'name': 'Одежда',
                        'navnodes': [{
                            'category': {
                                'entity': 'category',
                                'fullName': 'Женские джинсы',
                                'id': 7811907,
                                'isLeaf': true,
                                'modelsCount': 0,
                                'name': 'Джинсы',
                                'nid': 69476,
                                'offersCount': 11051,
                                'type': 'clusters',
                                'viewType': 'grid',
                                'warnings': [{
                                    'type': 'goods_return_rules',
                                    'value': {
                                        'full': 'Товар можно вернуть в течение 7 дней после получения',
                                        'short': 'Товар можно вернуть в течение 7 дней после получения',
                                    },
                                }],
                            },
                            'childrenType': 'clusters',
                            'entity': 'navnode',
                            'fullName': 'Женские джинсы',
                            'hasPromo': false,
                            'id': 69476,
                            'isLeaf': true,
                            'link': {
                                'params': {
                                    'hid': [
                                        '7811907',
                                    ],
                                    'nid': [
                                        '69476',
                                    ],
                                },
                                'target': 'catalog',
                            },
                            'name': 'Джинсы',
                            'rootNavnode': {
                                'entity': 'navnode',
                                'id': 54432,
                            },
                            'slug': 'zhenskie-dzhinsy',
                            'type': 'category',
                        }],
                        'rootNavnode': {
                            'entity': 'navnode',
                            'id': 54432,
                        },
                        'slug': 'zhenskaia-odezhda',
                        'type': 'category',
                    }],
                    'rootNavnode': {
                        'entity': 'navnode',
                        'id': 54432,
                    },
                    'slug': 'zhenshchinam',
                    'type': 'virtual',
                }],
                'rootNavnode': {
                    'entity': 'navnode',
                    'id': 54432,
                },
                'slug': 'odezhda-obuv-i-aksessuary',
                'type': 'category',
            }),
        },
    },
};
