-- auto-generated definition
CREATE TABLE COOrderEvent
(
    ORDER_ID            BIGINT         NOT NULL,
    EVENT_ID            BIGINT         NOT NULL,
    EVENT_TYPE          NVARCHAR(100)  NOT NULL,
    CREATED_AT          DATETIME       NOT NULL,
    UPDATED_AT          DATETIME       NOT NULL,
    PREV_STATUS         NVARCHAR(100),
    STATUS              NVARCHAR(100)  NOT NULL,
    BUYER_CURRENCY      NVARCHAR(100)  NOT NULL,
    PAYMENT_TYPE        NVARCHAR(100)  NOT NULL,
    DELIVERY_TYPE       NVARCHAR(100)  NOT NULL,
    DELIVERY_DATE       DATE           NOT NULL,
    DELIVERY_ADDRESS    NVARCHAR(3999) NOT NULL,
    DELIVERY_REGION_ID  INT,
    DELIVERY_CITY       NVARCHAR(200)  NOT NULL,
    DELIVERY_PRICE      DECIMAL,
    DELIVERY_SERVICE_ID INT,
    USER_ID             BIGINT         NOT NULL,
    ID                  BIGINT IDENTITY,
    MOD_TS              DATETIME,
    EXPORT_TS           DATETIME,
    IMPORT_TS           DATETIME,
    IMPORT_STATUS       INT,
    SUBSTATUS           NVARCHAR(100),
    PREV_SUBSTATUS      NVARCHAR(100),
    OUTLET_CODE         NVARCHAR(127),
    CERTIFICATE_ID      BIGINT,
    PS_CONTRACT_EXT_ID  NVARCHAR(100),
    PAYMENT_METHOD      NVARCHAR(100)  NOT NULL DEFAULT (''),
    BNPL                INT,
    REASON              INT,
    AUTHOR_ROLE         INT,
    PARTIAL_AVAILABLE   INT,
    PAYMENTPROPERTIES   NVARCHAR(MAX) NULL,
    BALANCE_CLIENT_ID   BIGINT,
    CONTRACT_ID         BIGINT,
    BUSINESSRECIPIENT   NVARCHAR(MAX) NULL
);

CREATE INDEX ImportStatusIdx
  ON COOrderEvent (IMPORT_STATUS);

CREATE INDEX IDIdx
  ON COOrderEvent (ID);

-- auto-generated definition
CREATE TABLE COOrderItem
(
  ORDER_ID      BIGINT,
  EVENT_ID      BIGINT,
  ITEM_ID       BIGINT,
  SHOP_PROMO_ID NVARCHAR (200),
  SUPPLIER_ID   BIGINT,
  SUPPLIER_TYPE NVARCHAR (100),
  SSKU          NVARCHAR (100),
  MSKU          BIGINT,
  COUNT         INT,
  PRICE         DECIMAL,
  VAT           NVARCHAR (100),
  ID            BIGINT IDENTITY,
  MOD_TS        DATETIME,
  EXPORT_TS     DATETIME,
  IMPORT_TS     DATETIME,
  IMPORT_STATUS INT,
  WAREHOUSE_ID  INT,
  SPASIBO       DECIMAL     NOT NULL,
);

CREATE INDEX OrderEventIdIdx
  ON COOrderItem (ORDER_ID, EVENT_ID);

--
CREATE TABLE COReturn
(
  ORDER_ID      BIGINT,
  EVENT_ID      BIGINT,
  RETURN_ID     BIGINT,
  STATUS        NVARCHAR (100),
  PREV_STATUS   NVARCHAR (100),
  CREATED_AT    DATETIME,
  UPDATED_AT    DATETIME,
  ID            BIGINT IDENTITY,
  MOD_TS        DATETIME,
  EXPORT_TS     DATETIME,
  IMPORT_TS     DATETIME,
  IMPORT_STATUS INT,
  PAY_OFFLINE   BIT
);

CREATE TABLE COReturnItem
(
  ORDER_ID    BIGINT,
  EVENT_ID    BIGINT,
  RETURN_ID   BIGINT,
  ITEM_ID     BIGINT,
  IS_DELIVERY BIT,
  COUNT       INT,
  PROPER_QUALITY BIT,
  ID            BIGINT IDENTITY,
  MOD_TS        DATETIME,
  EXPORT_TS     DATETIME,
  IMPORT_TS     DATETIME,
  IMPORT_STATUS INT
);

CREATE TABLE COPromo
(
  ORDER_ID              BIGINT        NOT NULL,
  EVENT_ID              BIGINT        NOT NULL,
  PROMO_ID              BIGINT        NOT NULL,
  TYPE                  NVARCHAR(100) NOT NULL,
  SUBSCRIPTION_ORDER_ID BIGINT,
  DELIVERY_DISCOUNT     DECIMAL       NOT NULL,
  ID                    BIGINT IDENTITY NOT NULL,
  MOD_TS                DATETIME      NOT NULL,
  EXPORT_TS             DATETIME      NOT NULL,
  IMPORT_TS             DATETIME,
  IMPORT_STATUS         INT           NOT NULL
);

CREATE TABLE COExternalCertificateIN
(
  CERTIFICATE_ID        INT      NOT NULL,
  CREATION_DATE         DATETIME NOT NULL,
  EXPIRATION_DATE       DATETIME NOT NULL,
  EXTERNAL_PAYMENT_DATE DATETIME NOT NULL,
  EXTERNAL_PAYMENT_ID   NVARCHAR(100) NOT NULL,
  PAYMENT_REGISTERED_AT DATETIME,
  MSKU                  BIGINT   NOT NULL,
  SSKU                  NVARCHAR(100) NOT NULL,
  SUPPLIER_TYPE         NVARCHAR(100) NOT NULL,
  SUPPLIER_ID           BIGINT   NOT NULL,
  PRICE                 DECIMAL  NOT NULL,
  VAT                   NVARCHAR(100) NOT NULL,
  WAREHOUSE_ID          INT      NOT NULL,
  STATUS                NVARCHAR(100) NOT NULL,
  STATUS_UPDATE_DATE    DATETIME NOT NULL,
  UPDATE_DATE           DATETIME NOT NULL,
  ID                    BIGINT IDENTITY NOT NULL,
  MOD_TS                DATETIME NOT NULL,
  EXPORT_TS             DATETIME NOT NULL,
  IMPORT_TS             DATETIME,
  IMPORT_STATUS         INT      NOT NULL
);
