package ru.yandex.direct.core.testing.info;

public enum FeedDefectIdsEnum {
    FEED_NAME_CANNOT_BE_EMPTY,
    FEED_INVALID_HREF,
    URL_CANNOT_BE_NULL,
    URL_IS_FAKE,
    FILE_DATA_CANNOT_BE_NULL,
    FEED_INVALID_FILENAME,
    FEED_LOGIN_IS_NOT_SET,
    FEED_LOGIN_CANNOT_BE_EMPTY,
    LOGIN_LENGTH_CANNOT_BE_MORE_THAN_MAX,
    FEED_PASSWORD_IS_NOT_SET,
    FEED_PASSWORD_CANNOT_BE_EMPTY,
    EMAIL_INVALID_VALUE,
    SHOP_NAME_CANNOT_BE_NULL,
    SHOP_NAME_CANNOT_BE_EMPTY,
}

