/* eslint-disable */
import { TestSuite, LoadSchemaType } from '../types';
import {
    catalogueV1BuiltinCollections,
    catalogueV1Categories,
    catalogueV1Collections,
    catalogueV1CompilationsSlug,
    catalogueV1Dialogs2,
    catalogueV1DialogsSearch,
    catalogueV1DialogsSkillIdAccountLinking,
    catalogueV1DialogsSkillIdSlug,
    catalogueV1DialogsSlug,
    catalogueV1DialogsSuggest,
    catalogueV1ExperimentsYandexuid,
    catalogueV1PagesMain,
    catalogueV1Reviewform,
    catalogueV1SmartHomeGetNativeSkills,
} from '../test-cases/catalogue';
import {
    devconsoleV1SkillsSkillIdDraft,
    devConsoleV1SkillsSkillIdDraftActionsWithdraw,
    devconsoleV1SkillsSkillIdFlags,
    devConsoleV1SkillsLogo,
    devConsoleV1SkillsMessage,
    devConsoleV1SkillsOperations,
    devConsoleV1SkillReviews,
    devConsoleV1SkillsRelease,
    devConsoleV1SkillsCandidate,
    devConsoleV1SkillsActionsStop,
    devConsoleV1SkillsSkillId,
    devConsoleV1EmailSend,
    devConsoleV1Subscription,
    devConsoleV1ModerationSkillSkillIdValidateToken,
    devConsoleV1Snapshot,
    devConsoleV1Skills,
    devConsoleV1SkillsNotificationsPhone,
} from '../test-cases/dev-console';
import {
    externalV2Chats,
    externalV2ChatsSkillId,
    externalV2ChatsSkillIdDraftStatus,
    externalV2SkillsBulkGet,
    externalV2SkillsSkillId,
    externalV2ChatsBulkGet,
} from '../test-cases/external';
import { publicV1SkillsSkillIdImages, publicV1SkillsSkillIdSounds, publicV1Status } from '../test-cases/public';

const test: TestSuite = {
    target: 'api-1.api.load.paskills-int.voice-ext.stable.qloud-d.yandex.net',
    tank: 'tank-1.tank.load.paskills-int.voice-ext.stable.qloud-d.yandex.net',
    description: 'test',
    name: 'test',
    operator: process.env.USER!,
    ticket: 'PASKILLS-975',
    loadProfile: {
        warmingUp: '1s',
        slowingDown: '1s',
        schema: [
            {
                type: LoadSchemaType.Const,
                dur: '1s',
                loadMultiplier: 1,
            },
            {
                type: LoadSchemaType.Line,
                dur: '1s',
                fromMultiplier: 1,
                toMultiplier: 2,
            },
            {
                type: LoadSchemaType.Line,
                dur: '1s',
                fromMultiplier: 2,
                toMultiplier: 1,
            },
        ],
    },
    routes: {
        ...catalogueV1Categories,
        ...catalogueV1DialogsSlug,
        ...catalogueV1DialogsSearch,
        ...catalogueV1DialogsSuggest,
        ...catalogueV1Dialogs2,
        ...catalogueV1DialogsSkillIdSlug,
        ...catalogueV1DialogsSkillIdAccountLinking,
        ...catalogueV1Collections,
        ...catalogueV1BuiltinCollections,
        ...catalogueV1Reviewform,
        ...catalogueV1CompilationsSlug,
        ...catalogueV1ExperimentsYandexuid,
        ...catalogueV1PagesMain,
        ...catalogueV1SmartHomeGetNativeSkills,
        ...devconsoleV1SkillsSkillIdDraft,
        ...devConsoleV1SkillsSkillIdDraftActionsWithdraw,
        ...devconsoleV1SkillsSkillIdFlags,
        ...devConsoleV1SkillsLogo,
        ...devConsoleV1SkillsMessage,
        ...devConsoleV1SkillsOperations,
        ...devConsoleV1SkillsRelease,
        ...devConsoleV1SkillsCandidate,
        ...devConsoleV1SkillsActionsStop,
        ...devConsoleV1SkillReviews,
        ...devConsoleV1Skills,
        ...devConsoleV1Snapshot,
        ...devConsoleV1SkillsSkillId,
        ...devConsoleV1Subscription,
        ...devConsoleV1EmailSend,
        ...devConsoleV1ModerationSkillSkillIdValidateToken,
        ...devConsoleV1SkillsNotificationsPhone,
        ...publicV1Status,
        ...publicV1SkillsSkillIdImages,
        ...externalV2SkillsSkillId,
        ...externalV2Chats,
        ...externalV2SkillsBulkGet,
        ...externalV2ChatsSkillId,
        ...externalV2ChatsSkillIdDraftStatus,
        ...externalV2ChatsBulkGet,
        ...publicV1SkillsSkillIdSounds,
        ...publicV1SkillsSkillIdImages,
    },
};

export default test;
