module.exports = {
    fullPage: '[class^="StackNavigator-Screen"]',
    mainScreen: '[class^="MainScreen_main__"]',
    monthScreen: '[class^="MonthScreen_container__"]',
    detailsScreen: '[class^="DetailsScreen_container__"]',
    regionScreen: '[class^="RegionScreen_page__"]',
    regionContainer: '[class^="Region_container__"]',
    searchRecommendations: '[class^="RecommendedLocations_container"]',
    mapsMap: '[class^="MapsFlat_map__"]',
    adv: {
        Container: '[class*="Advert_container__"]',
        Container2: '[class*="Advert_skeletonLoaded__"]',
        Container3: '[class*="Advert_relativeLoaded__"]',
        Item: '[id^="ADVERT_"]',
        Error: '[class^="Advert_error__"]',
        Dots: '[class*="Loader_dots"]',
        Loader: '[class*="Loader_loader"]',
        SmartBanner: '[id^="ADVERT_Y-A-"]'
    },
    index: {
        Header: '[class^="Header_container__"]',
        Fact: '[class^="MainScreen_main__"]',
        FactContainer: '[class*="Fact_container__"]',
        FactCondition: '[class*="Fact_condition__"]',
        MainNavigation: '[class*="MainNavigation_container__"]',
        MapImg: '[class*="MapItemFullScreen_map__"]',
        MapImgItem: '[class*="Image_Image__"]',
        MapImgPin: '[class*="MapItemFullScreen_pin__"]',
        MapAlert: '[class*="mapTop_alertContainer"]',
        MainSliders: '[class*="MainScreen_content__"]',
        HourlyMain: '[class*="MainScreen_hourlyMain__"]',
        HourlyContainer: '[class*="MainScreen_hourlyPageContainer__"]',
        Forecast: '.Forecast',
        ForecastFirst: '[class*="Forecast_container__"]:first-child',
        ForecastCollapsedContent: '[class*="ForecastCollapsed_forecastCollapsedBodyOpen"] [class*="ForecastCollapsed_content"]',
        ForecastWidget: '[class*="ForecastWidget_wrap"]',
        ForecastWidgetBtnOpen: '[class*="ForecastWidget_wrap"] [class*="Collapsible_title"]',
        ForecastWidgetBtnClosed: '[class*="ForecastWidget_wrap"] [class*="Collapsible_closed__"] [class*="Collapsible_title"]',
        ForecastWidgetOpened: '[class*="ForecastWidget_wrap"] [class*="Collapsible_open"]',
        MonthLink: '[class*="MonthLink_month-link__"]',
        MonthLinkSecond: '[class*="MonthLink_second-month-link__"]',
        MonthCard: '[class*="MonthsCard_container__"]',
        MonthCardTextWrap: '[class*="MonthsCard_month-text-wrap"]',
        HistoryCard: '[class*="HistoryCard_card__"]',
        MapsWidget: '[class*="MapsWidget_container__"]',
        CameraPlayer: '[class*="Camera_player__"]',
        CameraContainer: '[class*="Camera_container__"]',
        PushScribe: '[class*="PushScribe"]',
        ModalContent: '.Modal_theme_weather .Modal-Content',
        ModalParanja: '.Modal_theme_weather .Modal-Overlay',
        AlertsContainer: '[class*="Alerts_container__"]',
        AlertsSwipeableContent: '[class*="Alerts_hourlySwipeableContent"]',
        AlertsSingle: '[class*="Alerts_alerts__"]',
        AlertsPopup: '[class*="Alert_popupTheme__"]',
        AlertsVoteButton: '[class*="Alert_popupButton__"]',
        Search: '[class*="MainNavigation_side__"]',
        PrecipitationReport: '[class*="PrecipitationReport_precipitation__"]',
        PrecipitationReportBtnNo: '[class*="PrecipitationReport_buttonNo__"]',
        PrecipitationReportPopup: '[class*="PrecipitationReport_popupTheme__"]',
        PrecipitationReportPopupBtn: '[class*="PrecipitationReport_clarify__"]:first-of-type',
        Skeleton: '[class*="MainSkeleton_container__"]',
        SkiPromoCard: '[class*="SkiPromoCard_card__"]',
        LocationTitle: '[class*="location-place"]',
        NewsNew: '[class*="NewsNew_wrapper__"]',
        MobileWidgetPromo: '[class*="MobileWidgetPromo_widget__"]',
        WidgetOnboarding: '[class*="WidgetOnboarding_container__"]',
        WidgetTop: '[class*="WidgetTop_container__"]',
        SideblockFade: '[class*="SideBlock-Fade"]',
        SideblockSlider: '[class*="SideBlock-Slider"]',
        MenuButton: '[class*="Menu_menuButton__"]',
        MenuMenu: '[class*="Menu_menu__"]',
        SkiResortCardMenu: '[class*="SkiResortCard_close__"]',
        SkiResortCard: '[class*="SkiResortCard_wrapper__"]'
    },
    details: {
        Title: '[class^="TitleWithBackwardButton_title__"]',
        Tabs: '[class^="HorizontalScroll"]',
        TabLast: '[class*="Tabs_tab__"]:last-child',
        TabsTabAll: '[class*="Tabs_tab__"]',
        CardContainer: '[class^="Card_container"]',
        DetailsTemp: '.Details_block_0',
        DetailsWind: '.Details_block_1',
        DetailsHumidity: '.Details_block_2',
        DetailsPressure: '.Details_block_3',
        DetailsSun: '.Details_block_4',
        DetailsOther: '.Details_block_5',
        Skeleton: '[class*="DetailsSkeleton_container__"]',
        BackBtn: '[class*="BackwardButton_backward-button"]',
    },
    month: {
        Title: '[class^="TitleWithBackwardButton_title__"]',
        Calendar: '[class*="Calendar_container__"]',
        CalendarWrap: '.Calendar',
        MonthDiagramm: '[class*="MonthDiagramm_card__"]',
        CitiesList: '[class*="CitiesList_container__"]',
        CitiesListWithCountries: '[class*="CitiesList_containerWithCountries__"]',
        Skeleton: '[class*="MonthSkeleton_container__"]',
        Tabs: '[class*="Tabs_content__"]'
    },
    skeletons: {
        Text: '[class^="Skeleton_text"]',
        Rect: '[class^="Skeleton_rect"]',
    },
    tech: {
        Spinner: '[class^="NetworkState_loader"]',
        Offline: '[class^="OfflineLabel_modal"]',
        BaobabButton: '[class="BaobabButton"]',
    },
    header: {
        Common: '[class*="Header"]',
        White: '[class*="Header_white_header__"]',
        WhiteSkeleton: '[class*="MainSkeleton_head__"]',
        Gray: '[class*="Header_gray_header__"]',
        GraySkeleton: '[class*="DetailsSkeleton_header__"]',
        SearchIcon: '[class*="Header_base_search-icon"]'
    },
    region: {
        Row: '[class*="Region_row__"]',
        Letter: '[class*="Region_letter__"]',
        Backward: '[class*="BackwardLine_container__"]',
        Skeleton: '[class*="RegionSkeleton_container__"]'
    },
    forecastCollapsed: {
        Title: '[class*="ForecastList_title__"]',
        Temp: '[class*="Temp_detailsTemp__"]',
        TempFeels: '[class*="Temp_detailsTempFeels__"]',
        TempDivider: '[class*="Temp_divider__"]',
        CardTitle: '[class*="Title_title__"]',
        Slide: '[class*="SliderItem Slider-Item"]'
    },
    search: {
        RecommendationsLast: '[class*="RecommendedLocations_item__"]:last-child',
        Skeleton: '[class*="SearchSkeleton_container__"]'
    },
    maps: {
        Screen: '[class*="screenWrapper"]',
        ReportAndAlertAlert: '[class*="ReportAndAlertAlert_alert__"]',
        Adv: '[class*="Advert_container__"]',
        LayerSelector: '[class*="MapsFlat_btnLayerSelector__"]',
        ForecastBtn: '[class*="_forecastButton"]'
    },
    popup: '[class*="Popup_container"]',
    footer: '[class*="Footer_footer__"]',
    meteum: '[class*="Meteum_meteum__"]',
    iframe: {
        safebundle: 'iframe[src*="https://yastatic.net/safeframe-bundles/"]'
    }
};
