INCLUDE(${ARCADIA_ROOT}/mds/karl/tests/postgres_local/recipe/recipe.inc)
INCLUDE(${ARCADIA_ROOT}/mail/library/logbroker/logbroker2_consumer/test_base/test-data.inc)

DATA(
    arcadia/mail/so/familypay/database
    arcadia/mail/so/familypay/familypay_backend/test_base/resources/ru/yandex/passport/familypay/backend/blackbox-userinfo-template.json
    arcadia/mail/so/familypay/familypay_backend/test_base/resources/ru/yandex/passport/familypay/backend/services.json
    arcadia/mail/so/familypay/familypay_backend_service/files
    arcadia/mail/so/familypay/familypay_lbconsumer_service/files
    arcadia/mail/library/http/http_test/main/resources/ru/yandex/http/test/localhost.jks
    arcadia/mail/tools/nanny_helpers/nanny_service_base/files
)
