--liquibase formatted sql

--changeset zaharov_i:VNDMARKET-199_fix_tariffs_timestamps
UPDATE CS_BILLING.CAMPAIGN_TARIFF ct
SET ct.END_DATE = TRUNC(ct.END_DATE) + INTERVAL '1' DAY - INTERVAL '1' SECOND
WHERE ct.CS_ID = 132 AND ct.END_DATE != TRUNC(ct.END_DATE) + INTERVAL '1' DAY - INTERVAL '1' SECOND;

UPDATE CS_BILLING.CAMPAIGN_TARIFF ct
SET ct.START_DATE = TRUNC(ct.START_DATE)
WHERE ct.CS_ID = 132 AND ct.START_DATE != TRUNC(ct.START_DATE);

