/* eslint-disable */

import { NAlice } from './index';

describe('protos', function () {
    it('should correct decode TAliceMetaInfo', function() {
        const b64Str = 'CghNZWdhbWluZBKlAQoGYWxpY2VkEgMxLjAaAzEuMCIFTGludXgqIDU3NjAzNDAwODExOTU1ZDk2MjJmNzNhOWQzYzYxZWQyMiBlZTE1OGY0MWM1ODVmMDQ1NzMyMTNhMTM0ZmY2YjhkYjoFcnUtUlVCDzIwMjAwNDE2VDAyNDI0NUoNRXVyb3BlL01vc2Nvd1IKMTU4NzAwNDk2NVoMbGlua3BsYXlfYTk4YgVJcmJpcxr0BQgBEAAYACIxCg3QutC-0YDQvtC90LAuEQAAAAAAAAAAGhcKDNC60L7RgNC-0L3QsBEAAAAAAADwPyI3CgARAAAAAAAAAAAaFwoM0LrQvtGA0L7QvdCwEQAAAAAAAPA_GhEKBtC80LjRgBEAAAAAAADwPyIoCgARAAAAAAAAAAAaGwoQ0LrQvtGA0L7QvdCw0LzQuBEAAAAAAADwPyIzCgARAAAAAAAAAAAaFwoM0LrQvtGA0L7QvdCwEQAAAAAAAPA_Gg0KAtC4EQAAAAAAAPA_IjUKABEAAAAAAAAAABoXCgzQutC-0YDQvtC90LARAAAAAAAA8D8aDwoE0LzQuBEAAAAAAADwPyI5CgARAAAAAAAAAAAaFwoM0LrQvtGA0L7QvdCwEQAAAAAAAPA_GhMKCNC80LjRgNCwEQAAAAAAAPA_IjMKABEAAAAAAAAAABoXCgzQutC-0YDQvtC90LARAAAAAAAA8D8aDQoC0LwRAAAAAAAA8D8iNwoAEQAAAAAAAAAAGhcKDNC60L7RgNC-0L3QsBEAAAAAAADwPxoRCgbQvNC10YURAAAAAAAA8D8iJgoAEQAAAAAAAAAAGhkKDtC60L7RgNC-0L3QsNGAEQAAAAAAAPA_IiYKABEAAAAAAAAAABoZCg7QutC-0YDQvtC90LDQuxEAAAAAAADwP1p_EgkKB2RlZmF1bHQSCgoIaGlnaF90bnISCgoIaGlnaF90cHISDgoMbWF4X2FjY3VyYWN5GgJvayIkOGYyYTRiYjgtYTk5Yy00NGRhLTkyMWQtZjllNTEwYzIwNWFkKiA1NzYwMzQwMDgxMTk1NWQ5NjIyZjczYTlkM2M2MWVkMmJwCgJvaxIaCgVhZHVsdBEAAAAAFZrvPxoIY2hpbGRyZW4SGgoFY2hpbGQRAAAAAMB6iT8aCGNoaWxkcmVuEhkKBmZlbWFsZREAAAAgO52rPxoGZ2VuZGVyEhcKBG1hbGURAAAAQCxG7j8aBmdlbmRlcg,,';
        
        const binBuf = Buffer.from(b64Str, 'base64');
        const aliceMetaInfo = NAlice.TAliceMetaInfo.decode(binBuf);

        // null - ошибок валидации нет
        expect(NAlice.TAliceMetaInfo.verify(aliceMetaInfo)).toEqual(null);
    });
});