module.exports = {
    postgres: {
        host: 'localhost',
        port: 5432,
        username: 'postgres',
        password: '',
        extraFlags: '',
        database: 'riverbank_testing',
    },
    clickhouse: {
        host: 'localhost',
        port: 8123,
        user: '',
        password: '',
        protocol: 'http:',
        database: 'riverbank_testing',
    },
    rum_clickhouse: {
        host: 'localhost',
        port: 8123,
        user: '',
        password: '',
        protocol: 'http:',
        database: 'riverbank_testing',
    },
    drm_clickhouse: {
        host: 'localhost',
        port: 8123,
        user: '',
        password: '',
        protocol: 'http:',
        database: 'riverbank_testing',
    },
    ott_clickhouse: {
        host: 'localhost',
        port: 8123,
        user: '',
        password: '',
        protocol: 'http:',
        database: 'riverbank_testing',
    },
    gen_music_clickhouse: {
        host: 'localhost',
        port: 8123,
        user: '',
        password: '',
        protocol: 'http:',
        database: 'riverbank_testing',
    },
};
