PoolTable: "//home/search-runtime/bogdanovilya/join-new-hashes-market-model/join-to-big-pool-1Nov-14July/pool-shown-sample-10M"
SortPool: true
CleanAggregatorOutput: false
TmpDir: "//home/search-runtime/bogdanovilya/pipeline-aggregator-joiner/medium-test/tmp"
TableConfig {
   ParamTable: "//home/search-runtime/bogdanovilya/join-new-hashes-market-model/join-to-big-pool-1Nov-14July/tables-with-features/spylog-2020-11-01--2021-07-08-Filtered"
   SortParamTable: true
   Gap: 3600
   FeatureConfig {
      Key: "Title"
      ToKey: "Title_last_25"
      Limit: 25
   }
   FeatureConfig {
      Key: "UrlHash"
      ToKey: "UrlHash_last_25"
      OutputType: REPEATED
      Limit: 25
   }
}
TableConfig {
   ParamTable: "//home/search-runtime/bogdanovilya/join-new-hashes-market-model/join-to-big-pool-1Nov-14July/tables-with-features/cpa-clicks-2020-11-01--2021-07-14"
   SortParamTable: true
   Gap: 3600
   FeatureConfig {
      Key: "title"
      ToKey: "title_last_25"
      Limit: 25
   }
   FeatureConfig {
      Key: "ware_md5"
      ToKey: "ware_md5_last_25"
      OutputType: REPEATED
      Limit: 25
   }
}
TableConfig {
   ParamTable: "//home/search-runtime/bogdanovilya/join-new-hashes-market-model/join-to-big-pool-1Nov-14July/tables-with-features/paid-clicks-2020-11-01--2021-07-14"
   SortParamTable: true
   Gap: 3600
   FeatureConfig {
      Key: "title"
      ToKey: "title_last_25"
      Limit: 25
   }
   FeatureConfig {
      Key: "msku"
      ToKey: "msku_last_25"
      OutputType: REPEATED
      Limit: 25
   }
}
TableConfig {
   ParamTable: "//home/search-runtime/bogdanovilya/join-new-hashes-market-model/join-to-big-pool-1Nov-14July/tables-with-features/orders-2020-11-01--2021-07-14"
   SortParamTable: true
   Gap: 3600
   FeatureConfig {
      Key: "title"
      ToKey: "title_last_25"
      Limit: 25
   }
   FeatureConfig {
      Key: "shop_id"
      ToKey: "shop_id_last_25"
      OutputType: REPEATED
      Limit: 25
   }
}
TableConfig {
   ParamTable: "//home/search-runtime/bogdanovilya/join-new-hashes-market-model/join-to-big-pool-1Nov-14July/tables-with-features/billed-orders-2020-11-01--2021-07-14"
   SortParamTable: true
   Gap: 3600
   FeatureConfig {
      Key: "title"
      ToKey: "title_last_25"
      Limit: 25
   }
   FeatureConfig {
      Key: "reqid"
      ToKey: "reqid_last_25"
      OutputType: REPEATED
      Limit: 25
   }
}
