'use strict';

/* eslint-disable max-len */

module.exports = expect.objectContaining({
    cbirMinOfferPrice: undefined,
    model: {
        name: 'LG 43LJ510V',
        reviewsCount: 5,

        rating: 3.5,
        gradeCount: 6,
        info: {
            constants: {
                atMarket: 'на Яндекс.Маркете',
                avgPrice: 'Средняя цена',
                avgPriceGraph: 'График средней цены на',
                ratingTooltipText: 'Рейтинг товара %s из 5',
            },
        },
        isNew: false,
        links: {
            constants: {
                allPrices: 'Все цены',
                allPricesMarket: 'Все цены на Яндекс.Маркете',
                closestShops: 'Магазины рядом',
                reviews: 'Отзывы',
                reviewsMarket: 'Отзывы на Яндекс.Маркете',
                shopsOnMap: 'Предложения магазинов на карте',
            },
        },
        prices: {
            max: 26014,
            min: 20450,
            avg: 23849,
            curCode: 'RUR',
            curName: 'руб.',
        },
        offersCount: 67,
        mainPhoto: {
            url: expect.any(String),
            width: 321,
            height: 620,
        },
        photo: expect.any(String),
        urls: {
            model: '<wrapped url>',
            modelPicture: '<wrapped url>',
            offers: '<wrapped url>',
            map: '<wrapped url>',
            price: '<wrapped url>',
            reviews: '<wrapped url>',
            reviewsBadge: '<wrapped url>',
        },
    },
    feedback: {
        constants: {
            closeButtonText: 'Закрыть',
            error: 'Комментарий не может быть пустым.',
            placeholder:
                'Пожалуйста, расскажите, что именно случилось. Ваш комментарий поможет нам исправить проблему быстрее.',
            submitButtonText: 'Отправить',
            text: 'Ваше сообщение поможет улучшить Советника',
            thanks: 'Спасибо!',
            title: 'Спасибо, мы получили ваш отчёт об ошибке',
        },
    },
    offers: [
        {
            offerSurfaceUrl: '<wrapped url>',
            deliverySis: expect.any(Object),
            name: 'LED Телевизор LG 43LJ510V',
            price: {
                value: 22266,
                currencyCode: 'RUR',
                currencyName: 'руб.',
            },
            constants: {
                buttonText: 'В магазин',
                shopInfoTooltip: 'Перейти в магазин',
                shopRatingText: 'Рейтинг %s из 5 на основе',
                shopRatingDefaultText: 'оценки службы контроля качества Яндекс.Маркета',
            },
            category: {
                id: 90639,
                name: 'Телевизоры',
                fullName: 'Телевизоры',
                type: 'GURU',
                childCount: 0,
                advertisingModel: 'CPA',
                viewType: 'LIST',
            },
            target: 'pricebar',
            shopInfo: {
                name: 'TechPort.ru',
                id: 1672,
                rating: 5,
                gradeTotal: 53549,
                url: '<wrapped url>',
            },
            delivery: {
                free: false,
                pickup: true,
                brief: 'в Москву — 500 руб., возможен самовывоз',
                price: {
                    value: '500',
                    currencyCode: 'RUR',
                    currencyName: 'руб.',
                },
                delivery: true,
                daysFrom: 1,
                daysTo: 1,
                cityFrom: 'Москвы',
                cityTo: 'Москву',
            },
            warning: undefined,
            photo: 'https://avatars.mds.yandex.net/get-marketpic/206654/market_myG4UW7srrHrPHywu3JIHQ/orig',
            source: 'Market',
            bigPhoto: {
                width: 300,
                height: 300,
                url: 'https://avatars.mds.yandex.net/get-marketpic/206654/market_myG4UW7srrHrPHywu3JIHQ/orig',
            },
            id:
                'yDpJekrrgZH673vrypnRFH5nNUQRhvsuTGdxg8l7pNET0e8wf8ZwUv-PbFmNKlwzHj7Io6w8EuyexgApt8e-sVZIWJtsJ0FjkGD6dq7MkAZlaebd9yYC9VD2E7oW0M0A9U7eCXoYTEwkd38bJO41POVaff480_qEODXtz0W0RFLwn8zOdl_k58WMkFaQP5oVtJjtX1wmt3IRwthFUXcaBBj0rLQheNkQuVHe9DlYC5_g8oOSudbcztsdJ_r-x4dOZcRexCb22f25iswAz-aleSDDNPDN1MKy6_2UUaivXPw',
            url: '<wrapped url>',
            optOutUrl: '<wrapped url>',
            buttonUrl: '<wrapped url>',
            surfaceUrl: '<wrapped url>',
            profitBadgeText: {
                prefix: expect.any(String),
                value: expect.any(String),
            },
        },
        {
            offerSurfaceUrl: '<wrapped url>',
            deliverySis: expect.any(Object),
            name: 'Телевизор LED LG 43LJ510V, черный',
            price: {
                value: 25990,
                currencyCode: 'RUR',
                currencyName: 'руб.',
            },
            constants: {
                buttonText: 'В магазин',
                shopInfoTooltip: 'Перейти в магазин',
                shopRatingText: 'Рейтинг %s из 5 на основе',
                shopRatingDefaultText: 'оценки службы контроля качества Яндекс.Маркета',
            },
            category: {
                id: 90639,
                name: 'Телевизоры',
                fullName: 'Телевизоры',
                type: 'GURU',
                childCount: 0,
                advertisingModel: 'CPA',
                viewType: 'LIST',
            },
            target: 'price-list',
            shopInfo: {
                name: 'ОНЛАЙН ТРЕЙД.РУ',
                id: 255,
                rating: 5,
                gradeTotal: 66964,
                url: '<wrapped url>',
            },
            delivery: {
                free: false,
                pickup: true,
                brief: 'в Москву — 500 руб., возможен самовывоз',
                price: {
                    value: '500',
                    currencyCode: 'RUR',
                    currencyName: 'руб.',
                },
                delivery: true,
                daysFrom: 1,
                daysTo: 2,
                cityFrom: 'Москвы',
                cityTo: 'Москву',
            },
            warning: undefined,
            photo: 'https://avatars.mds.yandex.net/get-marketpic/169986/market_pAzqQXwnZXH6VvZuY6uMvw/orig',
            source: 'Market',
            bigPhoto: {
                width: 800,
                height: 528,
                url: 'https://avatars.mds.yandex.net/get-marketpic/169986/market_pAzqQXwnZXH6VvZuY6uMvw/orig',
            },
            id: 'yDpJekrrgZEHGQ54R7SISVI3Qh1knByVlgXJEEjGfeuM1oZdD0NkYA',
            url: '<wrapped url>',
            buttonUrl: '<wrapped url>',
        },
        {
            offerSurfaceUrl: '<wrapped url>',
            deliverySis: expect.any(Object),
            name: 'Телевизор 43" LG 43LJ510V черный 1920x1080 50 Гц USB',
            price: {
                value: 24240,
                currencyCode: 'RUR',
                currencyName: 'руб.',
            },
            constants: {
                buttonText: 'В магазин',
                shopInfoTooltip: 'Перейти в магазин',
                shopRatingText: 'Рейтинг %s из 5 на основе',
                shopRatingDefaultText: 'оценки службы контроля качества Яндекс.Маркета',
            },
            category: {
                id: 90639,
                name: 'Телевизоры',
                fullName: 'Телевизоры',
                type: 'GURU',
                childCount: 0,
                advertisingModel: 'CPA',
                viewType: 'LIST',
            },
            target: 'price-list',
            shopInfo: {
                name: 'JUST.RU',
                id: 17019,
                rating: 4,
                gradeTotal: 7257,
                url: '<wrapped url>',
            },
            delivery: {
                free: false,
                pickup: false,
                brief: 'в Москву — 500 руб.',
                price: {
                    value: '500',
                    currencyCode: 'RUR',
                    currencyName: 'руб.',
                },
                delivery: true,
                daysFrom: 2,
                daysTo: 2,
                cityFrom: 'Москвы',
                cityTo: 'Москву',
            },
            warning: undefined,
            photo: 'https://avatars.mds.yandex.net/get-marketpic/210846/market_IDLI4eMlE18ceZXxL5ZVRQ/orig',
            source: 'Market',
            bigPhoto: {
                width: 560,
                height: 371,
                url: 'https://avatars.mds.yandex.net/get-marketpic/210846/market_IDLI4eMlE18ceZXxL5ZVRQ/orig',
            },
            id:
                'yDpJekrrgZHTtq66TMHpGepHpYqN-BlwTh20v9Mvvz06IpiSczqD7sHo0nWOSp6LHK7DcbmQ9UzbGEKlh2ytf3CKsdfO8dGlmT0rquIWhlSh9ikSKwq7n1eB6c1_R9nxHxNvu3kluxd3_XjaE7KSS6dymePqb_v7d8TnTwxUQGeRSEEG-5n7KoVe49NyOH9wylA0WmfEpDgiFaxNUGY2V-pzS5rw8NDPMjSv8pUE4VPn2FHOG9hdZXbsIlZBavvn2sjByY3bXTe4MdC4TFDgmjCg-PtkCB3qL6J08qs3b9o',
            url: '<wrapped url>',
            buttonUrl: '<wrapped url>',
        },
        {
            offerSurfaceUrl: '<wrapped url>',
            deliverySis: expect.any(Object),
            name: 'LED Телевизор LG 43LJ510V',
            price: {
                value: 22266,
                currencyCode: 'RUR',
                currencyName: 'руб.',
            },
            constants: {
                buttonText: 'В магазин',
                shopInfoTooltip: 'Перейти в магазин',
                shopRatingText: 'Рейтинг %s из 5 на основе',
                shopRatingDefaultText: 'оценки службы контроля качества Яндекс.Маркета',
            },
            category: {
                id: 90639,
                name: 'Телевизоры',
                fullName: 'Телевизоры',
                type: 'GURU',
                childCount: 0,
                advertisingModel: 'CPA',
                viewType: 'LIST',
            },
            target: 'price-list',
            shopInfo: {
                name: 'TechPort.ru',
                id: 1672,
                rating: 5,
                gradeTotal: 53549,
                url: '<wrapped url>',
            },
            delivery: {
                free: false,
                pickup: true,
                brief: 'в Москву — 500 руб., возможен самовывоз',
                price: {
                    value: '500',
                    currencyCode: 'RUR',
                    currencyName: 'руб.',
                },
                delivery: true,
                daysFrom: 1,
                daysTo: 1,
                cityFrom: 'Москвы',
                cityTo: 'Москву',
            },
            warning: undefined,
            photo: 'https://avatars.mds.yandex.net/get-marketpic/206654/market_myG4UW7srrHrPHywu3JIHQ/orig',
            source: 'Market',
            bigPhoto: {
                width: 300,
                height: 300,
                url: 'https://avatars.mds.yandex.net/get-marketpic/206654/market_myG4UW7srrHrPHywu3JIHQ/orig',
            },
            id:
                'yDpJekrrgZH673vrypnRFH5nNUQRhvsuTGdxg8l7pNET0e8wf8ZwUv-PbFmNKlwzHj7Io6w8EuyexgApt8e-sVZIWJtsJ0FjkGD6dq7MkAZlaebd9yYC9VD2E7oW0M0A9U7eCXoYTEwkd38bJO41POVaff480_qEODXtz0W0RFLwn8zOdl_k58WMkFaQP5oVtJjtX1wmt3IRwthFUXcaBBj0rLQheNkQuVHe9DlYC5_g8oOSudbcztsdJ_r-x4dOZcRexCb22f25iswAz-aleSDDNPDN1MKy6_2UUaivXPw',
            url: '<wrapped url>',
            buttonUrl: '<wrapped url>',
        },
        {
            offerSurfaceUrl: '<wrapped url>',
            deliverySis: expect.any(Object),
            name: 'Телевизор LG 43LJ510V',
            price: {
                value: 22980,
                currencyCode: 'RUR',
                currencyName: 'руб.',
            },
            constants: {
                buttonText: 'В магазин',
                shopInfoTooltip: 'Перейти в магазин',
                shopRatingText: 'Рейтинг %s из 5 на основе',
                shopRatingDefaultText: 'оценки службы контроля качества Яндекс.Маркета',
            },
            category: {
                id: 90639,
                name: 'Телевизоры',
                fullName: 'Телевизоры',
                type: 'GURU',
                childCount: 0,
                advertisingModel: 'CPA',
                viewType: 'LIST',
            },
            target: 'price-list',
            shopInfo: {
                name: 'Assortiment-BT.ru',
                id: 197695,
                rating: 5,
                gradeTotal: 4577,
                url: '<wrapped url>',
            },
            delivery: {
                free: false,
                pickup: false,
                brief: 'в Москву — 450 руб.',
                price: {
                    value: '450',
                    currencyCode: 'RUR',
                    currencyName: 'руб.',
                },
                delivery: true,
                daysFrom: 1,
                daysTo: 2,
                cityFrom: 'Москвы',
                cityTo: 'Москву',
            },
            warning: undefined,
            source: 'Market',
            bigPhoto: undefined,
            id:
                'yDpJekrrgZHyXZWnWVyppX1pD7ROqZxtC8EudWLIrgc3z8cRaVwB9tDZvOdjRept4c_DSh-49pJAZfJrg5Zu1oP7NwgmY5CIOZd2SdVdprZBd_ENojWWyW9RSKhYW00DRznC7HqA3sM4PKCp8Yw7XIj4azdwpa1xTvirNrsnyD1ilX46fZyCDAaWelq2KnnmNvbUVH4wMj_Z52ck76oLM9SqNjBnEmbKEPe6DnzrQUfz2wd_pG1Vxj249j4FsSFx3A3dtC8F-6Yz3O0L0EVBYd0KOVCXMb7qieDMje242-A',
            url: '<wrapped url>',
            buttonUrl: '<wrapped url>',
        },
        {
            offerSurfaceUrl: '<wrapped url>',
            deliverySis: expect.any(Object),
            name: 'Телевизор Телевизор LG 43LJ510V черный',
            price: {
                value: 24130,
                currencyCode: 'RUR',
                currencyName: 'руб.',
            },
            constants: {
                buttonText: 'В магазин',
                shopInfoTooltip: 'Перейти в магазин',
                shopRatingText: 'Рейтинг %s из 5 на основе',
                shopRatingDefaultText: 'оценки службы контроля качества Яндекс.Маркета',
            },
            category: {
                id: 90639,
                name: 'Телевизоры',
                fullName: 'Телевизоры',
                type: 'GURU',
                childCount: 0,
                advertisingModel: 'CPA',
                viewType: 'LIST',
            },
            target: 'price-list',
            shopInfo: {
                name: '123.ru',
                id: 5570,
                rating: 4,
                gradeTotal: 8669,
                url: '<wrapped url>',
            },
            delivery: {
                free: false,
                pickup: true,
                brief: 'в Москву — 490 руб., возможен самовывоз',
                price: {
                    value: '490',
                    currencyCode: 'RUR',
                    currencyName: 'руб.',
                },
                delivery: true,
                daysFrom: 2,
                daysTo: 2,
                cityFrom: 'Москвы',
                cityTo: 'Москву',
            },
            warning: undefined,
            photo: 'https://avatars.mds.yandex.net/get-marketpic/173412/market_-SAt3_wG_SOWRSqXv2kazg/orig',
            source: 'Market',
            bigPhoto: {
                width: 533,
                height: 353,
                url: 'https://avatars.mds.yandex.net/get-marketpic/173412/market_-SAt3_wG_SOWRSqXv2kazg/orig',
            },
            id:
                'yDpJekrrgZGfEzQMJjn2bTyk7kV2qBLY68FfoUt384KZYq_BKar59nNYBtwiq_srkFs4v1pm6MNUYjmANmAUJMvrnyGSpg3tCpMqOyamkCLtGtjUiQaXeAX6enWmCozHyfCjVInvhjHrgbtPieXvWSdxk7KdMLScIznYiIAn7KajbmOQv8aVu7Xmx6UgFp7gVMr91fgJ4x0xz7rDf90rGrWpSNri47ZacMNCuA9_L5Amv-aaO3SZxE9tf0nedIu4l1Oc3mkiBW4Tn6b50huwhOHVJncg5ADHFKKfzPMLQHk',
            url: '<wrapped url>',
            buttonUrl: '<wrapped url>',
        },
        {
            offerSurfaceUrl: '<wrapped url>',
            deliverySis: expect.any(Object),
            name: 'Телевизор LG 43LJ510V',
            price: {
                value: 23990,
                currencyCode: 'RUR',
                currencyName: 'руб.',
            },
            constants: {
                buttonText: 'В магазин',
                shopInfoTooltip: 'Перейти в магазин',
                shopRatingText: 'Рейтинг %s из 5 на основе',
                shopRatingDefaultText: 'оценки службы контроля качества Яндекс.Маркета',
            },
            category: {
                id: 90639,
                name: 'Телевизоры',
                fullName: 'Телевизоры',
                type: 'GURU',
                childCount: 0,
                advertisingModel: 'CPA',
                viewType: 'LIST',
            },
            target: 'price-list',
            shopInfo: {
                name: 'Formula TV',
                id: 26104,
                rating: 5,
                gradeTotal: 807,
                url: '<wrapped url>',
            },
            delivery: {
                free: false,
                pickup: true,
                brief: 'в Москву — 590 руб., возможен самовывоз',
                price: {
                    value: '590',
                    currencyCode: 'RUR',
                    currencyName: 'руб.',
                },
                delivery: true,
                daysFrom: 0,
                daysTo: 2,
                cityFrom: 'Москвы',
                cityTo: 'Москву',
            },
            warning: undefined,
            photo: 'https://avatars.mds.yandex.net/get-marketpic/225051/market_QdFBl4_dcmhEC5VmWpMjzw/orig',
            source: 'Market',
            bigPhoto: {
                width: 600,
                height: 450,
                url: 'https://avatars.mds.yandex.net/get-marketpic/225051/market_QdFBl4_dcmhEC5VmWpMjzw/orig',
            },
            id:
                'yDpJekrrgZGUhq2ClsAogMesaZNVNgDaQcXHEKIL8E_6XnFDMoRbYWs6FWpuiTFzmj1Bv4Cy9v0h8pHqXcYxilgWC3VnGtosACTu3ed3oW9ZPi9xGHniMdq31TuiBGOexzg8nQ-eNkmUz6N864OcYOneYwxGWsYp17n1CVBObTGHeCrw1xaSTZERtyTUtkNK38xJ19UQpkzA51g2_1D8vuYaDUhJEbVfg683TsozxsVNcvABHNjjzQN5uL9gDMYCy9ocoCmgg1aMy01xgpanlIHotHqI3bHytKlXJSYxTvI',
            url: '<wrapped url>',
            buttonUrl: '<wrapped url>',
        },
    ],
    pricebar: {
        constants: {
            closeButtonTooltip: 'Закрыть',
            goButtonText: 'Посмотреть',
            goButtonTooltip: 'Посмотреть',
            inShopText: 'в магазине',
            infoButtonTooltip: 'О программе',
            moreButtonText: 'Еще предложения',
            moreButtonTooltip: 'Предложения других магазинов',
            prevText: 'Более выгодная цена на',
            settingsButtonTooltip: 'Настройки',
        },
    },
    searchResult: undefined,
    searchResultCaption: undefined,
    bucketInfo: {},
    shopInfo: {
        shopName: 'ЭЛЬДОРАДО',
        url: '<wrapped url>',
    },
    notification: undefined,
    searchInfo: {
        originalQuery: 'LED телевизор LG 43LJ510V',
        filteredQuery: 'LED телевизор LG 43LJ510V',
        convertedPrice: {
            value: 25999,
            currencyCode: 'RUR',
        },
        offersCount: 67,
        urls: {
            shopsInfo: '<wrapped url>',
            market: '<wrapped url>',
            search:
                'https://market.yandex.ru/search.xml?text=LED%20%D1%82%D0%B5%D0%BB%D0%B5%D0%B2%D0%B8%D0%B7%D0%BE%D1%80%20LG%2043LJ510V&clid=2270459&distr_type=4&utm_source=sovetnik&utm_medium=cpc&utm_campaign=offer-title&cvredirect=2&req_id=jbow18xiiwmgiumhdpsntuwd0rxvty2l&lr=213',
            searchButton: '<wrapped url>',
            prices: '<wrapped url>',
            eula: '<wrapped url>',
            feedback: '<wrapped url>',
            help: '<wrapped url>',
            helpPhone: '<wrapped url>',
            helpTablet: '<wrapped url>',
            disable: '<wrapped url>',
            features: '<wrapped url>',
            userHelp: '<wrapped url>',
        },
        category: undefined,
        categories: expect.any(Array),
        doNotComparePrice: undefined,
    },
    rules: undefined,
    optOutInfo: undefined,
    settings: {
        autoShowShopList: true,
        applicationName: 'Советник Яндекс.Маркета',
        isMbrApplication: true,
        items: [
            {
                title: 'Показывать предложения из других регионов',
                enabled: true,
            },
            {
                title: 'Показывать список предложений при наведении мыши',
                enabled: true,
            },
        ],
        constants: {
            changeRegion: 'Изменить регион',
            changeSettings: 'Изменить настройки',
            disable: 'Выключить на этом сайте',
            yourRegion: 'Ваш регион:',
        },
        region: 'Москва',
        needShowGDPR: false,
        needShowNotifications: true,
        showProductNotifications: true,
        showAviaNotifications: true,
        showAutoNotifications: true,
    },
    doNotSearchReason: undefined,
    footer: {
        constants: {
            autoDetectedRegion: 'Автоматически',
            changeCurrentRegion: 'Изменить текущий регион',
            changeRegion: 'Изменить регион',
            data: {
                letter: 'Я',
                prefix: 'Данные',
                suffix: 'ндекс.Маркета',
            },
            infoAboutShop: 'Информация о продавцах',
            infoAboutShopLegal: 'Юридическая информация о продавцах',
            feedback: 'Сообщить об ошибке',
            gotoMarket: 'Перейти на Яндекс.Маркет',
            wrongProductDetect: 'Неверно определен товар',
        },
    },
    info: {
        constants: {
            disableText: 'Как отключить Советника',
            featuresText: 'Что ещё умеет Советник',
            feedbackText: 'Обратная связь',
            helpText: 'Помощь',
            licenseText: 'Лицензионное соглашение',
            prefix: 'для ',
            text: 'Это приложение подсказывает вам более выгодные цены на товары, на которые вы смотрите прямо сейчас.',
            upperLine: 'Яндекс.Советник',
            yandexLLC: '© %s ООО «Яндекс.Маркет»',
        },
    },
    tabs: {
        constants: {
            offers: 'Предложения магазинов',
        },
    },
});
