/*
 * Yandex Taxi processing Service
 * Yandex Taxi processing Service
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.yandex.procaas.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for BatchedEvent
 */
public class BatchedEventTest {
    private final BatchedEvent model = new BatchedEvent();

    /**
     * Model tests for BatchedEvent
     */
    @Test
    public void testBatchedEvent() {
        // TODO: test BatchedEvent
    }

    /**
     * Test the property 'queue'
     */
    @Test
    public void queueTest() {
        // TODO: test queue
    }

    /**
     * Test the property 'itemId'
     */
    @Test
    public void itemIdTest() {
        // TODO: test itemId
    }

    /**
     * Test the property 'idempotencyToken'
     */
    @Test
    public void idempotencyTokenTest() {
        // TODO: test idempotencyToken
    }

    /**
     * Test the property 'due'
     */
    @Test
    public void dueTest() {
        // TODO: test due
    }

    /**
     * Test the property 'payload'
     */
    @Test
    public void payloadTest() {
        // TODO: test payload
    }

}
