/*
 * Yandex Taxi processing Service
 * Yandex Taxi processing Service
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.yandex.procaas.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for Checkpoint
 */
public class CheckpointTest {
    private final Checkpoint model = new Checkpoint();

    /**
     * Model tests for Checkpoint
     */
    @Test
    public void testCheckpoint() {
        // TODO: test Checkpoint
    }

    /**
     * Test the property 'eventId'
     */
    @Test
    public void eventIdTest() {
        // TODO: test eventId
    }

    /**
     * Test the property 'conditionKey'
     */
    @Test
    public void conditionKeyTest() {
        // TODO: test conditionKey
    }

    /**
     * Test the property 'conditionReason'
     */
    @Test
    public void conditionReasonTest() {
        // TODO: test conditionReason
    }

    /**
     * Test the property 'pipeline'
     */
    @Test
    public void pipelineTest() {
        // TODO: test pipeline
    }

    /**
     * Test the property 'stage'
     */
    @Test
    public void stageTest() {
        // TODO: test stage
    }

    /**
     * Test the property 'sharedState'
     */
    @Test
    public void sharedStateTest() {
        // TODO: test sharedState
    }

    /**
     * Test the property 'finishedHandlers'
     */
    @Test
    public void finishedHandlersTest() {
        // TODO: test finishedHandlers
    }

    /**
     * Test the property 'handlersResult'
     */
    @Test
    public void handlersResultTest() {
        // TODO: test handlersResult
    }

    /**
     * Test the property 'handleByVersion'
     */
    @Test
    public void handleByVersionTest() {
        // TODO: test handleByVersion
    }

}
