/*
 * Yandex Taxi processing Service
 * Yandex Taxi processing Service
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.yandex.procaas.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for CreateEventBatch
 */
public class CreateEventBatchTest {
    private final CreateEventBatch model = new CreateEventBatch();

    /**
     * Model tests for CreateEventBatch
     */
    @Test
    public void testCreateEventBatch() {
        // TODO: test CreateEventBatch
    }

    /**
     * Test the property 'events'
     */
    @Test
    public void eventsTest() {
        // TODO: test events
    }

}
