/*
 * Yandex Taxi processing Service
 * Yandex Taxi processing Service
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.yandex.procaas.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for CurrentState
 */
public class CurrentStateTest {
    private final CurrentState model = new CurrentState();

    /**
     * Model tests for CurrentState
     */
    @Test
    public void testCurrentState() {
        // TODO: test CurrentState
    }

    /**
     * Test the property 'currentState'
     */
    @Test
    public void currentStateTest() {
        // TODO: test currentState
    }

}
