/*
 * Yandex Taxi processing Service
 * Yandex Taxi processing Service
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.yandex.procaas.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for QueueEvent
 */
public class QueueEventTest {
    private final QueueEvent model = new QueueEvent();

    /**
     * Model tests for QueueEvent
     */
    @Test
    public void testQueueEvent() {
        // TODO: test QueueEvent
    }

    /**
     * Test the property 'eventId'
     */
    @Test
    public void eventIdTest() {
        // TODO: test eventId
    }

    /**
     * Test the property 'created'
     */
    @Test
    public void createdTest() {
        // TODO: test created
    }

    /**
     * Test the property 'handled'
     */
    @Test
    public void handledTest() {
        // TODO: test handled
    }

    /**
     * Test the property 'payload'
     */
    @Test
    public void payloadTest() {
        // TODO: test payload
    }

    /**
     * Test the property 'extraOrderKey'
     */
    @Test
    public void extraOrderKeyTest() {
        // TODO: test extraOrderKey
    }

}
