#!/usr/bin/env bash

[ -z "${KEEP}" ] && set -e

#export KEEP=1
export VERBOSE=1

SCRIPTS_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")"/.. && pwd) #"

export PG_PROD=1

. "${SCRIPTS_DIR}"/config.sh

ulimit -n 1000000
ulimit -n
sudo sysctl net.ipv4.ip_local_port_range="2000 64000"
#sysctl net.ipv4.ip_local_port_range
sudo sysctl net.core.somaxconn=50000
sudo sysctl net.core.netdev_max_backlog=50000
sudo sysctl net.ipv4.tcp_max_syn_backlog=50000

#export XIVA_SEND_TOKEN=zzz

#[ -n "$PROD" ] && export WEBSOCKET_PORT=${WEBSOCKET_PORT=9002}

[ -z "$PROD" ] && . "${SCRIPTS_DIR}"/wsnotify

# https://yc.yandex-team.ru/folders/foo00re08m0s670iusjg/ydb/databases/etn02ndo128h0mt57hdc/browse?path=%2Fstream_viewers

echo simple
${STARTER} ${ARCADIA_ROOT}/extsearch/video/vh/wsnotify/client/client --verbose=2 --threads=10 --uri="ws://${HOST}:${WEBSOCKET_PORT}/v2/subscribe/websocket?service=vhtest%3Atest*123%2Btest2&client=ether&session=1653782874162129-5790827006215367649-z7zgmghedxjqaxit-BAL&user=5668682531646263931" &
last_killer
sleep 1

echo no auth should fail
curl -sS "http://${HOST}:${HTTP_SEND_PORT}/beta/wild/send?user=vhtest&event=testevent&aa=bb" -X POST -d '{"tags": ["test","123"], "payload": {"test-payload":"ya-video"}}' \
    | jq --exit-status '.error == "wrong_authorization"'

echo with auth
curl -sS "http://${HOST}:${HTTP_SEND_PORT}/beta/wild/send?user=vhtest&event=testevent&aa=bb" --header "Authorization: Xiva ${XIVA_SEND_TOKEN}" -X POST -d '{"tags": ["test","123"], "payload": {"test-payload":"ya-video"}}' \
    | jq --exit-status '.status == "ok"'

sleep 1

echo stress
[ -z "${NO_BUILD}" ] && ${YA_MAKE} ${ARCADIA_ROOT}/extsearch/video/vh/wsnotify/client
${STARTER} ${ARCADIA_ROOT}/extsearch/video/vh/wsnotify/client/client --verbose=0 --threads=${STRESS=1000} --uri="ws://${HOST}:${WEBSOCKET_PORT}/v2/subscribe/websocket?service=vhnotify%3Astreams*4835278639222173563%2Bviewers*4835278639222173563&client=ether&session=1653782874162129-5790827006215367649-z7zgmghedxjqaxit-BAL&user=5668682531646263931" &
last_killer
sleep ${SLEEP_TEST1=11}
#${STARTER} ${ARCADIA_ROOT}/extsearch/video/vh/wsnotify/client/client ws://${HOST}:${WEBSOCKET_PORT}/v2/subscribe/websocket?service=vhnotify%3Astreams*4835278639222173563%2Bviewers*4835278639222173563&client=ether&session=1653782874162129-5790827006215367649-z7zgmghedxjqaxit-BAL&user=5668682531646263931  &
#last_killer

#httperf --hog --server ${HOST}:${HTTP_SEND_PORT} --num-conns 100 --rate 100 --uri=/beta/wild/send?user=vhnotify --add-header="Authorization: Xiva ${XIVA_SEND_TOKEN}"
echo '{"tags": ["viewers","4835278639222173563"], "payload": {"test-payload":"ya-video"}}' > post.data
ab -r -n ${STRESS1=1000} -c10 -p post.data  -H "Authorization: Xiva ${XIVA_SEND_TOKEN}" "http://${HOST}:${HTTP_SEND_PORT}/beta/wild/send?user=vhnotify"

curl -sS "http://${HOST}:${HTTP_SEND_PORT}/beta/wild/send?user=vhnotify" --header "Authorization: Xiva ${XIVA_SEND_TOKEN}" -X POST -d '{"tags": ["viewers","4835278639222173563"], "payload": {"test-payload":"ya-video"}}' ||:

sleep 5

#curl -sS "https://vh.test.yandex.ru/beta/wild/send?user=vhnotify" -X POST -d '{"tags": ["viewers","4835278639222173563"], "payload": {"test-payload":"ya-video"}}' ||:
#curl -sS "https://vh.test.yandex.ru/v2/subscribe/websocket?service=vhnotify%3Astreams*822175596154484715%2Bviewers*822175596154484715" ||:

#curl -sS "http://test-wsnotify-1.sas.yp-c.yandex.net:${HTTP_SEND_PORT}/beta/wild/send?user=vhnotify" --header "Authorization: Xiva ${XIVA_SEND_TOKEN}" -X POST -d '{"tags": ["viewers","4835278639222173563"], "payload": {"test-payload":"ya-video"}}' ||:
#curl -sS "http://test-wsnotify-1.sas.yp-c.yandex.net:${WEBSOCKET_PORT}/v2/subscribe/websocket?service=vhnotify%3Astreams*822175596154484715%2Bviewers*822175596154484715" ||:

# one port?
curl -sS "http://${HOST}:${WEBSOCKET_PORT}/beta/wild/send?user=vhnotify" -X POST -d '{"tags": ["viewers","4835278639222173563"], "payload": {"test-payload":"ya-video"}}' ||:


echo go pusher

. "${SCRIPTS_DIR}"/stream_viewers_pusher

sleep 3

echo go player-xiva send

SRCSETUP_PROVIDE="${SRCSETUP_PROVIDE} XIVA_PREPARE XIVA_PARSE"

[ -z "$PROD" ] && . "${SCRIPTS_DIR}"/src_setup
[ -z "$PROD" ] && . "${SCRIPTS_DIR}"/apphost

#${CURL} "https://internal.vh.yandex.net/xiva_player/v63fIP1n0aAs?${URL_ADD}${SRCRWR}&"
${CURL} "https://internal.vh.yandex.net/xiva_player/vey_f0E1cGkM?${URL_ADD}${SRCRWR}&"

sleep ${SLEEP_TEST=10}

${CURL} "http://${HOST}:${HTTP_SEND_PORT}/internal/stat"

