FROM registry.yandex.net/mail/fan/fan-pybase:latest

WORKDIR /app

COPY requirements/tests.txt /requirements

RUN apt-get update \
    && apt-get install -y \
        python3-dev \
        python3-dbg && \
    pip install -i https://pypi.yandex-team.ru/simple -r /requirements/tests.txt && \
    mkdir /var/log/fan_ui/ && \
    mkdir /var/log/fan_feedback/

COPY docker/runtests/test* /
RUN chmod u+x /test*
ENV PATH="$PATH:/"
