"""
DO NOT EDIT: this file was generated by horadric (search/horadric2).

WARNING:
    Enum value access will not work without `search.martylib.protobuf_utils.patch.patch_enums` call.
    Therefore enum stubs are invalid without said call.
"""

from typing import List  # noqa
from typing import Iterable  # noqa

import enum  # noqa

# noinspection PyUnresolvedReferences
from google.protobuf.wrappers_pb2 import BoolValue as google__protobuf__BoolValue  # noqa
# noinspection PyUnresolvedReferences
from google.protobuf.wrappers_pb2 import BytesValue as google__protobuf__BytesValue  # noqa
# noinspection PyUnresolvedReferences
from google.protobuf.wrappers_pb2 import DoubleValue as google__protobuf__DoubleValue  # noqa
# noinspection PyUnresolvedReferences
from google.protobuf.wrappers_pb2 import FloatValue as google__protobuf__FloatValue  # noqa
# noinspection PyUnresolvedReferences
from google.protobuf.wrappers_pb2 import Int32Value as google__protobuf__Int32Value  # noqa
# noinspection PyUnresolvedReferences
from google.protobuf.wrappers_pb2 import Int64Value as google__protobuf__Int64Value  # noqa
# noinspection PyUnresolvedReferences
from google.protobuf.wrappers_pb2 import StringValue as google__protobuf__StringValue  # noqa
# noinspection PyUnresolvedReferences
from google.protobuf.wrappers_pb2 import UInt32Value as google__protobuf__UInt32Value  # noqa
# noinspection PyUnresolvedReferences
from google.protobuf.wrappers_pb2 import UInt64Value as google__protobuf__UInt64Value  # noqa
# noinspection PyUnresolvedReferences
from search.martylib.proto.structures.test_pb2 import Alpha as martylib__test__Alpha  # noqa
# noinspection PyUnresolvedReferences
from search.martylib.proto.structures.test_pb2 import TestDeepMerge as martylib__test__TestDeepMerge  # noqa
# noinspection PyUnresolvedReferences
from search.martylib.proto.structures.test_pb2 import TestDeepMergeEnum as martylib__test__TestDeepMergeEnum  # noqa
# noinspection PyUnresolvedReferences
from search.martylib.proto.structures.test_pb2 import TestMessageHash as martylib__test__TestMessageHash  # noqa
# noinspection PyUnresolvedReferences
from search.martylib.proto.structures.test_pb2 import TestProtobufUtils as martylib__test__TestProtobufUtils  # noqa
# noinspection PyUnresolvedReferences
from search.martylib.proto.structures.test_pb2 import TestYtModel as martylib__test__TestYtModel  # noqa
# noinspection PyUnresolvedReferences
from search.martylib.proto.structures.test_pb2 import TopLevelEnum as martylib__test__TopLevelEnum  # noqa


class TestDeepMergeEnum(enum.IntEnum):
    DEFAULT = 0
    NOT_DEFAULT = 1


class TopLevelEnum(enum.IntEnum):
    NULL = 0
    ONE = 1


class Alpha(martylib__test__Alpha):
    class AlphaNestedEnum(enum.IntEnum):
        N_NULL = 0
        N_ONE = 1

    class AlphaNestedMessage(martylib__test__Alpha__AlphaNestedMessage):
        class AlphaNestedMessageNestedEnum(enum.IntEnum):
            NN_NULL = 0
            NN_ONE = 1

        def __init__(self):
            ...

    def __init__(self):
        ...


class TestDeepMerge(martylib__test__TestDeepMerge):
    s_wrapper: google__protobuf__StringValue
    b_wrapper: google__protobuf__BoolValue
    s_plain: str
    b_plain: bool
    rs: List[str]
    rm: TestDeepMerge
    rw: List[google__protobuf__StringValue]
    nested: TestDeepMerge
    m_nested: TestDeepMerge.MNestedEntry
    m_wrapper: TestDeepMerge.MWrapperEntry
    enum_field: martylib__test__TestDeepMergeEnum

    def __init__(
        self,
        s_wrapper: google__protobuf__StringValue = ...,
        b_wrapper: google__protobuf__BoolValue = ...,
        s_plain: str = ...,
        b_plain: bool = ...,
        rs: Iterable[str] = ...,
        rm: TestDeepMerge = ...,
        rw: Iterable[google__protobuf__StringValue] = ...,
        nested: TestDeepMerge = ...,
        m_nested: TestDeepMerge.MNestedEntry = ...,
        m_wrapper: TestDeepMerge.MWrapperEntry = ...,
        enum_field: martylib__test__TestDeepMergeEnum = ...,
    ):
        ...


class TestMessageHash(martylib__test__TestMessageHash):
    field_1: google__protobuf__BoolValue
    field_2: google__protobuf__BytesValue
    field_3: google__protobuf__DoubleValue
    field_4: google__protobuf__FloatValue
    field_5: google__protobuf__Int32Value
    field_6: google__protobuf__Int64Value
    field_7: google__protobuf__StringValue
    field_8: google__protobuf__UInt32Value
    field_9: google__protobuf__UInt64Value

    def __init__(
        self,
        field_1: google__protobuf__BoolValue = ...,
        field_2: google__protobuf__BytesValue = ...,
        field_3: google__protobuf__DoubleValue = ...,
        field_4: google__protobuf__FloatValue = ...,
        field_5: google__protobuf__Int32Value = ...,
        field_6: google__protobuf__Int64Value = ...,
        field_7: google__protobuf__StringValue = ...,
        field_8: google__protobuf__UInt32Value = ...,
        field_9: google__protobuf__UInt64Value = ...,
    ):
        ...


class TestProtobufUtils(martylib__test__TestProtobufUtils):
    type: TestProtobufUtils.Type
    disallowed_type: TestProtobufUtils.Type
    id: str
    disallowed_id: str
    container: TestProtobufUtils.Container
    disallowed_container: TestProtobufUtils.Container
    repeated_container: TestProtobufUtils.Container
    disallowed_repeated_container: TestProtobufUtils.Container
    map: TestProtobufUtils.MapEntry
    disallowed_map: TestProtobufUtils.DisallowedMapEntry

    class Container(martylib__test__TestProtobufUtils__Container):
        key: str
        value: str

        def __init__(
            self,
            key: str = ...,
            value: str = ...,
        ):
            ...

    class Type(enum.IntEnum):
        UNDEFINED = 0
        BASE = 1
        CUSTOM = 2

    def __init__(
        self,
        type: TestProtobufUtils.Type = ...,
        disallowed_type: TestProtobufUtils.Type = ...,
        id: str = ...,
        disallowed_id: str = ...,
        container: TestProtobufUtils.Container = ...,
        disallowed_container: TestProtobufUtils.Container = ...,
        repeated_container: TestProtobufUtils.Container = ...,
        disallowed_repeated_container: TestProtobufUtils.Container = ...,
        map: TestProtobufUtils.MapEntry = ...,
        disallowed_map: TestProtobufUtils.DisallowedMapEntry = ...,
    ):
        ...


class TestYtModel(martylib__test__TestYtModel):
    id: str

    def __init__(
        self,
        id: str = ...,
    ):
        ...
