"""
DO NOT EDIT: this file was generated by horadric (search/horadric2).

WARNING:
    Enum value access will not work without `search.martylib.protobuf_utils.patch.patch_enums` call.
    Therefore enum stubs are invalid without said call.
"""

from typing import List  # noqa
from typing import Iterable  # noqa

# noinspection PyUnresolvedReferences
from search.priemka.yappy.proto.structures.test_pb2 import TestExtensions as yappy__TestExtensions  # noqa


class TestExtensions(yappy__TestExtensions):
    no_str: str
    no_str_repeated: List[str]
    no_str_map: TestExtensions.NoStrMapEntry
    repeated: TestExtensions
    map: TestExtensions.MapEntry
    mes: TestExtensions
    str: str
    str_repeated: List[str]
    str_map: TestExtensions.StrMapEntry
    no_mes: TestExtensions
    no_repeated: TestExtensions
    no_map: TestExtensions.NoMapEntry

    def __init__(
        self,
        no_str: str = ...,
        no_str_repeated: Iterable[str] = ...,
        no_str_map: TestExtensions.NoStrMapEntry = ...,
        repeated: TestExtensions = ...,
        map: TestExtensions.MapEntry = ...,
        mes: TestExtensions = ...,
        str: str = ...,
        str_repeated: Iterable[str] = ...,
        str_map: TestExtensions.StrMapEntry = ...,
        no_mes: TestExtensions = ...,
        no_repeated: TestExtensions = ...,
        no_map: TestExtensions.NoMapEntry = ...,
    ):
        ...
