const HOST = 'https://api.content.market.yandex.ru';

const ROUTE = /\/v[0-9.]+\/shops/i;

const RESPONSE = {
    status: 'OK',
    context: {
        region: {
            id: 225,
            name: 'Россия',
            type: 'COUNTRY',
            childCount: 10,
            country: {
                id: 225,
                name: 'Россия',
                type: 'COUNTRY',
                childCount: 10,
            },
        },
        currency: {
            id: 'RUR',
            name: 'руб.',
        },
        processingOptions: {
            filters: {
                geoId: 0,
                host: 'ozon.ru',
            },
        },
        id: '1571780017398/a581f11d14d7d62971249a8d86950500',
        time: '2019-10-23T00:33:37.4+03:00',
        marketUrl: 'https://market.yandex.ru?pp=1002&clid=2210590&distr_type=4',
    },
    shops: [
        {
            region: {
                id: 213,
                name: 'Москва',
                type: 'CITY',
                childCount: 14,
                country: {
                    id: 225,
                    name: 'Россия',
                    type: 'COUNTRY',
                    childCount: 10,
                },
            },
            id: 557479,
            name: 'OZON.ru',
            domain: 'www.ozon.ru',
            registered: '2019-02-15',
            type: 'DEFAULT',
            opinionUrl: 'https://market.yandex.ru/shop--ozon-ru/557479/reviews?pp=1002&clid=2210590&distr_type=4',
            outlets: [],
        },
        {
            region: {
                id: 2,
                name: 'Санкт-Петербург',
                type: 'CITY',
                childCount: 18,
                country: {
                    id: 225,
                    name: 'Россия',
                    type: 'COUNTRY',
                    childCount: 10,
                },
            },
            id: 246951,
            name: 'OZON.ru',
            domain: 'www.ozon.ru',
            registered: '2014-08-27',
            type: 'DEFAULT',
            opinionUrl: 'https://market.yandex.ru/shop--ozon-ru/246951/reviews?pp=1002&clid=2210590&distr_type=4',
            outlets: [],
        },
        {
            region: {
                id: 54,
                name: 'Екатеринбург',
                type: 'CITY',
                childCount: 7,
                country: {
                    id: 225,
                    name: 'Россия',
                    type: 'COUNTRY',
                    childCount: 10,
                },
            },
            id: 326170,
            name: 'OZON.ru',
            domain: 'ozon.ru',
            registered: '2015-12-11',
            type: 'DEFAULT',
            opinionUrl: 'https://market.yandex.ru/shop--ozon-ru/326170/reviews?pp=1002&clid=2210590&distr_type=4',
            outlets: [],
        },
        {
            region: {
                id: 193,
                name: 'Воронеж',
                type: 'CITY',
                childCount: 6,
                country: {
                    id: 225,
                    name: 'Россия',
                    type: 'COUNTRY',
                    childCount: 10,
                },
            },
            id: 443605,
            name: 'OZON.ru',
            domain: 'www.ozon.ru',
            registered: '2017-10-25',
            type: 'DEFAULT',
            opinionUrl: 'https://market.yandex.ru/shop--ozon-ru/443605/reviews?pp=1002&clid=2210590&distr_type=4',
            outlets: [],
        },
        {
            region: {
                id: 2,
                name: 'Санкт-Петербург',
                type: 'CITY',
                childCount: 18,
                country: {
                    id: 225,
                    name: 'Россия',
                    type: 'COUNTRY',
                    childCount: 10,
                },
            },
            id: 575446,
            name: 'тестовый_1',
            domain: 'www.ozon.ru',
            registered: '2019-06-04',
            type: 'DEFAULT',
            opinionUrl: 'https://market.yandex.ru/shop--testovyi-1/575446/reviews?pp=1002&clid=2210590&distr_type=4',
            outlets: [],
        },
        {
            region: {
                id: 43,
                name: 'Казань',
                type: 'CITY',
                childCount: 7,
                country: {
                    id: 225,
                    name: 'Россия',
                    type: 'COUNTRY',
                    childCount: 10,
                },
            },
            id: 79354,
            name: 'OZON.ru',
            domain: 'ozon.ru',
            registered: '2011-10-25',
            type: 'DEFAULT',
            opinionUrl: 'https://market.yandex.ru/shop--ozon-ru/79354/reviews?pp=1002&clid=2210590&distr_type=4',
            outlets: [],
        },
        {
            region: {
                id: 65,
                name: 'Новосибирск',
                type: 'CITY',
                childCount: 10,
                country: {
                    id: 225,
                    name: 'Россия',
                    type: 'COUNTRY',
                    childCount: 10,
                },
            },
            id: 538886,
            name: 'OZON.ru',
            domain: 'www.ozon.ru',
            registered: '2018-10-03',
            type: 'DEFAULT',
            opinionUrl: 'https://market.yandex.ru/shop--ozon-ru/538886/reviews?pp=1002&clid=2210590&distr_type=4',
            outlets: [],
        },
        {
            region: {
                id: 14,
                name: 'Тверь',
                type: 'CITY',
                childCount: 4,
                country: {
                    id: 225,
                    name: 'Россия',
                    type: 'COUNTRY',
                    childCount: 10,
                },
            },
            id: 338794,
            name: 'OZON.ru',
            domain: 'ozon.ru',
            registered: '2016-02-10',
            type: 'DEFAULT',
            opinionUrl: 'https://market.yandex.ru/shop--ozon-ru/338794/reviews?pp=1002&clid=2210590&distr_type=4',
            outlets: [],
        },
        {
            region: {
                id: 213,
                name: 'Москва',
                type: 'CITY',
                childCount: 14,
                country: {
                    id: 225,
                    name: 'Россия',
                    type: 'COUNTRY',
                    childCount: 10,
                },
            },
            id: 343026,
            name: 'ads.ozon.ru',
            domain: 'ads.ozon.ru',
            registered: '2016-03-03',
            type: 'DEFAULT',
            opinionUrl: 'https://market.yandex.ru/shop--ads-ozon-ru/343026/reviews?pp=1002&clid=2210590&distr_type=4',
            outlets: [],
        },
        {
            region: {
                id: 213,
                name: 'Москва',
                type: 'CITY',
                childCount: 14,
                country: {
                    id: 225,
                    name: 'Россия',
                    type: 'COUNTRY',
                    childCount: 10,
                },
            },
            id: 155,
            name: 'OZON.ru',
            domain: 'ozon.ru',
            registered: '2000-12-22',
            type: 'DEFAULT',
            opinionUrl: 'https://market.yandex.ru/shop--ozon-ru/155/reviews?pp=1002&clid=2210590&distr_type=4',
            outlets: [],
        },
        {
            region: {
                id: 35,
                name: 'Краснодар',
                type: 'CITY',
                childCount: 4,
                country: {
                    id: 225,
                    name: 'Россия',
                    type: 'COUNTRY',
                    childCount: 10,
                },
            },
            id: 438600,
            name: 'OZON.ru',
            domain: 'ozon.ru',
            registered: '2017-09-27',
            type: 'DEFAULT',
            opinionUrl: 'https://market.yandex.ru/shop--ozon-ru/438600/reviews?pp=1002&clid=2210590&distr_type=4',
            outlets: [],
        },
    ],
};

module.exports = {
    host: HOST,
    route: ROUTE,
    response: RESPONSE,
};
