#!/usr/bin/env python
# -*- coding: utf-8 -*-


CRYPTA_YT_WORKING_DIR = '//home/crypta/testing'

MAX_TRAIN_ROWS = float(1e6)
APPS_FOR_TRAINING_COUNT = 1000
MAX_SEGMENT_SIZE = 5e4
USERS_TO_SAMPLE_CNT = 1e4
USER_DATA_SAMPLING_RATE = 0.1
VALIDATION_APPS_CNT = 50
