#!/usr/bin/env python
# -*- coding: utf-8 -*-

CRYPTA_YT_WORKING_DIR = '//home/crypta/testing'
CRYPTA_ML_JUGGLER_HOST = 'crypta.ml.testing'

SEGMENTS_NUM_FOR_TEST = 5
SEGMENTS_NUM_FOR_VALIDATION = 3
MIN_USERS_PER_SEGMENT = 10
MIN_USERS_PER_APP = 500
POSITIVES_VOLUME = 200e3
MAX_SEGMENTS_PER_TYPE = int(1e3)
MAX_GOALS_PER_TYPE = 500

SEGMENTS_DATA_SAMPLING_PCT = 1.0
USER_DATA_SAMPLING_RATE = 0.1
