INSERT INTO shop_offer_filter (id, shop_id, name, query, category, price_from, price_to, has_card, feed_id, created_at, updated_at, sort_order, purchase_price_from, purchase_price_to, click_days, click_count_from, click_count_to, click_price_from, click_price_to, order_days, order_count_from, order_count_to, order_cpo_from, order_cpo_to, is_available, card_position_from, card_position_to, bid_card_from, bid_card_to, bid_search_from, bid_search_to, is_shipping, card_price_from_type, card_price_from_delta, card_price_to_type, card_price_to_delta, is_free_shipping, is_query_only_id, competitors_rating_from, competitors_rating_to, is_local_delivery, ids_list, is_count_offers_in_model, has_strategy, type, description, order_conversion_from, order_conversion_to, category_id, reach_strategy, bid_card_recommended_position, bid_card_recommended_from, bid_card_recommended_to, experiment_type, is_discount, is_cpa, min_cbid_from, min_cbid_to, min_bid_from, min_bid_to, min_match_cbid, min_match_bid, hash, is_hide_on_market, category_type, quality_factor_from, quality_factor_to, order_drr_from, order_drr_to, directory_id, is_dont_up_to_min, bid_from, bid_to, bid_recommended_position, bid_recommended_from, bid_recommended_to, is_cutprice, shard) VALUES (1, 4, '2телефона и фотик', null, null, null, null, null, 448, null, '2016-07-14 13:06:52', 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 0, null, 0, null, 0, null, 1, null, null, 0, '["855618",1625005,"1481436"]', null, null, 'SHOP', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'bef7a590eaeebe07c801c6f4209d3efe', null, 'NAME', null, null, null, null, null, null, null, null, null, null, null, null, 'shard1');
INSERT INTO shop_offer_filter (id, shop_id, name, query, category, price_from, price_to, has_card, feed_id, created_at, updated_at, sort_order, purchase_price_from, purchase_price_to, click_days, click_count_from, click_count_to, click_price_from, click_price_to, order_days, order_count_from, order_count_to, order_cpo_from, order_cpo_to, is_available, card_position_from, card_position_to, bid_card_from, bid_card_to, bid_search_from, bid_search_to, is_shipping, card_price_from_type, card_price_from_delta, card_price_to_type, card_price_to_delta, is_free_shipping, is_query_only_id, competitors_rating_from, competitors_rating_to, is_local_delivery, ids_list, is_count_offers_in_model, has_strategy, type, description, order_conversion_from, order_conversion_to, category_id, reach_strategy, bid_card_recommended_position, bid_card_recommended_from, bid_card_recommended_to, experiment_type, is_discount, is_cpa, min_cbid_from, min_cbid_to, min_bid_from, min_bid_to, min_match_cbid, min_match_bid, hash, is_hide_on_market, category_type, quality_factor_from, quality_factor_to, order_drr_from, order_drr_to, directory_id, is_dont_up_to_min, bid_from, bid_to, bid_recommended_position, bid_recommended_from, bid_recommended_to, is_cutprice, shard) VALUES (8, 4, 'Карточка товара', null, null, null, null, 1, null, null, '2016-06-27 20:43:43', 2, null, null, 7, null, null, null, null, 7, null, null, null, null, null, null, null, null, null, null, null, 0, null, 0, null, 0, null, 0, null, null, 0, '[]', 0, null, 'SHOP', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '104f2f8f1f9bd5680e3e3a4d49877447', null, 'NAME', null, null, null, null, null, null, null, null, null, null, null, null, 'shard2');
INSERT INTO shop_offer_filter (id, shop_id, name, query, category, price_from, price_to, has_card, feed_id, created_at, updated_at, sort_order, purchase_price_from, purchase_price_to, click_days, click_count_from, click_count_to, click_price_from, click_price_to, order_days, order_count_from, order_count_to, order_cpo_from, order_cpo_to, is_available, card_position_from, card_position_to, bid_card_from, bid_card_to, bid_search_from, bid_search_to, is_shipping, card_price_from_type, card_price_from_delta, card_price_to_type, card_price_to_delta, is_free_shipping, is_query_only_id, competitors_rating_from, competitors_rating_to, is_local_delivery, ids_list, is_count_offers_in_model, has_strategy, type, description, order_conversion_from, order_conversion_to, category_id, reach_strategy, bid_card_recommended_position, bid_card_recommended_from, bid_card_recommended_to, experiment_type, is_discount, is_cpa, min_cbid_from, min_cbid_to, min_bid_from, min_bid_to, min_match_cbid, min_match_bid, hash, is_hide_on_market, category_type, quality_factor_from, quality_factor_to, order_drr_from, order_drr_to, directory_id, is_dont_up_to_min, bid_from, bid_to, bid_recommended_position, bid_recommended_from, bid_recommended_to, is_cutprice, shard) VALUES (24, 4, 'Книги без стратегии', null, 'Книги', null, null, null, null, null, '2016-06-27 20:43:43', 3, null, null, 7, null, null, null, null, 7, null, null, null, null, null, null, null, null, null, null, null, 0, null, 0, null, 0, null, 0, null, null, 0, '[]', 0, 0, 'SHOP', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '57f9e5308b9ec7e7ebd6cbfc4822530e', null, 'NAME', null, null, null, null, null, null, null, null, null, null, null, null, 'shard5');
INSERT INTO shop_offer_filter (id, shop_id, name, query, category, price_from, price_to, has_card, feed_id, created_at, updated_at, sort_order, purchase_price_from, purchase_price_to, click_days, click_count_from, click_count_to, click_price_from, click_price_to, order_days, order_count_from, order_count_to, order_cpo_from, order_cpo_to, is_available, card_position_from, card_position_to, bid_card_from, bid_card_to, bid_search_from, bid_search_to, is_shipping, card_price_from_type, card_price_from_delta, card_price_to_type, card_price_to_delta, is_free_shipping, is_query_only_id, competitors_rating_from, competitors_rating_to, is_local_delivery, ids_list, is_count_offers_in_model, has_strategy, type, description, order_conversion_from, order_conversion_to, category_id, reach_strategy, bid_card_recommended_position, bid_card_recommended_from, bid_card_recommended_to, experiment_type, is_discount, is_cpa, min_cbid_from, min_cbid_to, min_bid_from, min_bid_to, min_match_cbid, min_match_bid, hash, is_hide_on_market, category_type, quality_factor_from, quality_factor_to, order_drr_from, order_drr_to, directory_id, is_dont_up_to_min, bid_from, bid_to, bid_recommended_position, bid_recommended_from, bid_recommended_to, is_cutprice, shard) VALUES (57, 4, 'Конкурентная цена в ТОП6', null, null, 1000, 3000, null, null, null, '2016-06-27 20:43:43', 4, null, null, 7, null, null, null, null, 7, null, null, null, null, null, null, null, null, null, null, null, 0, null, 0, 'top5_avg', 1, null, 0, null, null, 0, '{}', 0, null, 'SHOP', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '5958938d9c9a35495a9a9dd1d47b6c24', null, 'NAME', null, null, null, null, null, null, null, null, null, null, null, null, null);
INSERT INTO shop_offer_filter (id, shop_id, name, query, category, price_from, price_to, has_card, feed_id, created_at, updated_at, sort_order, purchase_price_from, purchase_price_to, click_days, click_count_from, click_count_to, click_price_from, click_price_to, order_days, order_count_from, order_count_to, order_cpo_from, order_cpo_to, is_available, card_position_from, card_position_to, bid_card_from, bid_card_to, bid_search_from, bid_search_to, is_shipping, card_price_from_type, card_price_from_delta, card_price_to_type, card_price_to_delta, is_free_shipping, is_query_only_id, competitors_rating_from, competitors_rating_to, is_local_delivery, ids_list, is_count_offers_in_model, has_strategy, type, description, order_conversion_from, order_conversion_to, category_id, reach_strategy, bid_card_recommended_position, bid_card_recommended_from, bid_card_recommended_to, experiment_type, is_discount, is_cpa, min_cbid_from, min_cbid_to, min_bid_from, min_bid_to, min_match_cbid, min_match_bid, hash, is_hide_on_market, category_type, quality_factor_from, quality_factor_to, order_drr_from, order_drr_to, directory_id, is_dont_up_to_min, bid_from, bid_to, bid_recommended_position, bid_recommended_from, bid_recommended_to, is_cutprice, shard) VALUES (4703905, 27, 'страт_не_выпол.', null, 'телефон', 10.1, 10.2, null, null, '2017-11-22 17:18:41', '2017-11-22 17:15:28', 5, 11.1, 11.2, 7, 1, 2, 12.1, 12.2, 7, 3, 4, 13.1, 13.2, true, 5, 6, 14.1, 14.2, 15.1, 15.2, 0, 'MIN', 24.1, 'MIN', 24.2, true, 0, 2, 3, 0, '{"0": "999996", "1": 999995}', 0, 1, 'SHOP', null, 17.1, 17.2, null, 0, 1, 18.1, 18.2, null, true, true, null, 19.1, 19.2, 20.1, 20.2, 1, '914c5dc9fb3eecdb40fac445c16ff21d', true, 'NAME', null, null, 21.1, 21.2, null, true, 22.1, 22.2, 1, 23.1, 23.2, true, null);
INSERT INTO shop_offer_filter (id, shop_id, name, query, category, price_from, price_to, has_card, feed_id, created_at, updated_at, sort_order, purchase_price_from, purchase_price_to, click_days, click_count_from, click_count_to, click_price_from, click_price_to, order_days, order_count_from, order_count_to, order_cpo_from, order_cpo_to, is_available, card_position_from, card_position_to, bid_card_from, bid_card_to, bid_search_from, bid_search_to, is_shipping, card_price_from_type, card_price_from_delta, card_price_to_type, card_price_to_delta, is_free_shipping, is_query_only_id, competitors_rating_from, competitors_rating_to, is_local_delivery, ids_list, is_count_offers_in_model, has_strategy, type, description, order_conversion_from, order_conversion_to, category_id, reach_strategy, bid_card_recommended_position, bid_card_recommended_from, bid_card_recommended_to, experiment_type, is_discount, is_cpa, min_cbid_from, min_cbid_to, min_bid_from, min_bid_to, min_match_cbid, min_match_bid, hash, is_hide_on_market, category_type, quality_factor_from, quality_factor_to, order_drr_from, order_drr_to, directory_id, is_dont_up_to_min, bid_from, bid_to, bid_recommended_position, bid_recommended_from, bid_recommended_to, is_cutprice, shard) VALUES (2, 1284, 'С второго шарда', null, null, null, null, null, 448, null, '2016-07-14 13:06:52', 1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 0, null, 0, null, 0, null, 1, null, null, 0, '["855618",1625005,"1481436"]', null, null, 'SHOP', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'bef7a590eaeebe07c801c6f4209d3efe', null, 'NAME', null, null, null, null, null, null, null, null, null, null, null, null, null);


INSERT INTO shop_offer_param (id, shop_id, name, created_at) VALUES (2803, 4, 'popularity', '2016-03-29 16:55:00');
INSERT INTO shop_offer_param_filter (id, filter_id, param_id, value_from, value_to) VALUES (8703, 4703905, 2803, 1, null);

INSERT INTO shop_offer_param (id, shop_id, name, created_at) VALUES (2804, 4, 'popularity2', '2016-03-29 16:55:00');
INSERT INTO shop_offer_param_filter (id, filter_id, param_id, value_from, value_to) VALUES (8704, 4703905, 2804, null, 3);

insert into shop_offer_filter_ya_category(filter_id, ya_category_id) values (4703905, 101);
insert into shop_offer_filter_ya_category(filter_id, ya_category_id) values (4703905, 4556789094);

insert into shop_offer_filter_vendor(filter_id, vendor) values (4703905, 'V1');
insert into shop_offer_filter_vendor(filter_id, vendor) values (4703905, 'VENDOR2');

insert into shop_offer_param_name_filter(filter_id, param, value_from, value_to) values (4703905, 'Param1', null, null);
insert into shop_offer_param_name_filter(filter_id, param, value_from, value_to) values (4703905, 'Param2', 1, null);
insert into shop_offer_param_name_filter(filter_id, param, value_from, value_to) values (4703905, 'Param3', null, 2);
insert into shop_offer_param_name_filter(filter_id, param, value_from, value_to) values (4703905, 'Param4', 1, 2);
