# -*- coding: utf-8 -*-


class Header(object):
    TO = "To"
    FROM = "From"
    IN_REPLY_TO = "In-Reply-To"
    REPLY_TO = "Reply-To"
    REFERENCES = "References"
    RECEIVED = "Received"
    MESSAGE_ID = "Message-Id"
    LIST_ID = "List-Id"
    X_MAILER = "X-Mailer"
    SUBJECT = "Subject"
    AUTHENTICATION_RESULTS = "Authentication-Results"
    X_YANDEX_SPAM = "X-Yandex-Spam"
    X_SPAM_FLAG = "X-Spam-Flag"
    X_YANDEX_HINT = "X-Yandex-Hint"
    X_YANDEX_CAPTCHA_ENTERED = "X-Yandex-Captcha-Entered"
    X_YANDEX_FWD = "X-Yandex-Fwd"
    X_YANDEX_FORWARD = "X-Yandex-Forward"
    X_YANDEX_INTERNAL = "X-Yandex-Internal"
    X_YANDEX_TIMEMARK = "X-Yandex-TimeMark"
    X_YANDEX_LOCAL = "X-Yandex-Local"
    X_YANDEX_SUID_STATUS = "X-Yandex-Uid-Status"
    DATE = "Date"
    RETURN_PATH = "Return-Path"
    CONTENT_TYPE = "Content-Type"
    MIME_VERSION = "MIME-Version"
    CONTENT_TRANSFER_ENCODING = "Content-Transfer-Encoding"
    DKIM_SIGNATURE = "DKIM-Signature"
    AUTHENTICATION_RESULTS = "Authentication-Results"
