# coding: utf-8
from __future__ import absolute_import, division, print_function, unicode_literals

RAW_RIDE = {
    "bus": None,
    "bus_images": None,
    "buy_place_cnt_max": "5",
    "can_be_annulated": "1",
    "carrier_id": "87",
    "carrier_rating": None,
    "carrier_title": 'ООО "Перевозчик"',
    "currency_agent_id": 1,
    "currency_source_id": 1,
    "datetime_end": "2021-02-18 21:00:00",
    "datetime_end_inaccurate": 0,
    "datetime_start": "2021-02-18 10:00:00",
    "distance": 540,
    "is_direct": 1,
    "is_free_seating": 0,
    "is_relevant": 1,
    "place_cnt": 13,
    "price_agent_fee": 0,
    "price_agent_max": 602,
    "price_source_tariff": 602,
    "price_unitiki": 602,
    "properties": None,
    "ride_segment_id": "64036",
    "route_name": "Москва — Санкт-Петербург",
    "station_end": {
        "city_id": 6,
        "city_title": "Великий Новгород",
        "city_type": "город",
        "country_id": 1,
        "country_iso": "RU",
        "country_title": "Россия",
        "district_title": "",
        "lat": "58.522810",
        "lng": "31.269915",
        "region_title": "Новгородская область",
        "station_address": "Октябрьская улица, дом 1",
        "station_id": 7,
        "station_is_verified": "0",
        "station_lat": "58.525462",
        "station_lng": "31.250977",
        "station_title": "Автовокзал",
        "station_type": 0,
    },
    "station_start": {
        "city_id": 1,
        "city_title": "Москва",
        "city_type": "город федерального значения",
        "country_id": 1,
        "country_iso": "RU",
        "country_title": "Россия",
        "district_title": "",
        "lat": "55.753215",
        "lng": "37.622504",
        "region_title": "",
        "station_address": "Павелецкая площадь, дом 1Ас1",
        "station_id": 5,
        "station_is_verified": "3",
        "station_lat": "55.729823",
        "station_lng": "37.640596",
        "station_title": "Павелецкий вокзал",
        "station_type": 3,
    },
    "ticket_printed_required": "0",
    "vendor_id": 1048,
}

RESULT_RIDE = {
    "@id": "eyJyaWRlX3NpZCI6ICI2NDAzNiJ9",
    "arrival": "2021-02-18T21:00:00",
    "benefits": None,
    "bookFields": ["name", "gender", "birthDate", "phone", "document", "email"],
    "bookOnly": False,
    "bus": None,
    "canPayOffline": False,
    "carrier": 'ООО "Перевозчик"',
    "carrierID": 'ООО "Перевозчик"',
    "carrierModel": None,
    "connector": "unitiki-new",
    "currency": "RUB",
    "departure": "2021-02-18T10:00:00",
    "fee": 0.0,
    "freeSeats": 13,
    "from": {"supplier_id": "s5", "id": "backmap(s5)", "desc": "Москва, Павелецкий вокзал"},
    "name": "Москва — Санкт-Петербург",
    "number": None,
    "onlinePrice": None,
    "onlineRefund": True,
    "partner": "unitiki-new",
    "partnerEmail": None,
    "partnerName": "Unitiki",
    "partnerPhone": None,
    "price": 602.0,
    "refundConditions": "Возврат на сайте возможен не позднее чем за 15 минут до отправления автобуса.",
    "status": {"id": 1, "name": "sale"},
    "supplierModel": {
        "code": "unitiki-new",
        "id": 1,
        "name": "unitiki-new",
        "registerType": {"code": "register_type_code", "id": 1},
    },
    "ticketLimit": 5,
    "to": {"supplier_id": "s7", "id": "backmap(s7)", "desc": "Великий Новгород, Автовокзал"},
}

RAW_TICKET = {
    "baggage_info": (
        "«Багажом» является груз провозимый пассажиром в багажном отделении транспортного средства, в количестве не "
        "более двух мест, длина, ширина и высота каждого из которых в сумме не превышают 180 см.\r\n"
        "Стоимость провоза багажа 8 рублей.\r\n"
        "Количество багажа, превышающее 2 единицы на одного пассажира  (например, велосипед или байдарка), перевозятся "
        "при наличии места в багажном отделении автобуса по цене 50 рублей за одно место."
    ),
    "birthday": "1980-01-01",
    "bus": None,
    "card_identity_id": 1,
    "card_identity_title": "Паспорт",
    "carrier_id": "159",
    "carrier_rating": None,
    "carrier_title": 'ООО "Перевозчик"',
    "citizenship_id": 170,
    "citizenship_title": "Россия",
    "currency_agent_id": 1,
    "currency_source_id": 1,
    "datetime_buy": "2021-10-27 18:36:34",
    "datetime_cancel": None,
    "datetime_end": "2021-10-28 07:00:00",
    "datetime_start": "2021-10-28 00:00:00",
    "distance": None,
    "email": "ypetrov@yandex-team.ru",
    "gender": 0,
    "name": "Фамилия Имя Отчество",
    "operation_hash": "1b275d996119443bf7b20d6e6b551de1",
    "operation_id": 2262,
    "organization": {
        "inn": "7733333893",
        "ogrn": "1333300333195",
        "organization_id": None,
        "phone": None,
        "title_full": 'Общество с ограниченной ответственностью "Перевозчик"',
        "title_small": 'ООО "Перевозчик"',
        "use_vat": 0,
    },
    "phone": "79122417296",
    "position": 2,
    "price_agent": 0,
    "price_agent_fee": 0,
    "price_agent_max": 128,
    "price_source_tariff": 128,
    "price_unitiki": 128,
    "route_name": "Тверь - Великий Новгород",
    "series_number": "1234123456",
    "station_end": {
        "city_id": 6,
        "city_title": "Великий Новгород",
        "country_id": 1,
        "country_iso": "RU",
        "country_title": "Россия",
        "district_title": "",
        "lat": "58.522810",
        "lng": "31.269915",
        "region_title": "Новгородская область",
        "station_address": "Октябрьская улица, дом 1",
        "station_id": 7,
        "station_lat": "58.525462",
        "station_lng": "31.250977",
        "station_title": "Автовокзал",
        "station_type": 0,
    },
    "station_start": {
        "city_id": 5,
        "city_title": "Тверь",
        "country_id": 1,
        "country_iso": "RU",
        "country_title": "Россия",
        "district_title": "",
        "lat": "56.859847",
        "lng": "35.911995",
        "region_title": "Тверская область",
        "station_address": "улица Коминтерна, дом 10",
        "station_id": 6,
        "station_lat": "56.83413",
        "station_lng": "35.899395",
        "station_title": "Автовокзал",
        "station_type": 3,
    },
    "status": 1,
    "ticket_id": 2372,
    "ticket_printed_forgot_info": "Обратиться в справочное бюро автовокзала для получения дубликата билета.",
    "ticket_printed_required": "1",
    "ticket_refund": None,
    "ticket_refund_info": (
        "• До отправления осталось более 2 часов – возвращается 95 %.\n"
        "• До отправления осталось от 2 часов до 1 часа – возвращается 85 %.\n"
        "• До отправления осталось менее 1 часа – денежные средства не возвращаются.\n"
        "• В любое время после отправления – денежные средства не возвращаются."
    ),
    "user_id": None,
}
