# coding: utf-8
from __future__ import absolute_import, division, print_function, unicode_literals


RAW_TICKET = {
    "passenger": {
        "gender": "Мужской",
        "citizenship": "Россия",
        "firstname": "Иван",
        "lastname": "Кожедуб",
        "studentticket": "",
        "mailadress": None,
        "birthday": "1980-02-01",
        "isic": None,
        "documenttype": "1",
        "phonenumber": "+79126552244",
        "tariff_code": "Y",
        "document": "9417645155",
        "documentedate": None,
        "middlenames": "Савельевич",
        "tariffCost": 1147.94,
    },
    "commissions": {
        "commissions": [
            {
                "description": "agent fee №2",
                "disposition": 1,
                "return_value": None,
                "return_vat": None,
                "type": 3,
                "value": 6000,
                "vat": 1339,
                "vat_value": 2000,
            },
            {
                "description": "service charge",
                "disposition": 2,
                "return_value": None,
                "return_vat": None,
                "type": 6,
                "value": 3000,
                "vat": 1339,
                "vat_value": 2000,
            },
            {
                "description": "agent fee №1",
                "disposition": 2,
                "return_value": None,
                "return_vat": None,
                "type": 5,
                "value": 2000,
                "vat": 1339,
                "vat_value": 2000,
            },
        ]
    },
    "bus_class": "",
    "exchange_blank": False,
    "start_station_name": 'Автовокзал "Пермь"',
    "trip_number": "1301 Пермь-Североуральск",
    "is_online_refund": True,
    "date_to_buyout": "2021-02-16T12:11:35Z",
    "end_city": "Карпинск",
    "insurance": {"phone": "", "tm": None, "name": 'ЗАО "Страховая группа "УралСиб" Пермский филиал'},
    "end_station_adress": "",
    "start_city": "Пермь",
    "total_amount_vat": 574,
    "agentorder_id": "api_50fcda47-d2c0-437b-818b-5bb1ffa4bc0c",
    "platform": "8",
    "tariff_vat": 0,
    "is_baggage": False,
    "service_type": "Автобусный",
    "end_station_name": "Карпинск АС",
    "start_date": "2021-02-22",
    "ticket_id": 15093932,
    "updated_date": "2021-02-16T10:21:37Z",
    "tariff_code": "Y",
    "end_date": "2021-02-22",
    "order_id": 11451776,
    "ticket_series": "",
    "start_time": "08:30",
    "end_timezone": "Asia/Yekaterinburg",
    "start_station_adress": "улица  Революции; дом 68",
    "international_trip": False,
    "agent": {"phone": "", "tm": None, "name": 'АГН RU "Яндекс" ООО'},
    "tariff": 114794,
    "return_info": {"return_total_amount": None, "return_total_tariff": None, "return_total_tariff_vat": None},
    "start_timezone": "Asia/Yekaterinburg",
    "total_amount": 118238,
    "total_agent_income": 0,
    "ticket_status": 1,
    "number_seat": "1",
    "minutes_for_buyout": 109,
    "type_tariff_description": "Базовый тариф стоимости проезда одного пассажира в одном направлении",
    "return_cause": [
        {
            "approximate_amount": 118238,
            "cause": "Принудительно, при отмене рейса..",
            "id": "8D7D723399017167E0530300F00A7500",
        },
        {
            "approximate_amount": 109054,
            "cause": "Добровольно, более чем за 2 ч до отправления рейса.",
            "id": "B3FAD0D508A82132E053E41C0CB9F027",
        },
    ],
    "carrier": {"phone": "", "tm": "Лыкова Т.Ю.", "name": "Лыкова Т.Ю."},
    "end_time": "19:36",
    "bus_model": "",
    "carrier_ticket_number": "36606519100",
    "ticket_number": "15093932",
    "final_price_greater": False,
    "currency_code": "RUB",
    "created_date": "2021-02-16T10:21:37Z",
}
