package ru.beru.sortingcenter.test.allure

object ScEpic {
    const val INITIAL_ACCEPTANCE = "Первичная приемка"
    const val INITIAL_RETURN_ACCEPTANCE = "Первичная приёмка возвратов"
    const val XDOC_ACCEPTANCE = "Приемка XDOC"
    const val XDOC_ACCEPTANCE_FINISH = "Завершение приемки XDOC"
    const val XDOC_FIX_INBOUND = "Фиксировать поставку"
    const val HOME = "Главный экран"
    const val DISPATCH_TO_COURIER = "Отгрузка заказов курьеру"
    const val DISPATCH_LOTS_TO_COURIER = "Отгрузка лотов курьеру"
    const val DISPATCH_TO_WAREHOUSE = "Отгрузка заказов на возврат"
    const val INVENTORYING = "Инвентаризация"
    const val PREPARE_TO_DISPATCH_COURIER = "Подготовка к отгрузке курьеру"
    const val PREPARE_LOT_TO_DISPATCH = "Подготовить лоты"
    const val SORTING_ORDERS = "Сортировка заказов"
    const val RETURNS_UTILIZATION = "Утилизация возвратов"
    const val MOVE_ORDERS = "Перемещение заказов"
    const val ACCEPT_RETURN = "Приемка возвратов"
    const val ACCEPT_INBOUNDS = "Приемка поставки"
    const val ACCEPT_LOTS = "Приемка лотов"
    const val SORTABLE_ACCEPT_SIMPLE = "Операция - первичной приёмки посылок"
    const val TICKET_SCAN = "Операция - сканирование талона"
    const val LOT_ACCEPT = "Операция - первичной приёмки лотов"
    const val COMMON_INFO = "Инфо скан"
    const val ZONE_CHECK_IN = "Выбор зоны"
    const val TICKET_SYSTEM_ACCEPTANCE = "Пересчет на приемке"
    const val PALLETIZATION = "Палетизация"
    const val BUFFER_CELL = "Ячейка хранения"
    const val LOT_INVENTORY = "Инвентаризация лота"
    const val USER_PASSWORD = "Персональные пароли для кладовщиков"
    const val OUTBOUNDS = "Отгрузки"
    const val TRANSFER_LOT = "Вкладывание лота в лот"
}
