# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: http.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='http.proto',
  package='NAppHostHttp',
  syntax='proto3',
  serialized_pb=_b('\n\nhttp.proto\x12\x0cNAppHostHttp\"&\n\x07THeader\x12\x0c\n\x04Name\x18\x01 \x01(\t\x12\r\n\x05Value\x18\x02 \x01(\t\"\x9a\x02\n\x0cTHttpRequest\x12\x32\n\x06Method\x18\x01 \x01(\x0e\x32\".NAppHostHttp.THttpRequest.EMethod\x12\x32\n\x06Scheme\x18\x02 \x01(\x0e\x32\".NAppHostHttp.THttpRequest.EScheme\x12\x0c\n\x04Path\x18\x03 \x01(\t\x12&\n\x07Headers\x18\x04 \x03(\x0b\x32\x15.NAppHostHttp.THeader\x12\x0f\n\x07\x43ontent\x18\x05 \x01(\x0c\"1\n\x07\x45Method\x12\x07\n\x03Get\x10\x00\x12\x08\n\x04Post\x10\x01\x12\x07\n\x03Put\x10\x02\x12\n\n\x06\x44\x65lete\x10\x03\"(\n\x07\x45Scheme\x12\x08\n\x04None\x10\x00\x12\x08\n\x04Http\x10\x01\x12\t\n\x05Https\x10\x02\"s\n\rTHttpResponse\x12\x12\n\nStatusCode\x18\x01 \x01(\r\x12&\n\x07Headers\x18\x02 \x03(\x0b\x32\x15.NAppHostHttp.THeader\x12\x0f\n\x07\x43ontent\x18\x03 \x01(\x0c\x12\x15\n\rIsSdchEncoded\x18\x04 \x01(\x08\x62\x06proto3')
)



_THTTPREQUEST_EMETHOD = _descriptor.EnumDescriptor(
  name='EMethod',
  full_name='NAppHostHttp.THttpRequest.EMethod',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Get', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Post', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Put', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Delete', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=260,
  serialized_end=309,
)
_sym_db.RegisterEnumDescriptor(_THTTPREQUEST_EMETHOD)

_THTTPREQUEST_ESCHEME = _descriptor.EnumDescriptor(
  name='EScheme',
  full_name='NAppHostHttp.THttpRequest.EScheme',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='None', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Http', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Https', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=311,
  serialized_end=351,
)
_sym_db.RegisterEnumDescriptor(_THTTPREQUEST_ESCHEME)


_THEADER = _descriptor.Descriptor(
  name='THeader',
  full_name='NAppHostHttp.THeader',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Name', full_name='NAppHostHttp.THeader.Name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Value', full_name='NAppHostHttp.THeader.Value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=66,
)


_THTTPREQUEST = _descriptor.Descriptor(
  name='THttpRequest',
  full_name='NAppHostHttp.THttpRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Method', full_name='NAppHostHttp.THttpRequest.Method', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Scheme', full_name='NAppHostHttp.THttpRequest.Scheme', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Path', full_name='NAppHostHttp.THttpRequest.Path', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Headers', full_name='NAppHostHttp.THttpRequest.Headers', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Content', full_name='NAppHostHttp.THttpRequest.Content', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _THTTPREQUEST_EMETHOD,
    _THTTPREQUEST_ESCHEME,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=351,
)


_THTTPRESPONSE = _descriptor.Descriptor(
  name='THttpResponse',
  full_name='NAppHostHttp.THttpResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='StatusCode', full_name='NAppHostHttp.THttpResponse.StatusCode', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Headers', full_name='NAppHostHttp.THttpResponse.Headers', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Content', full_name='NAppHostHttp.THttpResponse.Content', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='IsSdchEncoded', full_name='NAppHostHttp.THttpResponse.IsSdchEncoded', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=353,
  serialized_end=468,
)

_THTTPREQUEST.fields_by_name['Method'].enum_type = _THTTPREQUEST_EMETHOD
_THTTPREQUEST.fields_by_name['Scheme'].enum_type = _THTTPREQUEST_ESCHEME
_THTTPREQUEST.fields_by_name['Headers'].message_type = _THEADER
_THTTPREQUEST_EMETHOD.containing_type = _THTTPREQUEST
_THTTPREQUEST_ESCHEME.containing_type = _THTTPREQUEST
_THTTPRESPONSE.fields_by_name['Headers'].message_type = _THEADER
DESCRIPTOR.message_types_by_name['THeader'] = _THEADER
DESCRIPTOR.message_types_by_name['THttpRequest'] = _THTTPREQUEST
DESCRIPTOR.message_types_by_name['THttpResponse'] = _THTTPRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

THeader = _reflection.GeneratedProtocolMessageType('THeader', (_message.Message,), dict(
  DESCRIPTOR = _THEADER,
  __module__ = 'http_pb2'
  # @@protoc_insertion_point(class_scope:NAppHostHttp.THeader)
  ))
_sym_db.RegisterMessage(THeader)

THttpRequest = _reflection.GeneratedProtocolMessageType('THttpRequest', (_message.Message,), dict(
  DESCRIPTOR = _THTTPREQUEST,
  __module__ = 'http_pb2'
  # @@protoc_insertion_point(class_scope:NAppHostHttp.THttpRequest)
  ))
_sym_db.RegisterMessage(THttpRequest)

THttpResponse = _reflection.GeneratedProtocolMessageType('THttpResponse', (_message.Message,), dict(
  DESCRIPTOR = _THTTPRESPONSE,
  __module__ = 'http_pb2'
  # @@protoc_insertion_point(class_scope:NAppHostHttp.THttpResponse)
  ))
_sym_db.RegisterMessage(THttpResponse)


# @@protoc_insertion_point(module_scope)
