# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: post_data.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='post_data.proto',
  package='NYabs',
  syntax='proto2',
  serialized_pb=_b('\n\x0fpost_data.proto\x12\x05NYabs\"4\n\tTPostData\x12\x14\n\x0c\x42igbResponse\x18\x01 \x01(\t\x12\x11\n\tCgiString\x18\x02 \x01(\t')
)




_TPOSTDATA = _descriptor.Descriptor(
  name='TPostData',
  full_name='NYabs.TPostData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='BigbResponse', full_name='NYabs.TPostData.BigbResponse', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='CgiString', full_name='NYabs.TPostData.CgiString', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=78,
)

DESCRIPTOR.message_types_by_name['TPostData'] = _TPOSTDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TPostData = _reflection.GeneratedProtocolMessageType('TPostData', (_message.Message,), dict(
  DESCRIPTOR = _TPOSTDATA,
  __module__ = 'post_data_pb2'
  # @@protoc_insertion_point(class_scope:NYabs.TPostData)
  ))
_sym_db.RegisterMessage(TPostData)


# @@protoc_insertion_point(module_scope)
