export const CURRENT_USER_ID = 769565082;
export const CURRENT_USER_LOGIN = 'rnpn.supplier.one';

export default {
    authType: 'SESSION',
    age: 98022,
    expires_in: 7677978,
    ttl: '5',
    error: 'OK',
    status: {value: 'VALID', id: 0},
    uid: {value: '769565082', lite: false, hosted: false},
    login: 'rnpn.supplier.one',
    have_password: true,
    have_hint: true,
    aliases: {'1': 'rnpn-supplier-one'},
    karma: {value: 0},
    karma_status: {value: 0},
    regname: 'rnpn.supplier.one',
    display_name: {name: 'rnpn.supplier.one', avatar: {default: '49368/jIruTOXhOEwS3BB929FgJtwFHlk-1', empty: false}},
    dbfields: {
        'accounts.login.uid': 'rnpn-supplier-one',
        'userinfo.birth_date.uid': '',
        'userinfo.firstname.uid': 'Vasily',
        'userinfo.lastname.uid': 'Pupkin',
        'userinfo.sex.uid': '0',
    },
    attributes: {'34': 'ru'},
    'address-list': [
        {
            address: 'rnpn.supplier.one@ya.ru',
            validated: true,
            default: false,
            rpop: false,
            silent: false,
            unsafe: false,
            native: true,
            'born-date': '2018-11-12 15:07:29',
        },
        {
            address: 'rnpn.supplier.one@yandex.by',
            validated: true,
            default: false,
            rpop: false,
            silent: false,
            unsafe: false,
            native: true,
            'born-date': '2018-11-12 15:07:29',
        },
        {
            address: 'rnpn.supplier.one@yandex.com',
            validated: true,
            default: false,
            rpop: false,
            silent: false,
            unsafe: false,
            native: true,
            'born-date': '2018-11-12 15:07:29',
        },
        {
            address: 'rnpn.supplier.one@yandex.kz',
            validated: true,
            default: false,
            rpop: false,
            silent: false,
            unsafe: false,
            native: true,
            'born-date': '2018-11-12 15:07:29',
        },
        {
            address: 'rnpn.supplier.one@yandex.ru',
            validated: true,
            default: true,
            rpop: false,
            silent: false,
            unsafe: false,
            native: true,
            'born-date': '2018-11-12 15:07:29',
        },
    ],
    phones: [],
    public_id: '08dy5ch88tf21cwr2x83bvujgw',
    auth: {password_verification_age: 12277786, have_password: true, secure: true, partner_pdd_token: false},
    connection_id: 's:1633691182959:NOmxO09r7YEAAIEAuAYCKg:43',
    user_ticket:
        '3:user:CMqmARDYooCTBhoiCgYImsP67gIQmsP67gIaDGJiOnNlc3Npb25pZCCQ_HooAA:SL1gfuSldiQkDXAZwm9dgzz9mWzm8aWXhEuV5FqnUKTDeeEeX_nUGCqMDicSg61WuNMPWjFUE1gaKRuOCMqcZ3ES-kJLnfGWtnKkNZRtbWkPCSULXU-CXwQqzTIaC7N9fyR_B_yBQ8_0pmAeYl138Rt2uWQ9hNpO6gmohoOQlZAdDbtw2fLUHFcPwxcO6pV3WhubqbS7-kYhg0w9Q_VXAezVZGnWeHZp6wVIApwBybtWkFCCh4QZXh0hSQBdkIUTjPTKVnYAe1EUZ8GkR_CXTuBGPIu52Wz3_qBUrOUjK2uhuOm-TbESBnk2hFxxas87tvODaohCibNAyDtJ4_fhuw',
};
