export const CURRENT_USER_ID = 477226873;
export const CURRENT_USER_LOGIN = 'b2b-mobile-tester';

export default {
    oauth: {
        uid: String(CURRENT_USER_ID),
        token_id: '2951689646',
        device_id: '',
        device_name: '',
        scope: 'market:partner-api',
        ctime: '2021-08-30 20:05:26',
        issue_time: '2021-08-30 20:05:26',
        expire_time: '2022-08-30 20:05:26',
        is_ttl_refreshable: true,
        client_id: 'f071950af434499180d509db1c778284',
        client_name: 'b2b-mobile-tester app',
        client_icon: '',
        client_homepage: 'http://rnpn-shop.yandex.ru/',
        client_ctime: '2017-03-20 18:43:42',
        client_is_yandex: false,
        xtoken_id: '',
        meta: '',
    },
    status: {value: 'VALID', id: 0},
    error: 'OK',
    uid: {value: String(CURRENT_USER_ID), lite: false, hosted: false},
    login: 'b2b-mobile-tester',
    have_password: true,
    have_hint: true,
    aliases: {1: 'rnpn-tst'},
    karma: {value: 0},
    karma_status: {value: 0},
    regname: 'b2b-mobile-tester',
    display_name: {
        name: 'b2b-mobile-tester',
        avatar: {default: '49368/gTFwUzHCZDnx2uYu4EwNaVQtfU-1', empty: false},
    },
    dbfields: {
        'accounts.login.uid': 'rnpn-tst',
        'userinfo.birth_date.uid': '',
        'userinfo.firstname.uid': 'Vasily',
        'userinfo.lastname.uid': 'Pupkin',
        'userinfo.sex.uid': '0',
    },
    attributes: {34: 'ru'},
    'address-list': [
        {
            address: 'b2b-mobile-tester@ya.ru',
            validated: true,
            default: false,
            rpop: false,
            silent: false,
            unsafe: false,
            native: true,
            'born-date': '2017-03-15 14:21:17',
        },
        {
            address: 'b2b-mobile-tester@yandex.by',
            validated: true,
            default: false,
            rpop: false,
            silent: false,
            unsafe: false,
            native: true,
            'born-date': '2017-03-15 14:21:17',
        },
        {
            address: 'b2b-mobile-tester@yandex.com',
            validated: true,
            default: false,
            rpop: false,
            silent: false,
            unsafe: false,
            native: true,
            'born-date': '2017-03-15 14:21:17',
        },
        {
            address: 'b2b-mobile-tester@yandex.kz',
            validated: true,
            default: false,
            rpop: false,
            silent: false,
            unsafe: false,
            native: true,
            'born-date': '2017-03-15 14:21:17',
        },
        {
            address: 'b2b-mobile-tester@yandex.ru',
            validated: true,
            default: true,
            rpop: false,
            silent: false,
            unsafe: false,
            native: true,
            'born-date': '2017-03-15 14:21:17',
        },
        {
            address: 'b2b-mobile-tester@yandex.ua',
            validated: true,
            default: false,
            rpop: false,
            silent: false,
            unsafe: false,
            native: true,
            'born-date': '2017-03-15 14:21:17',
        },
    ],
    phones: [],
    user_ticket: '3:user:COOQARC',
    connection_id: 't:2951689646',
};
