@echo off
setLocal EnableExtensions EnableDelayedExpansion
chcp 1251
if exist C:\work\crm-support\data\support\autoGen\testmail_*.eml del /f /q C:\work\crm-support\data\support\autoGen\testmail_*.eml
if exist C:\work\crm-support\tests\ru\yandex\crm\tests\delivery\stageOne\autoGeneratedSending.java del /f /q C:\work\crm-support\tests\ru\yandex\crm\tests\delivery\stageOne\autoGeneratedSending.java
if exist C:\work\crm-support\tests\ru\yandex\crm\tests\delivery\stageTwo\autoGeneratedChecking.java del /f /q C:\work\crm-support\tests\ru\yandex\crm\tests\delivery\stageTwo\autoGeneratedChecking.java
if exist send del /f /q send
set file=from.eml
set javatest=C:\work\crm-support\tests\ru\yandex\crm\tests\delivery\stageOne\autoGeneratedSending.java
set javacheck=C:\work\crm-support\tests\ru\yandex\crm\tests\delivery\stageTwo\autoGeneratedChecking.java
set dest=testmail_1.eml
set dir=C:\work\crm-support\data\support\autoGen\
set /a num=2

call :jtest_fill
call :jcheck_fill

For /F "Delims=" %%I In ('findstr /C:"(stop)" mrules.txt') Do (
  Set V=%%~I
  for /F "tokens=1* delims='THEN'" %%i in ("!V!") do (
    set summaryfile=!dir!!dest!
	set ttest=%%i
	set ttest=!ttest:%%=!
	call :mail !ttest!
	  )
  for /F "tokens=2* delims='THEN'" %%i in ("!V!") do call :rule %%i
  call :cmails !var0! !var1! !var2! !var3! !var4!
  call :send
  call :checks
  call :rename
)
echo }>>"%javatest%"
echo }>>"%javacheck%"
exit

:mail
  set rname=%1
  set rule1=%2
  set cond1=%3
  set cond1=!cond1:^"=!
  set cond1=!cond1:^(= !
  set cond1=!cond1:^)= !
  set rule2=%4
  set cond2=%5
  set cond2=!cond2:^"=!
  set rule3=%6
  set cond3=%7
  set cond3=!cond3:^"=!
  set rule4=%8
  set cond4=%9
  set cond4=!cond4:^"=!
  call :parser
 exit /b

:rule
  set rrule1=%1
  set rcond1=%2
  set rrule2=%3
  set rcond2=%4
  set rrule3=%5
  set rcond3=%6
  set rrule4=%7
  set rcond4=%8
  call :rparser %rrule1% %rcond1%
  call :rparser %rrule2% %rcond2%
  call :rparser %rrule3% %rcond3%
  call :rparser %rrule4% %rcond4%
 exit /b

:parser
set var0=nope
set var1=nope
set var2=nope
set var3=nope
set var4=nope
  for %%i in (%rule1%) do (
    if "%%i"=="subject" (set var0=%cond1%) else (
    set var0=!rname!
  ))
  for %%i in (%rule1%) do (
    if "%%i"=="from" (set var1=%cond1%) else (
    set var1=nope
  ))
  for %%i in (%rule1%) do (
    if "%%i"=="to" (set var2=%cond1%) else (
    if "%%i"=="tocc" (set var2=%cond1%) else (
    set var2=nope
  )))
    for %%i in (%rule1%) do (
    if "%%i"=="header[x-otrs-fromfeedback]" (set var3=%cond1%) else (
    set var3=nope
  ))
  for %%i in (%rule1%) do (
    if "%%i"=="bodyregex" (set var4=%cond1%) else (
    set var4=nope
  ))
  exit /b

:rparser
set queue=nope
set rqueue=nope
set category=nope
set rcategory=nope
set reply=nope
set rvar3=nope
set rvar4=nope
  for %%i in (%1) do (
    if "%%i"=="queueId" (set queue=%2) else (
    if "%%i"=="request.queueId" (set rqueue=%2) else (
    if "%%i"=="categoryId" (set category=%2) else (
    if "%%i"=="request.categoryId" (set rcategory=%2) else (
    if "%%i"=="autoreplyId" (set reply=%2) else (
    exit /b
  ))))))
rem echo %queue%
rem echo %rqueue%
rem echo %category%
rem echo %rcategory%
rem echo %reply%
exit /b

:cmails
echo Content-Type: text/plain; charset="utf-8" >>"%summaryfile%"
echo MIME-Version: 1.0 >>"%summaryfile%"
echo Content-Transfer-Encoding: quoted-printable >>"%summaryfile%"
call :sub
call :from
call :to
call :otrs
echo.>>"%summaryfile%"
call :wiki

echo Created %dest%

exit /b

:sub
call set sub=%%var0:^:=%%
call set sub=%%sub:^(= %%
call set sub=%%sub:^)= %%
call :base64_enc sub "%sub%"
echo Subject: =?utf-8?b?%sub%?= >>"%summaryfile%"
exit /b

:base64_enc <var_to_set> <str>
for /f "delims=" %%I in (
    'powershell "[convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes(\"%~2\"))"'
) do set "%~1=%%I"
exit /b

:from
for %%i in (%var1%) do (
  if "%%i"=="nope" (echo From: agroroza@yandex-team.ru>>"%summaryfile%") else (
echo From: %var1%>>"%summaryfile%"
))
exit /b

:to
for %%i in (%var2%) do (
  if "%%i"=="nope" (echo To: direct@support.yandex.ru>>"%summaryfile%") else (
  echo To: %var2% >>"%summaryfile%"
))
exit /b

:otrs
for %%i in (%var3%) do (
  if "%%i"=="nope" (echo.>>"%summaryfile%") else (
  echo X-OTRS-fromfeedback: %var3% >>"%summaryfile%"
))
exit /b

:wiki
for %%i in ("%var4%") do (
  if "%%i"==""nope"" (echo.>>"%summaryfile%") else (
  echo %var4% >>"%summaryfile%"
))
exit /b


:rename
  set dest=testmail_%num%.eml
  set /a num=num+1
exit /b

:send
set testname=!rname:-=_!
set testname=!testname:.=_!
call set testname=%%testname:~0,-7%%_%%dest:~0,-4%%
echo     @Test>>"%javatest%"
echo     public void %testname%() throws IOException {>>"%javatest%"
echo         String messageId = mailSender().sendFile("./data/support/autoGen/%dest%", newMessageId(), newClientLogin());>>"%javatest%"
echo         putStageMessageId("%testname%", messageId);>>"%javatest%"
echo     }>>"%javatest%"
echo.>>"%javatest%"
exit /b

:checks
echo    @Test>>"%javacheck%"
echo    public void %testname%() throws SQLException {>>"%javacheck%"
echo        String messageId = getStageMessageId("%testname%");>>"%javacheck%"
echo.>>"%javacheck%"
echo        TicketRow ticket = SupportTicketStorage.getTicketByMessageId(messageId);>>"%javacheck%"
echo        Assert.assertNotNull(ticket);>>"%javacheck%"
echo        Assert.assertEquals(%rcond1%, ticket.%rrule1%);>>"%javacheck%"
echo    }>>"%javacheck%"
echo.>>"%javacheck%"
exit /b

:jtest_fill
echo package ru.yandex.crm.tests.delivery.stageOne;>>"%javatest%"
echo.>>"%javatest%"
echo import org.junit.Test;>>"%javatest%"
echo import ru.yandex.core.MailProvider;>>"%javatest%"
echo.>>"%javatest%"
echo import java.io.IOException;>>"%javatest%"
echo.>>"%javatest%"
echo public class autoGeneratedSending extends MailProvider {>>"%javatest%"
echo     public autoGeneratedSending() throws IOException {>>"%javatest%"
echo     }>>"%javatest%"
echo.>>"%javatest%"
exit /b

:jcheck_fill
echo package ru.yandex.crm.tests.delivery.stageTwo;>>"%javacheck%"
echo.>>"%javacheck%"
echo import org.junit.*;>>"%javacheck%"
echo import ru.yandex.core.MailProvider;>>"%javacheck%"
echo import ru.yandex.crm.tests.support.*;>>"%javacheck%"
echo import java.io.IOException;>>"%javacheck%"
echo import java.sql.SQLException;>>"%javacheck%"
echo.>>"%javacheck%"
echo public class autoGeneratedChecking extends MailProvider {>>"%javacheck%"
echo     public autoGeneratedChecking() throws IOException {>>"%javacheck%"
echo     }>>"%javacheck%"
echo.>>"%javacheck%"
exit /b