import {Fqn, Metaclass} from 'types/models';

export const metaclasses: Record<Fqn, Metaclass> = {
    entity: {
        children: ['bo', 'refund'],
        title: 'Корневой метакласс',
        attributes: {},
        fqn: 'entity',
        logics: [],
        typed: false,
        type: false,
        participateInFastSearch: false,
        abstract: true,
        version: 1,
    },
    bo: {
        children: [],
        parent: 'entity',
        title: 'Абстрактный бизнес-объект',
        attributes: {},
        fqn: 'bo',
        logics: [],
        typed: false,
        type: false,
        participateInFastSearch: false,
        abstract: true,
        version: 1,
    },
    refund: {
        children: [],
        parent: 'entity',
        title: 'Возврат по заказу',
        attributes: {},
        fqn: 'refund',
        logics: [],
        typed: false,
        type: false,
        participateInFastSearch: false,
        abstract: false,
        version: 1,
    },
};

export const expectedGrouppedMetaclasses = {
    undefined: [
        {
            abstract: true,
            children: ['bo', 'refund'],
            title: 'Корневой метакласс',
            attributes: {},
            fqn: 'entity',
            logics: [],
            typed: false,
            type: false,
            participateInFastSearch: false,
            version: 1,
        },
    ],

    entity: [
        {
            abstract: true,
            children: [],
            parent: 'entity',
            title: 'Абстрактный бизнес-объект',
            attributes: {},
            fqn: 'bo',
            logics: [],
            typed: false,
            type: false,
            participateInFastSearch: false,
            version: 1,
        },
        {
            abstract: false,
            children: [],
            parent: 'entity',
            title: 'Возврат по заказу',
            attributes: {},
            fqn: 'refund',
            logics: [],
            typed: false,
            type: false,
            participateInFastSearch: false,
            version: 1,
        },
    ],
};

export const expectedFilteredMetaclasses = {
    entity: {
        abstract: true,
        children: ['bo', 'refund'],
        title: 'Корневой метакласс',
        attributes: {},
        fqn: 'entity',
        logics: [],
        typed: false,
        type: false,
        participateInFastSearch: false,
        version: 1,
    },
    refund: {
        abstract: false,
        children: [],
        parent: 'entity',
        title: 'Возврат по заказу',
        attributes: {},
        fqn: 'refund',
        logics: [],
        typed: false,
        type: false,
        participateInFastSearch: false,
        version: 1,
    },
};
