'use strict';

module.exports = {
    autoShowShopList: true,
    showAviaNotifications: true,
    showAutoNotifications: true,
    showProductNotifications: true,
    clientId: '77e4187c9b0e11a4435',
    activeCity: null,
    activeCountry: null,
    otherRegions: true,
    firstStartTime: 1514371824658,
    firstStartTimeExtension: 0,
    eulaAcceptTime: 1514371827507,
    noRandomize: false,
    randomContainer: false,
    disabledDomains: null,
    bucketInfo: {},
    currency: null,
    adultOffer: null,
    partnersWithDeclinedOptIn: null,
    partnersWithAcceptedOptIn: [2210496],
    removedPartners: null,
    percent: 64,
    group: 'A',
    userClids: [2210496],
    sovetnikDisabled: false,
    firefoxCampaignClid: null,
    firefoxCampaignAffId: null,
    lastUpdateTime: 1514371840574,
    rzdLastClosedTime: 0,
    lastOptInShowTime: 1514371825429,
    lastHourBarClosingsCount: 0,
    lastBarClosedTime: null,
};
