'use strict';

module.exports = {
    autoShowShopList: true,
    showAviaNotifications: true,
    showAutoNotifications: true,
    showProductNotifications: true,
    clientId: '77e4187c9b0e11a4435',
    activeCity: {
        id: 213,
        name: 'Москва',
    },
    activeCountry: {
        id: 225,
        name: 'Россия',
    },
    otherRegions: true,
    firstStartTime: 1514368628660,
    firstStartTimeExtension: 0,
    eulaAcceptTime: 0,
    noRandomize: false,
    randomContainer: false,
    disabledDomains: null,
    bucketInfo: {},
    currency: 'RUR',
    adultOffer: null,
    partnersWithDeclinedOptIn: null,
    partnersWithAcceptedOptIn: null,
    removedPartners: null,
    percent: 93,
    group: 'A',
    userClids: ['2270459'],
    sovetnikDisabled: false,
    firefoxCampaignClid: null,
    firefoxCampaignAffId: null,
    lastUpdateTime: 1514368718052,
    rzdLastClosedTime: 0,
    lastOptInShowTime: null,
    lastHourBarClosingsCount: 0,
    lastBarClosedTime: null,
};
