DROP TABLE IF EXISTS riverbank_testing.errors;
create table riverbank_testing.errors
(
    date                  Date,
    timestamp             UInt32,
    project LowCardinality(String),
    service LowCardinality(String),
    page LowCardinality(String),
    platform Enum8('DESKTOP' = 0, 'TOUCH' = 1, 'APP' = 2, 'TV' = 3, 'PAD' = 4, 'TVAPP' = 5, 'UNKNOWN' = 6, 'STATION' = 7, 'TURBO_APP' = 8, 'UNSUPPORTED' = 9, 'PLAYSTATION' = 10, 'CHROMECAST' = 11, 'TURBO_APP_DESKTOP' = 12),
    url                   String,
    url_id                UInt64,
    vhost LowCardinality(String),
    environment Enum8('DEVELOPMENT' = 0, 'TESTING' = 1, 'PRESTABLE' = 2, 'PRODUCTION' = 3, 'PRE_PRODUCTION' = 4, 'UNKNOWN' = 5, 'HAMSTER' = 6) default 'UNKNOWN',
    test_ids Array(UInt32),
    exp_flgs Array(LowCardinality(String)),
    browser_engine LowCardinality(String),
    browser_engine_version LowCardinality(String),
    browser_name LowCardinality(String),
    browser_version LowCardinality(String),
    browser_version_major LowCardinality(String),
    browser_base LowCardinality(String),
    os_family LowCardinality(String),
    os_name LowCardinality(String),
    os_version LowCardinality(String),
    os_version_major LowCardinality(String),
    device_name LowCardinality(String),
    device_vendor LowCardinality(String),
    in_app_browser        UInt8,
    is_robot              UInt8,
    is_tv                 UInt8,
    is_tablet             UInt8,
    is_touch              UInt8,
    is_mobile             UInt8,
    is_adblock            UInt8,
    version LowCardinality(String),
    region                UInt32,
    request_id            String,
    request_id_hash       UInt64,
    yandexuid             UInt64,
    kv_keys Array(LowCardinality(String)),
    kv_values Array(String),
    is_internal           UInt8,
    cdn LowCardinality(String),
    ipv6                  String,
    message               String,
    message_id            UInt64,
    original_message      String,
    error_urls_keys Array(LowCardinality(String)),
    error_urls_values Array(String),
    runtime Enum8('BROWSERJS' = 0, 'NODEJS' = 1, 'UNKNOWN' = 2, 'GO' = 3, 'PYTHON' = 4, 'JAVA' = 5, 'CPP' = 6, 'PERL' = 7),
    level Enum8('UNKNOWN' = 0, 'TRACE' = 1, 'DEBUG' = 2, 'INFO' = 3, 'WARNING' = 4, 'ERROR' = 5, 'CRITICAL' = 6),
    file                  String,
    file_id               UInt64,
    block LowCardinality(String),
    method LowCardinality(String),
    line                  UInt32,
    col                   UInt32,
    stack_trace           String,
    stack_trace_id        UInt64,
    original_stack_trace  String,
    stack_trace_names Array(LowCardinality(String)),
    stack_trace_urls Array(String),
    stack_trace_lines Array(Int32),
    stack_trace_cols Array(Int32),
    user_agent LowCardinality(String),
    user_agent_id         UInt64,
    source LowCardinality(String),
    source_method LowCardinality(String),
    source_type LowCardinality(String),
    client_timestamp      UInt64,
    replaced_url_keys Array(LowCardinality(String)),
    replaced_url_values Array(String),
    parser Enum8('UNKNOWN' = 0, 'MORDA_NODE' = 1, 'QLOUD_NODE' = 2, 'REPORT_RENDERER' = 3, 'REDIR_LOG' = 4, 'UNIVERSAL' = 5, 'SENTRY' = 6)     default 'UNKNOWN',
    icookie               UInt64,
    silent                UInt8,
    dc LowCardinality(String),
    coordinates_latitude  Float64,
    coordinates_longitude Float64,
    coordinates_precision UInt16,
    coordinates_timestamp UInt32,
    host LowCardinality(String),
    client_init_timestamp UInt64,
    logged_in             UInt8,
    logbroker_topic LowCardinality(String)
) ENGINE = Log();