DROP TABLE IF EXISTS riverbank_testing.csp;
CREATE TABLE riverbank_testing.csp (
  date Date,
  timestamp UInt32,
  user_agent String,
  origin String,
  line UInt32,
  col UInt32,
  source_file String,
  referer String,
  blocked_uri String,
  violated_directive String,
  effective_directive String,
  disposition Enum8('ENFORCE' = 0, 'REPORT' = 1, 'UNKNOWN' = 2),
  document_uri String,
  script_sample String,
  status_code UInt16,
  from String,
  yandexuid UInt32,
  request_id String,
  blocked_uri_scheme String,
  blocked_uri_host String,
  blocked_uri_is_yandex UInt8,
  kv_keys Array(String),
  kv_values Array(String),
  project String,
  platform Enum8('DESKTOP' = 0, 'TOUCH' = 1, 'APP' = 2, 'TV' = 3, 'PAD' = 4, 'TVAPP' = 5, 'UNKNOWN' = 6, 'STATION' = 7, 'TURBO_APP' = 8, 'UNSUPPORTED' = 9, 'PLAYSTATION' = 10, 'CHROMECAST' = 11, 'TURBO_APP_DESKTOP' = 12),
  page String,
  reporter Enum8('CSP' = 0, 'JSV' = 1),
  browser_name String,
  browser_version String,
  browser_version_major String,
  os_family String,
  os_name String,
  os_version String,
  os_version_major String,
  request_id_hash UInt64,
  ipv6 String,
  environment Enum8('DEVELOPMENT' = 0, 'TESTING' = 1, 'PRESTABLE' = 2, 'PRODUCTION' = 3, 'PRE_PRODUCTION' = 4, 'UNKNOWN' = 5, 'HAMSTER' = 6),
  version String,
  effective_directive_full String,
  is_robot UInt8,
  is_tv UInt8,
  is_mobile UInt8,
  is_tablet UInt8,
  is_touch UInt8,
  test_ids Array(UInt32)
) ENGINE = Log();