CREATE TABLE JAVA_SEC.AUTH_LINK_TEMP (
  ID NUMBER NOT NULL,
  MAIN_AUTH VARCHAR(320) NOT NULL,
  LINKED_AUTH VARCHAR(320) NOT NULL,
  REL VARCHAR(12) NOT NULL,
  LINKED_AUTH_PARAM VARCHAR(4000),
  MAIN_AUTH_ID NUMBER,
  LINKED_AUTH_ID NUMBER
);


