CREATE TABLE JAVA_SEC.DOMAIN_AUDIT (
  AUDIT_RECORD_ID NUMBER NOT NULL,
  AUDIT_RECORD_TYPE VARCHAR(32),
  CHANGE_TIME TIMESTAMP,
  CHANGE_USER_ID NUMBER,
  IP VARCHAR(160),
  ID NUMBER NOT NULL,
  NAME VARCHAR(256)
);


