CREATE TABLE JAVA_SEC.DOMAIN (
  ID NUMBER NOT NULL,
  NAME VARCHAR(256)
);

CREATE UNIQUE INDEX JAVA_SEC.DOMAIN_PK ON JAVA_SEC.DOMAIN (ID);
CREATE UNIQUE INDEX JAVA_SEC.DOMAIN_U01 ON JAVA_SEC.DOMAIN (NAME);

ALTER TABLE JAVA_SEC.DOMAIN ADD CONSTRAINT DOMAIN_PK PRIMARY KEY (ID);
