CREATE TABLE JAVA_SEC.MIGRATION_HISTORY (
  DOMAIN VARCHAR(512) NOT NULL,
  HASH VARCHAR(512) NOT NULL,
  TIME TIMESTAMP DEFAULT current_timestamp,
  STATUS VARCHAR(1024),
  HOST VARCHAR(320),
  META VARCHAR(512)
);

CREATE INDEX JAVA_SEC.I_MIGRATION_HISTORY_DT ON JAVA_SEC.MIGRATION_HISTORY (DOMAIN, TIME);

