CREATE TABLE JAVA_SEC.OP_DESC_AUDIT (
  AUDIT_RECORD_ID NUMBER NOT NULL,
  AUDIT_RECORD_TYPE VARCHAR(32),
  CHANGE_TIME TIMESTAMP,
  CHANGE_USER_ID NUMBER,
  IP VARCHAR(160),
  ID NUMBER NOT NULL,
  DOMAIN VARCHAR(200) NOT NULL,
  OP_NAME VARCHAR(400) NOT NULL,
  DESCRIPTION VARCHAR(4000),
  DOMAIN_ID NUMBER
);


