CREATE TABLE JAVA_SEC.OP_DESC (
  ID NUMBER NOT NULL,
  DOMAIN VARCHAR(200) NOT NULL,
  OP_NAME VARCHAR(400) NOT NULL,
  DESCRIPTION VARCHAR(4000),
  DOMAIN_ID NUMBER NOT NULL
);

CREATE UNIQUE INDEX JAVA_SEC.OP_DESC_PK ON JAVA_SEC.OP_DESC (ID);
CREATE UNIQUE INDEX JAVA_SEC.OP_DESC_U01 ON JAVA_SEC.OP_DESC (DOMAIN_ID, OP_NAME);

ALTER TABLE JAVA_SEC.OP_DESC ADD CONSTRAINT OP_DESC_PK PRIMARY KEY (ID);
