CREATE TABLE JAVA_SEC.OP_PERM (
  ID NUMBER NOT NULL,
  OP_ID NUMBER NOT NULL
);

CREATE INDEX JAVA_SEC.OP_PERM_OP_DESC_FK1_IND ON JAVA_SEC.OP_PERM (OP_ID);
CREATE UNIQUE INDEX JAVA_SEC.SYS_C0026340 ON JAVA_SEC.OP_PERM (ID);

ALTER TABLE JAVA_SEC.OP_PERM ADD CONSTRAINT OP_PERM_OP_DESC_FK1 FOREIGN KEY (OP_ID) REFERENCES JAVA_SEC.OP_DESC (ID) ON DELETE CASCADE;
ALTER TABLE JAVA_SEC.OP_PERM ADD CONSTRAINT SYS_C0026340 PRIMARY KEY (ID);
