CREATE TABLE JAVA_SEC.PERM_AUTH_AUDIT (
  AUDIT_RECORD_ID NUMBER NOT NULL,
  AUDIT_RECORD_TYPE VARCHAR(32),
  CHANGE_TIME TIMESTAMP,
  CHANGE_USER_ID NUMBER,
  IP VARCHAR(160),
  ID NUMBER NOT NULL,
  OP_PERM_ID NUMBER NOT NULL,
  AUTH_NAME VARCHAR(320) NOT NULL,
  PARAM VARCHAR(4000),
  AUTHORITY_ID NUMBER
);


