CREATE TABLE JAVA_SEC.PERM_AUTH (
  ID NUMBER NOT NULL,
  OP_PERM_ID NUMBER NOT NULL,
  AUTH_NAME VARCHAR(320) NOT NULL,
  PARAM VARCHAR(4000),
  AUTHORITY_ID NUMBER NOT NULL
);

CREATE INDEX JAVA_SEC.PERM_AUTH_OP_PERM_FK1_IND ON JAVA_SEC.PERM_AUTH (OP_PERM_ID);
CREATE UNIQUE INDEX JAVA_SEC.SYS_C0026341 ON JAVA_SEC.PERM_AUTH (ID);

ALTER TABLE JAVA_SEC.PERM_AUTH ADD CONSTRAINT PERM_AUTH_OP_PERM_FK1 FOREIGN KEY (OP_PERM_ID) REFERENCES JAVA_SEC.OP_PERM (ID) ON DELETE CASCADE;
ALTER TABLE JAVA_SEC.PERM_AUTH ADD CONSTRAINT SYS_C0026341 PRIMARY KEY (ID);
