CREATE TABLE JAVA_SEC.SERVICES_TREE (
  ID NUMBER NOT NULL,
  PARENT NUMBER,
  SYS_NAME VARCHAR(200),
  TITLE VARCHAR(200),
  SLUG VARCHAR(200),
  CHILDREN_NAME VARCHAR(200)
);

CREATE INDEX JAVA_SEC.I_SERVICES_TREE_PARENT ON JAVA_SEC.SERVICES_TREE (PARENT);
CREATE INDEX JAVA_SEC.I_SERVICES_TREE_SYS_NAME ON JAVA_SEC.SERVICES_TREE (SYS_NAME);
CREATE UNIQUE INDEX JAVA_SEC.SYS_C0026578 ON JAVA_SEC.SERVICES_TREE (ID);

ALTER TABLE JAVA_SEC.SERVICES_TREE ADD CONSTRAINT SYS_C0026578 PRIMARY KEY (ID);
