CREATE TABLE JAVA_SEC.STAFF_USERS_INFO
(
    LD_USER_ID       NUMBER NOT NULL,
    LD_LOGIN         VARCHAR(1020),
    FIRST_NAME       VARCHAR(1020),
    LAST_NAME        VARCHAR(1020),
    WORK_EMAIL       VARCHAR(1020),
    WORK_PHONE       VARCHAR(1020),
    TELEGRAM_ACCOUNT VARCHAR(100) default NULL,
    CRM_EMAIL        VARCHAR(255 char) default null,
    CHIEF_LOGIN      VARCHAR(255 char),
    CHIEF_WORK_EMAIL VARCHAR(255 char)
);

CREATE UNIQUE INDEX JAVA_SEC.STAFF_USERS_INFO_LOGIN_PK_ID ON JAVA_SEC.STAFF_USERS_INFO (LD_USER_ID);

ALTER TABLE JAVA_SEC.STAFF_USERS_INFO ADD CONSTRAINT STAFF_USERS_INFO_LOGIN_PK_ID PRIMARY KEY (LD_USER_ID);
