CREATE TABLE JAVA_SEC.TMP_AUTH_CHECKER (
  ID NUMBER NOT NULL,
  AUTH_NAME VARCHAR(320) NOT NULL,
  CHECKER VARCHAR(320) NOT NULL,
  AUTHORITY_ID NUMBER
);

CREATE UNIQUE INDEX JAVA_SEC.AUTH_CHECKER_AUTH_UK ON JAVA_SEC.TMP_AUTH_CHECKER (AUTH_NAME);
CREATE UNIQUE INDEX JAVA_SEC.SYS_C0026344 ON JAVA_SEC.TMP_AUTH_CHECKER (ID);

ALTER TABLE JAVA_SEC.TMP_AUTH_CHECKER ADD CONSTRAINT SYS_C0026344 PRIMARY KEY (ID);
