CREATE TABLE JAVA_SEC.USER_PASSPORTS (
  LD_USER_ID NUMBER,
  PASSPORT_ID NUMBER NOT NULL,
  PASSPORT_LOGIN VARCHAR(1020),
  INNER_PASSPORT_ID NUMBER
);

CREATE UNIQUE INDEX JAVA_SEC.I_USER_PASSPORTS$P_ID ON JAVA_SEC.USER_PASSPORTS (PASSPORT_ID);

