/* eslint-disable max-len */

'use strict';

module.exports = expect.objectContaining({
    bucketInfo: {},
    cbirMinOfferPrice: 3250,
    doNotSearchReason: undefined,
    footer: {
        constants: {
            autoDetectedRegion: 'Автоматически',
            changeCurrentRegion: 'Изменить текущий регион',
            changeRegion: 'Изменить регион',
            data: {
                letter: 'Я',
                prefix: 'Данные',
                suffix: 'ндекс.Маркета',
            },
            feedback: 'Сообщить об ошибке',
            infoAboutShop: 'Информация о продавцах',
            infoAboutShopLegal: 'Юридическая информация о продавцах',
            wrongProductDetect: 'Неверно определен товар',
            gotoMarket: 'Перейти на Яндекс.Маркет',
        },
    },
    info: {
        constants: {
            disableText: 'Как отключить Советника',
            featuresText: 'Что ещё умеет Советник',
            feedbackText: 'Обратная связь',
            helpText: 'Помощь',
            licenseText: 'Лицензионное соглашение',
            prefix: 'для ',
            text: 'Это приложение подсказывает вам более выгодные цены на товары, на которые вы смотрите прямо сейчас.',
            upperLine: 'Яндекс.Советник',
            yandexLLC: '© %s ООО «Яндекс.Маркет»',
        },
    },
    model: undefined,
    notification: undefined,
    offers: [
        {
            bigPhoto: {
                height: 800,
                url: 'https://avatars.mds.yandex.net/get-marketpic/236853/market_Oaq5psyMlG1A7gjP0L8b-Q/orig',
                width: 533,
            },
            buttonUrl: '<wrapped url>',
            category: {
                advertisingModel: 'HYBRID',
                childCount: 0,
                fullName: 'Женские платья',
                id: 7811901,
                name: 'Платья',
                type: 'VISUAL',
                viewType: 'GRID',
            },
            delivery: {
                brief: 'в Москву — 399 руб.',
                cityFrom: 'Москвы',
                cityTo: 'Москву',
                daysFrom: undefined,
                daysTo: undefined,
                delivery: true,
                free: false,
                pickup: false,
                price: {
                    currencyCode: 'RUR',
                    currencyName: 'руб.',
                    value: '399',
                },
            },
            id: 'yDpJekrrgZEWeVlmKSaNp6A8p3visGwUDg1N_2bzXOB7bbcEjN2LCA',
            mostRelevant: true,
            name: 'Платье Patricia B. NY1102-4 желтый',
            optOutUrl: '<wrapped url>',
            photo: 'https://avatars.mds.yandex.net/get-marketpic/236853/market_Oaq5psyMlG1A7gjP0L8b-Q/orig',
            price: {
                currencyCode: 'RUR',
                currencyName: 'руб.',
                value: 3250,
            },
            shopInfo: {
                gradeTotal: 9771,
                id: 302690,
                name: 'Москва KupiVIP.ru',
                rating: 5,
                url: '<wrapped url>',
            },
            source: 'Market',
            constants: {
                shopRatingText: 'Рейтинг %s из 5 на основе',
                shopRatingDefaultText: 'оценки службы контроля качества Яндекс.Маркета',
            },
            surfaceUrl: '<wrapped url>',
            target: 'pricebar',
            url: '<wrapped url>',
            warning: undefined,
        },
        {
            bigPhoto: {
                height: 800,
                url: 'https://avatars.mds.yandex.net/get-marketpic/236853/market_Oaq5psyMlG1A7gjP0L8b-Q/orig',
                width: 533,
            },
            buttonUrl: '<wrapped url>',
            category: {
                advertisingModel: 'HYBRID',
                childCount: 0,
                fullName: 'Женские платья',
                id: 7811901,
                name: 'Платья',
                type: 'VISUAL',
                viewType: 'GRID',
            },
            constants: {
                shopRatingText: 'Рейтинг %s из 5 на основе',
                shopRatingDefaultText: 'оценки службы контроля качества Яндекс.Маркета',
            },
            delivery: {
                brief: 'в Москву — 399 руб.',
                cityFrom: 'Москвы',
                cityTo: 'Москву',
                daysFrom: undefined,
                daysTo: undefined,
                delivery: true,
                free: false,
                pickup: false,
                price: {
                    currencyCode: 'RUR',
                    currencyName: 'руб.',
                    value: '399',
                },
            },
            id: 'yDpJekrrgZEWeVlmKSaNp6A8p3visGwUDg1N_2bzXOB7bbcEjN2LCA',
            mostRelevant: true,
            name: 'Платье Patricia B. NY1102-4 желтый',
            photo: 'https://avatars.mds.yandex.net/get-marketpic/236853/market_Oaq5psyMlG1A7gjP0L8b-Q/orig',
            price: {
                currencyCode: 'RUR',
                currencyName: 'руб.',
                value: 3250,
            },
            shopInfo: {
                gradeTotal: 9771,
                id: 302690,
                name: 'Москва KupiVIP.ru',
                rating: 5,
                url: '<wrapped url>',
            },
            source: 'Market',
            target: 'price-list',
            url: '<wrapped url>',
            warning: undefined,
        },
        {
            bigPhoto: {
                height: 800,
                url: 'https://avatars.mds.yandex.net/get-marketpic/236853/market_Oaq5psyMlG1A7gjP0L8b-Q/orig',
                width: 533,
            },
            buttonUrl: '<wrapped url>',
            category: {
                advertisingModel: 'HYBRID',
                childCount: 0,
                fullName: 'Женские платья',
                id: 7811901,
                name: 'Платья',
                type: 'VISUAL',
                viewType: 'GRID',
            },
            constants: {
                shopRatingText: 'Рейтинг %s из 5 на основе',
                shopRatingDefaultText: 'оценки службы контроля качества Яндекс.Маркета',
            },
            delivery: {
                brief: 'в Москву — 399 руб.',
                cityFrom: 'Москвы',
                cityTo: 'Москву',
                daysFrom: undefined,
                daysTo: undefined,
                delivery: true,
                free: false,
                pickup: false,
                price: {
                    currencyCode: 'RUR',
                    currencyName: 'руб.',
                    value: '399',
                },
            },
            id: 'yDpJekrrgZEWeVlmKSaNp6A8p3visGwUDg1N_2bzXOB7bbcEjN2LCA',
            name: 'Платье Patricia B. NY1102-4 желтый',
            photo: 'https://avatars.mds.yandex.net/get-marketpic/236853/market_Oaq5psyMlG1A7gjP0L8b-Q/orig',
            price: {
                currencyCode: 'RUR',
                currencyName: 'руб.',
                value: 3250,
            },
            shopInfo: {
                gradeTotal: 9771,
                id: 302690,
                name: 'Москва KupiVIP.ru',
                rating: 5,
                url: '<wrapped url>',
            },
            source: 'Market',
            target: 'price-list',
            url: '<wrapped url>',
            warning: undefined,
        },
        {
            bigPhoto: {
                height: 800,
                url: 'https://avatars.mds.yandex.net/get-marketpic/236853/market_Oaq5psyMlG1A7gjP0L8b-Q/orig',
                width: 533,
            },
            buttonUrl: '<wrapped url>',
            category: {
                advertisingModel: 'HYBRID',
                childCount: 0,
                fullName: 'Женские платья',
                id: 7811901,
                name: 'Платья',
                type: 'VISUAL',
                viewType: 'GRID',
            },
            constants: {
                shopRatingText: 'Рейтинг %s из 5 на основе',
                shopRatingDefaultText: 'оценки службы контроля качества Яндекс.Маркета',
            },
            delivery: {
                brief: 'в Москву — 399 руб.',
                cityFrom: 'Москвы',
                cityTo: 'Москву',
                daysFrom: undefined,
                daysTo: undefined,
                delivery: true,
                free: false,
                pickup: false,
                price: {
                    currencyCode: 'RUR',
                    currencyName: 'руб.',
                    value: '399',
                },
            },
            id: 'yDpJekrrgZEWeVlmKSaNp6A8p3visGwUDg1N_2bzXOB7bbcEjN2LCA',
            name: 'Платье Patricia B. NY1102-4 желтый',
            photo: 'https://avatars.mds.yandex.net/get-marketpic/236853/market_Oaq5psyMlG1A7gjP0L8b-Q/orig',
            price: {
                currencyCode: 'RUR',
                currencyName: 'руб.',
                value: 3250,
            },
            shopInfo: {
                gradeTotal: 9771,
                id: 302690,
                name: 'Москва KupiVIP.ru',
                rating: 5,
                url: '<wrapped url>',
            },
            source: 'Market',
            target: 'price-list',
            url: '<wrapped url>',
            warning: undefined,
        },
        {
            bigPhoto: {
                height: 800,
                url: 'https://avatars.mds.yandex.net/get-marketpic/236853/market_Oaq5psyMlG1A7gjP0L8b-Q/orig',
                width: 533,
            },
            buttonUrl: '<wrapped url>',
            category: {
                advertisingModel: 'HYBRID',
                childCount: 0,
                fullName: 'Женские платья',
                id: 7811901,
                name: 'Платья',
                type: 'VISUAL',
                viewType: 'GRID',
            },
            constants: {
                shopRatingText: 'Рейтинг %s из 5 на основе',
                shopRatingDefaultText: 'оценки службы контроля качества Яндекс.Маркета',
            },
            delivery: {
                brief: 'в Москву — 399 руб.',
                cityFrom: 'Москвы',
                cityTo: 'Москву',
                daysFrom: undefined,
                daysTo: undefined,
                delivery: true,
                free: false,
                pickup: false,
                price: {
                    currencyCode: 'RUR',
                    currencyName: 'руб.',
                    value: '399',
                },
            },
            id: 'yDpJekrrgZEWeVlmKSaNp6A8p3visGwUDg1N_2bzXOB7bbcEjN2LCA',
            name: 'Платье Patricia B. NY1102-4 желтый',
            photo: 'https://avatars.mds.yandex.net/get-marketpic/236853/market_Oaq5psyMlG1A7gjP0L8b-Q/orig',
            price: {
                currencyCode: 'RUR',
                currencyName: 'руб.',
                value: 3250,
            },
            shopInfo: {
                gradeTotal: 9771,
                id: 302690,
                name: 'Москва KupiVIP.ru',
                rating: 5,
                url: '<wrapped url>',
            },
            source: 'Market',
            target: 'price-list',
            url: '<wrapped url>',
            warning: undefined,
        },
    ],
    optOutInfo: undefined,
    feedback: {
        constants: {
            closeButtonText: 'Закрыть',
            error: 'Комментарий не может быть пустым.',
            placeholder:
                'Пожалуйста, расскажите, что именно случилось. Ваш комментарий поможет нам исправить проблему быстрее.',
            submitButtonText: 'Отправить',
            text: 'Ваше сообщение поможет улучшить Советника',
            thanks: 'Спасибо!',
            title: 'Спасибо, мы получили ваш отчёт об ошибке',
        },
    },
    pricebar: {
        constants: {
            byPartnerDisclaimer: 'по данным Яндекс.Маркета',
            fastDelivery: 'с быстрой доставкой',
            goButtonText: 'Посмотреть',
            fromText: 'от',
            goButtonTooltip: 'Посмотреть',
            inShop: 'в магазине',
            closeButtonTooltip: 'Закрыть',
            infoButtonTooltip: 'О программе',
            moreButtonText: 'Посмотреть',
            moreButtonTooltip: 'Предложения других магазинов',
            prevText: 'Посмотрите похожие товары из категории ',
            settingsButtonTooltip: 'Настройки',
        },
    },
    rules: undefined,
    searchInfo: {
        categories: [
            {
                id: expect.any(Number),
                name: expect.any(String),
                rank: expect.any(Number),
                url: '<wrapped url>',
            },
            {
                id: expect.any(Number),
                name: expect.any(String),
                rank: expect.any(Number),
                url: '<wrapped url>',
            },
            {
                id: expect.any(Number),
                name: expect.any(String),
                rank: expect.any(Number),
                url: '<wrapped url>',
            },
        ],
        category: {
            id: 7811901,
            name: 'Женские платья',
        },
        convertedPrice: {
            currencyCode: 'RUR',
            value: 2370,
        },
        doNotComparePrice: undefined,
        filteredQuery: 'Платье, Vero moda',
        offersCount: 0,
        originalQuery: 'Платье, Vero moda',
        urls: {
            disable: '<wrapped url>',
            eula: '<wrapped url>',
            features: '<wrapped url>',
            feedback: '<wrapped url>',
            help: '<wrapped url>',
            helpPhone: '<wrapped url>',
            helpTablet: '<wrapped url>',
            market: '<wrapped url>',
            prices: '<wrapped url>',
            search: expect.any(String),
            searchButton: '<wrapped url>',
            shopsInfo: '<wrapped url>',
            userHelp: '<wrapped url>',
        },
    },
    searchResult: undefined,
    searchResultCaption: 'Женские платья',
    isCategoryPricebar: true,
    settings: {
        applicationName: 'Яндекс.Советник',
        autoShowShopList: true,
        constants: {
            changeRegion: 'Изменить регион',
            changeSettings: 'Изменить настройки',
            disable: 'Выключить на этом сайте',
            yourRegion: 'Ваш регион:',
        },
        isMbrApplication: true,
        items: [
            {
                enabled: true,
                title: 'Показывать предложения из других регионов',
            },
            {
                enabled: true,
                title: 'Показывать список предложений при наведении мыши',
            },
        ],
        needShowNotifications: true,
        region: 'Автоматически',
        showAviaNotifications: true,
        showAutoNotifications: true,
        showProductNotifications: true,
    },
    shopInfo: {
        shopName: expect.any(String),
        url: '<wrapped url>',
    },
    tabs: {
        constants: {
            offers: 'Предложения магазинов',
        },
    },
});
