const HOST = 'https://api.content.market.yandex.ru';

const ROUTE = /\/v[0-9.]+\/categories\/match/;

const RESPONSE = {
    status: 'OK',
    context: {
        region: {
            id: 213,
            name: 'Москва',
            type: 'CITY',
            childCount: 14,
            country: 225,
        },
        currency: {
            id: 'RUR',
            name: 'руб.',
        },
        page: {
            number: 1,
            count: 100,
        },
        id: '1572129824441/1a8c3f36fe820a41af02baffd7950500',
        time: '2019-10-27T01:43:44.451+03:00',
        marketUrl: 'https://market.yandex.ru?pp=1002&clid=2210590&distr_type=4',
    },
    categories: [
        {
            id: 2724669,
            name: 'Портативная акустика',
            fullName: 'Портативная акустика',
            type: 'GURU',
            childCount: 0,
            advertisingModel: 'CPC',
            rank: 0.9738567821955858,
        },
        {
            id: 2134462,
            name: 'Комплекты умного дома',
            fullName: 'Комплекты умного дома',
            type: 'GURU',
            childCount: 0,
            advertisingModel: 'CPC',
            rank: -0.02068490893060906,
        },
        {
            id: 16265381,
            name: 'Аксессуары для умных часов и браслетов',
            fullName: 'Аксессуары для умных часов и браслетов',
            type: 'GURU',
            childCount: 0,
            advertisingModel: 'CPC',
            rank: -0.11080863018999429,
        },
        {
            id: 10382050,
            name: 'Док-станции',
            fullName: 'Док-станции для мобильных телефонов и умных часов',
            type: 'GURU',
            childCount: 0,
            advertisingModel: 'CPC',
            rank: -0.4510885046334724,
        },
        {
            id: 477439,
            name: 'Цифровые метеостанции',
            fullName: 'Цифровые бытовые метеостанции',
            type: 'GURU',
            childCount: 0,
            advertisingModel: 'CPC',
            rank: -0.6934689710813701,
        },
        {
            id: 91700,
            name: 'Розетки, выключатели и рамки',
            fullName: 'Розетки, выключатели и рамки',
            type: 'GURU',
            childCount: 0,
            advertisingModel: 'CPC',
            rank: -0.8210553162263552,
        },
        {
            id: 91503,
            name: 'Зарядные устройства и адаптеры',
            fullName: 'Зарядные устройства и адаптеры для мобильных телефонов',
            type: 'GURU',
            childCount: 0,
            advertisingModel: 'CPC',
            rank: -0.9731884337494421,
        },
        {
            id: 15311178,
            name: 'Док-станции',
            fullName: 'Док-станции для ноутбуков',
            type: 'GURU',
            childCount: 0,
            advertisingModel: 'CPC',
            rank: -1.0049714792438127,
        },
        {
            id: 91498,
            name: 'Чехлы',
            fullName: 'Чехлы для мобильных телефонов',
            type: 'GURU',
            childCount: 0,
            advertisingModel: 'CPC',
            rank: -1.0183520872508134,
        },
        {
            id: 2662954,
            name: 'Чехлы для планшетов',
            fullName: 'Чехлы для планшетов',
            type: 'GURU',
            childCount: 0,
            advertisingModel: 'CPC',
            rank: -1.1395426803244404,
        },
        {
            id: 16897567,
            name: 'Реле для умного дома',
            fullName: 'Реле для умного дома',
            type: 'GENERAL',
            childCount: 0,
            advertisingModel: 'CPC',
            rank: -1.1950026075503286,
        },
        {
            id: 91156,
            name: 'Аккумуляторы и зарядные устройства',
            fullName: 'Аккумуляторы и зарядные устройства для фото- и видеотехники',
            type: 'GURU',
            childCount: 0,
            advertisingModel: 'CPC',
            rank: -1.1990614523750185,
        },
        {
            id: 10983253,
            name: 'Программы',
            fullName: 'Программы',
            type: 'GURU',
            childCount: 0,
            advertisingModel: 'CPC',
            rank: -1.4354817668328879,
        },
        {
            id: 91664,
            name: 'Водяные насосы',
            fullName: 'Электрические водяные насосы',
            type: 'GURU',
            childCount: 0,
            advertisingModel: 'CPC',
            rank: -1.4611319185042413,
        },
        {
            id: 91011,
            name: 'Настольные компьютеры',
            fullName: 'Настольные компьютеры',
            type: 'GURU',
            childCount: 0,
            advertisingModel: 'CPC',
            rank: -1.5603762392809348,
        },
        {
            id: 91107,
            name: 'Компьютерная акустика',
            fullName: 'Компьютерная акустика',
            type: 'GURU',
            childCount: 0,
            advertisingModel: 'CPC',
            rank: -1.599410792484476,
        },
        {
            id: 90548,
            name: 'Акустические системы',
            fullName: 'Акустические системы',
            type: 'GURU',
            childCount: 0,
            advertisingModel: 'CPC',
            rank: -1.6424396986023748,
        },
        {
            id: 16302535,
            name: 'Пылесосы',
            fullName: 'Пылесосы',
            type: 'GURU',
            childCount: 0,
            advertisingModel: 'CPC',
            rank: -1.7197614848201526,
        },
        {
            id: 16312871,
            name: 'Парогенераторы',
            fullName: 'Парогенераторы',
            type: 'GURU',
            childCount: 0,
            advertisingModel: 'CPC',
            rank: -1.722229072485249,
        },
        {
            id: 91803,
            name: 'Сейфы',
            fullName: 'Сейфы',
            type: 'GURU',
            childCount: 0,
            advertisingModel: 'CPC',
            rank: -1.7847778531050513,
        },
        {
            id: 91734,
            name: 'Проекты домов',
            fullName: 'Проекты домов',
            type: 'GENERAL',
            childCount: 0,
            advertisingModel: 'CPC',
            rank: -1.7999532703953824,
        },
        {
            id: 16047348,
            name: 'Электрические паяльники',
            fullName: ' Электрические паяльники и паяльные станции',
            type: 'GURU',
            childCount: 0,
            advertisingModel: 'CPC',
            rank: -1.824214541960189,
        },
        {
            id: 7811912,
            name: 'Бюстгальтеры',
            fullName: 'Бюстгальтеры',
            type: 'VISUAL',
            childCount: 0,
            advertisingModel: 'CPC',
            rank: -1.859464963692555,
        },
        {
            id: 15720039,
            name: 'Смеси для выпечки',
            fullName: 'Смеси для выпечки',
            type: 'GURU',
            childCount: 0,
            advertisingModel: 'CPC',
            rank: -1.928942729812433,
        },
    ],
};

module.exports = {
    host: HOST,
    route: ROUTE,
    response: RESPONSE,
};
