CREATE VIEW V_UC_NET_CHECK_PART ("ID", "URL", "HTTP_STATUS", "STARTED_TIME", "FINISHED_TIME", "ENTITY_ID", "GEN_TYPE", "STATE", "CREATION_TIME", "SESSION_ID", "ANSWER_TIME") AS
  select
ID,
URL,
HTTP_STATUS,
STARTED_TIME,
FINISHED_TIME,
ENTITY_ID,
GEN_TYPE,
STATE,
CREATION_TIME,
SESSION_ID,
ANSWER_TIME
from uc_net_check
where state=0
limit 200;
