import { ShopInfo, CurrencyType, LoyaltyStatus } from 'src/entities/shop/types';

export const shopInfo: ShopInfo = {
  id: 1035100,
  entity: 'shop',
  historicOnly: false,
  shopCurrency: CurrencyType.RUR,
  deliveryCurrency: CurrencyType.RUR,
  shopName: 'Киндл Бук',
  businessId: 723377,
  businessName: 'Киндл Бук',
  slug: 'kindl-buk',
  logo: '//avatars.mds.yandex.net/get-market-shop-logo/1516951/2a000001785cbe50ff1455e7267fc465a4fc/orig',
  isGlobal: false,
  prepayEnabled: false,
  isCpaPartner: true,
  isSupplier: true,
  blueStatus: 'real',
  cpc: { shopsDat: 'real', isInShopCpcFilterDb: false, calculated: 'real' },
  shopPriorityRegion: {
    entity: 'region',
    id: 213,
    name: 'Москва',
    lingua: { name: { genitive: 'Москвы', preposition: 'в', prepositional: 'Москве', accusative: 'Москву' } },
    type: 6,
    subtitle: 'Москва и Московская область, Россия',
  },
  shopPriorityCountry: {
    entity: 'region',
    id: 225,
    name: 'Россия',
    lingua: { name: { genitive: 'России', preposition: 'в', prepositional: 'России', accusative: 'Россию' } },
    type: 3,
  },
  ignoreStocks: false,
  isVirtual: false,
  isDirectShipping: true,
  oldRating: 0,
  ratingToShow: 4.8,
  newRating: 4.8,
  newRatingTotal: 4.838235294,
  skkDisabled: false,
  newGradesCount3M: 20,
  newGradesCount: 612,
  overallGradesCount: 612,
  aboName: '',
  aboOldRating: 0,
  oldRawRating: 0,
  oldStatus: '',
  oldCutoff: '',
  oldGradeBase: 0,
  oldGradesCount: 0,
  ratingType: 3,
  feeds: [
    { warehouseId: 56912, feedId: 955809 },
    { warehouseId: 110126, feedId: 1124664 },
  ],
  workScheduleList: [
    { day: 0, from: { hour: 10, minute: 0 }, to: { hour: 18, minute: 0 } },
    { day: 1, from: { hour: 10, minute: 0 }, to: { hour: 18, minute: 0 } },
    { day: 2, from: { hour: 10, minute: 0 }, to: { hour: 18, minute: 0 } },
    { day: 3, from: { hour: 10, minute: 0 }, to: { hour: 18, minute: 0 } },
    { day: 4, from: { hour: 10, minute: 0 }, to: { hour: 18, minute: 0 } },
    { day: 5, from: { hour: 11, minute: 0 }, to: { hour: 16, minute: 0 } },
  ],
  currentWorkSchedule: { from: { hour: 10, minute: 0 }, to: { hour: 18, minute: 0 } },
  loyalty_program_status: LoyaltyStatus.DISABLED,
  campaignIds: [21995831],
  partnerLink: 'https://partner.market.fslb.yandex.ru/supplier/21995831/assortment/offer-card?offerId=867',
};

export const getShopInfoMock = (common?: Partial<ShopInfo>): ShopInfo => {
  return {
    ...shopInfo,
    ...common,
  };
};
