-- Automatically saved for TABLE.SITE_CATALOG.VD_MAPPING_TEST at 2022/04/12

  CREATE TABLE "SITE_CATALOG"."TO_DELETE_VD_MAPPING_TEST" 
   (	"ENTITY_ID" VARCHAR2(20), 
	"FROM_ID" VARCHAR2(20), 
	"TO_ID" VARCHAR2(950)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCATALOG_DATA" 