-- Automatically saved for TABLE.SITE_CATALOG.AS_CLUSTERIZER_HISTORY_TEST at 2022/04/12

  CREATE TABLE "SITE_CATALOG"."MIGRATED_AS_CLUSTERIZER_HISTORY_TEST" 
   (	"ID" NUMBER, 
	"METRIC" NUMBER, 
	"CHECK_DATE" DATE, 
	"METRIC_TYPE" VARCHAR2(20), 
	"DATA_COUNT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCATALOG_DATA" 