-- Automatically saved for TABLE.SITE_CATALOG.AST_TMP_TT_LOG_TEST at 2022/04/12

  CREATE TABLE "SITE_CATALOG"."TO_DELETE_AST_TMP_TT_LOG_TEST" 
   (	"OFFER_ID" VARCHAR2(32), 
	"OFFER_HASH" VARCHAR2(32), 
	"CLASSIFIER_GOOD_ID" VARCHAR2(32), 
	"GURU_CATEGORY_ID" NUMBER, 
	"SHOP_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCATALOG_DATA" 