-- Automatically saved for TABLE.SITE_CATALOG.MBO_36040_TEST_TABLE at 2022/04/12

  CREATE TABLE "SITE_CATALOG"."TO_DELETE_MBO_36040_TEST_TABLE" 
   (	"VALUE" VARCHAR2(100), 
	"DATE_" DATE DEFAULT CURRENT_TIMESTAMP, 
	"TIMESTAMP_" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"TSWLTZ_" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT CURRENT_TIMESTAMP, 
	"TSWTZ_" TIMESTAMP (6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCATALOG_DATA" 