-- Automatically saved for TABLE.CLASSIFIER.AUTO_TESTING_TASKS at 2022/04/12

  CREATE TABLE "CLASSIFIER"."AUTO_TESTING_TASKS" 
   (	"ID" NUMBER(10,0), 
	"OFFER_ID" VARCHAR2(512) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(4000), 
	"OLD_HYPER_CATEGORY_ID" NUMBER(10,0), 
	"ADDITIONAL_INFO" VARCHAR2(2048), 
	"OFFER" VARCHAR2(4000), 
	"HYPER_CATEGORY_ID" NUMBER(10,0), 
	"MATCHED" NUMBER(1,0), 
	"PROBABILITY" FLOAT(53), 
	"SHOP_NAME" VARCHAR2(512), 
	"SHOP_CATEGORY_NAME" VARCHAR2(4000), 
	"PRICE" NUMBER(20,2), 
	"PROCESSED" NUMBER(5,0) NOT NULL ENABLE, 
	"PARTITION_ID" NUMBER(2,0), 
	"APPROVED_TIME" TIMESTAMP (6), 
	"APPROVED_CATEGORY_ID" NUMBER(10,0), 
	"PARAMS" VARCHAR2(4000), 
	"CLASSIFICATION_TYPE" VARCHAR2(20), 
	"MARKET_CATEGORY" VARCHAR2(4000), 
	"OFFER_PARAMS" CLOB, 
	"PRIORITY" NUMBER(5,0), 
	"GOOD_ID" VARCHAR2(32 CHAR), 
	"CHECK_COUNT" NUMBER(3,0) NOT NULL ENABLE, 
	"TASK_TYPE" VARCHAR2(255 CHAR), 
	"OFFER_BODY" BLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CLASSIFIER_DTS" 
 LOB ("OFFER_PARAMS") STORE AS BASICFILE (
  TABLESPACE "CLASSIFIER_DTS" ENABLE STORAGE IN ROW CHUNK 16384 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("OFFER_BODY") STORE AS BASICFILE (
  TABLESPACE "CLASSIFIER_DTS" ENABLE STORAGE IN ROW CHUNK 16384 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 