-- Automatically saved for TABLE.WATCHES.TMP_TABLE_FOR_IMPORT_TEST at 2022/04/12

  CREATE TABLE "WATCHES"."TO_DELETE_TMP_TABLE_FOR_IMPORT_TEST" 
   (	"IMP_VALUE" VARCHAR2(1000 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "WATCHES_DTS" 