-- Automatically saved for TABLE.SITE_CATALOG.VD_MAP_TEST at 2022/04/12

  CREATE TABLE "SITE_CATALOG"."TO_DELETE_VD_MAP_TEST" 
   (	"ENTITY_ID" VARCHAR2(20), 
	"CATEGORY_ID" VARCHAR2(20), 
	"PARENT_ID" VARCHAR2(20), 
	"CATEGORY_NAME" VARCHAR2(20)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCATALOG_DATA" 