#!/usr/bin/env python
# -*- coding: utf-8 -*-

import runner  # noqa

from core.types import BlueOffer, MarketSku, Model, Offer, Shop
from core.testcase import TestCase, main
from time import sleep


class T(TestCase):
    @classmethod
    def prepare(cls):
        cls.settings.logbroker_port = 0

        cls.index.models += [
            Model(title="kiyanka model has_pic", hyperid=1, vendor_id=1348),  # picinfo will be autogenerated
            Model(title="kiyanka model no_pic", no_picture=True, no_add_picture=True, hyperid=2),
        ]

        cls.index.offers += [
            Offer(title='kiyanka offer has_pic', picture="1", waremd5='wgrU12_pd1mqJ6DJm_9nEA', vendor_id=3491),
            Offer(title='kiyanka offer no_pic', no_picture=True, waremd5='ZRK9Q9nKpuAsmQsKgmUtyg'),
        ]

        # test_offer_recommended_by_vendor data
        cls.index.offers += [
            Offer(title='recommended', is_recommended=True, waremd5='EUhIXt-nprRmCEEWR-cysw'),
            Offer(title='nonrecommended', is_recommended=False, waremd5='VpUwTl5gv-d1vJpKS_S0zQ'),
        ]

        # for a promo code support
        cls.index.shops += [
            Shop(fesh=10001, regions=[187], cpa=Shop.CPA_REAL, subsidies=Shop.SUBSIDIES_ON),
        ]
        cls.index.offers += [Offer(title='мяучий оффер', fesh=10001, cpa=Offer.CPA_REAL)]
        cls.index.offers += [Offer(title='не мяучий оффер', fesh=10001, cpa=Offer.CPA_NO)]

        cls.index.offers += [Offer(title='котиковый оффер', price=100, price_old=200)]

        cls.index.shops += [
            Shop(fesh=1, priority_region=213, regions=[213], name='Новые игрушки', cpa=Shop.CPA_REAL),
        ]

        cls.index.offers += [Offer(fesh=1, title='auction', price=100, price_old=200)]

        for i in range(10):
            cls.index.shops += [Shop(fesh=20000 + i, priority_region=213)]
            cls.index.offers += [Offer(title='offerincut', fesh=20000 + i)]

        # test_rgb_param
        cls.index.mskus += [
            MarketSku(sku=10000001, title="kiyanka blue sku", hyperid=100, blue_offers=[BlueOffer()]),
        ]

    def test_log_in_file_when_logbroker_failed(self):
        self.report.request_json(
            'place=prime&text=котиковый&show-urls=external'
            + '&rearr-factors=market_enable_direct_sending_feature_logs_to_logbroker=1'
        )

        sleep(1)
        self.assertFragmentIn(self.report.request_xml('admin_action=flushlogs'), '<status>Logs flushed ok</status>')
        self.feature_log.expect(discount=0.5).once()


if __name__ == '__main__':
    main()
