export const backendOffersData = [
    {
        offerId: 'offerId',
        offerName: 'offerName',
        offerQuery: 'offerQuery',
        offerType: 'offerType',
        price: 123,
        purchasePrice: 2,
        oldPrice: 3,
        currentPosAll: 4,
        currentPosTop: 5,
        topOffersCount: 5,
        strategyId: 3,
        strategyReached: false,
        msModelCount: 4,
        dontUpToMin: false,
        currency: 'RUR',
        modelDetails: {
            currencyId: 'RUR',
            modelId: 13,
            lastModelId: 3,
            minPrice: 34,
            avgPrice: 55,
            positionDetails: [],
            priceDetails: [
                {
                    pos: 1,
                    shopName: 'shopName',
                    price: 32,
                    preDiscountPrice: 3,
                    shopRating: 3,
                    regionId: 4,
                    shippingCost: 5,
                    inStock: 12,
                    shopId: 5,
                    feedId: 9,
                    offerId: '234',
                },
                {
                    pos: 2,
                    shopName: 'shopName',
                    price: 23,
                    preDiscountPrice: 3,
                    shopRating: 3,
                    regionId: 4,
                    shippingCost: 5,
                    inStock: 12,
                    shopId: 5,
                    feedId: 9,
                    offerId: '234',
                },
            ],
            updated_at: 3,
        },
        hidden: false,
        params: {},
        updated_at: 12,
        strategyUpdated_at: 3,
        strategyModified_at: 34,
        strategy_applied_at: 67,
        recommendationsUpdated_at: 90,
        feedId: 12345,
        marketCategoryId: 2345678,
        categoryId: 456789,
        categoryName: 'categoryName',
    },
    {
        offerId: 'offerId12',
        offerName: 'offerName3',
        offerQuery: 'offerQuery',
        offerType: 'offerType',
        price: 12323,
        purchasePrice: 2,
        oldPrice: 3,
        currentPos_all: 4,
        currentPosTop: 5,
        topOffersCount: 5,
        strategyId: 3,
        strategyReached: false,
        msModelCount: 4,
        dontUpToMin: false,
        currency: 'RUR',
        modelDetails: {
            currencyId: 'RUR',
            modelId: 12,
            lastModelId: 3,
            minPrice: 343,
            avgPrice: 554,
            positionDetails: [],
            priceDetails: [
                {
                    pos: 1,
                    shopName: 'shopName',
                    price: 23,
                    preDiscountPrice: 3,
                    shopRating: 3,
                    regionId: 4,
                    shippingCost: 5,
                    inStock: 12,
                    shopId: 5,
                    feedId: 9,
                    offerId: '234',
                },
                {
                    pos: 2,
                    shopName: 'shopName',
                    price: 32,
                    preDiscountPrice: 3,
                    shopRating: 3,
                    regionId: 4,
                    shippingCost: 5,
                    inStock: 12,
                    shopId: 5,
                    feedId: 9,
                    offerId: '234',
                },
            ],
            updatedAt: 3,
        },
        hidden: false,
        params: {},
        updatedAt: 12,
        strategyUpdatedAt: 3,
        strategyModifiedAt: 34,
        strategyAppliedAt: 67,
        recommendationsUpdatedAt: 90,
        feedId: 12345,
        marketCategoryId: 2345678,
        categoryId: 456789,
        categoryName: 'categoryName12',
    },
];

export const searchData = [
    {
        offerName: 'offerName',
        price: 123,
        category: 'categoryName',
        avgPrice: 55,
        minPrice: 34,
        positionDetails: [],
        modelId: 13,
        offerId: 'offerId',
        offerCurrency: 'RUR',
        topsCurrency: 'RUR',
        priceDetails: [
            {
                pos: 1,
                shopName: 'shopName',
                price: 32,
                preDiscountPrice: 3,
                shopRating: 3,
                regionId: 4,
                shippingCost: 5,
                inStock: 12,
                shopId: 5,
                feedId: 9,
                offerId: '234',
            },
            {
                pos: 2,
                shopName: 'shopName',
                price: 23,
                preDiscountPrice: 3,
                shopRating: 3,
                regionId: 4,
                shippingCost: 5,
                inStock: 12,
                shopId: 5,
                feedId: 9,
                offerId: '234',
            },
        ],
    },
    {
        avgPrice: 554,
        category: 'categoryName12',
        minPrice: 343,
        offerName: 'offerName3',
        price: 12323,
        positionDetails: [],
        modelId: 12,
        offerId: 'offerId12',
        offerCurrency: 'RUR',
        topsCurrency: 'RUR',
        priceDetails: [
            {
                pos: 1,
                shopName: 'shopName',
                price: 23,
                preDiscountPrice: 3,
                shopRating: 3,
                regionId: 4,
                shippingCost: 5,
                inStock: 12,
                shopId: 5,
                feedId: 9,
                offerId: '234',
            },
            {
                pos: 2,
                shopName: 'shopName',
                price: 32,
                preDiscountPrice: 3,
                shopRating: 3,
                regionId: 4,
                shippingCost: 5,
                inStock: 12,
                shopId: 5,
                feedId: 9,
                offerId: '234',
            },
        ],
    },
];
