export const testCampaign = {
    type: 'SHOP',
    clientId: 1351749876,
    datasourceId: 11143151,
    tariffId: 1015,
    id: 1001450258,
    supplier: false,
    shop: true,
    crossBorder: false,
    fmcg: false,
    tpl: false,
    eatsAndLavka: false,
    sortingCenter: false,
    tplOutlet: false,
    tplPartner: false,
    tplCarrier: false,
    direct: false,
    isNewbie: true,
    isOldbie: false,
    manager: {
        id: -2,
        name: 'Служба Яндекс.Маркет',
        login: 'market-sales-manager',
        hosted: false,
        managerType: 'SUPPORT',
    },
    currencyRates: [
        {
            currency: 'RUR',
            rate: '30',
            cnt: '1',
        },
        {
            currency: 'BYN',
            rate: '0.8',
            cnt: '1',
        },
        {
            currency: 'KZT',
            rate: '105',
            cnt: '1',
        },
    ],
    countryId: 225,
    datasource: {
        info: {
            placementTypes: ['DROPSHIP_BY_SELLER'],
            id: 11143151,
            domain: 'DBS ссылочник',
            internalName: 'DBS ссылочник',
            managerId: -2,
        },
        manager: {
            id: -2,
            name: 'Служба Яндекс.Маркет',
            login: 'market-sales-manager',
            hosted: false,
            managerType: 'SUPPORT',
        },
    },
};
