FROM_SANDBOX(
  2048464615
  AUTOUPDATED MARKET_DATASOURCES_TESTING
  PREFIX MARKET_DATASOURCES_TESTING
  OUT MARKET_DATASOURCES_TESTING/testing/properties.d/tnsnames.ora
  OUT MARKET_DATASOURCES_TESTING/testing/properties.d/50-datasources.properties
  OUT MARKET_DATASOURCES_TESTING/testing/properties.d/parameters.yml
  OUT MARKET_DATASOURCES_TESTING/testing/properties.d/indexer/stratocaster.conf
  OUT MARKET_DATASOURCES_TESTING/testing/properties.d/zookeeper/stratocaster.conf
  OUT MARKET_DATASOURCES_TESTING/testing/properties.d/indexer/gibson.conf
  OUT MARKET_DATASOURCES_TESTING/testing/properties.d/zookeeper/gibson.conf
  OUT MARKET_DATASOURCES_TESTING/testing/properties.d/indexer/planeshift.stratocaster.conf
  OUT MARKET_DATASOURCES_TESTING/testing/properties.d/zookeeper/planeshift.stratocaster.conf
  OUT MARKET_DATASOURCES_TESTING/testing/properties.d/indexer/planeshift.gibson.conf
  OUT MARKET_DATASOURCES_TESTING/testing/properties.d/zookeeper/planeshift.gibson.conf
  OUT MARKET_DATASOURCES_TESTING/testing/properties.d/indexer/yellow.stratocaster.conf
  OUT MARKET_DATASOURCES_TESTING/testing/properties.d/zookeeper/yellow.stratocaster.conf
  OUT MARKET_DATASOURCES_TESTING/testing/properties.d/indexer/yellow.gibson.conf
  OUT MARKET_DATASOURCES_TESTING/testing/properties.d/zookeeper/yellow.gibson.conf
  OUT MARKET_DATASOURCES_TESTING/testing/properties.d/indexer/blue.stratocaster.conf
  OUT MARKET_DATASOURCES_TESTING/testing/properties.d/zookeeper/blue.stratocaster.conf
  OUT MARKET_DATASOURCES_TESTING/testing/properties.d/indexer/blue.gibson.conf
  OUT MARKET_DATASOURCES_TESTING/testing/properties.d/zookeeper/blue.gibson.conf
  OUT MARKET_DATASOURCES_TESTING/testing/properties.d/indexer/turbo.gibson.conf
  OUT MARKET_DATASOURCES_TESTING/testing/properties.d/zookeeper/turbo.gibson.conf
  OUT MARKET_DATASOURCES_TESTING/testing/properties.d/indexer/turbo.stratocaster.conf
  OUT MARKET_DATASOURCES_TESTING/testing/properties.d/zookeeper/turbo.stratocaster.conf
)

DATA(sbr://2048908801=MARKET_DATA_CONTENT_API AUTOUPDATED MARKET_DATA_CONTENT_API)
