import {
  CommonParam,
  CommonParamUiSetting,
  CommonParamValue,
  FindResponse,
  MetadataResponse,
  WidgetType,
} from 'src/java/definitions';
import { EditorParam, EditorParamType } from 'src/widgets/ParamEditor/types';

export const navTreeTestMetadata: MetadataResponse = {
  widgetType: WidgetType.TREE,
  version: 'latest',
  commonEntityType: {
    commonEntityTypeEnum: 'MDM_NAVIGATION_TREE',
    commonParams: [
      {
        commonParamName: 'tree_node_id',
        commonParamValueType: 'NUMERIC',
        required: false,
        options: [],
        multivalue: false,
        ruTitle: 'че-нибудь',
        uiSettings: [CommonParamUiSetting.READ_ONLY],
      },
      {
        commonParamName: 'tree_node_title',
        commonParamValueType: 'STRING',
        required: false,
        options: [],
        multivalue: false,
        uiSettings: [CommonParamUiSetting.READ_ONLY],
      },
      {
        commonParamName: 'parent_id',
        commonParamValueType: 'NUMERIC',
        required: false,
        options: [],
        multivalue: false,
        uiSettings: [CommonParamUiSetting.READ_ONLY],
      },
      {
        commonParamName: 'mdm_navigation_tree_node_reference',
        commonParamValueType: 'NUMERIC',
        required: false,
        options: [],
        multivalue: false,
        uiSettings: [CommonParamUiSetting.READ_ONLY],
      },
      {
        commonParamName: 'mdm_entity_type_reference',
        commonParamValueType: 'NUMERIC',
        required: false,
        options: [],
        multivalue: false,
        uiSettings: [CommonParamUiSetting.READ_ONLY],
      },
    ] as unknown as CommonParam[],
  },
} as MetadataResponse;
export const navTreeTestFindResults: FindResponse = {
  metadata: {
    commonEntityTypeEnum: 'MDM_NAVIGATION_TREE_NODE',
    commonParams: [],
  },
  commonEntities: [
    {
      entityId: 0,
      commonEntityType: {
        commonEntityTypeEnum: 'MDM_NAVIGATION_TREE_NODE',
        commonParams: [
          {
            commonParamName: 'tree_node_id',
            commonParamValueType: 'NUMERIC',
            uiSettings: [CommonParamUiSetting.READ_ONLY],
            required: false,
            options: [],
            multivalue: false,
            ruTitle: 'че-нибудь',
          },
          {
            commonParamName: 'tree_node_title',
            commonParamValueType: 'STRING',
            uiSettings: [CommonParamUiSetting.READ_ONLY],
            required: false,
            options: [],
            multivalue: false,
            ruTitle: 'че-нибудь',
          },
          {
            commonParamName: 'parent_id',
            commonParamValueType: 'NUMERIC',
            uiSettings: [CommonParamUiSetting.READ_ONLY],
            required: false,
            options: [],
            multivalue: false,
            ruTitle: 'че-нибудь',
          },
          {
            commonParamName: 'mdm_navigation_tree_node_reference',
            commonParamValueType: 'NUMERIC',
            uiSettings: [CommonParamUiSetting.READ_ONLY],
            required: false,
            options: [],
            multivalue: false,
            ruTitle: 'че-нибудь',
          },
          {
            commonParamName: 'mdm_entity_type_reference',
            commonParamValueType: 'NUMERIC',
            uiSettings: [CommonParamUiSetting.READ_ONLY],
            required: false,
            options: [],
            multivalue: false,
            ruTitle: 'че-нибудь',
          },
        ] as unknown as CommonParam[],
      },
      commonParamValues: [
        {
          commonParamName: 'tree_node_id',
          numerics: [0],
        },
        {
          commonParamName: 'tree_node_title',
          strings: ['MDM'],
        },
        {
          commonParamName: 'parent_id',
        },
        {
          commonParamName: 'mdm_entity_type_reference',
          strings: [],
          numerics: [],
          booleans: [],
          options: [],
          version_from: 1616396565926,
          version_to: null,
        },
        {
          commonParamName: 'mdm_navigation_tree_node_reference',
          strings: [],
          numerics: [],
          booleans: [],
          options: [],
          version_from: 1616396565926,
          version_to: null,
        },
      ],
    },
    {
      entityId: 1,
      commonEntityType: {
        commonEntityTypeEnum: 'MDM_ENTITY_TYPE',
        commonParams: [
          {
            commonParamName: 'tree_node_id',
            commonParamValueType: 'NUMERIC',
            uiSettings: [CommonParamUiSetting.READ_ONLY],
            required: false,
            options: [],
            multivalue: false,
          },
          {
            commonParamName: 'tree_node_title',
            commonParamValueType: 'STRING',
            uiSettings: [CommonParamUiSetting.READ_ONLY],
            required: false,
            options: [],
            multivalue: false,
          },
          {
            commonParamName: 'parent_id',
            commonParamValueType: 'NUMERIC',
            uiSettings: [CommonParamUiSetting.READ_ONLY],
            required: false,
            options: [],
            multivalue: false,
          },
          {
            commonParamName: 'mdm_navigation_tree_node_reference',
            commonParamValueType: 'NUMERIC',
            uiSettings: [CommonParamUiSetting.READ_ONLY],
            required: false,
            options: [],
            multivalue: false,
          },
          {
            commonParamName: 'mdm_entity_type_reference',
            commonParamValueType: 'NUMERIC',
            uiSettings: [CommonParamUiSetting.READ_ONLY],
            required: false,
            options: [],
            multivalue: false,
          },
        ],
      },
      commonParamValues: [
        {
          commonParamName: 'tree_node_id',
          strings: [],
          numerics: [1],
          booleans: [],
          options: [],
          version_from: 1616396565981,
          version_to: null,
        },
        {
          commonParamName: 'tree_node_title',
          strings: ['Категория'],
          numerics: [],
          booleans: [],
          options: [],
          version_from: 1616396565981,
          version_to: null,
        },
        {
          commonParamName: 'parent_id',
          strings: [],
          numerics: [0],
          booleans: [],
          options: [],
          version_from: 1616396565981,
          version_to: null,
        },
        {
          commonParamName: 'mdm_entity_type_reference',
          strings: [],
          numerics: [1],
          booleans: [],
          options: [],
          version_from: 1616396565981,
          version_to: null,
        },
        {
          commonParamName: 'mdm_navigation_tree_node_reference',
          strings: [],
          numerics: [],
          booleans: [],
          options: [],
          version_from: 1616396565981,
          version_to: null,
        },
      ],
    },
    {
      entityId: 2,
      commonEntityType: {
        commonEntityTypeEnum: 'MDM_ENTITY_TYPE',
        commonParams: [
          {
            commonParamName: 'tree_node_id',
            commonParamValueType: 'NUMERIC',
            uiSettings: [CommonParamUiSetting.READ_ONLY],
            required: false,
            options: [],
            multivalue: false,
          },
          {
            commonParamName: 'tree_node_title',
            commonParamValueType: 'STRING',
            uiSettings: [CommonParamUiSetting.READ_ONLY],
            required: false,
            options: [],
            multivalue: false,
          },
          {
            commonParamName: 'parent_id',
            commonParamValueType: 'NUMERIC',
            uiSettings: [CommonParamUiSetting.READ_ONLY],
            required: false,
            options: [],
            multivalue: false,
          },
          {
            commonParamName: 'mdm_navigation_tree_node_reference',
            commonParamValueType: 'NUMERIC',
            uiSettings: [CommonParamUiSetting.READ_ONLY],
            required: false,
            options: [],
            multivalue: false,
          },
          {
            commonParamName: 'mdm_entity_type_reference',
            commonParamValueType: 'NUMERIC',
            uiSettings: [CommonParamUiSetting.READ_ONLY],
            required: false,
            options: [],
            multivalue: false,
          },
        ],
      },
      commonParamValues: [
        {
          commonParamName: 'tree_node_id',
          strings: [],
          numerics: [2],
          booleans: [],
          options: [],
          version_from: 1616396565981,
          version_to: null,
        },
        {
          commonParamName: 'tree_node_title',
          strings: ['Серебро SSKU'],
          numerics: [],
          booleans: [],
          options: [],
          version_from: 1616396565981,
          version_to: null,
        },
        {
          commonParamName: 'parent_id',
          strings: [],
          numerics: [0],
          booleans: [],
          options: [],
          version_from: 1616396565981,
          version_to: null,
        },
        {
          commonParamName: 'mdm_entity_type_reference',
          strings: [],
          numerics: [2],
          booleans: [],
          options: [],
          version_from: 1616396565981,
          version_to: null,
        },
        {
          commonParamName: 'mdm_navigation_tree_node_reference',
          strings: [],
          numerics: [],
          booleans: [],
          options: [],
          version_from: 1616396565981,
          version_to: null,
        },
      ],
    },
    {
      entityId: 3,
      commonEntityType: {
        commonEntityTypeEnum: 'MDM_ENTITY_TYPE',
        commonParams: [
          {
            commonParamName: 'tree_node_id',
            commonParamValueType: 'NUMERIC',
            uiSettings: [CommonParamUiSetting.READ_ONLY],
            required: false,
            options: [],
            multivalue: false,
          },
          {
            commonParamName: 'tree_node_title',
            commonParamValueType: 'STRING',
            uiSettings: [CommonParamUiSetting.READ_ONLY],
            required: false,
            options: [],
            multivalue: false,
          },
          {
            commonParamName: 'parent_id',
            commonParamValueType: 'NUMERIC',
            uiSettings: [CommonParamUiSetting.READ_ONLY],
            required: false,
            options: [],
            multivalue: false,
          },
          {
            commonParamName: 'mdm_navigation_tree_node_reference',
            commonParamValueType: 'NUMERIC',
            uiSettings: [CommonParamUiSetting.READ_ONLY],
            required: false,
            options: [],
            multivalue: false,
          },
          {
            commonParamName: 'mdm_entity_type_reference',
            commonParamValueType: 'NUMERIC',
            uiSettings: [CommonParamUiSetting.READ_ONLY],
            required: false,
            options: [],
            multivalue: false,
          },
        ],
      },
      commonParamValues: [
        {
          commonParamName: 'tree_node_id',
          strings: [],
          numerics: [3],
          booleans: [],
          options: [],
          version_from: 1616396565981,
          version_to: null,
        },
        {
          commonParamName: 'tree_node_title',
          strings: ['Сервисная SSKU'],
          numerics: [],
          booleans: [],
          options: [],
          version_from: 1616396565981,
          version_to: null,
        },
        {
          commonParamName: 'parent_id',
          strings: [],
          numerics: [0],
          booleans: [],
          options: [],
          version_from: 1616396565981,
          version_to: null,
        },
        {
          commonParamName: 'mdm_entity_type_reference',
          strings: [],
          numerics: [3],
          booleans: [],
          options: [],
          version_from: 1616396565981,
          version_to: null,
        },
        {
          commonParamName: 'mdm_navigation_tree_node_reference',
          strings: [],
          numerics: [],
          booleans: [],
          options: [],
          version_from: 1616396565981,
          version_to: null,
        },
      ],
    },
    {
      entityId: 4,
      commonEntityType: {
        commonEntityTypeEnum: 'MDM_ENTITY_TYPE',
        commonParams: [
          {
            commonParamName: 'tree_node_id',
            commonParamValueType: 'NUMERIC',
            uiSettings: [CommonParamUiSetting.READ_ONLY],
            required: false,
            options: [],
            multivalue: false,
          },
          {
            commonParamName: 'tree_node_title',
            commonParamValueType: 'STRING',
            uiSettings: [CommonParamUiSetting.READ_ONLY],
            required: false,
            options: [],
            multivalue: false,
          },
          {
            commonParamName: 'parent_id',
            commonParamValueType: 'NUMERIC',
            uiSettings: [CommonParamUiSetting.READ_ONLY],
            required: false,
            options: [],
            multivalue: false,
          },
          {
            commonParamName: 'mdm_navigation_tree_node_reference',
            commonParamValueType: 'NUMERIC',
            uiSettings: [CommonParamUiSetting.READ_ONLY],
            required: false,
            options: [],
            multivalue: false,
          },
          {
            commonParamName: 'mdm_entity_type_reference',
            commonParamValueType: 'NUMERIC',
            uiSettings: [CommonParamUiSetting.READ_ONLY],
            required: false,
            options: [],
            multivalue: false,
          },
        ],
      },
      commonParamValues: [
        {
          commonParamName: 'tree_node_id',
          strings: [],
          numerics: [4],
          booleans: [],
          options: [],
          version_from: 1616396565981,
          version_to: null,
        },
        {
          commonParamName: 'tree_node_title',
          strings: ['Золотая SSKU'],
          numerics: [],
          booleans: [],
          options: [],
          version_from: 1616396565981,
          version_to: null,
        },
        {
          commonParamName: 'parent_id',
          strings: [],
          numerics: [0],
          booleans: [],
          options: [],
          version_from: 1616396565981,
          version_to: null,
        },
        {
          commonParamName: 'mdm_entity_type_reference',
          strings: [],
          numerics: [4],
          booleans: [],
          options: [],
          version_from: 1616396565981,
          version_to: null,
        },
        {
          commonParamName: 'mdm_navigation_tree_node_reference',
          strings: [],
          numerics: [],
          booleans: [],
          options: [],
          version_from: 1616396565981,
          version_to: null,
        },
      ],
    },
    {
      entityId: 5,
      commonEntityType: {
        commonEntityTypeEnum: 'MDM_ENTITY_TYPE',
        commonParams: [
          {
            commonParamName: 'tree_node_id',
            commonParamValueType: 'NUMERIC',
            uiSettings: [CommonParamUiSetting.READ_ONLY],
            required: false,
            options: [],
            multivalue: false,
          },
          {
            commonParamName: 'tree_node_title',
            commonParamValueType: 'STRING',
            uiSettings: [CommonParamUiSetting.READ_ONLY],
            required: false,
            options: [],
            multivalue: false,
          },
          {
            commonParamName: 'parent_id',
            commonParamValueType: 'NUMERIC',
            uiSettings: [CommonParamUiSetting.READ_ONLY],
            required: false,
            options: [],
            multivalue: false,
          },
          {
            commonParamName: 'mdm_navigation_tree_node_reference',
            commonParamValueType: 'NUMERIC',
            uiSettings: [CommonParamUiSetting.READ_ONLY],
            required: false,
            options: [],
            multivalue: false,
          },
          {
            commonParamName: 'mdm_entity_type_reference',
            commonParamValueType: 'NUMERIC',
            uiSettings: [CommonParamUiSetting.READ_ONLY],
            required: false,
            options: [],
            multivalue: false,
          },
        ],
      },
      commonParamValues: [
        {
          commonParamName: 'tree_node_id',
          strings: [],
          numerics: [5],
          booleans: [],
          options: [],
          version_from: 1616396565981,
          version_to: null,
        },
        {
          commonParamName: 'tree_node_title',
          strings: ['Серебро SSKU'],
          numerics: [],
          booleans: [],
          options: [],
          version_from: 1616396565981,
          version_to: null,
        },
        {
          commonParamName: 'parent_id',
          strings: [],
          numerics: [0],
          booleans: [],
          options: [],
          version_from: 1616396565981,
          version_to: null,
        },
        {
          commonParamName: 'mdm_entity_type_reference',
          strings: [],
          numerics: [5],
          booleans: [],
          options: [],
          version_from: 1616396565981,
          version_to: null,
        },
        {
          commonParamName: 'mdm_navigation_tree_node_reference',
          strings: [],
          numerics: [],
          booleans: [],
          options: [],
          version_from: 1616396565981,
          version_to: null,
        },
      ],
    },
    {
      entityId: 6,
      commonEntityType: {
        commonEntityTypeEnum: 'MDM_ENTITY_TYPE',
        commonParams: [
          {
            commonParamName: 'tree_node_id',
            commonParamValueType: 'NUMERIC',
            uiSettings: [CommonParamUiSetting.READ_ONLY],
            required: false,
            options: [],
            multivalue: false,
          },
          {
            commonParamName: 'tree_node_title',
            commonParamValueType: 'STRING',
            uiSettings: [CommonParamUiSetting.READ_ONLY],
            required: false,
            options: [],
            multivalue: false,
          },
          {
            commonParamName: 'parent_id',
            commonParamValueType: 'NUMERIC',
            uiSettings: [CommonParamUiSetting.READ_ONLY],
            required: false,
            options: [],
            multivalue: false,
          },
          {
            commonParamName: 'mdm_navigation_tree_node_reference',
            commonParamValueType: 'NUMERIC',
            uiSettings: [CommonParamUiSetting.READ_ONLY],
            required: false,
            options: [],
            multivalue: false,
          },
          {
            commonParamName: 'mdm_entity_type_reference',
            commonParamValueType: 'NUMERIC',
            uiSettings: [CommonParamUiSetting.READ_ONLY],
            required: false,
            options: [],
            multivalue: false,
          },
        ],
      },
      commonParamValues: [
        {
          commonParamName: 'tree_node_id',
          strings: [],
          numerics: [6],
          booleans: [],
          options: [],
          version_from: 1616396565981,
          version_to: null,
        },
        {
          commonParamName: 'tree_node_title',
          strings: ['Золотая MSKU'],
          numerics: [],
          booleans: [],
          options: [],
          version_from: 1616396565981,
          version_to: null,
        },
        {
          commonParamName: 'parent_id',
          strings: [],
          numerics: [0],
          booleans: [],
          options: [],
          version_from: 1616396565981,
          version_to: null,
        },
        {
          commonParamName: 'mdm_entity_type_reference',
          strings: [],
          numerics: [6],
          booleans: [],
          options: [],
          version_from: 1616396565981,
          version_to: null,
        },
        {
          commonParamName: 'mdm_navigation_tree_node_reference',
          strings: [],
          numerics: [],
          booleans: [],
          options: [],
          version_from: 1616396565981,
          version_to: null,
        },
      ],
    },
    {
      entityId: 7,
      commonEntityType: {
        commonEntityTypeEnum: 'MDM_ENTITY_TYPE',
        commonParams: [
          {
            commonParamName: 'tree_node_id',
            commonParamValueType: 'NUMERIC',
            uiSettings: [CommonParamUiSetting.READ_ONLY],
            required: false,
            options: [],
            multivalue: false,
          },
          {
            commonParamName: 'tree_node_title',
            commonParamValueType: 'STRING',
            uiSettings: [CommonParamUiSetting.READ_ONLY],
            required: false,
            options: [],
            multivalue: false,
          },
          {
            commonParamName: 'parent_id',
            commonParamValueType: 'NUMERIC',
            uiSettings: [CommonParamUiSetting.READ_ONLY],
            required: false,
            options: [],
            multivalue: false,
          },
          {
            commonParamName: 'mdm_navigation_tree_node_reference',
            commonParamValueType: 'NUMERIC',
            uiSettings: [CommonParamUiSetting.READ_ONLY],
            required: false,
            options: [],
            multivalue: false,
          },
          {
            commonParamName: 'mdm_entity_type_reference',
            commonParamValueType: 'NUMERIC',
            uiSettings: [CommonParamUiSetting.READ_ONLY],
            required: false,
            options: [],
            multivalue: false,
          },
        ],
      },
      commonParamValues: [
        {
          commonParamName: 'tree_node_id',
          strings: [],
          numerics: [7],
          booleans: [],
          options: [],
          version_from: 1616396565981,
          version_to: null,
        },
        {
          commonParamName: 'tree_node_title',
          strings: ['Узел ТН ВЭД'],
          numerics: [],
          booleans: [],
          options: [],
          version_from: 1616396565981,
          version_to: null,
        },
        {
          commonParamName: 'parent_id',
          strings: [],
          numerics: [0],
          booleans: [],
          options: [],
          version_from: 1616396565981,
          version_to: null,
        },
        {
          commonParamName: 'mdm_entity_type_reference',
          strings: [],
          numerics: [7],
          booleans: [],
          options: [],
          version_from: 1616396565981,
          version_to: null,
        },
        {
          commonParamName: 'mdm_navigation_tree_node_reference',
          strings: [],
          numerics: [],
          booleans: [],
          options: [],
          version_from: 1616396565981,
          version_to: null,
        },
      ],
    },
    {
      entityId: 8,
      commonEntityType: {
        commonEntityTypeEnum: 'MDM_ENTITY_TYPE',
        commonParams: [
          {
            commonParamName: 'tree_node_id',
            commonParamValueType: 'NUMERIC',
            uiSettings: [CommonParamUiSetting.READ_ONLY],
            required: false,
            options: [],
            multivalue: false,
          },
          {
            commonParamName: 'tree_node_title',
            commonParamValueType: 'STRING',
            uiSettings: [CommonParamUiSetting.READ_ONLY],
            required: false,
            options: [],
            multivalue: false,
          },
          {
            commonParamName: 'parent_id',
            commonParamValueType: 'NUMERIC',
            uiSettings: [CommonParamUiSetting.READ_ONLY],
            required: false,
            options: [],
            multivalue: false,
          },
          {
            commonParamName: 'mdm_navigation_tree_node_reference',
            commonParamValueType: 'NUMERIC',
            uiSettings: [CommonParamUiSetting.READ_ONLY],
            required: false,
            options: [],
            multivalue: false,
          },
          {
            commonParamName: 'mdm_entity_type_reference',
            commonParamValueType: 'NUMERIC',
            uiSettings: [CommonParamUiSetting.READ_ONLY],
            required: false,
            options: [],
            multivalue: false,
          },
        ],
      },
      commonParamValues: [
        {
          commonParamName: 'tree_node_id',
          strings: [],
          numerics: [8],
          booleans: [],
          options: [],
          version_from: 1616396565981,
          version_to: null,
        },
        {
          commonParamName: 'tree_node_title',
          strings: ['Глобальная настройка'],
          numerics: [],
          booleans: [],
          options: [],
          version_from: 1616396565981,
          version_to: null,
        },
        {
          commonParamName: 'parent_id',
          strings: [],
          numerics: [0],
          booleans: [],
          options: [],
          version_from: 1616396565981,
          version_to: null,
        },
        {
          commonParamName: 'mdm_entity_type_reference',
          strings: [],
          numerics: [8],
          booleans: [],
          options: [],
          version_from: 1616396565981,
          version_to: null,
        },
        {
          commonParamName: 'mdm_navigation_tree_node_reference',
          strings: [],
          numerics: [],
          booleans: [],
          options: [],
          version_from: 1616396565981,
          version_to: null,
        },
      ],
    },
    {
      entityId: 9,
      commonEntityType: {
        commonEntityTypeEnum: 'MDM_ENTITY_TYPE',
        commonParams: [
          {
            commonParamName: 'tree_node_id',
            commonParamValueType: 'NUMERIC',
            uiSettings: [CommonParamUiSetting.READ_ONLY],
            required: false,
            options: [],
            multivalue: false,
          },
          {
            commonParamName: 'tree_node_title',
            commonParamValueType: 'STRING',
            uiSettings: [CommonParamUiSetting.READ_ONLY],
            required: false,
            options: [],
            multivalue: false,
          },
          {
            commonParamName: 'parent_id',
            commonParamValueType: 'NUMERIC',
            uiSettings: [CommonParamUiSetting.READ_ONLY],
            required: false,
            options: [],
            multivalue: false,
          },
          {
            commonParamName: 'mdm_navigation_tree_node_reference',
            commonParamValueType: 'NUMERIC',
            uiSettings: [CommonParamUiSetting.READ_ONLY],
            required: false,
            options: [],
            multivalue: false,
          },
          {
            commonParamName: 'mdm_entity_type_reference',
            commonParamValueType: 'NUMERIC',
            uiSettings: [CommonParamUiSetting.READ_ONLY],
            required: false,
            options: [],
            multivalue: false,
          },
        ],
      },
      commonParamValues: [
        {
          commonParamName: 'tree_node_id',
          strings: [],
          numerics: [9],
          booleans: [],
          options: [],
          version_from: 1616396565981,
          version_to: null,
        },
        {
          commonParamName: 'tree_node_title',
          strings: ['Партнёр'],
          numerics: [],
          booleans: [],
          options: [],
          version_from: 1616396565981,
          version_to: null,
        },
        {
          commonParamName: 'parent_id',
          strings: [],
          numerics: [0],
          booleans: [],
          options: [],
          version_from: 1616396565981,
          version_to: null,
        },
        {
          commonParamName: 'mdm_entity_type_reference',
          strings: [],
          numerics: [9],
          booleans: [],
          options: [],
          version_from: 1616396565981,
          version_to: null,
        },
        {
          commonParamName: 'mdm_navigation_tree_node_reference',
          strings: [],
          numerics: [],
          booleans: [],
          options: [],
          version_from: 1616396565981,
          version_to: null,
        },
      ],
    },
    {
      entityId: 10,
      commonEntityType: {
        commonEntityTypeEnum: 'MDM_ENTITY_TYPE',
        commonParams: [
          {
            commonParamName: 'tree_node_id',
            commonParamValueType: 'NUMERIC',
            uiSettings: [CommonParamUiSetting.READ_ONLY],
            required: false,
            options: [],
            multivalue: false,
          },
          {
            commonParamName: 'tree_node_title',
            commonParamValueType: 'STRING',
            uiSettings: [CommonParamUiSetting.READ_ONLY],
            required: false,
            options: [],
            multivalue: false,
          },
          {
            commonParamName: 'parent_id',
            commonParamValueType: 'NUMERIC',
            uiSettings: [CommonParamUiSetting.READ_ONLY],
            required: false,
            options: [],
            multivalue: false,
          },
          {
            commonParamName: 'mdm_navigation_tree_node_reference',
            commonParamValueType: 'NUMERIC',
            uiSettings: [CommonParamUiSetting.READ_ONLY],
            required: false,
            options: [],
            multivalue: false,
          },
          {
            commonParamName: 'mdm_entity_type_reference',
            commonParamValueType: 'NUMERIC',
            uiSettings: [CommonParamUiSetting.READ_ONLY],
            required: false,
            options: [],
            multivalue: false,
          },
        ],
      },
      commonParamValues: [
        {
          commonParamName: 'tree_node_id',
          strings: [],
          numerics: [10],
          booleans: [],
          options: [],
        },
        {
          commonParamName: 'tree_node_title',
          strings: ['Маппинг'],
          numerics: [],
          booleans: [],
          options: [],
        },
        {
          commonParamName: 'parent_id',
          strings: [],
          numerics: [0],
          booleans: [],
          options: [],
        },
        {
          commonParamName: 'mdm_entity_type_reference',
          strings: [],
          numerics: [10],
          booleans: [],
          options: [],
        },
        {
          commonParamName: 'mdm_navigation_tree_node_reference',
          strings: [],
          numerics: [],
          booleans: [],
          options: [],
        },
      ],
    },
  ],
} as FindResponse;

export const navTreeTestCommonEntityParam: CommonParamValue = {
  commonParamName: 'tree_node_id',
  numerics: [0],
};

export const testEditorParams: EditorParam[] = [
  {
    type: EditorParamType.TEXT,
    title: 'Some text param',
    name: 'some_param1',
    value: '123',
  },
  {
    type: EditorParamType.INPUT,
    title: 'Some input param',
    name: 'some_param2',
    value: 'qwe',
  },
  {
    type: EditorParamType.SELECT,
    title: 'Some select param',
    name: 'some_param3',
    options: [
      { value: 'value1', label: 'label1' },
      { value: 'value2', label: 'label2' },
    ],
    selectedOptions: [{ value: 'value1', label: 'label1' }],
    multivalue: true,
  },
  {
    type: EditorParamType.RADIO,
    title: 'Some radio param',
    name: 'some_param4',
    options: [
      { value: 'true', label: 'Да' },
      { value: 'false', label: 'Нет' },
      { value: '', label: 'Не задано' },
    ],
    selectedOption: '',
  },
];
