const orderMock = {
    id: 2476932,
    shopId: 363245,
    status: 'DELIVERY',
    creationDate: '14-07-2017 11:30:36',
    creationDateTimestamp: '1500021036000',
    updateDate: '29-08-2017 16:10:29',
    updateDateTimestamp: '1504012229000',
    statusUpdateDate: '18-07-2017 05:01:08',
    statusUpdateDateTimestamp: '1500343268000',
    currency: 'RUR',
    buyerCurrency: 'RUR',
    exchangeRate: 1,
    itemsTotal: 852.47,
    buyerItemsTotal: 852.47,
    total: 852.47,
    buyerTotal: 852.47,
    feeTotal: 1.42,
    paymentType: 'PREPAID',
    paymentMethod: 'YANDEX',
    items: [{
        feedId: 464866,
        offerId: '246332',
        wareMd5: 'OQvyz6D91pYufeJKgW5mGg',
        feedCategoryId: '1066',
        categoryId: 7811901,
        offerName: 'Женское приталенное платье ISEYMI из хлопка с длинными рукавами',
        price: 852.47,
        count: 8,
        availability: 'ON_DEMAND',
        isPromotedByVendor: false,
        modelId: -1,
        description: 'Женское приталенное платье ISEYMI из хлопка с длинными рукавами',
        pictures: [{url: '//avatars.mds.yandex.net/get-marketpic/373800/market_bVOvpqHLjlfeblfnGCqNQw/'}],
        buyerPrice: 852.47,
        unitInfo: 'уп',
        fee: 0.05,
        feeInt: 500,
        feeSum: 1.42,
        showUid: '0002094109124747313',
        realShowUid: '000209410912474731306000',
        shopUrl: 'https://www.rumall.com/iseymi-cotton-women-s-round-neck-black-long-sleeves-tight-sexy-irregular-sexy-club-sheath-fashion-slim-bodycon-party-dresses',
        kind2Params: [{
            type: 'enum',
            subType: 'color',
            name: 'Цвет',
            value: 'серый',
            code: '#666666',
            specifiedForOffer: false,
        }],
        id: 2504072,
    }],
    delivery: {
        type: 'DELIVERY',
        serviceName: 'SF-Express',
        price: 0,
        buyerPrice: 0,
        dates: {fromDate: '24-07-2017', toDate: '18-08-2017'},
        validatedDates: {},
        regionId: 213,
        shopAddress: {
            country: 'Russia',
            postcode: '119021',
            city: 'Moscow',
            subway: '',
            street: 'ulitsa L\'va Tolstogo',
            house: '16',
            block: '',
            entrance: '',
            entryphone: '',
            floor: '',
            apartment: '',
            recipient: 'Litvinov Dmitrij',
            phone: '+79150773709',
            language: 'ENG',
        },
        paymentOptions: [],
        hiddenPaymentOptions: [],
        validFeatures: ['PLAINCPA'],
        deliveryServiceId: 99,
        deliveryPartnerType: 'SHOP',

        shipments: [
            {
                id: 8623,
                creationDate: '20-07-2017 11:30:30',
                shopShipmentId: 0,
                weight: 0,
                width: 0,
                height: 0,
                depth: 0,
                items: [
                    {
                        itemId: 2504072,
                        count: 2,
                    },
                    {
                        itemId: 2504072,
                        count: 1,
                    },
                ],
                tracks: [
                    {
                        id: 8292,
                        trackCode: '12345',
                        deliveryServiceId: 124,
                        trackerId: 2914,
                        status: 'STARTED',
                        creationDate: '20-07-2017 11:30:30',
                        checkpoints: [
                            {
                                id: 39127,
                                trackerCheckpointId: 36918,
                                country: '',
                                city: '',
                                location: '',
                                message: 'Shipment loaded at 【Wuxi New District Distribution Center】, send to  ' +
                                '【Shenyang Hunnan New District Distribution Center】',
                                status: 'IN_TRANSIT',
                                date: '20-07-2017 08:32:04',
                                deliveryStatus: 30,
                                translatedCountry: '',
                                translatedCity: '',
                                translatedLocation: '',
                                translatedMessage: 'Груз загружается в 【уси новый район Центр распределения】, ' +
                                'отправить 【Шэньян Hunnan новый район Центр распределения】',
                            }, {
                                id: 39128,
                                trackerCheckpointId: 36917,
                                country: '',
                                city: '',
                                location: '',
                                message: 'Shipment arrive at 【Wuxi New District Distribution Center】',
                                status: 'IN_TRANSIT',
                                date: '20-07-2017 08:32:04',
                                deliveryStatus: 30,
                                translatedCountry: '',
                                translatedCity: '',
                                translatedLocation: '',
                                translatedMessage: 'Отгрузка прибыть в 【уси новый район Центр распределения】',
                            }],
                    },
                    {
                        id: 1234,
                        trackCode: '67890',
                        deliveryServiceId: 124,
                        trackerId: 2914,
                        status: 'STARTED',
                        creationDate: '23-07-2017 11:30:30',
                        checkpoints: [],
                    },
                ],
            },
            {
                id: 8623,
                shopShipmentId: 0,
                creationDate: '20-07-2017 11:31:00',
                weight: 0,
                width: 0,
                height: 0,
                depth: 0,
                items: [
                    {
                        itemId: 2504072,
                        count: 3,
                    },
                ],
                tracks: [],
            },
        ],
        userReceived: false,
    },
    buyer: {
        id: 'dprva+TgDkRmm72Fi2jmaw==',
        uid: 97305748,
        muidString: 'null',
        ip: '2a02:6b8:0:40c:19b9:b2e9:65c:3bb7',
        regionId: 213,
        lastName: 'Dmitrij',
        firstName: 'Litvinov',
        middleName: '',
        phone: '+79150773709',
        email: 'dlitvinov87@gmail.com',
        dontCall: false,
        assessor: false,
    },
    fake: false,
    context: 'MARKET',
    shopOrderId: '2476932',
    paymentId: 181081,
    balanceOrderId: '1629725589',
    userGroup: 'DEFAULT',
    noAuth: false,
    acceptMethod: 'PUSH_API',
    isBooked: false,
    archiveAtDate: '21-11-2017 11:30:36',
    archived: false,
    cpa20: false,
    displayOrderId: '2476932',
    global: true,
    payment: {
        id: 181081,
        orderId: 2476932,
        basketId: '596881300f7d7e2848c92bb7',
        fake: false,
        status: 'CLEARED',
        uid: 97305748,
        currency: 'RUR',
        totalAmount: 852.47,
        creationDate: '14-07-2017 11:30:38',
        updateDate: '18-07-2017 05:01:09',
        statusUpdateDate: '18-07-2017 05:01:09',
        prepayType: 'YANDEX_MONEY',
    },
    validFeatures: ['PLAINCPA'],
};

const ORDER_ID = orderMock.id;
const MARKET_BRANDED_ORDER_ID = orderMock.id;
const SHOP_ORDER_ID = orderMock.shopId;

const orders = {};
orders[ORDER_ID] = {
    id: ORDER_ID,
    /** Чтобы номер был двойным: с Маркета и магазина */
    shopOrderId: SHOP_ORDER_ID,
};

orders[MARKET_BRANDED_ORDER_ID] = orderMock;

export default orders;
