var stubs = require('@yandex-int/gemini-serp-stubs');

module.exports = {
    request_text: 'котики видео',
    type: 'snippet',
    data_stub: {
        num: 0,
        snippets: {
            full: {
                clips: [
                    {
                        clip_host: 'www.somelonghostname.com',
                        clip_href: 'http://www.youtube.com/watch?v=PuhOAAgXtAM',
                        dur: '394',
                        green_host: 'somelonghostname.com',
                        hst: 'www.somelonghostname.com',
                        is_playable: '1',
                        raw_pass: 'Смешные \u0007[Котики\u0007]!  YouTube.',
                        raw_title: 'Смешные \u0007[Котики\u0007]!',
                        thmb_h: 90,
                        thmb_href: stubs.imageUrlStub(140, 90, { color: 'bf390c', patternSize: 24, format: 'png' }),
                        thmb_w: 120,
                        title: 'Смешные Котики!',
                        url: 'http://www.youtube.com/watch?v=PuhOAAgXtAM',
                        vhd: '0',
                        vhdbin: '1',
                        views: '29047'
                    },
                    {
                        clip_host: 'www.anotherlonghostname.com',
                        clip_href: 'http://www.youtube.com/watch?v=h9RYjl4NyWc',
                        dur: '1234',
                        green_host: 'anotherlonghostname.com',
                        hst: 'www.anotherlonghostname.com',
                        is_playable: '1',
                        raw_pass: 'Funny Cats, Смешные \u0007[котики\u0007] - YouTube.',
                        raw_title: 'Funny Cats, Смешные \u0007[котики\u0007]',
                        thmb_h: 90,
                        thmb_href: stubs.imageUrlStub(140, 90, { color: '30caaa', patternSize: 24, format: 'png' }),
                        thmb_w: 120,
                        title: 'Funny Cats, Смешные котики',
                        url: 'http://www.youtube.com/watch?v=h9RYjl4NyWc',
                        vhd: '0',
                        vhdbin: '0',
                        views: '6079'
                    },
                    {
                        clip_host: 'www.somelonghostname.com',
                        clip_href: 'http://www.youtube.com/watch?v=LbxTRMKPNH4',
                        dur: '171',
                        green_host: 'somelonghostname.com',
                        hst: 'www.somelonghostname.com',
                        is_playable: '1',
                        raw_pass: 'смешные \u0007[котики\u0007] - YouTube.',
                        raw_title: 'смешные \u0007[котики\u0007]',
                        thmb_h: 90,
                        thmb_href: stubs.imageUrlStub(140, 90, { color: 'bf390c', patternSize: 24, format: 'png' }),
                        thmb_w: 120,
                        title: 'смешные котики',
                        url: 'http://www.youtube.com/watch?v=LbxTRMKPNH4',
                        vhd: '4',
                        vhdbin: '1',
                        views: '5322'
                    },
                    {
                        clip_host: 'www.youtube.com',
                        clip_href: 'http://www.youtube.com/watch?v=N7sGh4KKDg8',
                        dur: '80',
                        green_host: 'youtube.com',
                        hst: 'www.youtube.com',
                        is_playable: '1',
                        raw_pass: '\u0007[Котик\u0007] пытается поужинать - YouTube.',
                        raw_title: '\u0007[Котик\u0007] пытается поужинать',
                        thmb_h: 90,
                        thmb_href: stubs.imageUrlStub(140, 90, { color: '30aaca', patternSize: 24, format: 'png' }),
                        thmb_w: 120,
                        thumb: 'i.ytimg.com/vi/N7sGh4KKDg8/0.jpg',
                        title: 'Котик пытается поужинать',
                        url: 'http://www.youtube.com/watch?v=N7sGh4KKDg8',
                        vhd: '0',
                        vhdbin: '0',
                        views: '955042'
                    },
                    {
                        clip_host: 'www.youtube.com',
                        clip_href: 'http://www.youtube.com/watch?v=H02Oy8eq9Bs',
                        dur: '367',
                        green_host: 'youtube.com',
                        hst: 'www.youtube.com',
                        is_playable: '1',
                        raw_pass: 'Подборка 2016 смешные \u0007[котики\u0007] видео...',
                        raw_title: 'Приколы \u0007[Котики\u0007] и Кошечки СМОТРЕТЬ РЖАЧ Подборка 2016',
                        server_descr: 'VIDEOP',
                        thmb_h: 90,
                        thmb_href: stubs.imageUrlStub(140, 90, { color: '30caaa', patternSize: 24, format: 'png' }),
                        thmb_w: 120,
                        title: 'Приколы Котики и Кошечки СМОТРЕТЬ РЖАЧ Подборка 2016',
                        url: 'http://www.youtube.com/watch?v=H02Oy8eq9Bs',
                        vhd: '4',
                        vhdbin: '1',
                        views: '41780'
                    },
                    {
                        clip_host: 'www.youtube.com',
                        clip_href: 'http://www.youtube.com/watch?v=goFix58B-vg',
                        dur: '185',
                        global_img_id: 'f19bb4e271d0066ed19469dcadc9487e-00-96',
                        green_host: 'youtube.com',
                        hst: 'www.youtube.com',
                        raw_pass: 'Хорошего настроения! ',
                        raw_title: 'КОТЫ ПРИКОЛЫ 2016 - СМЕШНЫЕ КОТЫ 2016 - Funny Cats 2016',
                        thmb_h: 90,
                        thmb_href: stubs.imageUrlStub(140, 90, { color: '30caaa', patternSize: 24, format: 'png' }),
                        thmb_w: 120,
                        title: 'КОТЫ ПРИКОЛЫ 2016 - СМЕШНЫЕ КОТЫ 2016 - Funny Cats 2016',
                        url: 'http://www.youtube.com/watch?v=goFix58B-vg',
                        vhd: '4',
                        vhdbin: '1',
                        views: '1214786'
                    },
                    {
                        clip_host: 'www.youtube.com',
                        clip_href: 'http://www.youtube.com/watch?v=01EaG9LulMs',
                        dur: '300',
                        episode: '22',
                        green_host: 'youtube.com',
                        hst: 'www.youtube.com',
                        raw_pass: '\u0007[котики\u0007], \u0007[котики\u0007] вперёд, \u0007[котики\u0007] вперед...',
                        raw_title: '\u0007[Котики\u0007], вперед!  - Весёлые доктора (22 серия)',
                        sertitle: 'котики вперед',
                        thmb_h: 90,
                        thmb_href: stubs.imageUrlStub(140, 90, { color: '30caaa', patternSize: 24, format: 'png' }),
                        thmb_w: 120,
                        title: 'Котики, вперед!  - Весёлые доктора (22 серия)',
                        url: 'http://www.youtube.com/watch?v=01EaG9LulMs',
                        vhd: '4',
                        vhdbin: '1',
                        views: '1613224'
                    },
                    {
                        clip_host: 'www.1tv.ru',
                        clip_href: 'http://www.1tv.ru/shows/dobroe-utro/mezhdu-tem/chtoby-kotiki-ne-skuchali-dobroe-utro-fragment-vypuska-ot-08-12-2016',
                        dur: '139',
                        green_host: '1tv.ru',
                        hst: 'www.1tv.ru',
                        raw_pass: 'Чтобы \u0007[котики\u0007] не скучали…  Доброе утро. ',
                        raw_title: 'Чтобы \u0007[котики\u0007] не скучали.  Доброе утро.  Фрагмент выпуска от 08.12.2016',
                        thmb_h: 90,
                        thmb_href: stubs.imageUrlStub(140, 90, { color: '30caaa', patternSize: 24, format: 'png' }),
                        thmb_w: 120,
                        title: 'Чтобы котики не скучали.  Доброе утро.  Фрагмент выпуска от 08.12.2016',
                        url: 'http://www.1tv.ru/shows/dobroe-utro/mezhdu-tem/chtoby-kotiki-ne-skuchali-dobroe-utro-fragment-vypuska-ot-08-12-2016',
                        views: '0'
                    },
                    {
                        clip_host: 'www.youtube.com',
                        clip_href: 'http://www.youtube.com/watch?v=068IDKYOeOk',
                        dur: '133',
                        global_img_id: '8802e7ff524c3e71942a8c412f6c9f38-00-96',
                        green_host: 'youtube.com',
                        hst: 'www.youtube.com',
                        raw_pass: 'Март 201.  9 - YouTube. Веселые \u0007[Котики\u0007]! ',
                        raw_title: 'Веселые \u0007[Котики\u0007]!  Смешное Видео с Кошками!  Март 2015. №9',
                        thmb_h: 90,
                        thmb_href: stubs.imageUrlStub(140, 90, { color: '30caaa', patternSize: 24, format: 'png' }),
                        thmb_w: 120,
                        title: 'Веселые Котики!  Смешное Видео с Кошками!  Март 2015. №9',
                        url: 'http://www.youtube.com/watch?v=068IDKYOeOk',
                        vhd: '4',
                        vhdbin: '1',
                        views: '7927'
                    },
                    {
                        clip_host: 'www.youtube.com',
                        clip_href: 'http://www.youtube.com/watch?v=Qy6kvIh2_Q8',
                        dur: '364',
                        green_host: 'youtube.com',
                        hst: 'www.youtube.com',
                        raw_pass: '...новые приколы с \u0007[котиками\u0007], \u0007[котики\u0007]...',
                        raw_title: 'Приколы лучшие приколы с \u0007[котиками\u0007] декабрь 2016 #2',
                        thmb_h: 90,
                        thmb_href: stubs.imageUrlStub(140, 90, { color: '30caaa', patternSize: 24, format: 'png' }),
                        thmb_w: 120,
                        title: 'Приколы лучшие приколы с котиками декабрь 2016 #2',
                        url: 'http://www.youtube.com/watch?v=Qy6kvIh2_Q8',
                        vhd: '4',
                        vhdbin: '1',
                        views: '138'
                    }
                ],
                counter_prefix: '/snippet/video/',
                request_caps: {
                    user_request: 'котики видео'
                },
                serp_info: {
                    flat: '1',
                    format: 'json',
                    type: 'video'
                },
                slot: 'full',
                template: 'video',
                type: 'video',
                types: {
                    kind: 'wizard',
                    all: [
                        'snippets',
                        'video'
                    ],
                    main: 'video'
                }
            }
        }
    }
};
