var stubs = require('@yandex-int/gemini-serp-stubs');

module.exports = {
    request_text: 'игра престолов',
    type: 'snippet',
    data_stub: {
        num: 0,
        snippets: {
            full: {
                applicable: 1,
                clips: [
                    {
                        MediaDuration: '3434',
                        VisibleURL: 'http://www.myvi.ru/watch/KI9RphJ7rkeDCx1dpIrrnA2',
                        cdt: '2016-10-13T07:00:00+0000',
                        clip_host: 'www.myvi.ru',
                        clip_href: 'http://www.myvi.ru/watch/KI9RphJ7rkeDCx1dpIrrnA2',
                        dur: '3434',
                        embed: 'y',
                        episode: '3',
                        global_img_id: 'd3d249c3b5e727ee909264fcf7846bb6-00-96',
                        green_host: 'myvi.ru',
                        hst: 'www.myvi.ru',
                        html5: 'y',
                        is_playable: '0',
                        mtime: '2016-10-13T07:00:00+0000',
                        nid: 'd3d249c3b5e727ee909264fcf7846bb6-00-96',
                        pass: 'Игра, престолов, Кино и ТВ, Игра Престолов сезон 1 серия 3.avi, видео...',
                        raw_pass: '\u0007[Игра\u0007], \u0007[престолов\u0007], Кино и ТВ, \u0007[Игра\u0007] \u0007[Престолов\u0007] сезон 1 серия 3.avi, видео...',
                        raw_title: [
                            '\u0007[игра престолов\u0007]',
                            '1 сезон 3 серия'
                        ],
                        season: '1',
                        sertitle: 'игра престолов',
                        server_descr: 'VIDEOP',
                        thmb_h: 90,
                        thmb_href: stubs.imageUrlStub(140, 90, { color: 'bf390c', patternSize: 24, format: 'png' }),
                        thmb_href_ext: stubs.imageUrlStub(140, 90, { color: 'bf390c', patternSize: 24, format: 'png' }),
                        thmb_src: 'dur=3434;cdt=2016-10-13T07:00:00Z;VisibleURL=http://www.myvi.ru/watch/KI9RphJ7rkeDCx1dpIrrnA2;html5=y;thumb=fs.myvi.ru/thumbnail/_KI9RphJ7rkeDCx1dpIrrnA2/1_hq.jpg;nid=d3d249c3b5e727ee909264fcf7846bb6-00-96;views=0;embed=y;hst=www.myvi.ru;url=http://www.myvi.ru/watch/KI9RphJ7rkeDCx1dpIrrnA2;',
                        thmb_w: 120,
                        thumb: 'fs.myvi.ru/thumbnail/_KI9RphJ7rkeDCx1dpIrrnA2/1_hq.jpg',
                        title: 'Игра Престолов сезон 1 серия 3.avi',
                        url: 'http://www.myvi.ru/watch/KI9RphJ7rkeDCx1dpIrrnA2',
                        videoid: '319960895552795381',
                        views: '0'
                    },
                    {
                        MediaDuration: '2595',
                        VisibleURL: 'http://www.youtube.com/watch?v=we18GArR1o8',
                        cdt: '2015-03-28T14:38:01+0000',
                        clip_host: 'www.youtube.com',
                        clip_href: 'http://www.youtube.com/watch?v=we18GArR1o8',
                        dur: '2595',
                        embed: 'y',
                        episode: '4',
                        global_img_id: 'fafc97db9453779b3600b20e027d9c03-00-96',
                        green_host: 'youtube.com',
                        hosting_info: {
                            https_supported: '1',
                            id: 'youtube.com',
                            preview: {
                                enabled: true,
                                flash: true,
                                height: 334,
                                html5: true,
                                width: 450
                            },
                            required_params: {
                                param: [
                                    'embed'
                                ]
                            }
                        },
                        hst: 'www.youtube.com',
                        html5: 'y',
                        is_playable: '1',
                        mtime: null,
                        nid: 'fafc97db9453779b3600b20e027d9c03-00-96',
                        pass: 'Игра престолов (1-4 сезоны) - YouTube. Видео в хорошем качестве...',
                        raw_pass: '\u0007[Игра\u0007] \u0007[престолов\u0007] (1-4 сезоны) - YouTube. Видео в хорошем качестве...',
                        raw_title: [
                            '\u0007[игра престолов\u0007]',
                            '1 сезон 4 серия'
                        ],
                        season: '1',
                        sertitle: 'игра престолов',
                        server_descr: 'VIDEOP',
                        thmb_h: 90,
                        thmb_href: stubs.imageUrlStub(140, 90, { color: '30caaa', patternSize: 24, format: 'png' }),
                        thmb_href_ext: stubs.imageUrlStub(140, 90, { color: '30caaa', patternSize: 24, format: 'png' }),
                        thmb_src: 'dur=2595;cdt=2015-03-28T14:38:01Z;VisibleURL=http://www.youtube.com/watch?v=we18GArR1o8;html5=y;thumb=i.ytimg.com/vi/we18GArR1o8/0.jpg;nid=fafc97db9453779b3600b20e027d9c03-00-96;views=1536232;embed=y;hst=www.youtube.com;url=http://www.youtube.com/watch?v=we18GArR1o8;',
                        thmb_w: 120,
                        thumb: 'i.ytimg.com/vi/we18GArR1o8/0.jpg',
                        title: 'Игра престолов (1-4 сезоны)',
                        url: 'http://www.youtube.com/watch?v=we18GArR1o8',
                        videoid: '17811147164649371233',
                        views: '1536232'
                    },
                    {
                        MediaDuration: '3256',
                        VisibleURL: 'http://www.myvi.ru/watch/CYPs9OWOx0m_t52mJsGfYg2',
                        cdt: '2016-10-13T07:00:00+0000',
                        clip_host: 'www.myvi.ru',
                        clip_href: 'http://www.myvi.ru/watch/CYPs9OWOx0m_t52mJsGfYg2',
                        dur: '3256',
                        embed: 'y',
                        episode: '5',
                        global_img_id: 'f83063db9462f41eb29591e237a47005-00-96',
                        green_host: 'myvi.ru',
                        hst: 'www.myvi.ru',
                        html5: 'y',
                        is_playable: '0',
                        mtime: '2016-10-13T07:00:00+0000',
                        nid: 'f83063db9462f41eb29591e237a47005-00-96',
                        pass: 'Игра, престолов, game, thrones, сезон, Кино и ТВ, Игра Престолов сезон 1...',
                        raw_pass: '\u0007[Игра\u0007], \u0007[престолов\u0007], \u0007[game\u0007], \u0007[thrones\u0007], сезон, Кино и ТВ, \u0007[Игра\u0007] \u0007[Престолов\u0007] сезон 1...',
                        raw_title: [
                            '\u0007[игра престолов\u0007]',
                            '1 сезон 5 серия'
                        ],
                        season: '1',
                        sertitle: 'игра престолов',
                        server_descr: 'VIDEOP',
                        thmb_h: 90,
                        thmb_href: stubs.imageUrlStub(140, 90, { color: 'bf390c', patternSize: 24, format: 'png' }),
                        thmb_href_ext: stubs.imageUrlStub(140, 90, { color: 'bf390c', patternSize: 24, format: 'png' }),
                        thmb_src: 'dur=3256;cdt=2016-10-13T07:00:00Z;VisibleURL=http://www.myvi.ru/watch/CYPs9OWOx0m_t52mJsGfYg2;html5=y;thumb=api.myvi.ru/v2.0/images/fs130--myvi--ru-vv201-2164936_th1;nid=f83063db9462f41eb29591e237a47005-00-96;views=0;embed=y;hst=www.myvi.ru;url=http://www.myvi.ru/watch/CYPs9OWOx0m_t52mJsGfYg2;',
                        thmb_w: 120,
                        thumb: 'api.myvi.ru/v2.0/images/fs130--myvi--ru-vv201-2164936_th1',
                        title: 'Игра Престолов сезон 1 серия 5.avi',
                        url: 'http://www.myvi.ru/watch/CYPs9OWOx0m_t52mJsGfYg2',
                        videoid: '9411301729443878934',
                        views: '0'
                    },
                    {
                        MediaDuration: '3401',
                        VisibleURL: 'http://www.myvi.ru/watch/FUyyw-llr0KJYbOdVlzhag2',
                        cdt: '2016-09-19T07:00:00+0000',
                        clip_host: 'www.myvi.ru',
                        clip_href: 'http://www.myvi.ru/watch/FUyyw-llr0KJYbOdVlzhag2',
                        dur: '3401',
                        embed: 'y',
                        episode: '6',
                        global_img_id: '69b111b537bceb86f4ccfce0856a99b6-00-96',
                        green_host: 'myvi.ru',
                        hst: 'www.myvi.ru',
                        html5: 'y',
                        is_playable: '0',
                        mtime: '2016-09-19T07:00:00+0000',
                        nid: '69b111b537bceb86f4ccfce0856a99b6-00-96',
                        pass: 'Сериал Игра престолов/Game of Thrones 2 сезон онлайн Время благоденствия...',
                        raw_pass: 'Сериал \u0007[Игра\u0007] \u0007[престолов\u0007]/\u0007[Game\u0007] \u0007[of\u0007] \u0007[Thrones\u0007] 2 сезон онлайн Время благоденствия...',
                        raw_title: [
                            '\u0007[игра престолов\u0007]',
                            '2 сезон 6 серия'
                        ],
                        season: '2',
                        sertitle: 'игра престолов',
                        server_descr: 'VIDEOP',
                        thmb_h: 90,
                        thmb_href: stubs.imageUrlStub(140, 90, { color: 'bf390c', patternSize: 24, format: 'png' }),
                        thmb_href_ext: stubs.imageUrlStub(140, 90, { color: 'bf390c', patternSize: 24, format: 'png' }),
                        thmb_src: 'dur=3401;cdt=2016-09-19T07:00:00Z;VisibleURL=http://www.myvi.ru/watch/FUyyw-llr0KJYbOdVlzhag2;html5=y;thumb=fs.myvi.ru/thumbnail/_FUyyw-llr0KJYbOdVlzhag2/1_hq.jpg;nid=69b111b537bceb86f4ccfce0856a99b6-00-96;views=0;embed=y;hst=www.myvi.ru;url=http://www.myvi.ru/watch/FUyyw-llr0KJYbOdVlzhag2;',
                        thmb_w: 120,
                        thumb: 'fs.myvi.ru/thumbnail/_FUyyw-llr0KJYbOdVlzhag2/1_hq.jpg',
                        title: 'Игра престолов 2 сезон.06.серия...',
                        url: 'http://www.myvi.ru/watch/FUyyw-llr0KJYbOdVlzhag2',
                        videoid: '4270367029530677650',
                        views: '0'
                    },
                    {
                        MediaDuration: '3413',
                        VisibleURL: 'http://www.myvi.ru/watch/1wgG0BKg2E-lmmGItt7ubg2',
                        cdt: '2016-09-19T07:00:00+0000',
                        clip_host: 'www.myvi.ru',
                        clip_href: 'http://www.myvi.ru/watch/1wgG0BKg2E-lmmGItt7ubg2',
                        dur: '3413',
                        embed: 'y',
                        episode: '7',
                        global_img_id: 'c0bc44e1b2b679450bd0445444f31d34-00-96',
                        green_host: 'myvi.ru',
                        hst: 'www.myvi.ru',
                        html5: 'y',
                        is_playable: '0',
                        mtime: '2016-09-19T07:00:00+0000',
                        nid: 'c0bc44e1b2b679450bd0445444f31d34-00-96',
                        pass: 'Сериал Игра престолов/Game of Thrones 2 сезон онлайн Время благоденствия...',
                        raw_pass: 'Сериал \u0007[Игра\u0007] \u0007[престолов\u0007]/\u0007[Game\u0007] \u0007[of\u0007] \u0007[Thrones\u0007] 2 сезон онлайн Время благоденствия...',
                        raw_title: [
                            '\u0007[игра престолов\u0007]',
                            '2 сезон 7 серия'
                        ],
                        season: '2',
                        sertitle: 'игра престолов',
                        server_descr: 'VIDEOP',
                        thmb_h: 90,
                        thmb_href: stubs.imageUrlStub(140, 90, { color: 'bf390c', patternSize: 24, format: 'png' }),
                        thmb_href_ext: stubs.imageUrlStub(140, 90, { color: 'bf390c', patternSize: 24, format: 'png' }),
                        thmb_src: 'dur=3413;cdt=2016-09-19T07:00:00Z;VisibleURL=http://www.myvi.ru/watch/1wgG0BKg2E-lmmGItt7ubg2;html5=y;thumb=fs.myvi.ru/thumbnail/_1wgG0BKg2E-lmmGItt7ubg2/1_hq.jpg;nid=c0bc44e1b2b679450bd0445444f31d34-00-96;views=0;embed=y;hst=www.myvi.ru;url=http://www.myvi.ru/watch/1wgG0BKg2E-lmmGItt7ubg2;',
                        thmb_w: 120,
                        thumb: 'fs.myvi.ru/thumbnail/_1wgG0BKg2E-lmmGItt7ubg2/1_hq.jpg',
                        title: 'Игра престолов 2 сезон.07.серия...',
                        url: 'http://www.myvi.ru/watch/1wgG0BKg2E-lmmGItt7ubg2',
                        videoid: '1447895043228757393',
                        views: '0'
                    },
                    {
                        MediaDuration: '3308',
                        VisibleURL: 'http://www.myvi.ru/watch/JsxYDxE4KE67k3Reqe1Hcg2',
                        cdt: '2016-09-19T07:00:00+0000',
                        clip_host: 'www.myvi.ru',
                        clip_href: 'http://www.myvi.ru/watch/JsxYDxE4KE67k3Reqe1Hcg2',
                        dur: '3308',
                        embed: 'y',
                        episode: '8',
                        global_img_id: '744e0a488e4a4162ee6f569edc490387-00-96',
                        green_host: 'myvi.ru',
                        hst: 'www.myvi.ru',
                        html5: 'y',
                        is_playable: '0',
                        mtime: '2016-09-19T07:00:00+0000',
                        nid: '744e0a488e4a4162ee6f569edc490387-00-96',
                        pass: 'Сериал Игра престолов/Game of Thrones 2 сезон онлайн Время благоденствия...',
                        raw_pass: 'Сериал \u0007[Игра\u0007] \u0007[престолов\u0007]/\u0007[Game\u0007] \u0007[of\u0007] \u0007[Thrones\u0007] 2 сезон онлайн Время благоденствия...',
                        raw_title: [
                            '\u0007[игра престолов\u0007]',
                            '2 сезон 8 серия'
                        ],
                        season: '2',
                        sertitle: 'игра престолов',
                        server_descr: 'VIDEOP',
                        thmb_h: 90,
                        thmb_href: stubs.imageUrlStub(140, 90, { color: 'bf390c', patternSize: 24, format: 'png' }),
                        thmb_href_ext: stubs.imageUrlStub(140, 90, { color: 'bf390c', patternSize: 24, format: 'png' }),
                        thmb_src: 'dur=3308;cdt=2016-09-19T07:00:00Z;VisibleURL=http://www.myvi.ru/watch/JsxYDxE4KE67k3Reqe1Hcg2;html5=y;thumb=fs.myvi.ru/thumbnail/_JsxYDxE4KE67k3Reqe1Hcg2/1_hq.jpg;nid=744e0a488e4a4162ee6f569edc490387-00-96;views=0;embed=y;hst=www.myvi.ru;url=http://www.myvi.ru/watch/JsxYDxE4KE67k3Reqe1Hcg2;',
                        thmb_w: 120,
                        thumb: 'fs.myvi.ru/thumbnail/_JsxYDxE4KE67k3Reqe1Hcg2/1_hq.jpg',
                        title: 'Игра престолов 2 сезон.08.серия...',
                        url: 'http://www.myvi.ru/watch/JsxYDxE4KE67k3Reqe1Hcg2',
                        videoid: '837432292612362770',
                        views: '0'
                    },
                    {
                        MediaDuration: '3370',
                        VisibleURL: 'http://www.myvi.ru/watch/Ud7TTagbHE6P2nn3o3Zegw2',
                        cdt: '2016-09-19T07:00:00+0000',
                        clip_host: 'www.myvi.ru',
                        clip_href: 'http://www.myvi.ru/watch/Ud7TTagbHE6P2nn3o3Zegw2',
                        dur: '3370',
                        embed: 'y',
                        episode: '9',
                        global_img_id: '23800c3c1ab9cc13525d20bd2c7f5968-00-96',
                        green_host: 'myvi.ru',
                        hst: 'www.myvi.ru',
                        html5: 'y',
                        is_playable: '0',
                        mtime: '2016-09-19T07:00:00+0000',
                        nid: '23800c3c1ab9cc13525d20bd2c7f5968-00-96',
                        pass: 'Игра престолов 2 сезон.09.серия...',
                        raw_pass: '\u0007[Игра\u0007] \u0007[престолов\u0007] 2 сезон.09.серия...',
                        raw_title: [
                            '\u0007[игра престолов\u0007]',
                            '2 сезон 9 серия'
                        ],
                        season: '2',
                        sertitle: 'игра престолов',
                        server_descr: 'VIDEOP',
                        thmb_h: 90,
                        thmb_href: stubs.imageUrlStub(140, 90, { color: 'bf390c', patternSize: 24, format: 'png' }),
                        thmb_href_ext: stubs.imageUrlStub(140, 90, { color: 'bf390c', patternSize: 24, format: 'png' }),
                        thmb_src: 'dur=3370;cdt=2016-09-19T07:00:00Z;VisibleURL=http://www.myvi.ru/watch/Ud7TTagbHE6P2nn3o3Zegw2;html5=y;thumb=api.myvi.ru/v2.0/images/fs40--myvi--ru-2135718_th1;nid=23800c3c1ab9cc13525d20bd2c7f5968-00-96;views=0;embed=y;hst=www.myvi.ru;url=http://www.myvi.ru/watch/Ud7TTagbHE6P2nn3o3Zegw2;',
                        thmb_w: 120,
                        thumb: 'api.myvi.ru/v2.0/images/fs40--myvi--ru-2135718_th1',
                        title: 'Игра престолов 2 сезон.09.серия...',
                        url: 'http://www.myvi.ru/watch/Ud7TTagbHE6P2nn3o3Zegw2',
                        videoid: '8327271910619180340',
                        views: '0'
                    },
                    {
                        MediaDuration: '3439',
                        VisibleURL: 'http://www.myvi.ru/watch/OIT44Q5_ika3EXh9_I8X-g2',
                        cdt: '2016-09-19T07:00:00+0000',
                        clip_host: 'www.myvi.ru',
                        clip_href: 'http://www.myvi.ru/watch/OIT44Q5_ika3EXh9_I8X-g2',
                        dur: '3439',
                        embed: 'y',
                        episode: '1',
                        global_img_id: 'c4921a35b3e23e052ffa5575a8000e12-00-96',
                        green_host: 'myvi.ru',
                        hst: 'www.myvi.ru',
                        html5: 'y',
                        is_playable: '0',
                        mtime: '2016-09-19T07:00:00+0000',
                        nid: 'c4921a35b3e23e052ffa5575a8000e12-00-96',
                        pass: 'Сериал Игра престолов/Game of Thrones 3 сезон онлайн Счастливый период...',
                        raw_pass: 'Сериал \u0007[Игра\u0007] \u0007[престолов\u0007]/\u0007[Game\u0007] \u0007[of\u0007] \u0007[Thrones\u0007] 3 сезон онлайн Счастливый период...',
                        raw_title: [
                            '\u0007[игра престолов\u0007]',
                            '3 сезон 1 серия'
                        ],
                        season: '3',
                        sertitle: 'игра престолов',
                        server_descr: 'VIDEOP',
                        thmb_h: 90,
                        thmb_href: stubs.imageUrlStub(140, 90, { color: 'bf390c', patternSize: 24, format: 'png' }),
                        thmb_href_ext: stubs.imageUrlStub(140, 90, { color: 'bf390c', patternSize: 24, format: 'png' }),
                        thmb_src: 'dur=3439;cdt=2016-09-19T07:00:00Z;VisibleURL=http://www.myvi.ru/watch/OIT44Q5_ika3EXh9_I8X-g2;html5=y;thumb=api.myvi.ru/v2.0/images/fs70--myvi--ru-2136048_th2;nid=c4921a35b3e23e052ffa5575a8000e12-00-96;views=0;embed=y;hst=www.myvi.ru;url=http://www.myvi.ru/watch/OIT44Q5_ika3EXh9_I8X-g2;',
                        thmb_w: 120,
                        thumb: 'api.myvi.ru/v2.0/images/fs70--myvi--ru-2136048_th2',
                        title: 'Игра престолов.03. сезон.01.серия...',
                        url: 'http://www.myvi.ru/watch/OIT44Q5_ika3EXh9_I8X-g2',
                        videoid: '15812219525048455391',
                        views: '0'
                    },
                    {
                        MediaDuration: '3338',
                        VisibleURL: 'http://www.myvi.ru/watch/tYtIrStkZU242_ZqLjwVwg2',
                        cdt: '2016-09-20T07:00:00+0000',
                        clip_host: 'www.myvi.ru',
                        clip_href: 'http://www.myvi.ru/watch/tYtIrStkZU242_ZqLjwVwg2',
                        dur: '3338',
                        embed: 'y',
                        episode: '4',
                        global_img_id: '44f0f8aadb90ef2ebeff80b61cbaef9b-00-96',
                        green_host: 'myvi.ru',
                        hst: 'www.myvi.ru',
                        html5: 'y',
                        is_playable: '0',
                        mtime: '2016-09-20T07:00:00+0000',
                        nid: '44f0f8aadb90ef2ebeff80b61cbaef9b-00-96',
                        pass: 'Сериал Игра престолов/Game of Thrones 4 сезон онлайн Действие...',
                        raw_pass: 'Сериал \u0007[Игра\u0007] \u0007[престолов\u0007]/\u0007[Game\u0007] \u0007[of\u0007] \u0007[Thrones\u0007] 4 сезон онлайн Действие...',
                        raw_title: [
                            '\u0007[игра престолов\u0007]',
                            '4 сезон 4 серия'
                        ],
                        season: '4',
                        sertitle: 'игра престолов',
                        server_descr: 'VIDEOP',
                        thmb_h: 90,
                        thmb_href: stubs.imageUrlStub(140, 90, { color: 'bf390c', patternSize: 24, format: 'png' }),
                        thmb_href_ext: stubs.imageUrlStub(140, 90, { color: 'bf390c', patternSize: 24, format: 'png' }),
                        thmb_src: 'dur=3338;cdt=2016-09-20T07:00:00Z;VisibleURL=http://www.myvi.ru/watch/tYtIrStkZU242_ZqLjwVwg2;html5=y;thumb=fs.myvi.ru/thumbnail/_tYtIrStkZU242_ZqLjwVwg2/1_hq.jpg;nid=44f0f8aadb90ef2ebeff80b61cbaef9b-00-96;views=0;embed=y;hst=www.myvi.ru;url=http://www.myvi.ru/watch/tYtIrStkZU242_ZqLjwVwg2;',
                        thmb_w: 120,
                        thumb: 'fs.myvi.ru/thumbnail/_tYtIrStkZU242_ZqLjwVwg2/1_hq.jpg',
                        title: 'Игра престолов.04. сезон.04.серия...',
                        url: 'http://www.myvi.ru/watch/tYtIrStkZU242_ZqLjwVwg2',
                        videoid: '268432516593779180',
                        views: '0'
                    },
                    {
                        MediaDuration: '3181',
                        VisibleURL: 'http://www.myvi.ru/watch/BaZJNpFjwk-lZzuYrtdB9A2',
                        cdt: '2016-09-20T07:00:00+0000',
                        clip_host: 'www.myvi.ru',
                        clip_href: 'http://www.myvi.ru/watch/BaZJNpFjwk-lZzuYrtdB9A2',
                        dur: '3181',
                        embed: 'y',
                        episode: '8',
                        global_img_id: '08d67fc2738bbfcd454392666db4208e-00-96',
                        green_host: 'myvi.ru',
                        hst: 'www.myvi.ru',
                        html5: 'y',
                        is_playable: '0',
                        mtime: '2016-09-20T07:00:00+0000',
                        nid: '08d67fc2738bbfcd454392666db4208e-00-96',
                        pass: 'Сериал Игра престолов/Game of Thrones 4 сезон онлайн Действие...',
                        raw_pass: 'Сериал \u0007[Игра\u0007] \u0007[престолов\u0007]/\u0007[Game\u0007] \u0007[of\u0007] \u0007[Thrones\u0007] 4 сезон онлайн Действие...',
                        raw_title: [
                            '\u0007[игра престолов\u0007]',
                            '4 сезон 8 серия'
                        ],
                        season: '4',
                        sertitle: 'игра престолов',
                        server_descr: 'VIDEOP',
                        thmb_h: 90,
                        thmb_href: stubs.imageUrlStub(140, 90, { color: 'bf390c', patternSize: 24, format: 'png' }),
                        thmb_href_ext: stubs.imageUrlStub(140, 90, { color: 'bf390c', patternSize: 24, format: 'png' }),
                        thmb_src: 'dur=3181;cdt=2016-09-20T07:00:00Z;VisibleURL=http://www.myvi.ru/watch/BaZJNpFjwk-lZzuYrtdB9A2;html5=y;thumb=api.myvi.ru/v2.0/images/fs129--myvi--ru-vv195-2137378_th1;nid=08d67fc2738bbfcd454392666db4208e-00-96;views=0;embed=y;hst=www.myvi.ru;url=http://www.myvi.ru/watch/BaZJNpFjwk-lZzuYrtdB9A2;',
                        thmb_w: 120,
                        thumb: 'api.myvi.ru/v2.0/images/fs129--myvi--ru-vv195-2137378_th1',
                        title: 'Игра престолов.04. сезон.08.серия...',
                        url: 'http://www.myvi.ru/watch/BaZJNpFjwk-lZzuYrtdB9A2',
                        videoid: '1295920104450531113',
                        views: '0'
                    }
                ],
                count: 21354,
                counter_prefix: '/snippet/video/',
                data: {},
                request_caps: {
                    has_seasons: '1',
                    serial: '3015479900',
                    series_struct: [
                        [
                            1,
                            [
                                1,
                                2,
                                3,
                                4,
                                5,
                                6,
                                7,
                                8,
                                9,
                                10
                            ]
                        ],
                        [
                            2,
                            [
                                1,
                                2,
                                3,
                                4,
                                5,
                                6,
                                7,
                                8,
                                9,
                                10
                            ]
                        ],
                        [
                            3,
                            [
                                1,
                                2,
                                3,
                                4,
                                5,
                                6,
                                7,
                                8,
                                9,
                                10
                            ]
                        ],
                        [
                            4,
                            [
                                1,
                                2,
                                3,
                                4,
                                5,
                                6,
                                7,
                                8,
                                9,
                                10
                            ]
                        ],
                        [
                            5,
                            [
                                1,
                                2,
                                3,
                                4,
                                5,
                                6,
                                7,
                                8,
                                9,
                                10
                            ]
                        ],
                        [
                            6,
                            [
                                1,
                                2,
                                3,
                                4,
                                5,
                                6,
                                7,
                                8,
                                9,
                                10
                            ]
                        ]
                    ],
                    series_thumb: {
                        h: 300,
                        query: 'text=%D0%B8%D0%B3%D1%80%D0%B0%20%D0%BF%D1%80%D0%B5%D1%81%D1%82%D0%BE%D0%BB%D0%BE%D0%B2%20%D1%81%D0%B5%D1%80%D0%B8%D0%B0%D0%BB',
                        url: '//im3-tub-ru.yandex.net/i?id=5608cc2d318f0ec1a68e45538f513409',
                        w: 480
                    },
                    series_title: 'Игра престолов',
                    series_title_url: '%D0%B8%D0%B3%D1%80%D0%B0-%D0%BF%D1%80%D0%B5%D1%81%D1%82%D0%BE%D0%BB%D0%BE%D0%B2',
                    sertitle: 'игра престолов',
                    user_request: 'игра престолов',
                    wizTemplate: 'series'
                },
                serp_info: {
                    flat: '1',
                    format: 'json',
                    type: 'video'
                },
                slot: 'full',
                slot_rank: 0,
                template: 'video',
                type: 'video',
                types: {
                    all: [
                        'snippets',
                        'video'
                    ],
                    kind: 'wizard',
                    main: 'video'
                },
                urls: {
                    host: 'yandex.ru',
                    paths: {
                        favorites: '/video/favorites',
                        main: '/video/',
                        search: '/video/search'
                    }
                },
                wizTexts: {
                    greenurl1: 'yandex.ru/video?path=wizard',
                    greenurlTitle1: 'yandex.ru/video',
                    greenurlTitle2: '\u0007[Игра престолов\u0007]',
                    title: '\u0007[Игра престолов\u0007]: смотреть все серии'
                }
            }
        }
    }
};
