#!/bin/sh

SERVANT=market-checkout-test-util

if [ "x$1" == "xupgrade" ]
then
    exit 0;
fi

echo Removing /usr/bin/${SERVANT}.sh
rm -f /usr/bin/${SERVANT}.sh
rm -rf /usr/lib/yandex/${SERVANT}/ENV

exit 0

