module.exports = {
    host: 'https://yandex.ru',
    route: '/images/api/v1/cbir/market?req_id=12345&url=http%3A%2F%2Furl.ru&lr=Moscow&relev=relev&cbird=115',
    allowUnmocked: false,
    response: {
        data: {
            cbir_id: '1970537/JnFDt23nIFap53O0Dc2IKQ8888',
            images: [
                {
                    market_info: {
                        Relevance: 0.6868349314,
                        MarketRelevance: 0.3434,
                        ImageRelevance: 2949933625,
                        RawCommercialData: JSON.stringify({
                            avg_model_price: '650',
                            is_new: false,
                            image_width: '190',
                            category_id: '12785133',
                            money_id: 'xB8Gq58F0pvaR5RWoUmQKg',
                            similar_offers_info: [],
                            image_height: '135',
                            slug: 'fitnes-rezinka-30-kh-1-9-kh-0-5-sm-nagruzka-45-kg-tsvet-krasnyi',
                            currency: 'RUR',
                            model_id: '1407854380',
                            shop_domain: 'pokupki.market.yandex.ru',
                            cluster_id: null,
                            min_model_price: '650',
                            offers_to_request: [],
                            price: '650',
                            is_adult: false,
                            url:
                                '//pokupki.market.yandex.ru/product/101407556774?clid=2322165&lr=213&offerid=xB8Gq58F0pvaR5RWoUmQKg&src_pof=&utm_source_service=img&wprid=1631789542737655-18238832805553725590-sas2-0737-afd-sas-l7-balancer-8080-BAL-9701',
                            rank: '0',
                            shop_id: '431782',
                            confidence: '1',
                            offers_info: [
                                {
                                    avg_model_price: '650',
                                    is_new: false,
                                    image_width: '190',
                                    category_id: '12785133',
                                    money_id: 'xB8Gq58F0pvaR5RWoUmQKg',
                                    similar_offers_info: [],
                                    image_height: '135',
                                    slug: 'fitnes-rezinka-30-kh-1-9-kh-0-5-sm-nagruzka-45-kg-tsvet-krasnyi',
                                    currency: 'RUR',
                                    model_id: '1407854380',
                                    shop_domain: 'pokupki.market.yandex.ru',
                                    min_model_price: '650',
                                    offers_to_request: [],
                                    price: '650',
                                    is_adult: false,
                                    url:
                                        '//pokupki.market.yandex.ru/product/101407556774?clid=2322165&lr=213&offerid=xB8Gq58F0pvaR5RWoUmQKg&src_pof=&utm_source_service=img&wprid=1631789542737655-18238832805553725590-sas2-0737-afd-sas-l7-balancer-8080-BAL-9701',
                                    rank: '0',
                                    shop_id: '431782',
                                    confidence: '1',
                                    offers_info: [],
                                    title: 'Фитнес-резинка, 30 х 1,9 х 0,5 см, нагрузка 45 кг, цвет красный',
                                    image_url:
                                        '//avatars.mds.yandex.net/get-mpic/5243677/img_id2400889250671764256.jpeg/190x250',
                                    shop_rating: '4.46',
                                    source: '2',
                                    description:
                                        '3551208 Фитнес-резинка, 30 х 1,9 х 0,5 см, нагрузка 45 кг, цвет красный Размер резинок в обхвате: 60 см.',
                                    interior_attrs: {
                                        brutto_dimensions: {
                                            width_mkm: 280000,
                                            height_mkm: 280000,
                                            length_mkm: 280000,
                                        },
                                        shop_vendor: 'NewStory',
                                        brutto_weight_in_grams: 200,
                                    },
                                    offers: [],
                                    shop_url:
                                        'https://pokupki.market.yandex.ru/product/101407556774?offerid=xB8Gq58F0pvaR5RWoUmQKg',
                                },
                            ],
                            title: 'Фитнес-резинка, 30 х 1,9 х 0,5 см, нагрузка 45 кг, цвет красный',
                            image_url:
                                '//avatars.mds.yandex.net/get-mpic/5243677/img_id2400889250671764256.jpeg/190x250',
                            shop_rating: '4.46',
                            source: '2',
                            description:
                                '3551208 Фитнес-резинка, 30 х 1,9 х 0,5 см, нагрузка 45 кг, цвет красный Размер резинок в обхвате: 60 см.',
                            interior_attrs: {
                                brutto_dimensions: {
                                    width_mkm: 280000,
                                    height_mkm: 280000,
                                    length_mkm: 280000,
                                },
                                shop_vendor: 'NewStory',
                                brutto_weight_in_grams: 200,
                            },
                            offers: ['xB8Gq58F0pvaR5RWoUmQKg'],
                            shop_url:
                                'https://pokupki.market.yandex.ru/product/101407556774?offerid=xB8Gq58F0pvaR5RWoUmQKg',
                        }),
                    },
                },
                {
                    market_info: {
                        Relevance: 0.74547643,
                        MarketRelevance: 0.39781,
                        ImageRelevance: 1874672632,
                        RawCommercialData: JSON.stringify({
                            is_new: false,
                            image_width: '250',
                            category_id: '12785133',
                            money_id: 'YyZzqVG-yIV4TALKYCJvJw',
                            similar_offers_info: [],
                            image_height: '250',
                            currency: 'RUR',
                            model_id: null,
                            shop_domain: 'ganteli-kacheli.ru',
                            cluster_id: null,
                            offers_to_request: [],
                            price: '285',
                            is_adult: false,
                            url:
                                '//market-click2.yandex.ru/redir/GAkkM7lQwz7vv7M_pnW8mTv2cKRsybxBD6Pp9HTXvGaHApkwQ6mVUI42Xo8UTQki9Hk1yKhMvjFSTSn-C77zuj3wXiFY5L0DMX8FBR-tNWb9uXa4Q267CXHHe5f6EykcPoiTrekocmU86eXwMMP92dBlSnBTDit6muNZ5E4zV3KNB1ZqTxWoXKOtJ62wibeuf4Z_8XoZ3wMglu2SINepEhccBkQx3BKSGRURpsbV4Jjfcel3CnWbbQAA9CoL0lE5WRvDew9MZTG9YcL4MwoZamcAIHnuEkF0CI00KILMZAEwX4dJa-9ys3YpZy_ZA6TP8wN3xOtEdUFAi-69-tLIHbPo4i30uVkemyANvs3_2k54frhblX1qjxjc-geGa1wg_Efe0jd9BdkXIfxndRpEYOeD_c1Aamp15UnvQScwoxvL9EFYU024O_MtGMcUGUqaTFcNy_EyGg0z9rYOb2ewTeeiE1rfp1D-rGAPfR_mnsv0Gt01u_99TuOyZaWDijJcNLKlMWZGWylINjh7JbTorMlINZNlAUM__kjtX0gHQAw4_Qqfyj2-aBSvm3hmqYfHW-iYxkC5R8MzmB9mA-buiYXpBU3WstHXGPD1L1HMC4W3BoJaUi8eDV_wpUnEzzUgCtGuro9VAoCORUd3OrcW3twqDQgDRA3PSgEpFhH8frh2J4Bqko2FI33Kz0ZKGKaD-QCz6HPUFpekgLos5DcAvGl7eQGgh18NznRjNYb6qfsbNmlL5HVbvoIAurbhkTllaRdf8_y5luAsCr_fc0c_T9--SawwAVjebjA4y3yoEaQfFMIlr2hmdQ6QSNNHrx-2C5VxyU2keh047pkNbegvb0lf3fct1nzgorvFrKFlazQRjhDDAThymzHyCMVL4asvZ4SgWdq7-4nMdvI-BQNEmmQIt-fn2Ivx6JUG8DLye3NfoPHMqhGl-j_pKqi4ISQWb6KuCrv1l9DPfA59HVOUT0pX6uw7qD2ywhvqd8jk4tX4M4Uycaeu-D8GhOMrcEf6TnvpYwNEVwAfeJGPjLccF_UGQmUVTWesQO3HKh7EY06qQRzYKsFCPU6MICxPgdR7ge6xOhqY4ur8izo70ZFuyA,,?data=QVyKqSPyGQwNvdoowNEPjQ5EXjgJhV0_gTUY0uv2PapVp6qg-8lGwe4TxUHSjaXF4VWpip5lXIe6jpIm0-oS-oqREqxZX08rphfPpwa9PHwkfSe2IF6g8Rgfz6cWIpEDU-aJt8eG2IH1QTwZPIPstmAbjCRw8dgemlJBlOJf8yBaLCU3OkiAE_uq3MJEs4yKqk1qdLQ8OceJ4bat3tZrrJAe63QSs9fGqbeNHJdtGuM,&b64e=1&sign=68caa1f43c4355d95a44d4e6667f34d0&keyno=1',
                            rank: '3',
                            shop_id: '976994',
                            confidence: '1',
                            offers_info: [
                                {
                                    is_new: false,
                                    image_width: '250',
                                    category_id: '12785133',
                                    money_id: 'YyZzqVG-yIV4TALKYCJvJw',
                                    similar_offers_info: [],
                                    image_height: '250',
                                    currency: 'RUR',
                                    shop_domain: 'ganteli-kacheli.ru',
                                    offers_to_request: [],
                                    price: '285',
                                    is_adult: false,
                                    url:
                                        '//market-click2.yandex.ru/redir/GAkkM7lQwz7vv7M_pnW8mTv2cKRsybxBD6Pp9HTXvGaHApkwQ6mVUI42Xo8UTQki9Hk1yKhMvjFSTSn-C77zuj3wXiFY5L0DMX8FBR-tNWb9uXa4Q267CXHHe5f6EykcPoiTrekocmU86eXwMMP92dBlSnBTDit6muNZ5E4zV3KNB1ZqTxWoXKOtJ62wibeuf4Z_8XoZ3wMglu2SINepEhccBkQx3BKSGRURpsbV4Jjfcel3CnWbbQAA9CoL0lE5WRvDew9MZTG9YcL4MwoZamcAIHnuEkF0CI00KILMZAEwX4dJa-9ys3YpZy_ZA6TP8wN3xOtEdUFAi-69-tLIHbPo4i30uVkemyANvs3_2k54frhblX1qjxjc-geGa1wg_Efe0jd9BdkXIfxndRpEYOeD_c1Aamp15UnvQScwoxvL9EFYU024O_MtGMcUGUqaTFcNy_EyGg0z9rYOb2ewTeeiE1rfp1D-rGAPfR_mnsv0Gt01u_99TuOyZaWDijJcNLKlMWZGWylINjh7JbTorMlINZNlAUM__kjtX0gHQAw4_Qqfyj2-aBSvm3hmqYfHW-iYxkC5R8MzmB9mA-buiYXpBU3WstHXGPD1L1HMC4W3BoJaUi8eDV_wpUnEzzUgCtGuro9VAoCORUd3OrcW3twqDQgDRA3PSgEpFhH8frh2J4Bqko2FI33Kz0ZKGKaD-QCz6HPUFpekgLos5DcAvGl7eQGgh18NznRjNYb6qfsbNmlL5HVbvoIAurbhkTllaRdf8_y5luAsCr_fc0c_T9--SawwAVjebjA4y3yoEaQfFMIlr2hmdQ6QSNNHrx-2C5VxyU2keh047pkNbegvb0lf3fct1nzgorvFrKFlazQRjhDDAThymzHyCMVL4asvZ4SgWdq7-4nMdvI-BQNEmmQIt-fn2Ivx6JUG8DLye3NfoPHMqhGl-j_pKqi4ISQWb6KuCrv1l9DPfA59HVOUT0pX6uw7qD2ywhvqd8jk4tX4M4Uycaeu-D8GhOMrcEf6TnvpYwNEVwAfeJGPjLccF_UGQmUVTWesQO3HKh7EY06qQRzYKsFCPU6MICxPgdR7ge6xOhqY4ur8izo70ZFuyA,,?data=QVyKqSPyGQwNvdoowNEPjQ5EXjgJhV0_gTUY0uv2PapVp6qg-8lGwe4TxUHSjaXF4VWpip5lXIe6jpIm0-oS-oqREqxZX08rphfPpwa9PHwkfSe2IF6g8Rgfz6cWIpEDU-aJt8eG2IH1QTwZPIPstmAbjCRw8dgemlJBlOJf8yBaLCU3OkiAE_uq3MJEs4yKqk1qdLQ8OceJ4bat3tZrrJAe63QSs9fGqbeNHJdtGuM,&b64e=1&sign=68caa1f43c4355d95a44d4e6667f34d0&keyno=1',
                                    rank: '3',
                                    shop_id: '976994',
                                    confidence: '1',
                                    offers_info: [],
                                    title:
                                        'Эспандер для степа INDIGO неопреновые ручки 1 жгут SM-373 120 см, Оранжевый',
                                    image_url:
                                        '//avatars.mds.yandex.net/get-marketpic/1860579/market_5rW5INDZRNUPHERsjXyInA/190x250',
                                    shop_rating: '0',
                                    source: '2',
                                    interior_attrs: {
                                        shop_vendor: 'INDIGO',
                                    },
                                    offers: [],
                                    shop_url:
                                        'https://ganteli-kacheli.ru/magazin/product/espander-graciya-indigo-4-zhguta-sm-054-2',
                                },
                            ],
                            title: 'Эспандер для степа INDIGO неопреновые ручки 1 жгут SM-373 120 см, Оранжевый',
                            image_url:
                                '//avatars.mds.yandex.net/get-marketpic/1860579/market_5rW5INDZRNUPHERsjXyInA/190x250',
                            shop_rating: '0',
                            source: '2',
                            interior_attrs: {
                                shop_vendor: 'INDIGO',
                            },
                            offers: ['YyZzqVG-yIV4TALKYCJvJw'],
                            shop_url:
                                'https://ganteli-kacheli.ru/magazin/product/espander-graciya-indigo-4-zhguta-sm-054-2',
                        }),
                    },
                },
                {
                    market_info: {
                        Relevance: 0.17236313,
                        MarketRelevance: 0.103482,
                        ImageRelevance: 625648372,
                        RawCommercialData: JSON.stringify({
                            image_url:
                                '//avatars.mds.yandex.net/get-marketpic/1592727/market_eXpJsvxwH3v32suT48eCzg/190x250',
                            working_days_from: '1',
                            is_adult: false,
                            rank: '3',
                            offers_to_request: [],
                            working_hours_from: '08:00',
                            working_hours_till: '23:00',
                            model_id: null,
                            interior_attrs: {
                                shop_vendor: 'Body Form',
                            },
                            currency: 'RUR',
                            telephone_city_code: '800',
                            offers_info: [
                                {
                                    image_url:
                                        '//avatars.mds.yandex.net/get-marketpic/1592727/market_eXpJsvxwH3v32suT48eCzg/190x250',
                                    working_days_from: '1',
                                    is_adult: false,
                                    rank: '3',
                                    offers_to_request: [],
                                    working_hours_from: '08:00',
                                    working_hours_till: '23:00',
                                    interior_attrs: {
                                        shop_vendor: 'Body Form',
                                    },
                                    currency: 'RUR',
                                    telephone_city_code: '800',
                                    offers_info: [],
                                    money_id: 'yeV_ZICAjIj9e6d2ejvBxQ',
                                    street: 'Люблинская',
                                    city: 'Москва',
                                    category_id: '12785133',
                                    shop_id: '600920',
                                    description:
                                        'Новый вид универсального эспандера, используемого в специальных упражнениях для тренировки различных групп мышц. Для функционального тренинга высокого уровня.',
                                    shop_url: 'https://lishop.by/catalog/fitnes_i_gimnastika/fitnes/espander/302063/',
                                    image_width: '250',
                                    offers: [],
                                    source: '2',
                                    telephone_country_code: '7',
                                    call_url:
                                        '//market-click2.yandex.ru/redir/GAkkM7lQwz7vv7M_pnW8mce9ppMxJH_zILDWP4-k0jFYZGXddxtBnHLtLRYeXZa7ob1p9mGF1J8U0xvc97nSKHAyz1VB4gEHRLK4C-kSUc9EKJfLhP83lTWwT3CNycDL6q_9Vj4LMQkTdijJKHDRSVman3G7rxNmiE4AgMr4IGl_ZEFyzmoFOvW8StpSYUi-Fsh6TSjGx1hQr7djMwdvWkbhBI_Guy2cdp_fMMmg30nuhjWqFx4JyRjqpSmgP-tpHaMR4jeAKTLJ64ApkBlstsyncT-jJwsqP44fmTZ3d3s7G6tijjL0M8o--0vkGsSrAlS881P6IXF6Ri9hVebm6YEQVgAScPoKfEj0IOFxX0p2gorVCTR2PxRlB4yFSMGx7UqgDMyMwelPhs1sVbsZQokSm1vUwDDdO7oL7SjcyPozvYhzfq2yHCPbpPlFscdP9BTiNhuJVT1P9mUyCXJjnbwYIj4Ryx1HS7Er9bv-OLLIPIkLTCN5V68oHZGRE034lB_rXSLDuZUqfJP5mINbvoQsuuDxIHRSjMDaegB00nB-N9VIw-RvGtCr6fxYjtKEfqsig_NHo6sO7bav36Hfl0zgala9yfcpPxVvC5vmaAXT3L6wlD5nGHuPxYYCk2VimZNIAKAhpDIUyI6ptz7cP3IVq24sbMxjmKcIpbz39lsYqr9m0ljoov6Q5I-ktKm4nqHk1ZgukBDQhwnRyZ2dOGwX0DOfAQDebNPa3XesHJdTTffqJblmW505T2asavhzhMJ3WFqcmXKcp-Q2JbQGf1f1xoukoawLoto0Z9mtU4YUsoRo-mNNcjEFF0GZXCPiCA3H1UQSrSCGi8JUOxYGVGTLL29JuXPOGRSDt022XNMXTCb-uPVhr7InBxus90SiIPf8WeGgkkcZYfXG0UwByR_dh8Yl-XKKPWZTUSMzPQjOAHjsRp2zdZ1eG8764zBZQ1j6itwhSH9gFN6R8hM0ykSnvMEpzhL6wJRhzJ39KD_wcKOE0h8lSEGhCBVxI3HfNvJ_89qLSsSVdhae_2U0xHuV57arm2ZwmXA7TLFhwpLIEFYDHZvSRueODCYNVZyW2Fy51KPkbD7u1kknDO1X9Q,,?data=41WTYndNxdlaG-5xTfn6okY8p8Pwg5ELyADQ33z3ZnQsN0ihxi6gLm7SxkrSQC0mWT8uQU__21AevOLog3r7Pn8QdMUWCR5FvjoH4KdaQZhWQw7qPT8cuRA8vnAcoMMEo6kVXlk20DqgrhvqskLZXh2aXVXakuRe7d51KJK_PSxgCnPti-v31g,,&b64e=1&sign=8f8ef1a3024749fcca80c3d55c22fa22&keyno=1',
                                    is_new: false,
                                    title: 'Петля Body Form BF-RL70-208 см 32-80 кг',
                                    price: '2784',
                                    shop_domain: 'lishop.by',
                                    working_days_till: '1',
                                    telephone_number: '5115067',
                                    confidence: '1',
                                    house_number: '126',
                                    image_height: '250',
                                    url:
                                        '//market-click2.yandex.ru/redir/GAkkM7lQwz7vv7M_pnW8mce9ppMxJH_zILDWP4-k0jFYZGXddxtBnHLtLRYeXZa7ob1p9mGF1J8U0xvc97nSKHAyz1VB4gEHRLK4C-kSUc9EKJfLhP83lTWwT3CNycDL6q_9Vj4LMQkTdijJKHDRSVman3G7rxNmiE4AgMr4IGl_ZEFyzmoFOvW8StpSYUi-Fsh6TSjGx1hQr7djMwdvWkbhBI_Guy2cdp_fMMmg30nuhjWqFx4JyeDEe4Q1Cj6Fbij1fQgZgbOnEY81f6HKtqLz2SCWWKVXSr2oa5RhgQGcz1_xMzfwUeAaxRJgYvdDZYDiFORZuZXi59ulOpfvy1ZenrXlDTJr_l3MtxSF5XKmqV5_Uy9c0m-VNe4AUniNdyhZ7af_9GGRYkYw1NOZVNHw3fWQ2qa1hWNZTkgySNeoClZ7rLfzGakgusa4l5hqUw3toASg6sXZDU2NBStrVdPgnF8GhzFqUkocfM0pCAnzUjKn1DarBM3XmkFyqNQ6-g9e_TQIC9D8HQUwfiMJC4oFELfVnb1WvfXf9zQWFDBbSHvJCc-uTT47osXkn91g2mDXggDRnebQQGrOixXyci3_KuR0hb6r_q3vtzyGy50JzS7JmmJdC5cURGjJMIKWA5xAcvh_-tDk9qWRiojgjGGBveHTfAc71WfD2OiVWOm4zX21n9DelCh3xeFuKOca0kJVlBDRoh6JjvWqOtEToqGrpuNB677QHzz3oAANgjykBcrBR2w-gnub0BmsIP7K0FW3TwipRJauuPxOITLLySD2ZQUFemkdlpFu0SazOvu9bhBGODWsvPEvmdBSS6_32dumJzM9J_iMvEiiv5wSvjnooLNSm3VrwCr9TeGaQ9O8czTqllAVnrIB7Z_KRfdWupKuB9QjFrMLjA0IHeSf3v5bp3XYGrBFKsEoeYo_xNKIDJ0ioWAhNGAWjUfevfFStEQbyPp5YoTOhu4bZiqbFzRwlMqyrpZbHCxAEzoLh99OBkofDwtBC3gf2AEXj7C54bg8MaFUufQj6L2tHnqRSBXZf0PyqzC0ZtPMfqnaWqUDdSfm0QBwV6UBMmKNS1LHfxiG5b4WrbZvRy4MlrVAig,,?data=QVyKqSPyGQwNvdoowNEPjSyYvWrLOawK0NSxG2Iu01RLSU7mQxzZSqVAAGUl6-H0dynQ6Kglwk6I3F9hamPLviVBL4EzCpnfv6jOajwHdfA7-6Kt4UVkCZcNzpoGmki_uOtDeZlJA4nNbBu61JGGP_8ai9GcEP-aJsVWBIzx2NQlZGZFX5oIUX0--Ki8lzGR8o_impUtOxQCtcrpl1EnLfejDjSoe9uF&b64e=1&sign=3457abd703bd25570bb9c1f6c278186b&keyno=1',
                                    similar_offers_info: [],
                                    shop_rating: '4.63',
                                },
                            ],
                            money_id: 'yeV_ZICAjIj9e6d2ejvBxQ',
                            street: 'Люблинская',
                            city: 'Москва',
                            category_id: '12785133',
                            cluster_id: null,
                            shop_id: '600920',
                            description:
                                'Новый вид универсального эспандера, используемого в специальных упражнениях для тренировки различных групп мышц. Для функционального тренинга высокого уровня.',
                            shop_url: 'https://lishop.by/catalog/fitnes_i_gimnastika/fitnes/espander/302063/',
                            image_width: '250',
                            offers: ['yeV_ZICAjIj9e6d2ejvBxQ'],
                            source: '2',
                            telephone_country_code: '7',
                            call_url:
                                '//market-click2.yandex.ru/redir/GAkkM7lQwz7vv7M_pnW8mce9ppMxJH_zILDWP4-k0jFYZGXddxtBnHLtLRYeXZa7ob1p9mGF1J8U0xvc97nSKHAyz1VB4gEHRLK4C-kSUc9EKJfLhP83lTWwT3CNycDL6q_9Vj4LMQkTdijJKHDRSVman3G7rxNmiE4AgMr4IGl_ZEFyzmoFOvW8StpSYUi-Fsh6TSjGx1hQr7djMwdvWkbhBI_Guy2cdp_fMMmg30nuhjWqFx4JyRjqpSmgP-tpHaMR4jeAKTLJ64ApkBlstsyncT-jJwsqP44fmTZ3d3s7G6tijjL0M8o--0vkGsSrAlS881P6IXF6Ri9hVebm6YEQVgAScPoKfEj0IOFxX0p2gorVCTR2PxRlB4yFSMGx7UqgDMyMwelPhs1sVbsZQokSm1vUwDDdO7oL7SjcyPozvYhzfq2yHCPbpPlFscdP9BTiNhuJVT1P9mUyCXJjnbwYIj4Ryx1HS7Er9bv-OLLIPIkLTCN5V68oHZGRE034lB_rXSLDuZUqfJP5mINbvoQsuuDxIHRSjMDaegB00nB-N9VIw-RvGtCr6fxYjtKEfqsig_NHo6sO7bav36Hfl0zgala9yfcpPxVvC5vmaAXT3L6wlD5nGHuPxYYCk2VimZNIAKAhpDIUyI6ptz7cP3IVq24sbMxjmKcIpbz39lsYqr9m0ljoov6Q5I-ktKm4nqHk1ZgukBDQhwnRyZ2dOGwX0DOfAQDebNPa3XesHJdTTffqJblmW505T2asavhzhMJ3WFqcmXKcp-Q2JbQGf1f1xoukoawLoto0Z9mtU4YUsoRo-mNNcjEFF0GZXCPiCA3H1UQSrSCGi8JUOxYGVGTLL29JuXPOGRSDt022XNMXTCb-uPVhr7InBxus90SiIPf8WeGgkkcZYfXG0UwByR_dh8Yl-XKKPWZTUSMzPQjOAHjsRp2zdZ1eG8764zBZQ1j6itwhSH9gFN6R8hM0ykSnvMEpzhL6wJRhzJ39KD_wcKOE0h8lSEGhCBVxI3HfNvJ_89qLSsSVdhae_2U0xHuV57arm2ZwmXA7TLFhwpLIEFYDHZvSRueODCYNVZyW2Fy51KPkbD7u1kknDO1X9Q,,?data=41WTYndNxdlaG-5xTfn6okY8p8Pwg5ELyADQ33z3ZnQsN0ihxi6gLm7SxkrSQC0mWT8uQU__21AevOLog3r7Pn8QdMUWCR5FvjoH4KdaQZhWQw7qPT8cuRA8vnAcoMMEo6kVXlk20DqgrhvqskLZXh2aXVXakuRe7d51KJK_PSxgCnPti-v31g,,&b64e=1&sign=8f8ef1a3024749fcca80c3d55c22fa22&keyno=1',
                            is_new: false,
                            title: 'Петля Body Form BF-RL70-208 см 32-80 кг',
                            price: '2784',
                            shop_domain: 'lishop.by',
                            working_days_till: '1',
                            telephone_number: '5115067',
                            confidence: '1',
                            house_number: '126',
                            image_height: '250',
                            url:
                                '//market-click2.yandex.ru/redir/GAkkM7lQwz7vv7M_pnW8mce9ppMxJH_zILDWP4-k0jFYZGXddxtBnHLtLRYeXZa7ob1p9mGF1J8U0xvc97nSKHAyz1VB4gEHRLK4C-kSUc9EKJfLhP83lTWwT3CNycDL6q_9Vj4LMQkTdijJKHDRSVman3G7rxNmiE4AgMr4IGl_ZEFyzmoFOvW8StpSYUi-Fsh6TSjGx1hQr7djMwdvWkbhBI_Guy2cdp_fMMmg30nuhjWqFx4JyeDEe4Q1Cj6Fbij1fQgZgbOnEY81f6HKtqLz2SCWWKVXSr2oa5RhgQGcz1_xMzfwUeAaxRJgYvdDZYDiFORZuZXi59ulOpfvy1ZenrXlDTJr_l3MtxSF5XKmqV5_Uy9c0m-VNe4AUniNdyhZ7af_9GGRYkYw1NOZVNHw3fWQ2qa1hWNZTkgySNeoClZ7rLfzGakgusa4l5hqUw3toASg6sXZDU2NBStrVdPgnF8GhzFqUkocfM0pCAnzUjKn1DarBM3XmkFyqNQ6-g9e_TQIC9D8HQUwfiMJC4oFELfVnb1WvfXf9zQWFDBbSHvJCc-uTT47osXkn91g2mDXggDRnebQQGrOixXyci3_KuR0hb6r_q3vtzyGy50JzS7JmmJdC5cURGjJMIKWA5xAcvh_-tDk9qWRiojgjGGBveHTfAc71WfD2OiVWOm4zX21n9DelCh3xeFuKOca0kJVlBDRoh6JjvWqOtEToqGrpuNB677QHzz3oAANgjykBcrBR2w-gnub0BmsIP7K0FW3TwipRJauuPxOITLLySD2ZQUFemkdlpFu0SazOvu9bhBGODWsvPEvmdBSS6_32dumJzM9J_iMvEiiv5wSvjnooLNSm3VrwCr9TeGaQ9O8czTqllAVnrIB7Z_KRfdWupKuB9QjFrMLjA0IHeSf3v5bp3XYGrBFKsEoeYo_xNKIDJ0ioWAhNGAWjUfevfFStEQbyPp5YoTOhu4bZiqbFzRwlMqyrpZbHCxAEzoLh99OBkofDwtBC3gf2AEXj7C54bg8MaFUufQj6L2tHnqRSBXZf0PyqzC0ZtPMfqnaWqUDdSfm0QBwV6UBMmKNS1LHfxiG5b4WrbZvRy4MlrVAig,,?data=QVyKqSPyGQwNvdoowNEPjSyYvWrLOawK0NSxG2Iu01RLSU7mQxzZSqVAAGUl6-H0dynQ6Kglwk6I3F9hamPLviVBL4EzCpnfv6jOajwHdfA7-6Kt4UVkCZcNzpoGmki_uOtDeZlJA4nNbBu61JGGP_8ai9GcEP-aJsVWBIzx2NQlZGZFX5oIUX0--Ki8lzGR8o_impUtOxQCtcrpl1EnLfejDjSoe9uF&b64e=1&sign=3457abd703bd25570bb9c1f6c278186b&keyno=1',
                            similar_offers_info: [],
                            shop_rating: '4.63',
                        }),
                    },
                },
            ],
        },
        reqId: '12345',
        status: 'success',
    },
};
