--liquibase formatted sql

--changeset zaharov-i:VNDMARKET-620_remove_test_requests_from_prod endDelimiter:///
begin
  DELETE FROM VENDORS.BRAND_EDITOR_BRAND WHERE REQUEST_ID = 457;
  DELETE FROM VENDORS.BRAND_EDITOR_FIELD_DATA WHERE REQUEST_ID = 457;
  DELETE FROM VENDORS.BRAND_EDITOR_LOGO WHERE REQUEST_ID = 457;
  DELETE FROM VENDORS.BRAND_EDITOR_REQUEST WHERE ID = 457;
end;
///
