/* eslint-disable max-len */

'use strict';

module.exports = expect.objectContaining({
    model: {
        name: 'Apple iPhone SE 64GB',
        reviewsCount: 95,

        rating: 4.5,
        gradeCount: 163,
        prices: {
            max: 33990,
            min: 24450,
            avg: 26790,
            curCode: 'RUR',
            curName: 'руб.',
        },
        offersCount: 19,
        mainPhoto: {
            url: expect.any(String),
            width: expect.any(Number),
            height: expect.any(Number),
        },
        isNew: false,
        photo: expect.any(String),
        urls: {
            model: '<wrapped url>',
            modelPicture: '<wrapped url>',
            offers: '<wrapped url>',
            map: '<wrapped url>',
            price: '<wrapped url>',
            reviews: '<wrapped url>',
            reviewsBadge: '<wrapped url>',
        },
        links: {
            constants: {
                allPrices: 'Все цены',
                allPricesMarket: 'Все цены на Яндекс.Маркете',
                closestShops: 'Магазины рядом',
                shopsOnMap: 'Предложения магазинов на карте',
                reviews: 'Отзывы',
                reviewsMarket: 'Отзывы на Яндекс.Маркете',
            },
        },
        info: {
            constants: {
                atMarket: 'на Яндекс.Маркете',
                avgPrice: 'Средняя цена',
                avgPriceGraph: 'График средней цены на',
                ratingTooltipText: 'Рейтинг товара %s из 5',
            },
        },
    },
    feedback: {
        constants: {
            closeButtonText: 'Закрыть',
            error: 'Комментарий не может быть пустым.',
            placeholder:
                'Пожалуйста, расскажите, что именно случилось. Ваш комментарий поможет нам исправить проблему быстрее.',
            submitButtonText: 'Отправить',
            text: 'Ваше сообщение поможет улучшить Советника',
            thanks: 'Спасибо!',
            title: 'Спасибо, мы получили ваш отчёт об ошибке',
        },
    },
    offers: [
        {
            offerSurfaceUrl: '<wrapped url>',
            deliverySis: expect.any(Object),
            name: 'Смартфон Apple iPhone SE 64Gb Silver (A1723)',
            price: {
                value: 24390,
                currencyCode: 'RUR',
                currencyName: 'руб.',
            },
            category: {
                id: 91491,
                name: 'Мобильные телефоны',
                fullName: 'Мобильные телефоны',
                type: 'GURU',
                childCount: 0,
                advertisingModel: 'CPA',
                viewType: 'GRID',
            },
            target: 'pricebar',
            shopInfo: {
                name: 'NaviToys.Ru',
                id: 29295,
                rating: 5,
                gradeTotal: 1303,
                url: '<wrapped url>',
            },
            delivery: {
                free: false,
                pickup: true,
                brief: 'в Москву — 290 руб., возможен самовывоз',
                price: {
                    value: '290',
                    currencyCode: 'RUR',
                    currencyName: 'руб.',
                },
                delivery: true,
                daysFrom: 0,
                daysTo: 2,
                cityFrom: 'Москвы',
                cityTo: 'Москву',
            },
            photo: 'https://avatars.mds.yandex.net/get-marketpic/165430/market_RnSRR1-VOgfW6hZ7abwsFQ/orig',
            source: 'Market',
            bigPhoto: {
                width: 1200,
                height: 1200,
                url: 'https://avatars.mds.yandex.net/get-marketpic/165430/market_RnSRR1-VOgfW6hZ7abwsFQ/orig',
            },
            id:
                'yDpJekrrgZH_gNmuUF13OJCXvhy6Q_LReOEnrsb5pkXjiqiKtO9xfoMjCSLpwAHrQOyGD2dNZJOR7_aXw11qOMn-iGpaL5is6cTrgpKYvuF4fovuEpWBaelg8vgH83bF0c1qUFF7Z7JWgrwiSHWpkvq-Vrz6f9uEmoSK31dnhJg8epeIR-9iZYMeKMbdtLQbs9aWdcCf3Z46xpxCANRg1mDyAdl80OgM4kT7a0J2ypXkQBGnqFoq8jpdwSmGVWu9R-BG-8Rjg7GjfjFBIBL7ugisSogVLVhjKMQ5RvO2xPw',
            url: '<wrapped url>',
            optOutUrl: '<wrapped url>',
            buttonUrl: '<wrapped url>',
            surfaceUrl: '<wrapped url>',
            constants: {
                buttonText: 'В магазин',
                shopInfoTooltip: 'Перейти в магазин',
                shopRatingText: 'Рейтинг %s из 5 на основе',
                shopRatingDefaultText: 'оценки службы контроля качества Яндекс.Маркета',
            },
            warning: undefined,
        },
        {
            offerSurfaceUrl: '<wrapped url>',
            deliverySis: expect.any(Object),
            name: 'Мобильный телефон Apple iPhone SE 64Gb Rose Gold',
            price: {
                value: 24480,
                currencyCode: 'RUR',
                currencyName: 'руб.',
            },
            category: {
                id: 91491,
                name: 'Мобильные телефоны',
                fullName: 'Мобильные телефоны',
                type: 'GURU',
                childCount: 0,
                advertisingModel: 'CPA',
                viewType: 'GRID',
            },
            target: 'price-list',
            shopInfo: {
                name: 'Mobilfunk.ru',
                id: 38615,
                rating: 5,
                gradeTotal: 3879,
                url: '<wrapped url>',
            },
            delivery: {
                free: false,
                pickup: true,
                brief: 'в Москву — 390 руб., возможен самовывоз',
                price: {
                    value: '390',
                    currencyCode: 'RUR',
                    currencyName: 'руб.',
                },
                delivery: true,
                daysFrom: 1,
                daysTo: 2,
                cityFrom: 'Москвы',
                cityTo: 'Москву',
            },
            photo: expect.any(String),
            source: 'Market',
            bigPhoto: {
                width: 484,
                height: 484,
                url: 'https://avatars.mds.yandex.net/get-marketpic/250456/market_TG0s89BbigdbzxuQqRT-rw/orig',
            },
            id:
                'yDpJekrrgZHJZHjgW5L1MMm0U6iRYwm-lR4Fpt3UVOyMfe08lw3q1vfjfyxhbHlY6GD_vlBYHgVjdNt6WyxzdZltN01mQjwAfBAhzwdGAJezYOaRVNG9f53nOCbwkPwwQqXUR3vOEP3hhb5V_5Q1wfYMfQAA1oSGgMcxGJ8ybBfy7KAUlTJW0a6Q0SBwuYbuiRgndSt55xMilxM0JhGSn2KtF75xIxcgy6fXxpqbmaWae3DEhtStPelHdIhEyOCUo7j3El-u3jc98UIcd4OUXbjlL0tUNOGbzT-K1VMZL1U',
            url: '<wrapped url>',
            buttonUrl: '<wrapped url>',
            constants: {
                buttonText: 'В магазин',
                shopInfoTooltip: 'Перейти в магазин',
                shopRatingText: 'Рейтинг %s из 5 на основе',
                shopRatingDefaultText: 'оценки службы контроля качества Яндекс.Маркета',
            },
            warning: undefined,
        },
        {
            offerSurfaceUrl: '<wrapped url>',
            deliverySis: expect.any(Object),
            name: 'Мобильный телефон Apple iPhone SE 64Gb Gold',
            price: {
                value: 24480,
                currencyCode: 'RUR',
                currencyName: 'руб.',
            },
            category: {
                id: 91491,
                name: 'Мобильные телефоны',
                fullName: 'Мобильные телефоны',
                type: 'GURU',
                childCount: 0,
                advertisingModel: 'CPA',
                viewType: 'GRID',
            },
            target: 'price-list',
            shopInfo: {
                name: 'Mobilfunk.ru',
                id: 38615,
                rating: 5,
                gradeTotal: 3879,
                url: '<wrapped url>',
            },
            delivery: {
                free: false,
                pickup: true,
                brief: 'в Москву — 390 руб., возможен самовывоз',
                price: {
                    value: '390',
                    currencyCode: 'RUR',
                    currencyName: 'руб.',
                },
                delivery: true,
                daysFrom: 1,
                daysTo: 2,
                cityFrom: 'Москвы',
                cityTo: 'Москву',
            },
            photo: 'https://avatars.mds.yandex.net/get-marketpic/331110/market_X1iWnCeN6lBRRnRoxyb-sw/orig',
            source: 'Market',
            bigPhoto: {
                width: 320,
                height: 320,
                url: 'https://avatars.mds.yandex.net/get-marketpic/331110/market_X1iWnCeN6lBRRnRoxyb-sw/orig',
            },
            id:
                'yDpJekrrgZHhpLQrPyL817Y7bVCuPkC-pnxnPrx7uZfjmHhHvhA79PtYqkp4J6rWK_IzauKFwA72JnEjRUORzO4t9LiwTXY2G6BM660Z0GFgLmekAIEvlFobbdCiIJHYvtDsQR1CVTW2o-qnmGQeYst1xvtAEJLl8a7msvKXzbUV7gvKr-tAcEnkxtfIgqnvqZsh6lyeJ0i_DMwr3DWWYSeIMcIBOMJsfkKnSoa6NYm4nsb1Tb8qJCJ9bJqbK3mY2Il3njPL6N2lUI1LIe8ikLEnLJtCnC8MP3lzK5pzMjI',
            url: '<wrapped url>',
            buttonUrl: '<wrapped url>',
            constants: {
                buttonText: 'В магазин',
                shopInfoTooltip: 'Перейти в магазин',
                shopRatingText: 'Рейтинг %s из 5 на основе',
                shopRatingDefaultText: 'оценки службы контроля качества Яндекс.Маркета',
            },
            warning: undefined,
        },
        {
            offerSurfaceUrl: '<wrapped url>',
            deliverySis: expect.any(Object),
            name: 'Мобильный телефон Apple iPhone SE 64Gb Silver',
            price: {
                value: 24480,
                currencyCode: 'RUR',
                currencyName: 'руб.',
            },
            category: {
                id: 91491,
                name: 'Мобильные телефоны',
                fullName: 'Мобильные телефоны',
                type: 'GURU',
                childCount: 0,
                advertisingModel: 'CPA',
                viewType: 'GRID',
            },
            target: 'price-list',
            shopInfo: {
                name: 'Mobilfunk.ru',
                id: 38615,
                rating: 5,
                gradeTotal: 3879,
                url: '<wrapped url>',
            },
            delivery: {
                free: false,
                pickup: true,
                brief: 'в Москву — 390 руб., возможен самовывоз',
                price: {
                    value: '390',
                    currencyCode: 'RUR',
                    currencyName: 'руб.',
                },
                delivery: true,
                daysFrom: 1,
                daysTo: 2,
                cityFrom: 'Москвы',
                cityTo: 'Москву',
            },
            photo: 'https://avatars.mds.yandex.net/get-marketpic/219360/market_vnoByxgUVlNHap-edJkRFg/orig',
            source: 'Market',
            bigPhoto: {
                width: 330,
                height: 316,
                url: 'https://avatars.mds.yandex.net/get-marketpic/219360/market_vnoByxgUVlNHap-edJkRFg/orig',
            },
            id:
                'yDpJekrrgZEH3k02tkFS08MHx6tQtvdcxRGD2Uigyn1OAx0ZlWQbD8xMVDkebSTvRKWqQxuuAuJpRuIVE9aTWZB10pnVIP47_aTF3_HxOjl6n0GzOPsronGCGAVLclS3LKsz_-4Y1pca6SGEBpYE8Mg8EII49nKVcI1-hgEmDK-mq4QOGivp2wwAiIN6Nt6sP6tiSmM_GlshN4ip0mvCmFktoROoIcBx-JLCf4swPrWneurd00w-WSByDrrQQW1VWXLeyptXKR03eubcwWd9eCPLABLHlRdCzEXEio1JFK8',
            url: '<wrapped url>',
            buttonUrl: '<wrapped url>',
            constants: {
                buttonText: 'В магазин',
                shopInfoTooltip: 'Перейти в магазин',
                shopRatingText: 'Рейтинг %s из 5 на основе',
                shopRatingDefaultText: 'оценки службы контроля качества Яндекс.Маркета',
            },
            warning: undefined,
        },
        {
            offerSurfaceUrl: '<wrapped url>',
            deliverySis: expect.any(Object),
            name: 'Apple iPhone SE 64Gb Silver',
            price: {
                value: 33990,
                currencyCode: 'RUR',
                currencyName: 'руб.',
            },
            category: {
                id: 91491,
                name: 'Мобильные телефоны',
                fullName: 'Мобильные телефоны',
                type: 'GURU',
                childCount: 0,
                advertisingModel: 'CPA',
                viewType: 'GRID',
            },
            target: 'price-list',
            shopInfo: {
                name: 'ФОТОТЕХНИКА',
                id: 955,
                rating: 5,
                gradeTotal: 2722,
                url: '<wrapped url>',
            },
            delivery: {
                free: false,
                pickup: true,
                brief: 'в Москву — 399 руб., возможен самовывоз',
                price: {
                    value: '399',
                    currencyCode: 'RUR',
                    currencyName: 'руб.',
                },
                delivery: true,
                daysFrom: 0,
                daysTo: 2,
                cityFrom: 'Москвы',
                cityTo: 'Москву',
            },
            photo: 'https://avatars.mds.yandex.net/get-marketpic/225310/market_xAD_zcC2eWWdY8bfuIaYTw/orig',
            source: 'Market',
            bigPhoto: {
                width: 300,
                height: 300,
                url: 'https://avatars.mds.yandex.net/get-marketpic/225310/market_xAD_zcC2eWWdY8bfuIaYTw/orig',
            },
            id: 'yDpJekrrgZEsIuDO8TypEkR9xljiJNvRcIav2udWGbIOF0eC16yp_Q',
            url: '<wrapped url>',
            buttonUrl: '<wrapped url>',
            constants: {
                buttonText: 'В магазин',
                shopInfoTooltip: 'Перейти в магазин',
                shopRatingText: 'Рейтинг %s из 5 на основе',
                shopRatingDefaultText: 'оценки службы контроля качества Яндекс.Маркета',
            },
            warning: undefined,
        },
        {
            offerSurfaceUrl: '<wrapped url>',
            deliverySis: expect.any(Object),
            name: 'Apple iPhone SE 64GB Silver',
            price: {
                value: 30500,
                currencyCode: 'RUR',
                currencyName: 'руб.',
            },
            category: {
                id: 91491,
                name: 'Мобильные телефоны',
                fullName: 'Мобильные телефоны',
                type: 'GURU',
                childCount: 0,
                advertisingModel: 'CPA',
                viewType: 'GRID',
            },
            target: 'price-list',
            shopInfo: {
                name: 'MrDroid.ru',
                id: 304604,
                rating: 5,
                gradeTotal: 301,
                url: '<wrapped url>',
            },
            delivery: {
                free: false,
                pickup: true,
                brief: 'в Москву — 350 руб., возможен самовывоз',
                price: {
                    value: '350',
                    currencyCode: 'RUR',
                    currencyName: 'руб.',
                },
                delivery: true,
                daysFrom: 1,
                daysTo: 1,
                cityFrom: 'Москвы',
                cityTo: 'Москву',
            },
            photo: 'https://avatars.mds.yandex.net/get-marketpic/212340/market_hGYpflGs6QSVv_ZJ3Kbc_g/orig',
            source: 'Market',
            bigPhoto: {
                width: 600,
                height: 600,
                url: 'https://avatars.mds.yandex.net/get-marketpic/212340/market_hGYpflGs6QSVv_ZJ3Kbc_g/orig',
            },
            id: 'yDpJekrrgZFNreN8PzivVIULyY87XMrlISSBEswhV_nZhPhoxidxTw',
            url: '<wrapped url>',
            buttonUrl: '<wrapped url>',
            constants: {
                buttonText: 'В магазин',
                shopInfoTooltip: 'Перейти в магазин',
                shopRatingText: 'Рейтинг %s из 5 на основе',
                shopRatingDefaultText: 'оценки службы контроля качества Яндекс.Маркета',
            },
            warning: undefined,
        },
        {
            offerSurfaceUrl: '<wrapped url>',
            deliverySis: expect.any(Object),
            name: 'Смартфон Apple iPhone SE 64Gb Silver (A1723)',
            price: {
                value: 24390,
                currencyCode: 'RUR',
                currencyName: 'руб.',
            },
            category: {
                id: 91491,
                name: 'Мобильные телефоны',
                fullName: 'Мобильные телефоны',
                type: 'GURU',
                childCount: 0,
                advertisingModel: 'CPA',
                viewType: 'GRID',
            },
            target: 'price-list',
            shopInfo: {
                name: 'NaviToys.Ru',
                id: 29295,
                rating: 5,
                gradeTotal: 1303,
                url: '<wrapped url>',
            },
            delivery: {
                free: false,
                pickup: true,
                brief: 'в Москву — 290 руб., возможен самовывоз',
                price: {
                    value: '290',
                    currencyCode: 'RUR',
                    currencyName: 'руб.',
                },
                delivery: true,
                daysFrom: 0,
                daysTo: 2,
                cityFrom: 'Москвы',
                cityTo: 'Москву',
            },
            photo: 'https://avatars.mds.yandex.net/get-marketpic/165430/market_RnSRR1-VOgfW6hZ7abwsFQ/orig',
            source: 'Market',
            bigPhoto: {
                width: 1200,
                height: 1200,
                url: 'https://avatars.mds.yandex.net/get-marketpic/165430/market_RnSRR1-VOgfW6hZ7abwsFQ/orig',
            },
            id:
                'yDpJekrrgZH_gNmuUF13OJCXvhy6Q_LReOEnrsb5pkXjiqiKtO9xfoMjCSLpwAHrQOyGD2dNZJOR7_aXw11qOMn-iGpaL5is6cTrgpKYvuF4fovuEpWBaelg8vgH83bF0c1qUFF7Z7JWgrwiSHWpkvq-Vrz6f9uEmoSK31dnhJg8epeIR-9iZYMeKMbdtLQbs9aWdcCf3Z46xpxCANRg1mDyAdl80OgM4kT7a0J2ypXkQBGnqFoq8jpdwSmGVWu9R-BG-8Rjg7GjfjFBIBL7ugisSogVLVhjKMQ5RvO2xPw',
            url: '<wrapped url>',
            buttonUrl: '<wrapped url>',
            constants: {
                buttonText: 'В магазин',
                shopInfoTooltip: 'Перейти в магазин',
                shopRatingText: 'Рейтинг %s из 5 на основе',
                shopRatingDefaultText: 'оценки службы контроля качества Яндекс.Маркета',
            },
            warning: undefined,
        },
    ],
    bucketInfo: {},
    cbirMinOfferPrice: undefined,
    doNotSearchReason: undefined,
    optOutInfo: undefined,
    rules: undefined,
    searchResult: undefined,
    searchResultCaption: undefined,
    shopInfo: {
        shopName: 'ЭЛЬДОРАДО',
        url: '<wrapped url>',
    },
    notification: {
        title: 'Более выгодная цена - 24 390 руб.',
        text: 'на Apple iPhone SE 64GB\nв магазине NaviToys.Ru',
        link: '%3Cwrapped%20url%3E?target=notification&click_type=paid',
        contextMessage: 'Доставка 290 руб.',
        buttons: [
            {
                title: 'Посмотреть',
                link: '%3Cwrapped%20url%3E?target=notification-button&click_type=paid',
            },
            {
                title: 'Еще предложения',
                link: '%3Cwrapped%20url%3E?target=notification-market-button&click_type=market',
            },
        ],
        showWhen: [
            'parent',
            'display',
            'position',
            'text-change',
            'size',
            'zindex',
            'zindexframe',
            'opacity',
            'transform',
            'node-remove',
            'inline-styles',
            'external-styles',
            'stylesheets',
        ],
        requireInteraction: true,
        duration: 30000,
        hasMedicine: false,
    },
    searchInfo: {
        originalQuery: 'Смартфон Apple iPhone SE 64Gb Silver A1662',
        filteredQuery: 'Смартфон Apple iPhone SE 64Gb Silver A1662',
        convertedPrice: {
            value: 24450,
            currencyCode: 'RUR',
        },
        offersCount: 19,
        category: undefined,
        doNotComparePrice: undefined,
        urls: {
            shopsInfo: '<wrapped url>',
            market: '<wrapped url>',
            search:
                'https://market.yandex.ru/search.xml?text=%D0%A1%D0%BC%D0%B0%D1%80%D1%82%D1%84%D0%BE%D0%BD%20Apple%20iPhone%20SE%2064Gb%20Silver%20A1662&clid=2210590&distr_type=4&utm_source=sovetnik&utm_medium=cpc&utm_campaign=offer-title&cvredirect=2&req_id=jbr1dm5pf3qyrqv1s3onqjxlss1o0au7',
            searchButton: '<wrapped url>',
            prices: '<wrapped url>',
            eula: '<wrapped url>',
            feedback: '<wrapped url>',
            help: '<wrapped url>',
            helpPhone: '<wrapped url>',
            helpTablet: '<wrapped url>',
            disable: '<wrapped url>',
            features: '<wrapped url>',
            userHelp: '<wrapped url>',
        },
        categories: [
            {
                id: expect.any(Number),
                name: 'Мобильные телефоны',
                rank: expect.any(Number),
                url: '<wrapped url>',
            },
            {
                id: expect.any(Number),
                name: 'Чехлы',
                rank: expect.any(Number),
                url: '<wrapped url>',
            },
            {
                id: expect.any(Number),
                name: expect.any(String),
                rank: expect.any(Number),
                url: '<wrapped url>',
            },
        ],
    },
    pricebar: {
        constants: {
            infoButtonTooltip: 'О программе',
            settingsButtonTooltip: 'Настройки',
            closeButtonTooltip: 'Закрыть',
            prevText: 'Более выгодная цена на',
            inShopText: 'в магазине',
            goButtonText: 'Посмотреть',
            goButtonTooltip: 'Посмотреть',
            moreButtonText: 'Еще предложения',
            moreButtonTooltip: 'Предложения других магазинов',
        },
    },
    tabs: {
        constants: {
            offers: 'Предложения магазинов',
        },
    },
    settings: {
        autoShowShopList: true,
        applicationName: 'Яндекс.Советник',
        isMbrApplication: true,
        constants: {
            yourRegion: 'Ваш регион:',
            changeRegion: 'Изменить регион',
            changeSettings: 'Изменить настройки',
            disable: 'Выключить на этом сайте',
        },
        items: [
            {
                title: 'Показывать предложения из других регионов',
                enabled: true,
            },
            {
                title: 'Показывать список предложений при наведении мыши',
                enabled: true,
            },
        ],
        region: 'Автоматически',
        needShowNotifications: true,
        showProductNotifications: true,
        showAviaNotifications: true,
        showAutoNotifications: true,
    },
    info: {
        constants: {
            text: 'Это приложение подсказывает вам более выгодные цены на товары, на которые вы смотрите прямо сейчас.',
            helpText: 'Помощь',
            feedbackText: 'Обратная связь',
            yandexLLC: '© %s ООО «Яндекс.Маркет»',
            licenseText: 'Лицензионное соглашение',
            disableText: 'Как отключить Советника',
            featuresText: 'Что ещё умеет Советник',
            upperLine: 'Яндекс.Советник',
            prefix: 'для ',
        },
    },
    footer: {
        constants: {
            changeRegion: 'Изменить регион',
            changeCurrentRegion: 'Изменить текущий регион',
            autoDetectedRegion: 'Автоматически',
            infoAboutShop: 'Информация о продавцах',
            infoAboutShopLegal: 'Юридическая информация о продавцах',
            feedback: 'Сообщить об ошибке',
            gotoMarket: 'Перейти на Яндекс.Маркет',
            wrongProductDetect: 'Неверно определен товар',
            data: {
                prefix: 'Данные',
                letter: 'Я',
                suffix: 'ндекс.Маркета',
            },
        },
    },
});
