// константа из kadavrique
export const FREE_DELIVERY_THRESHOLD = 2499;
export const DELIVERY_PRICE = 99;

export const OFFER_PRICE_TRESHOLD_EXCEED = FREE_DELIVERY_THRESHOLD + 10;
export const OFFER_PRICE_TRESHOLD_UNREACHED = FREE_DELIVERY_THRESHOLD - 10;
export const OFFER_PICE_LEFT = FREE_DELIVERY_THRESHOLD - OFFER_PRICE_TRESHOLD_UNREACHED;
