create schema if not exists wmwhse1;

create table if not exists wmwhse1.LOGISTIC_UNIT
(
    SERIALKEY int,
    WHSEID nvarchar(30),
    RECEIPTKEY nvarchar(10) not null,
    STORERKEY nvarchar(15) default '' not null,
    SKU nvarchar(50) null,
    EXTERN_ORDER_KEY nvarchar(50),
    EXTERN_RECEIPT_KEY nvarchar(50),
    REGISTER_KEY nvarchar(50),
    UNIT_KEY nvarchar(50) not null,
    PARENT_UNIT_KEY nvarchar(50),
    TYPE nvarchar(10) not null,
    STATUS nvarchar(50) not null,
    COUNT decimal(22, 5) default 0 not null,
    MAX_RECEIPT_DATE datetime,
    BOXES_IN_ORDER decimal(10),
    SHOULD_BE_RECEIPT bit,
    ADDDATE datetime not null,
    ADDWHO nvarchar(256) not null,
    EDITDATE datetime not null,
    EDITWHO nvarchar(256) not null,
    STOCKTYPE nvarchar(50),
    primary key (SERIALKEY),
    constraint order_key_unit_key_unique_constraint unique (EXTERN_ORDER_KEY, UNIT_KEY)
);

create table if not exists wmwhse1.ORDERS
(
    SERIALKEY int auto_increment,
    WHSEID nvarchar(30) default 'test',
    ORDERKEY nvarchar(10) not null primary key,
    ORIGINORDERKEY nvarchar(max),
    STORERKEY nvarchar(15) default '' not null,
    EXTERNORDERKEY nvarchar(32) default '' not null,
    ORDERDATE datetime default now() not null,
    DELIVERYDATE datetime,
    PRIORITY nvarchar(10) default '5' not null,
    CONSIGNEEKEY nvarchar(15) default '' not null,
    C_CONTACT1 nvarchar(30),
    C_CONTACT2 nvarchar(30),
    C_COMPANY nvarchar(45),
    C_ADDRESS1 nvarchar(45),
    C_ADDRESS2 nvarchar(45),
    C_ADDRESS3 nvarchar(45),
    C_ADDRESS4 nvarchar(45),
    C_CITY nvarchar(100),
    C_STATE nvarchar(100),
    C_ZIP nvarchar(18),
    C_COUNTRY nvarchar(30),
    C_ISOCNTRYCODE nvarchar(10),
    C_PHONE1 nvarchar(18),
    C_PHONE2 nvarchar(18),
    C_FAX1 nvarchar(18),
    C_FAX2 nvarchar(18),
    C_VAT nvarchar(18),
    BUYERPO nvarchar(50),
    BILLTOKEY nvarchar(15) default '' not null,
    B_CONTACT1 nvarchar(30),
    B_CONTACT2 nvarchar(30),
    B_COMPANY nvarchar(45),
    B_ADDRESS1 nvarchar(45),
    B_ADDRESS2 nvarchar(45),
    B_ADDRESS3 nvarchar(45),
    B_ADDRESS4 nvarchar(45),
    B_CITY nvarchar(45),
    B_STATE nvarchar(25),
    B_ZIP nvarchar(18),
    B_COUNTRY nvarchar(30),
    B_ISOCNTRYCODE nvarchar(10),
    B_PHONE1 nvarchar(18),
    B_PHONE2 nvarchar(18),
    B_FAX1 nvarchar(18),
    B_FAX2 nvarchar(18),
    B_VAT nvarchar(18),
    INCOTERM nvarchar(10),
    PMTTERM nvarchar(10),
    DOOR nvarchar(10) default '' not null,
    SORTATIONLOCATION nvarchar(18),
    BATCHFLAG nvarchar(1) default '0' not null,
    BULKCARTONGROUP nvarchar(10),
    ROUTE nvarchar(10) default '' not null,
    STOP int,
    OPENQTY decimal(22,5) default 0,
    STATUS nvarchar(10) default '02' not null,
    DISCHARGEPLACE nvarchar(30),
    DELIVERYPLACE nvarchar(30),
    INTERMODALVEHICLE nvarchar(30) default '' not null,
    COUNTRYOFORIGIN nvarchar(30),
    COUNTRYDESTINATION nvarchar(30),
    UPDATESOURCE nvarchar(10) default '0' not null,
    TYPE nvarchar(10) default '0' not null,
    ORDERGROUP nvarchar(20) default '' not null,
    EFFECTIVEDATE datetime,
    STAGE nvarchar(10) default '',
    DC_ID nvarchar(10) default '',
    WHSE_ID nvarchar(10) default '',
    SPLIT_ORDERS nvarchar(1) default '0',
    APPT_STATUS nvarchar(10),
    CHEPPALLETINDICATOR nvarchar(10),
    CONTAINERTYPE nvarchar(20),
    CONTAINERQTY decimal(22,5),
    BILLEDCONTAINERQTY decimal(22,5),
    TRANSPORTATIONMODE nvarchar(30),
    TRANSPORTATIONSERVICE nvarchar(30),
    EXTERNALORDERKEY2 nvarchar(32),
    C_EMAIL1 nvarchar(55),
    C_EMAIL2 nvarchar(55),
    SUSR1 nvarchar(30),
    SUSR2 nvarchar(30),
    SUSR3 nvarchar(30),
    SUSR4 nvarchar(30),
    SUSR5 nvarchar(30),
    NOTES2 nvarchar(2000),
    ITEM_NUMBER decimal(28) default 0,
    FORTE_FLAG nvarchar(6) default 'I' not null,
    LOADID nvarchar(20),
    SHIPTOGETHER nvarchar(1) default 'N' not null,
    DELIVERYDATE2 datetime,
    REQUESTEDSHIPDATE datetime,
    ACTUALSHIPDATE datetime,
    DELIVER_DATE datetime,
    ORDERVALUE decimal(10,2) default 0 not null,
    OHTYPE nvarchar(10) default '1',
    EXTERNALLOADID nvarchar(20) default '',
    DESTINATIONNESTID int,
    REFERENCENUM nvarchar(30),
    INTRANSITKEY nvarchar(10),
    RECEIPTKEY nvarchar(10),
    CaseLabelType nvarchar(10),
    LABELNAME nvarchar(20),
    STDSSCCLABELNAME nvarchar(20),
    STDGTINLABELNAME nvarchar(20),
    RFIDSSCCLABELNAME nvarchar(20),
    RFIDGTINLABELNAME nvarchar(20),
    RFIDFLAG nvarchar(1) default '0' not null,
    CarrierCode nvarchar(15),
    CarrierName nvarchar(45),
    CarrierAddress1 nvarchar(45),
    CarrierAddress2 nvarchar(45),
    CarrierCity nvarchar(45),
    CarrierState nvarchar(25),
    CarrierZip nvarchar(18),
    CarrierCountry nvarchar(30),
    CarrierPhone nvarchar(18),
    DriverName nvarchar(25),
    TrailerNumber nvarchar(20),
    TrailerOwner nvarchar(25),
    TrailerType nvarchar(10),
    DepDateTime datetime,
    ORDERBREAK nvarchar(1),
    ALLOCATEDONERP nvarchar(1) default '0' not null,
    TRADINGPARTNER nvarchar(30),
    PRONUMBER nvarchar(32),
    ENABLEPACKING nvarchar(1) default '0',
    PACKINGLOCATION nvarchar(10),
    ORDERSID nvarchar(32),
    SUSPENDEDINDICATOR nvarchar(1) default '0',
    PICKLISTREPORTID nvarchar(8),
    PACKINGLISTREPORTID nvarchar(8),
    SOURCEVERSION nvarchar(22),
    REFERENCETYPE nvarchar(64),
    REFERENCEDOCUMENT nvarchar(64),
    REFERENCELOCATION nvarchar(64),
    REFERENCEVERSION nvarchar(20),
    FREIGHTCHARGEAMOUNT decimal(22,5),
    FREIGHTCOSTAMOUNT decimal(22,5),
    APPOINTMENTKEY nvarchar(10),
    AllowOverPick int default 0,
    TOTALQTY decimal(22,5) default 0,
    TOTALGROSSWGT decimal(22,5) default 0,
    TOTALCUBE decimal(22,5) default 0,
    TOTALORDERLINES int default 0,
    ReferenceAccountingEntity nvarchar(64),
    POKEY nvarchar(50),
    APPORTION nvarchar(1) default '0' not null,
    CONTAINERID nvarchar(18),
    PROMISEDSHIPDATE datetime,
    PLANNEDSHIPDATE datetime,
    SCHEDULEDSHIPDATE datetime,
    SHIPMENTDATETIME datetime,
    PROMISEDDELVDATE datetime,
    PLANNEDDELVDATE datetime,
    SCHEDULEDDELVDATE datetime,
    ACTUALDELVDATE datetime,
    EARLIESTSHIPDATE datetime,
    EARLIESTDELIVERYDATE datetime,
    CARRIERROUTEDOCUMENT nvarchar(64),
    CARRIERROUTEACCOUNTINGENTITY nvarchar(64),
    CARRIERROUTELOCATION nvarchar(64),
    CARRIERROUTEVERSION nvarchar(20),
    TMHOUSEAIRWAYBILLNUMBER nvarchar(64),
    TMMASTERAIRWAYBILLNUMBER nvarchar(64),
    TMBOOKINGNUMBER nvarchar(64),
    TMHOUSEOCEANBOLNUMBER nvarchar(64),
    TMMASTEROCEANBOLNUMBER nvarchar(64),
    TMEQUIPMENTNUMBER nvarchar(64),
    TMSEALNUMBER nvarchar(64),
    TMLICENSEPLATENUMBER nvarchar(64),
    TMEQUIPMENTTYPE nvarchar(30),
    TMEQUIPMENTLENGTH nvarchar(10),
    TMEQUIPMENTATTRIBUTE nvarchar(64),
    TMAIRSERVICELEVEL nvarchar(30),
    TMOCEANSERVICELEVEL nvarchar(30),
    TMOCEANTARIFFSERVICE nvarchar(30),
    TMPORTOFLOADING nvarchar(64),
    TMPORTOFDISCHARGE nvarchar(64),
    TMROUTEDVIA nvarchar(64),
    TMSERVICEATTRIBUTE nvarchar(64),
    TMFREIGHTCOSTCURRENCY nvarchar(3),
    TMFREIGHTCHARGECURRENCY nvarchar(3),
    ACTUALARRIVALDATE datetime,
    C_ADDRESS5 nvarchar(45),
    C_ADDRESS6 nvarchar(45),
    B_ADDRESS5 nvarchar(45),
    B_ADDRESS6 nvarchar(45),
    RETURNTOPARTY nvarchar(64),
    TRAILERKEY nvarchar(20),
    CARRIERROUTESTATUS nvarchar(10) default 'NEW',
    SPLITSHIPMENTINDICATOR nvarchar(1) default '0' not null,
    SPLITSHIPMENTORIGINALORDERKEY nvarchar(32),
    SPLITSHIPMENTFINALSHIPMENT nvarchar(1),
    BODAPPLICATIONAREA nvarchar(max),
    FREIGHTCOSTBASEAMOUNT decimal(22,5),
    FREIGHTCHARGEBASEAMOUNT decimal(22,5),
    PACKINGVALTEMPLATE nvarchar(10),
    PACKNOTES nvarchar(255),
    TOTALROUTES decimal(22,5),
    AUTODOORASSIGNED nvarchar(10),
    AUTOSTAGEASSIGNED nvarchar(10),
    AUTOPACKASSIGNED nvarchar(10),
    AUTODOCKASSIGNEDHOW nvarchar(10),
    AUTODOCKASSIGNEDSET nvarchar(20),
    AUTODOCKASSIGNEDSTEP int,
    AUTODOCKASSIGNTIME datetime,
    TOTALPALLETESTIMATE int,
    REQUIREORDERCLOSE nvarchar(1) default '0',
    NOTES nvarchar(2000),
    SPSAPISTRATEGYKEY nvarchar(10),
    BOLNUMBER nvarchar(20),
    BOLPRINTED nvarchar(1) default '0' not null,
    SHIPTOGROUP nvarchar(10),
    BATCHORDERNUMBER nvarchar(10),
    HOSTPROCESSREQUIRED nvarchar(1) default '0' not null,
    ADDDATE datetime default  now() not null,
    ADDWHO nvarchar(256) default 'test' not null,
    EDITDATE datetime default now() not null,
    EDITWHO nvarchar(256) default 'test' not null,
    MAX_ABSENT_ITEMS_PRICE_PERCENT numeric(4,2),
    ROWVERSION int,
    BUILDING int,
    ORDER_FLOW_ID int
    );

create table if not exists wmwhse1.EXTERNORDERKEY_REGISTRY
(
    EXTERNORDERKEY nvarchar(32) NOT NULL PRIMARY KEY,
    ADDDATE        datetime default now() NOT NULL,
    ADDWHO         nvarchar(256) default 'test' not null
    );

