create schema if not exists WMS;

create table if not exists WMS.ITRNSERIAL
(
    SERIALKEY int auto_increment primary key,
    WHSEID nvarchar(30) default 'test',
    ITRNSERIALKEY nvarchar(10) not null unique,
    ITRNKEY nvarchar(10) not null,
    STORERKEY nvarchar(15) default '' not null,
    SKU nvarchar(50) default '' not null,
    LOT nvarchar(10) default '' not null,
    ID nvarchar(50) default '' not null,
    LOC nvarchar(10) default '' not null,
    SERIALNUMBER nvarchar(30) not null,
    QTY decimal(22,5) default 0 not null,
    TRANTYPE nvarchar(30),
    DATA2 nvarchar(30),
    DATA3 nvarchar(30),
    DATA4 nvarchar(30),
    DATA5 nvarchar(30),
    GROSSWEIGHT decimal(22,5) default 0,
    NETWEIGHT decimal(22,5) default 0,
    SERIALNUMBERLONG nvarchar(500),
    ADDDATE datetime default now() not null,
    ADDWHO nvarchar(256) default 'test' not null,
    EDITDATE datetime default now() not null,
    EDITWHO nvarchar(256) default 'test' not null
    );

create table if not exists WMS.ITRN
(
    SERIALKEY        int auto_increment primary key,
    WHSEID            nvarchar(30),
    ITRNKEY           nvarchar(10)   not null,
    ITRNSYSID         int,
    TRANTYPE          nvarchar(10)   not null,
    STORERKEY         nvarchar(15)   not null,
    SKU               nvarchar(50)   not null,
    LOT               nvarchar(10)   not null,
    FROMLOC           nvarchar(10)   not null,
    FROMID            nvarchar(50)   not null,
    TOLOC             nvarchar(10)   not null,
    TOID              nvarchar(50)   not null,
    SOURCEKEY         nvarchar(20),
    SOURCETYPE        nvarchar(30),
    STATUS            nvarchar(10),
    LOTTABLE01        nvarchar(50)   not null,
    LOTTABLE02        nvarchar(50)   not null,
    LOTTABLE03        nvarchar(50)   not null,
    LOTTABLE04        datetime,
    LOTTABLE05        datetime,
    LOTTABLE06        nvarchar(50)   not null,
    LOTTABLE07        nvarchar(50)   not null,
    LOTTABLE08        nvarchar(50)   not null,
    LOTTABLE09        nvarchar(50)   not null,
    LOTTABLE10        nvarchar(50)   not null,
    CASECNT           decimal(22, 5) not null,
    INNERPACK         decimal(22, 5) not null,
    QTY               decimal(22, 5) not null,
    PALLET            decimal(22, 5) not null,
    CUBE              float          not null,
    GROSSWGT          decimal(22, 5) not null,
    NETWGT            decimal(22, 5) not null,
    OTHERUNIT1        float          not null,
    OTHERUNIT2        float          not null,
    PACKKEY           nvarchar(50),
    UOM               nvarchar(10),
    UOMCALC           int,
    UOMQTY            decimal(22, 5),
    EFFECTIVEDATE     datetime       not null,
    RECEIPTKEY        nvarchar(10),
    RECEIPTLINENUMBER nvarchar(10),
    HOLDCODE          nvarchar(10),
    LOTTABLE11        datetime,
    LOTTABLE12        datetime,
    COUNTSEQUENCE     int            not null,
    TAREWGT           decimal(22, 5) not null,
    FINALTOLOC        nvarchar(20),
    INTRANSIT         nvarchar,
    ADDDATE           datetime       not null,
    ADDWHO            nvarchar(256)  not null,
    EDITDATE          datetime       not null,
    EDITWHO           nvarchar(256)  not null
);
