Received: from mxback23g.mail.yandex.net ([127.0.0.1])
	by mxback23g.mail.yandex.net with LMTP id erQQSLpE
	for <nnty3ik@yandex.ru>; Wed, 13 Mar 2019 11:51:15 +0300
Received: from mxback23g.mail.yandex.net (localhost.localdomain [127.0.0.1])
	by mxback23g.mail.yandex.net (Yandex) with ESMTP id F11C916421C7
	for <nnty3ik@yandex.ru>; Wed, 13 Mar 2019 11:51:14 +0300 (MSK)
X-Yandex-Internal: 1
Received: from localhost (localhost [::1])
	by mxback23g.mail.yandex.net (nwsmtp/Yandex) with ESMTP id 3i6t03OCFC-pECSfjgA;
	Wed, 13 Mar 2019 11:51:14 +0300
X-Yandex-Front: mxback23g.mail.yandex.net
X-Yandex-TimeMark: 1552467074.461
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=yandex.ru; s=mail; t=1552467074;
	bh=z7AX19CIVYtbY6qzG3ZHau3r8JOpwYcCPdLzXIl8SCc=;
	h=Message-Id:Date:Subject:To:From;
	b=QJLcI25HCQld5XHAFp3kFfetE7Z4AldZb0b5gKdMOyDS0jZfTH5XelPvBSp5OgVPS
	 TI/F8zlWqA3dhwPRV3QEouGqEqM15kdWPyNNo63UnhFQUFcaKNA7k1lERaZ+uLh6Qf
	 oUMgSSMGb18wvT5g12dao/rFqrQY0YGuyjl0G/Hc=
Authentication-Results: mxback23g.mail.yandex.net; dkim=pass header.i=@yandex.ru
X-Yandex-Spam: 1
X-Yandex-Sender-Uid: 849698168
Received: by iva4-406defa25fee.qloud-c.yandex.net with HTTP;
	Wed, 13 Mar 2019 11:51:14 +0300
From: =?UTF-8?B?0KLQtdGB0YIg0KLQtdGB0YLQvtCy0LjRhw==?= <nnty3ik@yandex.ru>
Envelope-From: nnty3ik@yandex.ru
To: =?UTF-8?B?0KLQtdGB0YIg0KLQtdGB0YLQvtCy0LjRhw==?= <nnty3ik@yandex.ru>
Subject: =?utf-8?B?0KLQtdC80LAg0L/QuNGB0YzQvNCwINC60LjRgNC40LvQu9C40YbQtdC5?=
MIME-Version: 1.0
X-Mailer: Yamail [ http://yandex.ru ] 5.0
Date: Wed, 13 Mar 2019 13:51:14 +0500
Message-Id: <3827481552467074@iva4-406defa25fee.qloud-c.yandex.net>
Content-Transfer-Encoding: 8bit
Content-Type: text/html; charset=utf-8
Return-Path: nnty3ik@yandex.ru
X-YandexSms-Digest: 70931c4d2d05c0e4386415da04f3ecc7

<div xmlns="http://www.w3.org/1999/xhtml">HTML тело письма</div><div xmlns="http://www.w3.org/1999/xhtml">из</div><div xmlns="http://www.w3.org/1999/xhtml">нескольких</div><div xmlns="http://www.w3.org/1999/xhtml">строк</div>
