Received: from mxcorp1g.mail.yandex.net ([127.0.0.1])
	by mxcorp1g.mail.yandex.net with LMTP id GerD7y1x
	for <tesseract@mail.yandex-team.ru>; Wed, 13 Mar 2019 12:46:11 +0300
Received: from mxcorp1g.mail.yandex.net (localhost.localdomain [127.0.0.1])
	by mxcorp1g.mail.yandex.net (Yandex) with ESMTP id B62AC742604
	for <tesseract@mail.yandex-team.ru>; Wed, 13 Mar 2019 12:46:11 +0300 (MSK)
Received: from forward300p.mail.yandex.net (forward300p.mail.yandex.net [77.88.28.104])
	by mxcorp1g.mail.yandex.net (nwsmtp/Yandex) with ESMTPS id 6GU1syHaUs-kB64HHRQ;
	Wed, 13 Mar 2019 12:46:11 +0300
	(using TLSv1.2 with cipher ECDHE-RSA-AES128-GCM-SHA256 (128/128 bits))
	(Client certificate not present)
X-Yandex-Front: mxcorp1g.mail.yandex.net
X-Yandex-TimeMark: 1552470371.353
Authentication-Results: mxcorp1g.mail.yandex.net; spf=pass (mxcorp1g.mail.yandex.net: domain of calendar.yandex-team.ru designates 77.88.28.104 as permitted sender, rule=[ip4:77.88.0.0/18]) smtp.mail=info@calendar.yandex-team.ru; dkim=pass header.i=@yandex-team.ru
X-Spam-Flag: NO
X-Yandex-Fwd: NzA1NDc2NjA3ODYxMzAyNjMwNiwxMDQ0MjU4MTY2MjA0NTM3NjM1
Received: from yaback1p.mail.yandex.net (yaback1p.mail.yandex.net [IPv6:2a02:6b8:0:1472::186])
	by forward300p.mail.yandex.net (Yandex) with ESMTP id 466B2382B77
	for <tesseract@yandex-team.ru>; Wed, 13 Mar 2019 12:46:11 +0300 (MSK)
Received: from calcorp-work1o.cmail.yandex.net (calcorp-work1o.cmail.yandex.net [37.9.109.122])
	by yaback1p.mail.yandex.net (nwsmtp/Yandex) with ESMTP id Fq0Fv9qb0q-kAdOKUat;
	Wed, 13 Mar 2019 12:46:11 +0300
X-Yandex-Local: yes
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=yandex-team.ru; s=default;
	t=1552470371; bh=K0SxUSVCLaT8DNuZH1pwwqejecU6m1ELd4DAmps4XfA=;
	h=Subject:Message-Id:Reply-To:To:From:Date;
	b=gJIwzkDVevsuYTVImBhulMYmr5cEk3U/IOEaQQavkh23gKxBT2mBKKpSQdjBxNk9I
	 xJipkI/9gFiKsq0DW8LaZRjaFmiephI0X/hJGnGKJVaugLN+5wABEauUMkrDHHaOA3
	 rsZ+Saw/svinQkY3IuIkA0gslKNPEnwQKNQQwpeQ=
Date: Wed, 13 Mar 2019 09:46:06 +0000 (UTC)
From: =?utf-8?B?0J/QsNCy0LXQuyDQnNC40YXQtdC10LI=?= <info@calendar.yandex-team.ru>
Reply-To: =?utf-8?B?0J/QsNCy0LXQuyDQnNC40YXQtdC10LI=?= <pm01@yandex-team.ru>
To: tesseract@yandex-team.ru
Message-Id: 1a06901f-fd5f-488c-883d-3be06076b3dc@calendar.yandex-team.ru
Subject: =?utf-8?B?0J7RgtC+0LHRgNCw0LbQtdC90LjQtSDQuNC30LzQtdC90LXQvQ==?=
 =?utf-8?B?0LjQuSDQtNCw0YIg0LTQvtGB0YLQsNCy0LrQuCDQvdCwINCy?=
 =?utf-8?B?0LXQsdC1INCx0LXRgNGDINGB0YDQtdC00YHRgtCy0LDQvNC4IA==?=
 =?utf-8?B?0YLRgNC40LPQs9C10YDQvdC+0Lkg0L/Qu9Cw0YLRhNC+0YDQvNGL?=
MIME-Version: 1.0
Content-Type: multipart/mixed;
	boundary="----=_Part_272688_1971496659.1552470370942"
X-Mailer: Yandex Calendar
X-Calendar-Request-Id: f2e5b2ff47b1d49/1a06901f-fd5f-488c-883d-3be06076b3dc_1o
X-Calendar-Server-Host: calcorp-work1o.cmail.yandex.net
X-Calendar-Action-Source: WEB_MAYA
X-Calendar-Mail-Type: event_invitation
Return-Path: info@calendar.yandex-team.ru
X-Yandex-Forward: cd59ccc28b5bd79ed8e930328c89d9d2

------=_Part_272688_1971496659.1552470370942
Content-Type: multipart/alternative;
	boundary="----=_Part_272689_1359329833.1552470370942"

------=_Part_272689_1359329833.1552470370942
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: quoted-printable

=C2=AB=D0=9E=D1=82=D0=BE=D0=B1=D1=80=D0=B0=D0=B6=D0=B5=D0=BD=D0=B8=D0=B5 =
=D0=B8=D0=B7=D0=BC=D0=B5=D0=BD=D0=B5=D0=BD=D0=B8=D0=B9 =D0=B4=D0=B0=D1=82 =
=D0=B4=D0=BE=D1=81=D1=82=D0=B0=D0=B2=D0=BA=D0=B8 =D0=BD=D0=B0 =D0=B2=D0=B5=
=D0=B1=D0=B5 =D0=B1=D0=B5=D1=80=D1=83 =D1=81=D1=80=D0=B5=D0=B4=D1=81=D1=82=
=D0=B2=D0=B0=D0=BC=D0=B8 =D1=82=D1=80=D0=B8=D0=B3=D0=B3=D0=B5=D1=80=D0=BD=
=D0=BE=D0=B9 =D0=BF=D0=BB=D0=B0=D1=82=D1=84=D0=BE=D1=80=D0=BC=D1=8B=C2=BB
=D0=A1=D0=B5=D0=B3=D0=BE=D0=B4=D0=BD=D1=8F, 13-=D0=B3=D0=BE =D0=BC=D0=B0=D1=
=80=D1=82=D0=B0, =D1=81 20:30 =D0=B4=D0=BE 21:00 (Asia/Yekaterinburg, GMT+0=
5:00)

=D0=9F=D0=BE=D0=B9=D0=B4=D1=83:=C2=A0https://calendar.yandex-team.ru/api/ad=
d-event-invitation?uid=3D1120000000016875&private_token=3D31a9c61efe415ea82=
5514394a2bcaea3d59a6128&event_id=3D35180804&decision=3Dyes&from_mail=3D1
=D0=92=D0=BE=D0=B7=D0=BC=D0=BE=D0=B6=D0=BD=D0=BE,=C2=A0=D0=BF=D0=BE=D0=B9=
=D0=B4=D1=83:=C2=A0https://calendar.yandex-team.ru/api/add-event-invitation=
?uid=3D1120000000016875&private_token=3D31a9c61efe415ea825514394a2bcaea3d59=
a6128&event_id=3D35180804&decision=3Dmaybe&from_mail=3D1
=D0=9D=D0=B5=C2=A0=D0=BF=D0=BE=D0=B9=D0=B4=D1=83:=C2=A0https://calendar.yan=
dex-team.ru/api/add-event-invitation?uid=3D1120000000016875&private_token=
=3D31a9c61efe415ea825514394a2bcaea3d59a6128&event_id=3D35180804&decision=3D=
no

=D0=93=D0=B4=D0=B5:=C2=A011.=D0=9B=D0=B5=D0=BC=D1=83=D1=80=D0=B8=D1=8F (PAL=
LADIUM 11-3), 3. =D0=97=D0=BE=D0=BE=D0=BC=D0=B0=D0=B3=D0=B0=D0=B7=D0=B8=D0=
=BD (ST 3-03), 506M

=D0=9E=D1=80=D0=B3=D0=B0=D0=BD=D0=B8=D0=B7=D0=B0=D1=82=D0=BE=D1=80:=C2=A0=
=D0=9F=D0=B0=D0=B2=D0=B5=D0=BB =D0=9C=D0=B8=D1=85=D0=B5=D0=B5=D0=B2
=D0=9F=D1=80=D0=B8=D0=B3=D0=BB=D0=B0=D1=88=D0=B5=D0=BD=D1=8B:
=C2=A0=C2=A0=D0=94=D0=BC=D0=B8=D1=82=D1=80=D0=B8=D0=B9 =D0=9F=D0=BE=D1=82=
=D0=B0=D0=BF=D0=BE=D0=B2
=C2=A0=C2=A0=D0=9C=D0=B0=D0=BA=D1=81=D0=B8=D0=BC =D0=A8=D0=B0=D0=B1=D0=B0=
=D0=BB=D0=BA=D0=B8=D0=BD
=C2=A0=C2=A0=D0=9D=D0=B8=D0=BA=D0=BE=D0=BB=D0=B0=D0=B9 =D0=A8=D0=B5=D1=81=
=D1=82=D0=B0=D0=BA=D0=BE=D0=B2
=C2=A0=C2=A0=D0=90=D0=BD=D0=B4=D1=80=D0=B5=D0=B9 =D0=98=D0=B2=D0=B0=D0=BD=
=D0=BE=D0=B2
=C2=A0=C2=A0=D0=9D=D0=B8=D0=BA=D0=BE=D0=BB=D0=B0=D0=B9 =D0=9A=D0=BE=D0=BD=
=D0=B4=D1=80=D0=B0=D1=82=D1=8C=D0=B5=D0=B2

=D0=9F=D0=BE=D1=81=D0=BC=D0=BE=D1=82=D1=80=D0=B5=D1=82=D1=8C, =D0=BA=D1=82=
=D0=BE =D0=BF=D0=BE=D0=B9=D0=B4=D1=91=D1=82:
https://calendar.yandex-team.ru/event/?uid=3D1120000000016875&private_token=
=3D31a9c61efe415ea825514394a2bcaea3d59a6128&event_id=3D35180804&show_date=
=3D2019-03-13

--=20
=D0=A3=D0=B2=D0=B5=D0=B4=D0=BE=D0=BC=D0=BB=D0=B5=D0=BD=D0=B8=D0=B5 =D0=BE=
=D1=82=D0=BF=D1=80=D0=B0=D0=B2=D0=BB=D0=B5=D0=BD=D0=BE =D1=87=D0=B5=D1=80=
=D0=B5=D0=B7=C2=A0=D0=AF=D0=BD=D0=B4=D0=B5=D0=BA=D1=81.=D0=9A=D0=B0=D0=BB=
=D0=B5=D0=BD=D0=B4=D0=B0=D1=80=D1=8C (https://calendar.yandex-team.ru?uid=
=3D1120000000016875).=C2=A0=D0=95=D1=81=D0=BB=D0=B8 =D0=B2=D1=8B =D0=BD=D0=
=B5 =D1=85=D0=BE=D1=82=D0=B8=D1=82=D0=B5 =D0=BF=D0=BE=D0=BB=D1=83=D1=87=D0=
=B0=D1=82=D1=8C =D1=82=D0=B0=D0=BA=D0=B8=D0=B5 =D0=BF=D0=B8=D1=81=D1=8C=D0=
=BC=D0=B0,=C2=A0=D0=BE=D1=82=D0=BA=D0=B0=D0=B6=D0=B8=D1=82=D0=B5=D1=81=D1=
=8C =D0=BE=D1=82 =D0=BD=D0=B8=D1=85 (https://calendar.yandex-team.ru/tune?u=
id=3D1120000000016875).=C2=A0=C2=A0=C2=A9=C2=A02007=E2=80=942019=C2=A0=C2=
=AB=D0=AF=D0=BD=D0=B4=D0=B5=D0=BA=D1=81=C2=BB
------=_Part_272689_1359329833.1552470370942
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: quoted-printable

<html><head><meta http-equiv=3D"Content-type" content=3D"text/html; charset=
=3Dutf-8" /></head><body link=3D"#1952ce" alink=3D"red" style=3D"line-heigh=
t: 1.4"><table cellpadding=3D"4" width=3D"100%"><tr><td><font face=3D"Arial=
,sans-serif" size=3D"4">=C2=AB<a href=3D"https://calendar.yandex-team.ru/ev=
ent/?uid=3D1120000000016875&amp;event_id=3D35180804&amp;show_date=3D2019-03=
-13&amp;view_type=3Dweek">=D0=9E=D1=82=D0=BE=D0=B1=D1=80=D0=B0=D0=B6=D0=B5=
=D0=BD=D0=B8=D0=B5 =D0=B8=D0=B7=D0=BC=D0=B5=D0=BD=D0=B5=D0=BD=D0=B8=D0=B9 =
=D0=B4=D0=B0=D1=82 =D0=B4=D0=BE=D1=81=D1=82=D0=B0=D0=B2=D0=BA=D0=B8 =D0=BD=
=D0=B0 =D0=B2=D0=B5=D0=B1=D0=B5 =D0=B1=D0=B5=D1=80=D1=83 =D1=81=D1=80=D0=B5=
=D0=B4=D1=81=D1=82=D0=B2=D0=B0=D0=BC=D0=B8 =D1=82=D1=80=D0=B8=D0=B3=D0=B3=
=D0=B5=D1=80=D0=BD=D0=BE=D0=B9 =D0=BF=D0=BB=D0=B0=D1=82=D1=84=D0=BE=D1=80=
=D0=BC=D1=8B</a>=C2=BB</font><br /></td></tr><tr><td><font face=3D"Arial,sa=
ns-serif" size=3D"3">=D0=A1=D0=B5=D0=B3=D0=BE=D0=B4=D0=BD=D1=8F, 13-=D0=B3=
=D0=BE =D0=BC=D0=B0=D1=80=D1=82=D0=B0, =D1=81 20:30 =D0=B4=D0=BE 21:00 (Asi=
a/Yekaterinburg, GMT+05:00)</font></td></tr></table><table cellpadding=3D"4=
" width=3D"100%"><tr><td bgcolor=3D"#e3eafd"><table cellspacing=3D"0" cellp=
adding=3D"5"><tr><td style=3D"padding: 0 7px 1px"><font size=3D"3" face=3D"=
Arial,sans-serif"><b><a href=3D"https://calendar.yandex-team.ru/api/add-eve=
nt-invitation?uid=3D1120000000016875&amp;private_token=3D31a9c61efe415ea825=
514394a2bcaea3d59a6128&amp;event_id=3D35180804&amp;decision=3Dyes&amp;from_=
mail=3D1">=D0=9F=D0=BE=D0=B9=D0=B4=D1=83</a></b></font></td><td style=3D"pa=
dding: 0 7px 1px"><font size=3D"3" face=3D"Arial,sans-serif"><b><a href=3D"=
https://calendar.yandex-team.ru/api/add-event-invitation?uid=3D112000000001=
6875&amp;private_token=3D31a9c61efe415ea825514394a2bcaea3d59a6128&amp;event=
_id=3D35180804&amp;decision=3Dmaybe&amp;from_mail=3D1">=D0=92=D0=BE=D0=B7=
=D0=BC=D0=BE=D0=B6=D0=BD=D0=BE,=C2=A0=D0=BF=D0=BE=D0=B9=D0=B4=D1=83</a></b>=
</font></td><td style=3D"padding: 0 7px 1px"><font size=3D"3" face=3D"Arial=
,sans-serif"><b><a href=3D"https://calendar.yandex-team.ru/api/add-event-in=
vitation?uid=3D1120000000016875&amp;private_token=3D31a9c61efe415ea82551439=
4a2bcaea3d59a6128&amp;event_id=3D35180804&amp;decision=3Dno">=D0=9D=D0=B5=
=C2=A0=D0=BF=D0=BE=D0=B9=D0=B4=D1=83</a></b></font></td></tr></table></td><=
/tr></table><table cellpadding=3D"4"><tr><td valign=3D"top"><font color=3D"=
#a2a2a2" face=3D"Arial,sans-serif" size=3D"3"><b>=D0=93=D0=B4=D0=B5</b></fo=
nt></td><td width=3D"5" /><td><font face=3D"Arial,sans-serif" size=3D"3"><a=
 href=3D"https://staff.yandex-team.ru/map/#/conference_room/name_exchange/c=
onf_ekb_lemuria">11.=D0=9B=D0=B5=D0=BC=D1=83=D1=80=D0=B8=D1=8F (PALLADIUM 1=
1-3)</a>, <a href=3D"https://staff.yandex-team.ru/map/#/conference_room/nam=
e_exchange/conf_st_3_03">3. =D0=97=D0=BE=D0=BE=D0=BC=D0=B0=D0=B3=D0=B0=D0=
=B7=D0=B8=D0=BD (ST 3-03)</a>, <a href=3D"https://staff.yandex-team.ru/map/=
#/conference_room/name_exchange/conf_zub_506m">506M</a></font></td></tr><tr=
><td valign=3D"top"><font color=3D"#a2a2a2" face=3D"Arial,sans-serif" size=
=3D"3"><b>=D0=9E=D1=80=D0=B3=D0=B0=D0=BD=D0=B8=D0=B7=D0=B0=D1=82=D0=BE=D1=
=80</b></font></td><td width=3D"5" /><td><font face=3D"Arial,sans-serif" si=
ze=3D"3">=D0=9F=D0=B0=D0=B2=D0=B5=D0=BB =D0=9C=D0=B8=D1=85=D0=B5=D0=B5=D0=
=B2</font></td></tr><tr><td valign=3D"top"><font color=3D"#a2a2a2" face=3D"=
Arial,sans-serif" size=3D"3"><b>=D0=9F=D1=80=D0=B8=D0=B3=D0=BB=D0=B0=D1=88=
=D0=B5=D0=BD=D1=8B</b></font></td><td width=3D"5" /><td><font face=3D"Arial=
,sans-serif" size=3D"3">=D0=94=D0=BC=D0=B8=D1=82=D1=80=D0=B8=D0=B9 =D0=9F=
=D0=BE=D1=82=D0=B0=D0=BF=D0=BE=D0=B2<br />=D0=9C=D0=B0=D0=BA=D1=81=D0=B8=D0=
=BC =D0=A8=D0=B0=D0=B1=D0=B0=D0=BB=D0=BA=D0=B8=D0=BD<br />=D0=9D=D0=B8=D0=
=BA=D0=BE=D0=BB=D0=B0=D0=B9 =D0=A8=D0=B5=D1=81=D1=82=D0=B0=D0=BA=D0=BE=D0=
=B2<br />=D0=90=D0=BD=D0=B4=D1=80=D0=B5=D0=B9 =D0=98=D0=B2=D0=B0=D0=BD=D0=
=BE=D0=B2<br />=D0=9D=D0=B8=D0=BA=D0=BE=D0=BB=D0=B0=D0=B9 =D0=9A=D0=BE=D0=
=BD=D0=B4=D1=80=D0=B0=D1=82=D1=8C=D0=B5=D0=B2<br /></font><a href=3D"https:=
//calendar.yandex-team.ru/event/?uid=3D1120000000016875&amp;private_token=
=3D31a9c61efe415ea825514394a2bcaea3d59a6128&amp;event_id=3D35180804&amp;sho=
w_date=3D2019-03-13"><font face=3D"Verdana,sans-serif" size=3D"1">=D0=9F=D0=
=BE=D1=81=D0=BC=D0=BE=D1=82=D1=80=D0=B5=D1=82=D1=8C, =D0=BA=D1=82=D0=BE =D0=
=BF=D0=BE=D0=B9=D0=B4=D1=91=D1=82</font></a></td></tr></table><table cellpa=
dding=3D"4" width=3D"100%"><tr><td><hr size=3D"1" noshade=3D"noshade" color=
=3D"#cccccc" style=3D"border: 0 hidden; border-top: 1px solid #cccccc; heig=
ht: 0; margin-top: 30px;" /><font size=3D"1" face=3D"Verdana, sans-serif" c=
olor=3D"#9a9a9a">=D0=A3=D0=B2=D0=B5=D0=B4=D0=BE=D0=BC=D0=BB=D0=B5=D0=BD=D0=
=B8=D0=B5 =D0=BE=D1=82=D0=BF=D1=80=D0=B0=D0=B2=D0=BB=D0=B5=D0=BD=D0=BE =D1=
=87=D0=B5=D1=80=D0=B5=D0=B7=C2=A0<a style=3D"color: #9a9a9a" href=3D"https:=
//calendar.yandex-team.ru?uid=3D1120000000016875">=D0=AF=D0=BD=D0=B4=D0=B5=
=D0=BA=D1=81.=D0=9A=D0=B0=D0=BB=D0=B5=D0=BD=D0=B4=D0=B0=D1=80=D1=8C</a>.=C2=
=A0=D0=95=D1=81=D0=BB=D0=B8 =D0=B2=D1=8B =D0=BD=D0=B5 =D1=85=D0=BE=D1=82=D0=
=B8=D1=82=D0=B5 =D0=BF=D0=BE=D0=BB=D1=83=D1=87=D0=B0=D1=82=D1=8C =D1=82=D0=
=B0=D0=BA=D0=B8=D0=B5 =D0=BF=D0=B8=D1=81=D1=8C=D0=BC=D0=B0,=C2=A0<a style=
=3D"color: #9a9a9a" href=3D"https://calendar.yandex-team.ru/tune?uid=3D1120=
000000016875">=D0=BE=D1=82=D0=BA=D0=B0=D0=B6=D0=B8=D1=82=D0=B5=D1=81=D1=8C =
=D0=BE=D1=82 =D0=BD=D0=B8=D1=85</a>.=C2=A0=C2=A0=C2=A9=C2=A02007=E2=80=9420=
19=C2=A0=C2=AB<a style=3D"color: #9a9a9a" href=3D"http://www.yandex.ru">=D0=
=AF=D0=BD=D0=B4=D0=B5=D0=BA=D1=81</a>=C2=BB</font></td></tr></table></body>=
</html>
------=_Part_272689_1359329833.1552470370942
Content-Type: text/calendar; charset=utf-8; method=REQUEST
Content-Transfer-Encoding: quoted-printable

BEGIN:VCALENDAR
PRODID:-//Yandex LLC//Yandex Calendar//EN
VERSION:2.0
CALSCALE:GREGORIAN
METHOD:REQUEST
X-YANDEX_MAIL_TYPE:event_invitation
BEGIN:VTIMEZONE
TZID:Europe/Moscow
TZURL:http://tzurl.org/zoneinfo-outlook/Europe/Moscow
X-LIC-LOCATION:Europe/Moscow
BEGIN:STANDARD
TZOFFSETFROM:+0300
TZOFFSETTO:+0300
TZNAME:MSK
DTSTART:19700101T000000
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
DTSTART;TZID=3DEurope/Moscow:20190313T183000
DTEND;TZID=3DEurope/Moscow:20190313T190000
SUMMARY:=D0=9E=D1=82=D0=BE=D0=B1=D1=80=D0=B0=D0=B6=D0=B5=D0=BD=D0=B8=D0=B5 =
=D0=B8=D0=B7=D0=BC=D0=B5=D0=BD=D0=B5=D0=BD=D0=B8=D0=B9 =D0=B4=D0=B0=D1=82 =
=D0=B4=D0=BE=D1=81=D1=82=D0=B0=D0=B2=D0=BA=D0=B8 =D0=BD=D0=B0 =D0=B2=D0=B5=
=D0=B1=D0=B5 =D0=B1=D0=B5=D1=80=D1=83 =D1=81=D1=80=D0=B5=D0=B4=D1=81=D1=82=
=D0=B2=D0=B0=D0=BC=D0=B8 =D1=82=D1=80=D0=B8=D0=B3=D0=B3=D0=B5=D1=80=D0=BD=
=D0=BE=D0=B9 =D0=BF=D0=BB=D0=B0=D1=82=D1=84=D0=BE=D1=80=D0=BC=D1=8B
UID:4Jd6BP2yyandex.ru
SEQUENCE:0
DTSTAMP:20190313T094606Z
CREATED:20190313T094606Z
LOCATION:11.=D0=9B=D0=B5=D0=BC=D1=83=D1=80=D0=B8=D1=8F (PALLADIUM 11-3)\, 3=
. =D0=97=D0=BE=D0=BE=D0=BC=D0=B0=D0=B3=D0=B0=D0=B7=D0=B8=D0=BD (ST 3-03)\, =
506M
DESCRIPTION:
URL:https://calendar.yandex-team.ru/event?event_id=3D35180804
CATEGORIES:=D0=9D=D0=B8=D0=BA=D0=BE=D0=BB=D0=B0=D0=B9 =D0=A8=D0=B5=D1=81=D1=
=82=D0=B0=D0=BA=D0=BE=D0=B2
ORGANIZER;CN=3D"=D0=9F=D0=B0=D0=B2=D0=B5=D0=BB =D0=9C=D0=B8=D1=85=D0=B5=D0=
=B5=D0=B2":mailto:pm01@yandex-team.ru
ATTENDEE;CUTYPE=3DROOM;PARTSTAT=3DACCEPTED;CN=3D"11.=D0=9B=D0=B5=D0=BC=D1=
=83=D1=80=D0=B8=D1=8F":mailto:conf_ekb_lemuria@yandex-team.ru
ATTENDEE;CUTYPE=3DROOM;PARTSTAT=3DACCEPTED;CN=3D"3. =D0=97=D0=BE=D0=BE=D0=
=BC=D0=B0=D0=B3=D0=B0=D0=B7=D0=B8=D0=BD":mailto:conf_st_3_03@yandex-team.ru
ATTENDEE;CUTYPE=3DROOM;PARTSTAT=3DACCEPTED;CN=3D506M:mailto:conf_zub_506m@y=
andex-team.ru
ATTENDEE;PARTSTAT=3DACCEPTED;CN=3D"=D0=9F=D0=B0=D0=B2=D0=B5=D0=BB =D0=9C=D0=
=B8=D1=85=D0=B5=D0=B5=D0=B2":mailto:pm01@yandex-team.ru
ATTENDEE;PARTSTAT=3DNEEDS-ACTION;CN=3D"=D0=94=D0=BC=D0=B8=D1=82=D1=80=D0=B8=
=D0=B9 =D0=9F=D0=BE=D1=82=D0=B0=D0=BF=D0=BE=D0=B2":mailto:dimpot@yandex-tea=
m.ru
ATTENDEE;PARTSTAT=3DNEEDS-ACTION;CN=3D"=D0=9C=D0=B0=D0=BA=D1=81=D0=B8=D0=BC=
 =D0=A8=D0=B0=D0=B1=D0=B0=D0=BB=D0=BA=D0=B8=D0=BD":mailto:gromit@yandex-tea=
m.ru
ATTENDEE;PARTSTAT=3DNEEDS-ACTION;CN=3D"=D0=9D=D0=B8=D0=BA=D0=BE=D0=BB=D0=B0=
=D0=B9 =D0=A8=D0=B5=D1=81=D1=82=D0=B0=D0=BA=D0=BE=D0=B2":mailto:tesseract@y=
andex-team.ru
ATTENDEE;PARTSTAT=3DNEEDS-ACTION;CN=3D"=D0=90=D0=BD=D0=B4=D1=80=D0=B5=D0=B9=
 =D0=98=D0=B2=D0=B0=D0=BD=D0=BE=D0=B2":mailto:andvalerevich@yandex-team.ru
ATTENDEE;PARTSTAT=3DNEEDS-ACTION;CN=3D"=D0=9D=D0=B8=D0=BA=D0=BE=D0=BB=D0=B0=
=D0=B9 =D0=9A=D0=BE=D0=BD=D0=B4=D1=80=D0=B0=D1=82=D1=8C=D0=B5=D0=B2":mailto=
:kondratyev-nv@yandex-team.ru
X-MICROSOFT-CDO-BUSYSTATUS:TENTATIVE
LAST-MODIFIED:20190313T094606Z
END:VEVENT
END:VCALENDAR

------=_Part_272689_1359329833.1552470370942--

------=_Part_272688_1971496659.1552470370942
Content-Type: application/ics; charset=utf-8; name=event.ics
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename=event.ics; filename=event.ics

QkVHSU46VkNBTEVOREFSDQpQUk9ESUQ6LS8vWWFuZGV4IExMQy8vWWFuZGV4IENhbGVuZGFyLy9F
Tg0KVkVSU0lPTjoyLjANCkNBTFNDQUxFOkdSRUdPUklBTg0KTUVUSE9EOlJFUVVFU1QNClgtWUFO
REVYX01BSUxfVFlQRTpldmVudF9pbnZpdGF0aW9uDQpCRUdJTjpWVElNRVpPTkUNClRaSUQ6RXVy
b3BlL01vc2Nvdw0KVFpVUkw6aHR0cDovL3R6dXJsLm9yZy96b25laW5mby1vdXRsb29rL0V1cm9w
ZS9Nb3Njb3cNClgtTElDLUxPQ0FUSU9OOkV1cm9wZS9Nb3Njb3cNCkJFR0lOOlNUQU5EQVJEDQpU
Wk9GRlNFVEZST006KzAzMDANClRaT0ZGU0VUVE86KzAzMDANClRaTkFNRTpNU0sNCkRUU1RBUlQ6
MTk3MDAxMDFUMDAwMDAwDQpFTkQ6U1RBTkRBUkQNCkVORDpWVElNRVpPTkUNCkJFR0lOOlZFVkVO
VA0KRFRTVEFSVDtUWklEPUV1cm9wZS9Nb3Njb3c6MjAxOTAzMTNUMTgzMDAwDQpEVEVORDtUWklE
PUV1cm9wZS9Nb3Njb3c6MjAxOTAzMTNUMTkwMDAwDQpTVU1NQVJZOtCe0YLQvtCx0YDQsNC20LXQ
vdC40LUg0LjQt9C80LXQvdC10L3QuNC5INC00LDRgiDQtNC+0YHRgtCw0LLQutC4INC90LAg0LLQ
tdCx0LUg0LHQtdGA0YMg0YHRgNC10LTRgdGC0LLQsNC80Lgg0YLRgNC40LPQs9C10YDQvdC+0Lkg
0L/Qu9Cw0YLRhNC+0YDQvNGLDQpVSUQ6NEpkNkJQMnl5YW5kZXgucnUNClNFUVVFTkNFOjANCkRU
U1RBTVA6MjAxOTAzMTNUMDk0NjA2Wg0KQ1JFQVRFRDoyMDE5MDMxM1QwOTQ2MDZaDQpMT0NBVElP
TjoxMS7Qm9C10LzRg9GA0LjRjyAoUEFMTEFESVVNIDExLTMpXCwgMy4g0JfQvtC+0LzQsNCz0LDQ
t9C40L0gKFNUIDMtMDMpXCwgNTA2TQ0KREVTQ1JJUFRJT046DQpVUkw6aHR0cHM6Ly9jYWxlbmRh
ci55YW5kZXgtdGVhbS5ydS9ldmVudD9ldmVudF9pZD0zNTE4MDgwNA0KQ0FURUdPUklFUzrQndC4
0LrQvtC70LDQuSDQqNC10YHRgtCw0LrQvtCyDQpPUkdBTklaRVI7Q049ItCf0LDQstC10Lsg0JzQ
uNGF0LXQtdCyIjptYWlsdG86cG0wMUB5YW5kZXgtdGVhbS5ydQ0KQVRURU5ERUU7Q1VUWVBFPVJP
T007UEFSVFNUQVQ9QUNDRVBURUQ7Q049IjExLtCb0LXQvNGD0YDQuNGPIjptYWlsdG86Y29uZl9l
a2JfbGVtdXJpYUB5YW5kZXgtdGVhbS5ydQ0KQVRURU5ERUU7Q1VUWVBFPVJPT007UEFSVFNUQVQ9
QUNDRVBURUQ7Q049IjMuINCX0L7QvtC80LDQs9Cw0LfQuNC9IjptYWlsdG86Y29uZl9zdF8zXzAz
QHlhbmRleC10ZWFtLnJ1DQpBVFRFTkRFRTtDVVRZUEU9Uk9PTTtQQVJUU1RBVD1BQ0NFUFRFRDtD
Tj01MDZNOm1haWx0bzpjb25mX3p1Yl81MDZtQHlhbmRleC10ZWFtLnJ1DQpBVFRFTkRFRTtQQVJU
U1RBVD1BQ0NFUFRFRDtDTj0i0J/QsNCy0LXQuyDQnNC40YXQtdC10LIiOm1haWx0bzpwbTAxQHlh
bmRleC10ZWFtLnJ1DQpBVFRFTkRFRTtQQVJUU1RBVD1ORUVEUy1BQ1RJT047Q049ItCU0LzQuNGC
0YDQuNC5INCf0L7RgtCw0L/QvtCyIjptYWlsdG86ZGltcG90QHlhbmRleC10ZWFtLnJ1DQpBVFRF
TkRFRTtQQVJUU1RBVD1ORUVEUy1BQ1RJT047Q049ItCc0LDQutGB0LjQvCDQqNCw0LHQsNC70LrQ
uNC9IjptYWlsdG86Z3JvbWl0QHlhbmRleC10ZWFtLnJ1DQpBVFRFTkRFRTtQQVJUU1RBVD1ORUVE
Uy1BQ1RJT047Q049ItCd0LjQutC+0LvQsNC5INCo0LXRgdGC0LDQutC+0LIiOm1haWx0bzp0ZXNz
ZXJhY3RAeWFuZGV4LXRlYW0ucnUNCkFUVEVOREVFO1BBUlRTVEFUPU5FRURTLUFDVElPTjtDTj0i
0JDQvdC00YDQtdC5INCY0LLQsNC90L7QsiI6bWFpbHRvOmFuZHZhbGVyZXZpY2hAeWFuZGV4LXRl
YW0ucnUNCkFUVEVOREVFO1BBUlRTVEFUPU5FRURTLUFDVElPTjtDTj0i0J3QuNC60L7Qu9Cw0Lkg
0JrQvtC90LTRgNCw0YLRjNC10LIiOm1haWx0bzprb25kcmF0eWV2LW52QHlhbmRleC10ZWFtLnJ1
DQpYLU1JQ1JPU09GVC1DRE8tQlVTWVNUQVRVUzpURU5UQVRJVkUNCkxBU1QtTU9ESUZJRUQ6MjAx
OTAzMTNUMDk0NjA2Wg0KRU5EOlZFVkVOVA0KRU5EOlZDQUxFTkRBUg0K
------=_Part_272688_1971496659.1552470370942--