CREATE SCHEMA IF NOT EXISTS sorter;
SET SCHEMA sorter;

CREATE TABLE IF NOT EXISTS CONFIG_PROPERTIES (
    ID SERIAL NOT NULL,
    NAME VARCHAR(32) NOT NULL,
    VALUE VARCHAR(128) NOT NULL,
    DESCRIPTION VARCHAR(512),
    ADDWHO VARCHAR(256),
    EDITWHO VARCHAR(256),
    CONSTRAINT PK_CONFIG_PROPERTIES PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS SORTEREXIT (
    SORTEREXITKEY VARCHAR(10) NOT NULL,
    ADDWHO VARCHAR(256) NOT NULL,
    EDITWHO VARCHAR(256) NOT NULL,
    ADDDATE timestamp DEFAULT CURRENT_TIMESTAMP,
    EDITDATE timestamp DEFAULT CURRENT_TIMESTAMP,
    ISALTERNATEEXIT BOOLEAN DEFAULT FALSE,
    ISERROREXIT BOOLEAN DEFAULT FALSE,
    CONVEYORLOC VARCHAR(20),
    LOCATIONTYPE VARCHAR(10),
    ZONE VARCHAR(32) DEFAULT '' NOT NULL,
    CONSTRAINT PK_SORTEREXIT PRIMARY KEY (SORTEREXITKEY)
);

CREATE TABLE IF NOT EXISTS SORTERBOXWEIGHTDEVIATION (
    ID SERIAL NOT NULL,
    WEIGHTFROM int NOT NULL,
    WEIGHTTO int NOT NULL,
    PERCENTAGE decimal(18, 2) NOT NULL,
    ADDWHO VARCHAR(256) NOT NULL,
    EDITWHO VARCHAR(256) NOT NULL,
    ADDDATE timestamp DEFAULT CURRENT_TIMESTAMP,
    EDITDATE timestamp DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_SORTERBOXWEIGHTDEVIATION PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS SORTERDIMENSIONSCONTROL (
    ID SERIAL NOT NULL,
    UNITKEY varchar(50) NOT NULL,
    ORDERKEY varchar(10) NOT NULL,
    WEIGHT decimal(18, 3) NOT NULL,
    ADDWHO VARCHAR(256) NOT NULL,
    EDITWHO VARCHAR(256) NOT NULL,
    ADDDATE timestamp DEFAULT CURRENT_TIMESTAMP,
    EDITDATE timestamp DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_SORTERDIMENSIONSCONTROL PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS SORTEREXITTOCARRIER (
    SORTEREXITTOCARRIERKEY SERIAL NOT NULL,
    SORTEREXITKEY varchar(10) NOT NULL,
    CARRIERCODE varchar(15) NOT NULL,
    SCHEDULEDSHIPDATE timestamp,
    ADDWHO VARCHAR(256) NOT NULL,
    EDITWHO VARCHAR(256) NOT NULL,
    ADDDATE timestamp DEFAULT CURRENT_TIMESTAMP,
    EDITDATE timestamp DEFAULT CURRENT_TIMESTAMP,
    WEIGHTMAX int,
    WEIGHTMIN int,
    VERSION int DEFAULT 1 NOT NULL,
    TIMEFROM time NOT NULL default '00:00:00',
    TIMETO time NOT NULL default '23:59:59',
    CONSTRAINT PK_SORTEREXITTOCARRIER PRIMARY KEY (SORTEREXITTOCARRIERKEY),
    CONSTRAINT UQ_SORTEREXITTOCARRIER_SORTEREXIT_CARRIER_SHIPDATE_TIME_WEIGHT UNIQUE (SORTEREXITKEY,
                                                                                      CARRIERCODE,
                                                                                      SCHEDULEDSHIPDATE,
                                                                                      TIMEFROM,
                                                                                      TIMETO,
                                                                                      WEIGHTMIN,
                                                                                      WEIGHTMAX),
    CONSTRAINT FK_SORTEREXITTOCARRIER_SORTEXITKEY FOREIGN KEY (SORTEREXITKEY) REFERENCES SORTEREXIT (SORTEREXITKEY),
    CONSTRAINT SORTEREXITTOCARRIER_TIMETO_TIMEFROM_CHECK CHECK (TIMETO > TIMEFROM)
);

CREATE TABLE IF NOT EXISTS SORTERORDER (
    SORTERORDERKEY SERIAL NOT NULL,
    ACTUALLOCATIONKEY VARCHAR(10) NOT NULL,
    PACKSTATIONKEY VARCHAR(10) NOT NULL,
    SORTEREXITKEY VARCHAR(10) NOT NULL,
    UNITKEY VARCHAR(50) NOT NULL,
    ASSIGNEE VARCHAR(512),
    STATUS VARCHAR(100) DEFAULT 'NEW' NOT NULL,
    PRIORITY INT DEFAULT 0 NOT NULL,
    VERSION INT DEFAULT 1 NOT NULL,
    ADDWHO VARCHAR(256) NOT NULL,
    EDITWHO VARCHAR(256) NOT NULL,
    ADDDATE timestamp DEFAULT CURRENT_TIMESTAMP,
    EDITDATE timestamp DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_SORTERORDER PRIMARY KEY (SORTERORDERKEY),
    CONSTRAINT FK_SORTERORDER_SORTEXITKEY FOREIGN KEY (SORTEREXITKEY) REFERENCES SORTEREXIT (SORTEREXITKEY)
);

CREATE TABLE IF NOT EXISTS SORTER
(
    SORTER_ID            VARCHAR(40)                    NOT NULL,
    ENABLED              BOOLEAN      DEFAULT TRUE,
    SORTER_ZONE          VARCHAR(10) PRIMARY KEY        NOT NULL,
    EXTERNAL_SORTER_ZONE VARCHAR(10)                    NOT NULL,
    LOC_PATTERN          VARCHAR(256),
    AUTOMATION           VARCHAR(256) DEFAULT 'UNKNOWN' NOT NULL,
    CHECKPOINT           VARCHAR(20),
    ADDWHO               VARCHAR(256)                   NOT NULL,
    EDITWHO              VARCHAR(256)                   NOT NULL,
    ADDDATE              timestamp    DEFAULT CURRENT_TIMESTAMP,
    EDITDATE             timestamp    DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE IF NOT EXISTS BOX_INFO
(
    UNIT_KEY         VARCHAR(50)
    CONSTRAINT PK_BOX_INFO PRIMARY KEY                NOT NULL,
    WEIGHT           NUMERIC(18, 3)                       NOT NULL,
    WIDTH            NUMERIC(18, 3)                       NOT NULL,
    HEIGHT           NUMERIC(18, 3)                       NOT NULL,
    LENGTH           NUMERIC(18, 3)                       NOT NULL,
    CARRIER_CODE     VARCHAR(15)                          NOT NULL,
    CARRIER_NAME     VARCHAR(45)                          NOT NULL,
    OPERATION_DAY_ID BIGINT                               NOT NULL,
    SERVICE_FROM     VARCHAR(50)                          NOT NULL,
    ADD_WHO          VARCHAR(256)                         NOT NULL,
    EDIT_WHO         VARCHAR(256)                         NOT NULL,
    ADD_DATE         timestamp DEFAULT CURRENT_TIMESTAMP,
    EDIT_DATE        timestamp DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE IF NOT EXISTS ARRIVAL_TO_NOK
(
    ARRIVAL_TO_NOK_KEY     SERIAL
        CONSTRAINT PK_ARRIVAL_TO_NOK PRIMARY KEY,
    UNIT_KEY               VARCHAR(50)                             NOT NULL,
    ARRIVAL_TO_NOK_REASON  VARCHAR(40)                             NOT NULL,
    SORTER_ORDER_KEY       INTEGER                                 NULL
        CONSTRAINT FK_ARRIVAL_TO_NOK_SORTER_ORDER_KEY REFERENCES SORTERORDER,
    ADD_WHO                VARCHAR(256)                            NOT NULL,
    EDIT_WHO               VARCHAR(256)                            NOT NULL,
    ADD_DATE               TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    EDIT_DATE              TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);
