SET DATABASE SQL SYNTAX ORA TRUE;

CREATE TABLE "TASK"
(  "ID" NUMBER,
   "STATUS" NUMBER,
   "NAME" VARCHAR2(100 BYTE),
   "LIVE_SERVICE_ID" NUMBER,
   "SOURCE_ID" NUMBER,
   "SESSION_ID" NUMBER,
   "START_TIME" DATE,
   "FINISH_TIME" DATE,
   "CREATED_TIME" DATE,
   "PRIORITY" NUMBER DEFAULT 0,
   "TIMEOUT" NUMBER DEFAULT 0,
   "PROGRESS" NUMBER DEFAULT 0,
   "RESULT" VARCHAR2(1000 CHAR),
   "STOP_TIME" DATE,
   "LOCKED_BY" NUMBER DEFAULT 0,
   "SOURCE_TASK_ID" NUMBER,
   "ENTITY_ID" NUMBER,
   "PROCESSED_ELEMENTS" NUMBER DEFAULT 0,
   "MESSAGE_VERSION" NUMBER,
   "MESSAGE_CODE" VARCHAR2(4000 BYTE),
   "MESSAGE_PARAMS" VARCHAR2(4000 BYTE)
)