CREATE USER cubes2_itest IDENTIFIED BY '';
CREATE SCHEMA cubes2_itest AUTHORIZATION cubes2_itest;
CREATE RESOURCE POOL cubes2_itest_pool EXECUTIONPARALLELISM 4 MAXMEMORYSIZE '2G' PRIORITY -50 RUNTIMECAP '0:20:00' RUNTIMEPRIORITY LOW;
GRANT USAGE ON RESOURCE POOL cubes2_itest_pool to cubes2_itest;
ALTER USER cubes2_itest RESOURCE POOL cubes2_itest_pool;
