CREATE SCHEMA IF NOT EXISTS [WMWHSE1];

CREATE ALIAS IF NOT EXISTS WMWHSE1.SELECTHOLD AS ' String SELECTHOLD(String s1, String s2) { return null; } ';

CREATE TABLE IF NOT EXISTS WMWHSE1.NSQLCONFIG
(
    CONFIGKEY                       VARCHAR(64)    NULL,
    NSQLVALUE                       VARCHAR(255)   NULL
);


CREATE TABLE IF NOT EXISTS WMWHSE1.SKU
(
    SERIALKEY                       INT            NOT NULL,
    WHSEID                          VARCHAR(30)    NULL,
    STORERKEY                       VARCHAR(15)    NULL,
    SKU                             VARCHAR(50)    NOT NULL,
    SOURCEVERSION                   VARCHAR(22)    DEFAULT ('0'),
    HAZMATCODESKEY                  VARCHAR(10)    DEFAULT (''),
    ITEMREFERENCE                   VARCHAR(8)     DEFAULT (' '),
    SERIALNUMBERSTART               DECIMAL(15, 0) NULL,
    SERIALNUMBEREND                 DECIMAL(15, 0) NULL,
    SERIALNUMBERNEXT                DECIMAL(15, 0) NULL,
    DESCR                           VARCHAR(200),
    SUSR1                           VARCHAR(18),
    SUSR2                           VARCHAR(18),
    SUSR3                           VARCHAR(18),
    SUSR4                           VARCHAR(18),
    SUSR5                           VARCHAR(18),
    MANUFACTURERSKU                 VARCHAR(150),
    RETAILSKU                       VARCHAR(50),
    ALTSKU                          VARCHAR(50),
    PACKKEY                         VARCHAR(50)    DEFAULT ('STD'),
    STDGROSSWGT                     DECIMAL(22, 5) DEFAULT ((0)),
    STDNETWGT                       DECIMAL(22, 5) DEFAULT ((0)),
    STDCUBE                         DECIMAL(22, 5) DEFAULT ((0)),
    TARE                            DECIMAL(22, 5) DEFAULT ((0)),
    CLASS                           VARCHAR(10)    DEFAULT ('STD'),
    ACTIVE                          VARCHAR(10)    DEFAULT ('1'),
    SKUGROUP                        VARCHAR(10)    DEFAULT ('STD'),
    TARIFFKEY                       VARCHAR(10)    DEFAULT ('XXXXXXXXXX'),
    BUSR1                           VARCHAR(30),
    BUSR2                           VARCHAR(30),
    BUSR3                           VARCHAR(30),
    BUSR4                           VARCHAR(30),
    BUSR5                           VARCHAR(30),
    LOTTABLE01LABEL                 VARCHAR(20)    DEFAULT ('JULIAN	DT.'),
    LOTTABLE02LABEL                 VARCHAR(20)    DEFAULT ('CUST.LOT'),
    LOTTABLE03LABEL                 VARCHAR(20)    DEFAULT ('COLOR'),
    LOTTABLE04LABEL                 VARCHAR(20)    DEFAULT ('MAN.DATE'),
    LOTTABLE05LABEL                 VARCHAR(20)    DEFAULT ('EXP.DATE'),
    LOTTABLE06LABEL                 VARCHAR(20)    DEFAULT (''),
    LOTTABLE07LABEL                 VARCHAR(20)    DEFAULT (''),
    LOTTABLE08LABEL                 VARCHAR(20)    DEFAULT (''),
    LOTTABLE09LABEL                 VARCHAR(20),
    LOTTABLE10LABEL                 VARCHAR(20),
    PICKCODE                        VARCHAR(10),
    STRATEGYKEY                     VARCHAR(10),
    CARTONGROUP                     VARCHAR(10),
    PUTCODE                         VARCHAR(10),
    PUTAWAYLOC                      VARCHAR(10),
    PUTAWAYZONE                     VARCHAR(10),
    INNERPACK                       DECIMAL(22, 5),
    CUBE                            FLOAT,
    GROSSWGT                        FLOAT,
    NETWGT                          FLOAT,
    ABC                             VARCHAR(5),
    CYCLECOUNTFREQUENCY             INT,
    LASTCYCLECOUNT                  DATETIME,
    REORDERPOINT                    INT,
    REORDERQTY                      DECIMAL(22, 5),
    STDORDERCOST                    FLOAT,
    CARRYCOST                       FLOAT,
    PRICE                           DECIMAL(19, 4),
    COST                            DECIMAL(19, 4),
    ONRECEIPTCOPYPACKKEY            VARCHAR(10),
    RECEIPTHOLDCODE                 VARCHAR(10),
    RECEIPTINSPECTIONLOC            VARCHAR(10),
    ROTATEBY                        VARCHAR(10),
    DATECODEDAYS                    INT,
    DEFAULTROTATION                 VARCHAR(1),
    SHIPPABLECONTAINER              VARCHAR(10),
    IOFLAG                          VARCHAR(5),
    TAREWEIGHT                      DECIMAL(22, 5),
    LOTXIDDETAILOTHERLABEL1         VARCHAR(30),
    LOTXIDDETAILOTHERLABEL2         VARCHAR(30),
    LOTXIDDETAILOTHERLABEL3         VARCHAR(30),
    AVGCASEWEIGHT                   DECIMAL(22, 5),
    TOLERANCEPCT                    DECIMAL(12, 6),
    SHELFLIFEINDICATOR              VARCHAR(10),
    SHELFLIFE                       INT,
    TRANSPORTATIONMODE              VARCHAR(30),
    SKUGROUP2                       VARCHAR(30),
    SUSR6                           VARCHAR(30),
    SUSR7                           VARCHAR(30),
    SUSR8                           VARCHAR(30),
    SUSR9                           VARCHAR(30),
    SUSR10                          VARCHAR(30),
    BUSR6                           VARCHAR(30),
    BUSR7                           VARCHAR(30),
    BUSR8                           VARCHAR(30),
    BUSR9                           VARCHAR(30),
    BUSR10                          VARCHAR(30),
    MINIMUMSHELFLIFEONRFPICKING     DECIMAL(10, 0),
    FREIGHTCLASS                    VARCHAR(10),
    ICWFLAG                         VARCHAR(1),
    ICWBY                           VARCHAR(1),
    IDEWEIGHT                       VARCHAR(1),
    ICDFLAG                         VARCHAR(1),
    ICDLABEL1                       VARCHAR(5),
    ICDLABEL2                       VARCHAR(5),
    ICDLABEL3                       VARCHAR(5),
    OCWFLAG                         VARCHAR(1),
    OCWBY                           VARCHAR(1),
    ODEWEIGHT                       VARCHAR(1),
    OACOVERRIDE                     VARCHAR(1),
    OCDFLAG                         VARCHAR(1),
    OCDLABEL1                       VARCHAR(5),
    OCDLABEL2                       VARCHAR(5),
    OCDLABEL3                       VARCHAR(5),
    OTAREWEIGHT                     DECIMAL(22, 5),
    OAVGCASEWEIGHT                  DECIMAL(22, 5),
    OTOLERANCEPCT                   DECIMAL(12, 6),
    RFDEFAULTPACK                   VARCHAR(50),
    RFDEFAULTUOM                    VARCHAR(10),
    SHELFLIFECODETYPE               VARCHAR(1),
    SHELFLIFEONRECEIVING            INT,
    LOTTABLEVALIDATIONKEY           VARCHAR(10),
    ALLOWCONSOLIDATION              VARCHAR(1),
    MINIMUMWAVEQTY                  DECIMAL(22, 5),
    BULKCARTONGROUP                 VARCHAR(10),
    PICKUOM                         VARCHAR(2),
    EACHKEY                         VARCHAR(10),
    CASEKEY                         VARCHAR(10),
    TYPE                            VARCHAR(32),
    EFFECSTARTDATE                  DATETIME,
    EFFECENDDATE                    DATETIME,
    CONVEYABLE                      VARCHAR(1),
    FLOWTHRUITEM                    VARCHAR(1),
    NOTES1                          VARCHAR(2000),
    NOTES2                          VARCHAR(2000),
    VERT_STORAGE                    VARCHAR(1),
    CWFLAG                          VARCHAR(10),
    VERIFYLOT04LOT05                VARCHAR(1),
    PUTAWAYSTRATEGYKEY              VARCHAR(10),
    RETURNSLOC                      VARCHAR(10),
    QCLOC                           VARCHAR(10),
    RECEIPTVALIDATIONTEMPLATE       VARCHAR(18),
    SKUTYPE                         VARCHAR(1),
    StackLimit                      INT,
    MaxPalletsPerZone               INT,
    CCDISCREPANCYRULE               VARCHAR(10),
    MANUALSETUPREQUIRED             VARCHAR(1),
    QCLOCOUT                        VARCHAR(10),
    OCDCATCHWHEN                    VARCHAR(10),
    OCDCATCHQTY1                    VARCHAR(10),
    OCDCATCHQTY2                    VARCHAR(10),
    OCDCATCHQTY3                    VARCHAR(10),
    HASIMAGE                        VARCHAR(1),
    GUID                            VARCHAR(32),
    NONSTOCKEDINDICATOR             VARCHAR(1),
    LOTTABLE11LABEL                 VARCHAR(20),
    LOTTABLE12LABEL                 VARCHAR(20),
    TOEXPIREDAYS                    INT,
    TODELIVERBYDAYS                 INT,
    TOBESTBYDAYS                    INT,
    SNUM_POSITION                   INT,
    SNUM_LENGTH                     INT,
    SNUM_DELIMITER                  VARCHAR(1),
    SNUM_DELIM_COUNT                INT,
    SNUM_QUANTITY                   INT,
    SNUM_INCR_POS                   INT,
    SNUM_INCR_LENGTH                INT,
    SNUM_ENDTOEND                   INT,
    SNUM_MASK                       VARCHAR(50),
    ICDLABEL4                       VARCHAR(5),
    ICDLABEL5                       VARCHAR(5),
    OCDLABEL4                       VARCHAR(5),
    OCDLABEL5                       VARCHAR(5),
    ICD1UNIQUE                      VARCHAR(1),
    OCD1UNIQUE                      VARCHAR(1),
    SNUMLONG_DELIMITER              VARCHAR(5),
    SNUMLONG_FIXED                  INT,
    SNUM_AUTOINCREMENT              INT,
    ACCOUNTINGENTITY                VARCHAR(64),
    VOICEGROUPINGID                 VARCHAR(1),
    COUNTSEQUENCE                   INT,
    DAPICKSORT                      VARCHAR(1),
    RPLNSORT                        VARCHAR(1),
    CATCHGROSSWGT                   INT,
    CATCHNETWGT                     INT,
    CATCHTAREWGT                    INT,
    TAREWGT1                        FLOAT,
    STDNETWGT1                      FLOAT,
    STDGROSSWGT1                    FLOAT,
    STDUOM                          VARCHAR(10),
    ZERODEFAULTWGTFORPICK           INT,
    FILLQTYUOM                      VARCHAR(2),
    CARTONIZEFT                     VARCHAR(1),
    RECURCODE                       VARCHAR(10),
    WGTUOM                          VARCHAR(20),
    DIMENUOM                        VARCHAR(20),
    CUBEUOM                         VARCHAR(20),
    STORAGETYPE                     VARCHAR(20),
    NMFCCLASS                       VARCHAR(40),
    MATEABILITYCODE                 VARCHAR(64),
    LOTHOLDCODE                     VARCHAR(10),
    AUTORELEASELOTBY                VARCHAR(10),
    HOURSTOHOLDLOT                  DECIMAL(10, 2),
    AUTORELEASELPNBY                VARCHAR(10),
    HOURSTOHOLDLPN                  DECIMAL(10, 2),
    AMSTRATEGYKEY                   VARCHAR(10),
    TEMPFORASN                      VARCHAR(1),
    IBSUMCWFLG                      VARCHAR(1),
    OBSUMCWFLG                      VARCHAR(1),
    SHOWRFCWONTRANS                 VARCHAR(1),
    PUTAWAYCLASS                    VARCHAR(10),
    GROUPFTEACH                     VARCHAR(1),
    TRANSPORTATIONSERVICE           VARCHAR(10),
    SKUFACILITYGROUP                VARCHAR(10),
    LOTCTRLATPACK                   VARCHAR(1),
    LASTCCRELEASEDATE               DATETIME,
    DEFAULTEQUIPMENTATTRIBUTE       VARCHAR(10),
    DEFAULTEQUIPMENTTYPE            VARCHAR(10),
    DEFAULTEQUIPMENTLENGTH          VARCHAR(10),
    BARCODECONFIGKEY                VARCHAR(18),
    AUTOASSIGNCONSLOC               VARCHAR(1),
    CONSPICKLOCMIN                  DECIMAL(22, 5),
    CONSPICKLOCMAX                  DECIMAL(22, 5),
    CONSPICKMINMAXUOM               VARCHAR(10),
    CONSPICKREPLENUOM               VARCHAR(10),
    ROUNDBACKFLUSHQTY               VARCHAR(1),
    ITEMCHARACTERISTIC1             VARCHAR(25),
    ITEMCHARACTERISTIC2             VARCHAR(25),
    COMMODITYCLASS                  VARCHAR(25),
    STOCKCATEGORY                   VARCHAR(25),
    COUNTRYOFORIGIN                 VARCHAR(25),
    COLLECTION                      VARCHAR(25),
    THEME                           VARCHAR(25),
    SEASON                          VARCHAR(25),
    STYLE                           VARCHAR(25),
    COLOR                           VARCHAR(25),
    SKUSIZE                         VARCHAR(25),
    CAMPAIGNSTART                   VARCHAR(25),
    CAMPAIGNEND                     VARCHAR(25),
    ALLOWMULTILOTLPN                VARCHAR(1),
    RECEIPTUNITLABELNAME            VARCHAR(20),
    RECEIPTUNITLABELUOM             VARCHAR(10),
    QCFIRSTCOMPL                    VARCHAR(1),
    NEWALLOCATIONSTRATEGY           VARCHAR(10),
    SLOTGROUP                       VARCHAR(15),
    PICKCONTPLACEMENT               VARCHAR(10),
    FORCEUOMREPLENQTY               VARCHAR(1),
    DATACAPTURESTRATEGYKEY          VARCHAR(10),
    SERIALPARCINGSTRATEGYKEY        VARCHAR(10),
    ICWVALIDATIONUOMLEVEL           VARCHAR(10),
    OCWVALIDATIONUOMLEVEL           VARCHAR(10),
    ICWAVGGROSSWEIGHT               DECIMAL(22, 5),
    ICWAVGNETWEIGHT                 DECIMAL(22, 5),
    ICWAVGTAREWEIGHT                DECIMAL(22, 5),
    ICWTOLERANCEPCT                 DECIMAL(12, 6),
    OCWAVGGROSSWEIGHT               DECIMAL(22, 5),
    OCWAVGNETWEIGHT                 DECIMAL(22, 5),
    OCWAVGTAREWEIGHT                DECIMAL(22, 5),
    OCWTOLERANCEPCT                 DECIMAL(12, 6),
    STDWEIGHTUOMLEVEL               VARCHAR(10),
    STDGROSSWEIGHT                  DECIMAL(22, 5),
    STDNETWEIGHT                    DECIMAL(22, 5),
    STDTAREWEIGHT                   DECIMAL(22, 5),
    ADDDATE                         DATETIME,
    ADDWHO                          VARCHAR(256),
    EDITDATE                        DATETIME,
    EDITWHO                         VARCHAR(256),
    SHELFLIFE_PERCENTAGE            INT,
    SHELFLIFEONRECEIVING_PERCENTAGE INT,
    SHELFLIFE_EDITDATE              DATETIME,
    NEEDMEASUREMENT                 INT
);

CREATE TABLE IF NOT EXISTS WMWHSE1.LOTXLOCXID
(
    SERIALKEY              INT NOT NULL,
    WHSEID                 VARCHAR(30),
    LOT                    VARCHAR(10),
    LOC                    VARCHAR(10),
    ID                     VARCHAR(50),
    STORERKEY              VARCHAR(15),
    SKU                    VARCHAR(50),
    QTY                    DECIMAL(22, 5),
    QTYALLOCATED           DECIMAL(22, 5),
    QTYPICKED              DECIMAL(22, 5),
    QTYEXPECTED            DECIMAL(22, 5),
    QTYPICKINPROCESS       DECIMAL(22, 5),
    PENDINGMOVEIN          DECIMAL(22, 5),
    ARCHIVEQTY             DECIMAL(22, 5),
    ARCHIVEDATE            DATETIME,
    STATUS                 VARCHAR(10),
    TAREWGT                DECIMAL(22, 5),
    NETWGT                 DECIMAL(22, 5),
    GROSSWGT               DECIMAL(22, 5),
    ADDDATE                DATETIME,
    ADDWHO                 VARCHAR(256),
    EDITDATE               DATETIME,
    EDITWHO                VARCHAR(256),
    SHAREDWIDTHFROMLOC     VARCHAR(10),
    SHAREDWIDTHFROMLOCPCT  INT,
    SHAREDWEIGHTFROMLOC    VARCHAR(10),
    SHAREDWEIGHTFROMLOCQTY DECIMAL(22, 5)
);

create table if not exists wmwhse1.PUTAWAYZONE
(
    SERIALKEY int AUTO_INCREMENT,
    WHSEID nvarchar(30) default 'test',
    PUTAWAYZONE nvarchar(10) default '' not null primary key,
    DESCR nvarchar(60) default '' not null,
    INLOC nvarchar(10) default '' not null,
    OUTLOC nvarchar(10) default '' not null,
    UOM1PICKMETHOD nvarchar(1) default '1' not null,
    UOM2PICKMETHOD nvarchar(1) default '3' not null,
    UOM3PICKMETHOD nvarchar(1) default '3' not null,
    UOM4PICKMETHOD nvarchar(1) default '1' not null,
    UOM5PICKMETHOD nvarchar(1) default '3' not null,
    UOM6PICKMETHOD nvarchar(1) default '3' not null,
    CLEAN_LOCATION nvarchar(1) default '0',
    TOP_OFF nvarchar(1) default 'A',
    REPLENISHMENT_FLAG nvarchar(1) default '0',
    REPLENISHMENT_HOTLEVEL nvarchar(1) default '6',
    REPLENISHMENTMETHOD nvarchar(10) default '0' not null,
    MAXCUBE float default 0 not null,
    MAXWEIGHT float default 0 not null,
    MAXCASECNT decimal(22,5) default 0 not null,
    PICKTOLOC nvarchar(10) default 'PICKTO',
    MaxPalletsPerSku int default 0 not null,
    POSVERMETHOD nvarchar(10) default 'LOC' not null,
    PICKCC nvarchar(1) default '0' not null,
    QTYCC decimal(22,5) default 0 not null,
    CREATEASSIGNMENTS nvarchar(1) default '0' not null,
    ZONEBREAK nvarchar(1) default '0' not null,
    MAXPICKLINES int default 100 not null,
    MAXPICKINGCONTAINERS int default 0 not null,
    LABORMAXCASECNT int default 0 not null,
    LABORMAXCUBE int default 0 not null,
    LABORMAXWEIGHT int default 0 not null,
    AISLESTART int default 1 not null,
    AISLEEND int default 1 not null,
    SLOTSTART int default 1 not null,
    SLOTEND int default 1 not null,
    AUTOPRINTADDRLABEL nvarchar(1) default '0' not null,
    AUTOPRINTCARTONCONTENT nvarchar(1) default '0' not null,
    DEFAULTLABELPRINTER nvarchar(45),
    DEFAULTREPORTPRINTER nvarchar(45),
    ABANDONLOC nvarchar(10) default 'LOST',
    IGNORESTAGELOC nvarchar(1) default '0',
    BUILDCLUSTERASSN nvarchar(1) default '0' not null,
    ASSIGNCARTONGRP nvarchar(10),
    TRACKMOVETODOCK nvarchar(1) default '1' not null,
    MAXLOCWGHTSHAREPCT int default 0 not null,
    RFPICKSTRATEGYKEY nvarchar(10),
    ADDDATE datetime default now() not null,
    ADDWHO nvarchar(256) default 'test' not null,
    EDITDATE datetime default now() not null,
    EDITWHO nvarchar(256) default 'test' not null,
    TYPE nvarchar(50) default 'UNDEFINED' not null,
    maxWeightPickingOrd numeric(10,4),
    maxVolumePickingOrd numeric(10,4),
    maxItemsPickingOrd int
);

CREATE TABLE IF NOT EXISTS WMWHSE1.LOTATTRIBUTE
(
    SERIALKEY   INT,
    WHSEID      VARCHAR(30),
    STORERKEY   VARCHAR(15),
    SKU         VARCHAR(50),
    LOT         VARCHAR(10),
    LOTTABLE01  VARCHAR(50),
    LOTTABLE02  VARCHAR(50),
    LOTTABLE03  VARCHAR(50),
    LOTTABLE04  DATETIME,
    LOTTABLE05  DATETIME,
    LOTTABLE06  VARCHAR(50),
    LOTTABLE07  VARCHAR(50),
    LOTTABLE08  VARCHAR(50),
    LOTTABLE09  VARCHAR(50),
    LOTTABLE10  VARCHAR(50),
    EXTERNALLOT VARCHAR(100),
    LOTTABLE11  DATETIME,
    LOTTABLE12  DATETIME,
    ADDDATE     DATETIME,
    ADDWHO      VARCHAR(256),
    EDITDATE    DATETIME,
    EDITWHO     VARCHAR(256)
);

CREATE TABLE IF NOT EXISTS WMWHSE1.LOT
(
    SERIALKEY            INT,
    WHSEID               VARCHAR(30),
    LOT                  VARCHAR(10),
    STORERKEY            VARCHAR(15),
    SKU                  VARCHAR(50),
    CASECNT              DECIMAL(22, 5),
    INNERPACK            DECIMAL(22, 5),
    QTY                  DECIMAL(22, 5),
    PALLET               DECIMAL(22, 5),
    CUBE                 FLOAT,
    GROSSWGT             DECIMAL(22, 5),
    NETWGT               DECIMAL(22, 5),
    OTHERUNIT1           FLOAT,
    OTHERUNIT2           FLOAT,
    QTYPREALLOCATED      DECIMAL(22, 5),
    QTYALLOCATED         DECIMAL(22, 5),
    QTYPICKED            DECIMAL(22, 5),
    QTYONHOLD            DECIMAL(22, 5),
    STATUS               VARCHAR(10),
    ARCHIVEQTY           DECIMAL(22, 5),
    ARCHIVEDATE          DATETIME,
    ADDDATE              DATETIME,
    ADDWHO               VARCHAR(256),
    EDITDATE             DATETIME,
    EDITWHO              VARCHAR(256),
    GROSSWGTPREALLOCATED FLOAT,
    NETWGTPREALLOCATED   FLOAT,
    GROSSWGTALLOCATED    FLOAT,
    NETWGTALLOCATED      FLOAT,
    GROSSWGTPICKED       FLOAT,
    NETWGTPICKED         FLOAT,
    TAREWGT              DECIMAL(22, 5)
);

CREATE TABLE IF NOT EXISTS WMWHSE1.LOC
(
    SERIALKEY                  INT,
    WHSEID                     VARCHAR(30),
    LOC                        VARCHAR(10),
    CUBE                       FLOAT,
    LENGTH                     FLOAT,
    WIDTH                      FLOAT,
    HEIGHT                     FLOAT,
    LOCATIONTYPE               VARCHAR(10),
    LOCATIONFLAG               VARCHAR(10),
    LOCATIONHANDLING           VARCHAR(10),
    LOCATIONCATEGORY           VARCHAR(10),
    LOGICALLOCATION            VARCHAR(18),
    CUBICCAPACITY              FLOAT,
    WEIGHTCAPACITY             FLOAT,
    STATUS                     VARCHAR(10),
    LOSEID                     VARCHAR(1),
    FACILITY                   VARCHAR(256),
    SECTION                    VARCHAR(10),
    ABC                        VARCHAR(1),
    PICKZONE                   VARCHAR(10),
    PUTAWAYZONE                VARCHAR(10),
    SECTIONKEY                 VARCHAR(10),
    PICKMETHOD                 VARCHAR(1),
    COMMINGLESKU               VARCHAR(1),
    COMMINGLELOT               VARCHAR(1),
    LOCLEVEL                   INT,
    XCOORD                     INT,
    YCOORD                     INT,
    ZCOORD                     INT,
    OPTLOC                     VARCHAR(10),
    StackLimit                 INT,
    FootPrint                  INT,
    ORIENTATION                INT,
    INTERLEAVINGSEQUENCE       INT,
    AutoShip                   INT,
    CYCLECLASS                 VARCHAR(10),
    LASTCCRELEASEDATE          DATETIME,
    LASTLOCCOUNTDATE           DATETIME,
    MAXDOCKASSIGNORDERS        INT,
    MAXDOCKASSIGNESTPALLETS    DECIMAL(22, 5),
    BACKFLUSHINDICATOR         VARCHAR(1),
    PRODSTAGELOC               VARCHAR(10),
    LPNSORTALLOCATION          VARCHAR(10),
    ALLOCATIONZONE             VARCHAR(10),
    ADDDATE                    DATETIME,
    ADDWHO                     VARCHAR(256),
    EDITDATE                   DATETIME,
    EDITWHO                    VARCHAR(256),
    LOCGROUPID                 INT,
    COMMINGLELOTTABLE1         VARCHAR(1),
    COMMINGLELOTTABLE2         VARCHAR(1),
    COMMINGLELOTTABLE3         VARCHAR(1),
    COMMINGLELOTTABLE6         VARCHAR(1),
    COMMINGLELOTTABLE7         VARCHAR(1),
    COMMINGLELOTTABLE8         VARCHAR(1),
    COMMINGLELOTTABLE9         VARCHAR(1),
    COMMINGLELOTTABLE10        VARCHAR(1),
    CHECKDIGIT                 VARCHAR(3),
    SHAREWIDTHFROMLOC          VARCHAR(10),
    SHAREWEIGHTCAPACITYFROMLOC VARCHAR(10)
);

CREATE TABLE IF NOT EXISTS WMWHSE1.BILLOFMATERIAL
(
    SERIALKEY    INT,
    WHSEID       VARCHAR(30),
    STORERKEY    VARCHAR(15),
    SKU          VARCHAR(50),
    COMPONENTSKU VARCHAR(50),
    SEQUENCE     VARCHAR(10),
    BOMONLY      VARCHAR(1),
    QTY          DECIMAL(22, 5),
    ADDDATE      DATETIME,
    ADDWHO       VARCHAR(256),
    EDITDATE     DATETIME,
    EDITWHO      VARCHAR(256),
    NOTES        VARCHAR(512)
);

CREATE TABLE IF NOT EXISTS WMWHSE1.INVENTORYHOLDCODE
(
    SERIALKEY     INT IDENTITY(1,1),
    WHSEID        VARCHAR(30),
    CODE          VARCHAR(10),
    RANK          INT,
    DESCRIPTION   VARCHAR(250),
    SOURCEVERSION INT,
    ADDDATE       DATETIME,
    ADDWHO        VARCHAR(256),
    EDITDATE      DATETIME,
    EDITWHO       VARCHAR(256),
    IS_EXPIRING   BIT,
    IS_DAMAGE     BIT
);

CREATE TABLE IF NOT EXISTS WMWHSE1.INVENTORYHOLD
(
    SERIALKEY        int,
    WHSEID           VARCHAR(30),
    INVENTORYHOLDKEY VARCHAR(10),
    LOT              VARCHAR(10),
    ID               VARCHAR(50),
    LOC              VARCHAR(10),
    HOLD             VARCHAR(1),
    STATUS           VARCHAR(10),
    DATEON           DATETIME,
    WHOON            VARCHAR(256),
    DATEOFF          DATETIME,
    WHOOFF           VARCHAR(256),
    COMMENTS         VARCHAR(60),
    HOURSTOHOLD      DECIMAL(10, 2),
    AUTORELEASEDATE  DATETIME,
    ADDDATE          DATETIME,
    ADDWHO           VARCHAR(256),
    EDITDATE         DATETIME,
    EDITWHO          VARCHAR(256)
);


CREATE VIEW IF NOT EXISTS WMWHSE1.vLotExpired AS
SELECT a.LOT,
       case when s.SHELFLIFECODETYPE = 'E' then 'Expiration' else 'Manufactured' end AS CheckBy,
       s.ROTATEBY,
       DATEADD(dd,- s.SHELFLIFE + 1,isnull(a.LOTTABLE05,dateadd(dd,s.TOEXPIREDAYS, a.LOTTABLE04))) AS DateX,
       a.LOTTABLE04,
       a.LOTTABLE05,
       s.SHELFLIFE,
       c.QTY,
       a.STORERKEY,
       a.SKU
FROM WMWHSE1.LOTATTRIBUTE AS a
    JOIN WMWHSE1.LOT AS c ON a.LOT = c.LOT
    JOIN WMWHSE1.SKU AS s ON a.STORERKEY = s.STORERKEY AND a.SKU = s.SKU
WHERE c.QTY > 0
  AND s.SHELFLIFEINDICATOR = 'Y'
  and isnull(a.LOTTABLE05,dateadd(dd,s.TOEXPIREDAYS, a.LOTTABLE04))< DATEADD(dd, s.SHELFLIFE,GETDATE());


CREATE TABLE IF NOT EXISTS wmwhse1.PACK
(
    SERIALKEY          INT,
    WHSEID             VARCHAR(30),
    PACKKEY            VARCHAR(50),
    PACKDESCR          VARCHAR(45),
    PACKUOM1           VARCHAR(10),
    CASECNT            FLOAT,
    ISWHQTY1           VARCHAR(1),
    REPLENISHUOM1      VARCHAR(1),
    REPLENISHZONE1     VARCHAR(10),
    CARTONIZEUOM1      VARCHAR(1),
    LENGTHUOM1         FLOAT,
    WIDTHUOM1          FLOAT,
    HEIGHTUOM1         FLOAT,
    CUBEUOM1           FLOAT,
    FilterValueUOM1    INT      NULL,
    IndicatorDigitUOM1 INT      NULL,
    PACKUOM2           VARCHAR(10),
    INNERPACK          FLOAT,
    ISWHQTY2           VARCHAR(1),
    REPLENISHUOM2      VARCHAR(1),
    REPLENISHZONE2     VARCHAR(10),
    CARTONIZEUOM2      VARCHAR(1),
    LENGTHUOM2         FLOAT,
    WIDTHUOM2          FLOAT,
    HEIGHTUOM2         FLOAT,
    CUBEUOM2           FLOAT,
    FilterValueUOM2    INT,
    IndicatorDigitUOM2 INT,
    PACKUOM3           VARCHAR(10),
    QTY                DECIMAL(22, 5),
    ISWHQTY3           VARCHAR(1),
    REPLENISHUOM3      VARCHAR(1),
    REPLENISHZONE3     VARCHAR(10),
    CARTONIZEUOM3      VARCHAR(1),
    LENGTHUOM3         FLOAT,
    WIDTHUOM3          FLOAT,
    HEIGHTUOM3         FLOAT,
    CUBEUOM3           FLOAT,
    FilterValueUOM3    INT,
    IndicatorDigitUOM3 INT,
    PACKUOM4           VARCHAR(10),
    PALLET             FLOAT,
    ISWHQTY4           VARCHAR(1),
    REPLENISHUOM4      VARCHAR(1),
    REPLENISHZONE4     VARCHAR(10),
    CARTONIZEUOM4      VARCHAR(1),
    LENGTHUOM4         FLOAT NULL,
    WIDTHUOM4          FLOAT NULL,
    HEIGHTUOM4         FLOAT NULL,
    CUBEUOM4           FLOAT NULL,
    FilterValueUOM4    INT,
    IndicatorDigitUOM4 INT,
    PALLETWOODLENGTH   FLOAT,
    PALLETWOODWIDTH    FLOAT,
    PALLETWOODHEIGHT   FLOAT,
    PALLETTI           DECIMAL(22, 5),
    PALLETHI           DECIMAL(22, 5),
    PACKUOM5           VARCHAR(10),
    CUBE               FLOAT NULL,
    ISWHQTY5           VARCHAR(1),
    FilterValueUOM5    INT,
    IndicatorDigitUOM5 INT,
    PACKUOM6           VARCHAR(10),
    GROSSWGT           FLOAT,
    ISWHQTY6           VARCHAR(1),
    FilterValueUOM6    INT,
    IndicatorDigitUOM6 INT,
    PACKUOM7           VARCHAR(10),
    NETWGT             FLOAT,
    ISWHQTY7           VARCHAR(1),
    FilterValueUOM7    INT,
    IndicatorDigitUOM7 INT,
    PACKUOM8           VARCHAR(10),
    OTHERUNIT1         FLOAT,
    ISWHQTY8           VARCHAR(1),
    REPLENISHUOM8      VARCHAR(1),
    REPLENISHZONE8     VARCHAR(10),
    CARTONIZEUOM8      VARCHAR(1),
    LENGTHUOM8         FLOAT,
    WIDTHUOM8          FLOAT,
    HEIGHTUOM8         FLOAT,
    FilterValueUOM8    INT,
    IndicatorDigitUOM8 INT,
    PACKUOM9           VARCHAR(10),
    OTHERUNIT2         FLOAT,
    ISWHQTY9           VARCHAR(1),
    REPLENISHUOM9      VARCHAR(1),
    REPLENISHZONE9     VARCHAR(10),
    CARTONIZEUOM9      VARCHAR(1),
    LENGTHUOM9         FLOAT,
    WIDTHUOM9          FLOAT,
    HEIGHTUOM9         FLOAT,
    FilterValueUOM9    INT,
    IndicatorDigitUOM9 INT,
    ACCOUNTINGENTITY   VARCHAR(64),
    ADDDATE            DATETIME,
    ADDWHO             VARCHAR(256),
    EDITDATE           DATETIME,
    EDITWHO            VARCHAR(256)
);


CREATE TABLE IF NOT EXISTS wmwhse1.ALTSKU
(
    SERIALKEY  INT,
    WHSEID     VARCHAR(30),
    STORERKEY  VARCHAR(15),
    SKU        VARCHAR(50),
    ALTSKU     VARCHAR(50),
    VENDOR     VARCHAR(15),
    PACKKEY    VARCHAR(50),
    DEFAULTUOM VARCHAR(10),
    TYPE       VARCHAR(10),
    UDF1       VARCHAR(32),
    UDF2       VARCHAR(32),
    UDF3       VARCHAR(32),
    UDF4       VARCHAR(32),
    UDF5       VARCHAR(32),
    ADDDATE    DATETIME,
    ADDWHO     VARCHAR(256),
    EDITDATE   DATETIME,
    EDITWHO    VARCHAR(256)
);

-- this is fake table, mimicking vInventoryDetail. DBUNIT does not like definition of vInventoryDetail.
CREATE TABLE IF NOT EXISTS WMWHSE1.vInventoryDetail
(
    STORERKEY        VARCHAR(15),
    SKU              VARCHAR(50),
    bom_sku          VARCHAR(50),
    sku_serialkey    INT,
    current_offset   INT,
    QTY              DECIMAL(22, 5),
    QtyAllocated     DECIMAL(22, 5),
    QtyPicked        DECIMAL(22, 5),
    Tarewgt          DECIMAL(22, 5),
    Grosswgt         DECIMAL(22, 5),
    Netwgt           DECIMAL(22, 5),
    qtypreallocated  DECIMAL(22, 5),
    qtydefect        DECIMAL(22, 5),
    qtyexpired       DECIMAL(22, 5),
    qtysurplus       DECIMAL(22, 5),
    qtyquarantine    DECIMAL(22, 5),
    qtyonhold        DECIMAL(22, 5),
    manufacturedates DATETIME,
    QtySusr1         int,
    qty_item_bom     int,
    qty_in_master    int,
    lastupdatestock  DATETIME
);

CREATE TABLE IF NOT EXISTS wmwhse1.delivery_service_cutoffs
(
    SERIALKEY             INT,
    delivery_service_code NVARCHAR(15),
    order_creation_cutoff VARCHAR(10),
    picking_cutoff        VARCHAR(10),
    shipping_cutoff       VARCHAR(10),
    warehouse_cutoff      VARCHAR(10),
    adddate               DATETIME,
    addwho                NVARCHAR(256),
    editdate              DATETIME,
    editwho               NVARCHAR(256),
    comment               VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS wmwhse1.DELIVERY_SERVICE_CUTOFFS_DIFF
(
    delivery_service_code nvarchar(15),
    order_creation_cutoff varchar(10),
    picking_cutoff        varchar(10),
    shipping_cutoff       varchar(10),
    adddate               datetime,
    addwho                nvarchar(256),
    editdate              datetime,
    editwho               nvarchar(256),
    comment               varchar(255),
    warehouse_cutoff      varchar(10)
);

CREATE TABLE if not exists wmwhse1.IDENTITY_TYPE
(
    SERIALKEY   INT IDENTITY(1,1) NOT NULL,
    TYPE        nvarchar(255) NOT NULL,
    REGEX       nvarchar(255) NOT NULL,
    DESCRIPTION nvarchar(255) NULL,
    adddate               DATETIME,
    addwho                NVARCHAR(256),
    editdate              DATETIME,
    editwho               NVARCHAR(256)
);

CREATE TABLE if not exists wmwhse1.SKU_IDENTITY(
                                     SERIALKEY int IDENTITY(1,1) NOT NULL,
                                     STORER nvarchar(15) NOT NULL,
                                     SKU nvarchar(50) NOT NULL,
                                     TYPE nvarchar(255) NOT NULL,
                                     REQUIREMENT int NOT NULL,
                                     adddate               DATETIME,
                                     addwho                NVARCHAR(256),
                                     editdate              DATETIME,
                                     editwho               NVARCHAR(256),
                                     MARK_HANDLE_MODE int
);

CREATE TABLE if not exists wmwhse1.SKU_CARGOTYPES(
                                       SERIALKEY int IDENTITY(1,1) NOT NULL,
                                       STORERKEY nvarchar(15) NOT NULL,
                                       SKU nvarchar(50) NOT NULL,
                                       CARGOTYPE int NOT NULL,
                                       adddate               DATETIME,
                                       addwho                NVARCHAR(256),
                                       editdate              DATETIME,
                                       editwho               NVARCHAR(256)
);

CREATE TABLE IF NOT EXISTS wmwhse1.STORER
(
    SERIALKEY                    INT,
    WHSEID                       NVARCHAR(30)   default 'wmwhse1',
    STORERKEY                    NVARCHAR(15)                        not null,
    TYPE                         NVARCHAR(30)   default '1'          not null,
    SOURCEVERSION                NVARCHAR(22)   default '0'          not null,
    COMPANY                      NVARCHAR(45)   default '',
    VAT                          NVARCHAR(18),
    ADDRESS1                     NVARCHAR(45),
    ADDRESS2                     NVARCHAR(45),
    ADDRESS3                     NVARCHAR(45),
    ADDRESS4                     NVARCHAR(45),
    CITY                         NVARCHAR(45),
    STATE                        NVARCHAR(25)   default '',
    ZIP                          NVARCHAR(18)   default '',
    COUNTRY                      NVARCHAR(30)   default '',
    ISOCNTRYCODE                 NVARCHAR(10),
    CONTACT1                     NVARCHAR(30),
    CONTACT2                     NVARCHAR(30),
    PHONE1                       NVARCHAR(18),
    PHONE2                       NVARCHAR(18),
    FAX1                         NVARCHAR(18),
    FAX2                         NVARCHAR(18),
    EMAIL1                       NVARCHAR(60),
    EMAIL2                       NVARCHAR(60),
    B_CONTACT1                   NVARCHAR(30),
    B_CONTACT2                   NVARCHAR(30),
    B_COMPANY                    NVARCHAR(45),
    B_ADDRESS1                   NVARCHAR(45),
    B_ADDRESS2                   NVARCHAR(45),
    B_ADDRESS3                   NVARCHAR(45),
    B_ADDRESS4                   NVARCHAR(45),
    B_CITY                       NVARCHAR(45),
    B_STATE                      NVARCHAR(25),
    B_ZIP                        NVARCHAR(18),
    B_COUNTRY                    NVARCHAR(30),
    B_ISOCNTRYCODE               NVARCHAR(10),
    B_PHONE1                     NVARCHAR(18),
    B_PHONE2                     NVARCHAR(18),
    B_FAX1                       NVARCHAR(18),
    B_FAX2                       NVARCHAR(18),
    B_EMAIL1                     NVARCHAR(60),
    B_EMAIL2                     NVARCHAR(60),
    CREDITLIMIT                  NVARCHAR(18),
    CARTONGROUP                  NVARCHAR(10)   default 'STD'        not null,
    PICKCODE                     NVARCHAR(10)   default 'NSPFIFO'    not null,
    CREATEPATASKONRFRECEIPT      NVARCHAR(10)   default '0'          not null,
    CALCULATEPUTAWAYLOCATION     NVARCHAR(10)   default '2'          not null,
    STATUS                       NVARCHAR(18),
    DEFAULTSTRATEGY              NVARCHAR(10),
    DEFAULTSKUROTATION           NVARCHAR(10)   default 'Lot',
    DEFAULTROTATION              NVARCHAR       default '1',
    SCAC_CODE                    NVARCHAR(10),
    TITLE1                       NVARCHAR(50),
    TITLE2                       NVARCHAR(50),
    DESCRIPTION                  NVARCHAR(50),
    SUSR1                        NVARCHAR(30),
    SUSR2                        NVARCHAR(30),
    SUSR3                        NVARCHAR(30),
    SUSR4                        NVARCHAR(30),
    SUSR5                        NVARCHAR(30),
    SUSR6                        NVARCHAR(30),
    MULTIZONEPLPA                NVARCHAR       default '0',
    CWOFLAG                      NVARCHAR       default '',
    ROLLRECEIPT                  NVARCHAR       default '1'          not null,
    NOTES1                       NVARCHAR(2000),
    NOTES2                       NVARCHAR(2000),
    APPORTIONRULE                NVARCHAR(10)   default '0',
    ENABLEOPPXDOCK               NVARCHAR       default '0',
    ALLOWOVERSHIPMENT            NVARCHAR       default '0',
    MAXIMUMORDERS                INT            default 0,
    MINIMUMPERCENT               DECIMAL(12, 6) default 0.0,
    ORDERDATESTARTDAYS           INT            default 1,
    ORDERDATEENDDAYS             INT            default 1,
    ORDERTYPERESTRICT01          NVARCHAR(10),
    ORDERTYPERESTRICT02          NVARCHAR(10),
    ORDERTYPERESTRICT03          NVARCHAR(10),
    ORDERTYPERESTRICT04          NVARCHAR(10),
    ORDERTYPERESTRICT05          NVARCHAR(10),
    ORDERTYPERESTRICT06          NVARCHAR(10),
    OPPORDERSTRATEGYKEY          NVARCHAR(10),
    RECEIPTVALIDATIONTEMPLATE    NVARCHAR(18)   default ''           not null,
    ALLOWAUTOCLOSEFORPO          NVARCHAR       default '1'          not null,
    ALLOWAUTOCLOSEFORASN         NVARCHAR       default '1'          not null,
    ALLOWAUTOCLOSEFORPS          NVARCHAR       default '1'          not null,
    ALLOWSYSTEMGENERATEDLPN      NVARCHAR       default '1'          not null,
    ALLOWDUPLICATELICENSEPLATES  NVARCHAR       default '1'          not null,
    ALLOWCOMMINGLEDLPN           NVARCHAR       default '1'          not null,
    LPNBARCODESYMBOLOGY          NVARCHAR(60)   default '1',
    LPNBARCODEFORMAT             NVARCHAR(60)   default '',
    ALLOWSINGLESCANRECEIVING     NVARCHAR       default '1'          not null,
    LPNLENGTH                    INT            default 6            not null,
    APPLICATIONID                NVARCHAR(2)    default '00'         not null,
    SSCC1STDIGIT                 INT            default '0'          not null,
    UCCVENDORNUMBER              NVARCHAR(9)    default ' '          not null,
    CASELABELTYPE                NVARCHAR(10)   default 'STD',
    AUTOPRINTLABELLPN            NVARCHAR       default '1'          not null,
    AUTOPRINTLABELPUTAWAY        NVARCHAR       default '1'          not null,
    LPNSTARTNUMBER               NVARCHAR(50)   default ''           not null,
    NEXTLPNNUMBER                NVARCHAR(50)   default ''           not null,
    LPNROLLBACKNUMBER            NVARCHAR(50)   default ''           not null,
    BARCODECONFIGKEY             NVARCHAR(18),
    DEFAULTPUTAWAYSTRATEGY       NVARCHAR(10)   default 'STD',
    AUTOCLOSEASN                 NVARCHAR       default '0'          not null,
    AUTOCLOSEPO                  NVARCHAR       default '0'          not null,
    TRACKINVENTORYBY             NVARCHAR       default '0',
    DUPCASEID                    NVARCHAR       default '0',
    DEFAULTRETURNSLOC            NVARCHAR(10)   default 'RETURN'     not null,
    DEFAULTQCLOC                 NVARCHAR(10)   default 'QC'         not null,
    PISKUXLOC                    NVARCHAR       default '0'          not null,
    CCSKUXLOC                    NVARCHAR       default '0'          not null,
    CCDISCREPANCYRULE            NVARCHAR(10)   default 'STD'        not null,
    CCADJBYRF                    NVARCHAR(10)   default '0'          not null,
    ORDERBREAKDEFAULT            NVARCHAR       default '0'          not null,
    SKUSETUPREQUIRED             NVARCHAR       default '0'          not null,
    DEFAULTQCLOCOUT              NVARCHAR(10)   default 'PICKTO'     not null,
    ENABLEPACKINGDEFAULT         NVARCHAR       default '0',
    DEFAULTPACKINGLOCATION       NVARCHAR(10),
    GENERATEPACKLIST             NVARCHAR       default '0',
    PACKINGVALIDATIONTEMPLATE    NVARCHAR(10),
    INSPECTATPACK                NVARCHAR       default '0',
    ADDRESSOVERWRITEINDICATOR    NVARCHAR       default '0',
    ACCOUNTINGENTITY             NVARCHAR(64),
    CREATEOPPXDTASKS             INT            default 1,
    ISSUEOPPXDTASKS              INT            default 1,
    OPPXDPICKFROM                NVARCHAR(20)   default 'XDSTAGE',
    OBXDSTAGE                    NVARCHAR(20)   default 'XDLANE',
    KSHIP_CARRIER                INT            default 0            not null,
    SPSUOMWEIGHT                 NVARCHAR(10),
    SPSUOMDIMENSION              NVARCHAR(10),
    DEFDAPICKSORT                NVARCHAR       default '1',
    DEFRPLNSORT                  NVARCHAR       default '1',
    REQREASONSHORTSHIP           INT            default 0            not null,
    EXPLODELPNLENGTH             INT            default 9,
    EXPLODELPNROLLBACKNUMBER     NVARCHAR(18)   default '999999999',
    EXPLODELPNSTARTNUMBER        NVARCHAR(18)   default '000000001',
    EXPLODENEXTLPNNUMBER         NVARCHAR(18)   default '000000001',
    OWNERPREFIX                  NVARCHAR(18),
    CONTAINEREXCHANGEFLAG        INT            default 0            not null,
    CARTONIZEFTDFLT              NVARCHAR       default '0'          not null,
    DEFFTLABELPRINT              NVARCHAR       default '0'          not null,
    DEFFTTASKCONTROL             NVARCHAR       default '0'          not null,
    MEASURECODE                  NVARCHAR(10),
    WGTUOM                       NVARCHAR(20),
    DIMENUOM                     NVARCHAR(20),
    CUBEUOM                      NVARCHAR(20),
    CURRCODE                     NVARCHAR(3),
    TAXGROUP                     NVARCHAR(20),
    DEFCORPCODE                  NVARCHAR(40),
    SURCHGBASETEMP               DECIMAL(22, 5),
    AMBTEMPERATURE               DECIMAL(22, 5),
    INVOICETERMS                 NVARCHAR(10),
    ARCORP                       NVARCHAR(40),
    ARDEPT                       NVARCHAR(40),
    ARACCT                       NVARCHAR(40),
    INVOICELEVEL                 NVARCHAR(20),
    NONNEGLEVEL                  NVARCHAR(20),
    TAXID                        NVARCHAR(40),
    DUNSID                       NVARCHAR(40),
    RECURCODE                    NVARCHAR(10),
    QFSURCHARGE                  DECIMAL(22, 5),
    BFSURCHARGE                  DECIMAL(22, 5),
    TAXEXEMPT                    NVARCHAR(2),
    TAXEXEMPTCODE                NVARCHAR(40),
    TIMEZONE                     NVARCHAR(250),
    PLANDAYS                     SMALLINT       default 0            not null,
    ARCHIVEPLANNINGDAYS          SMALLINT       default 0            not null,
    ARCHIVEREPORTINGDATA         SMALLINT       default 0            not null,
    PLANENABLED                  SMALLINT       default 0            not null,
    DEFAULTHOURLYRATE            DECIMAL(9, 6)  default 0.0          not null,
    DISTCALCMETHOD               SMALLINT,
    MAXCORNERANGLE               SMALLINT,
    SAVESTANDARDSAUDIT           SMALLINT       default 0            not null,
    ADDRESS5                     NVARCHAR(45),
    ADDRESS6                     NVARCHAR(45),
    PARENT                       NVARCHAR(15),
    SPSACCOUNTNUM                NVARCHAR(40),
    SPSCOSTCENTER                NVARCHAR(20),
    SPSRETURNLABEL               NVARCHAR,
    AMSTRATEGYKEY                NVARCHAR(10),
    TEMPFORASN                   NVARCHAR       default 'N'          not null,
    MIXEDLPNPUTSTRATEGY          NVARCHAR(10)   default 'STD'        not null,
    GROUPFTEACHDFLT              NVARCHAR       default '1',
    ALLOCATEFTONCLOSE            NVARCHAR       default '0',
    SPS_SCAC                     NVARCHAR(10),
    SPSAPISTRATEGYKEY            NVARCHAR(10),
    PRINTPACKLIST                NVARCHAR(10)   default '0',
    PRINTPACKTEMPLATE            NVARCHAR(10)   default '0',
    PRINTCONTENTSREPORT          NVARCHAR(10)   default '0',
    PKTRACKINGID                 NVARCHAR       default '0',
    AUTOPRINTADDRESSLABEL        NVARCHAR       default '0',
    AUTOPRINTORDERLABELS         NVARCHAR       default '0',
    LOCALE                       NVARCHAR(10),
    PAYROLLPERIOD                NVARCHAR(20),
    INITIALPAYROLLPERIODENDDATE  DATETIME,
    PAYROLLEXTRACTFOLDER         NVARCHAR(MAX),
    INCREMENTALEXTRACT           NVARCHAR       default '0',
    DAYBOUNDARYMINUTES           INT,
    AUTOMATICFIRSTACTIVITY       NVARCHAR(30),
    VENDORCOMPLYSTRATEGYKEY      NVARCHAR(10),
    BACKORDER                    NVARCHAR(10),
    BOTYPE                       NVARCHAR(10)   default '12',
    DEFAULTTRANSPORTATIONSERVICE NVARCHAR(10),
    DEFAULTEQUIPMENTATTRIBUTE    NVARCHAR(10),
    DEFAULTEQUIPMENTTYPE         NVARCHAR(10),
    DEFAULTEQUIPMENTLENGTH       NVARCHAR(10),
    MIXPALLETPUTAWAYMETHOD       NVARCHAR       default '0',
    DFLTEQUIPMENTFORASSGN        NVARCHAR(50),
    DFLTEQUIPMENTFORPALLET       NVARCHAR(50),
    RFAUTOFILLRCVLPN             NVARCHAR       default '1'          not null,
    INBOUNDLPNLENGTH             INT            default 0            not null,
    INBOUNDLPNPREFIX             NVARCHAR(10),
    RFRCVAUTOPRINTLPN            NVARCHAR(10),
    RECEIPTUNITLABELNAME         NVARCHAR(20),
    RECEIPTUNITLABELUOM          NVARCHAR(10),
    LASTSHIPPEDLOTCTRL           NVARCHAR       default '0',
    ALLOCATIONLOTLIMIT           NVARCHAR       default '0',
    OUTLABELSREQUIREDTOSHIP      NVARCHAR(10),
    OUTLABELSREQUIREDTOBOL       NVARCHAR(10),
    OUTBOUNDLABELSLEVEL          NVARCHAR(10),
    OUTBOUNDLABELSCOUNTLEVEL     NVARCHAR(10),
    STANDARDOUTBOUNDLABELPREFIX  NVARCHAR(10),
    USEPARTNERLPNCONTROL         NVARCHAR       default '0'          not null,
    EXTERNSTORERKEY              NVARCHAR(100),
    DEFAULTNEWALLOCATIONSTRATEGY NVARCHAR(10),
    MINSHELFLIFEOVERRIDEPCT      INT            default 0,
    AUTOFINALIZEPRODORDER        NVARCHAR       default '0'          not null,
    CREATEMOVESFROMPROD          NVARCHAR       default '0'          not null,
    PRODCOUNTLOC                 NVARCHAR(10)   default 'CCPROD'     not null,
    SHIPTOGROUP                  NVARCHAR(10),
    PACKINGTOIDPREFIX            NVARCHAR(10),
    PACKINGTOIDLENGTH            INT            default 10,
    QUARANTINEINDICATOR          NVARCHAR       default '0'          not null,
    CDOFLAG                      NVARCHAR,
    ADDDATE                      DATETIME,
    ADDWHO                       NVARCHAR(256)  default 'test'  not null,
    EDITDATE                     DATETIME,
    EDITWHO                      NVARCHAR(256)  default 'test'  not null,
    primary key (STORERKEY, TYPE)
)
