// Autogenerated test file. Test skipped by default.

import { screen } from '@testing-library/react';

// atomic:test:field-layout
describe.skip('molecules/field-layout', () => {
    test('renders component successfully', () => {
        // TODO
        // render(<FieldLayout testId="test-field-layout" />);

        const element = screen.getByTestId('test-field-layout');

        expect(element).toBeInTheDocument();
    });
});
