// Autogenerated test file. Test skipped by default.

import { render, screen } from '@testing-library/react';

import { Label } from './label';

// atomic:test:label
describe.skip('molecules/label', () => {
    test('renders component successfully', () => {
        render(<Label testId="test-label" />);

        const element = screen.getByTestId('test-label');

        expect(element).toBeInTheDocument();
    });
});
