// Autogenerated test file. Test skipped by default.

import { render, screen } from '@testing-library/react';

import { ListBoxItem } from './list-box-item';

// atomic:test:list-box-item
describe.skip('atoms/list-box-item', () => {
    test('renders component successfully', () => {
        render(<ListBoxItem testId="test-list-box-item">Item</ListBoxItem>);

        const element = screen.getByTestId('test-list-box-item');

        expect(element).toBeInTheDocument();
    });
});
