// Autogenerated test file. Test skipped by default.

import { render, screen } from '@testing-library/react';

import { Popover } from './popover';

// atomic:test:popover
describe.skip('molecules/popover', () => {
    test('renders component successfully', () => {
        render(<Popover testId="test-popover" />);

        const element = screen.getByTestId('test-popover');

        expect(element).toBeInTheDocument();
    });
});
