// Autogenerated test file. Test skipped by default.

import { render, screen } from '@testing-library/react';
import { RangeControl } from './range-control';

// atomic:test:range-control
describe.skip('atoms/range-control', () => {
    test('renders component successfully', () => {
        render(<RangeControl size="sm" min={0} max={10} value={1} testId="test-range-control" />);

        const element = screen.getByTestId('test-range-control');

        expect(element).toBeInTheDocument();
    });
});
