// Autogenerated test file. Test skipped by default.

import { render, screen } from '@testing-library/react';
import { Range } from './range';

// atomic:test:range
describe.skip('molecules/range', () => {
    test('renders component successfully', () => {
        render(<Range value={[1, 2]} testId="test-range" />);

        const element = screen.getByTestId('test-range');

        expect(element).toBeInTheDocument();
    });
});
