// Autogenerated test file. Test skipped by default.

import { render, screen } from '@testing-library/react';

import { Select } from './select';

// atomic:test:select
describe.skip('organisms/select', () => {
    test('renders component successfully', () => {
        render(<Select testId="test-select" data={[]} />);

        const element = screen.getByTestId('test-select');

        expect(element).toBeInTheDocument();
    });
});
