/* eslint-disable max-len */

'use strict';

/**
 * @deprecated
 * use `__tests__/integration/sovetnik/product/search/model/by-url.iphone-x.stub.js`
 */
module.exports = {
    model: {
        name: 'Apple iPhone X 256GB',
        reviewsCount: 21,

        rating: 3.5,
        gradeCount: 88,
        prices: {
            max: 123990,
            min: 80720,
            avg: 85000,
            curCode: 'RUR',
            curName: 'руб.',
        },
        offersCount: 190,
        mainPhoto: {
            url: 'https://avatars.mds.yandex.net/get-mpic/397397/img_id7051974271832358544.png/orig',
            width: 321,
            height: 620,
        },
        isNew: 1,
        photo: 'https://avatars.mds.yandex.net/get-mpic/397397/img_id7051974271832358544.png/4hq',
        urls: {
            model: '<wrapped url>',
            modelPicture: '<wrapped url>',
            offers: '<wrapped url>',
            map: '<wrapped url>',
            price: '<wrapped url>',
            reviews: '<wrapped url>',
            reviewsBadge: '<wrapped url>',
        },
        links: {
            constants: {
                allPrices: 'Все цены',
                allPricesMarket: 'Все цены на Яндекс.Маркете',
                closestShops: 'Магазины рядом',
                shopsOnMap: 'Предложения магазинов на карте',
                reviews: 'Отзывы',
                reviewsMarket: 'Отзывы на Яндекс.Маркете',
            },
        },
        info: {
            constants: {
                atMarket: 'на Яндекс.Маркете',
                avgPrice: 'Средняя цена',
                avgPriceGraph: 'График средней цены на',
                ratingTooltipText: 'Рейтинг товара %s из 5',
            },
        },
    },
    offers: [
        {
            name: 'Мобильный телефон Apple iPhone X 256GB A1901 black',
            price: {
                value: 79990,
                currencyCode: 'RUR',
                currencyName: 'руб.',
            },
            category: {
                id: 91491,
                name: 'Мобильные телефоны',
                fullName: 'Мобильные телефоны',
                type: 'GURU',
                childCount: 0,
                advertisingModel: 'CPA',
                viewType: 'GRID',
            },
            target: 'pricebar',
            shopInfo: {
                name: 'Video-shoper.ru',
                id: 58825,
                rating: 5,
                gradeTotal: 10876,
                url: '<wrapped url>',
            },
            delivery: {
                free: false,
                pickup: true,
                brief: 'в Москву — 400 руб., возможен самовывоз',
                price: {
                    value: '400',
                    currencyCode: 'RUR',
                    currencyName: 'руб.',
                },
                delivery: true,
                daysFrom: 1,
                daysTo: 1,
                cityFrom: 'Москвы',
                cityTo: 'Москву',
            },
            photo: 'https://avatars.mds.yandex.net/get-marketpic/207337/market_ULfbbkMTv41Lu1DJf9IxQg/orig',
            source: 'Market',
            bigPhoto: {
                width: 175,
                height: 350,
                url: 'https://avatars.mds.yandex.net/get-marketpic/207337/market_ULfbbkMTv41Lu1DJf9IxQg/orig',
            },
            id:
                'yDpJekrrgZEgj5XdRwrVTQsR1FWEAtwxHfjRiNpcQzFOJXKWYsF_fNQLDnfVBnNJcjAmdp66o0PuyzcKx1CYK1Kv-hOP-93dmHv3lW5S154QPyXRpV9-RHK_0porEoDeDJu_Yv3oUp38rs7OpdSojpwXuqULpMaOyAonbeiREJuXvB3gQaOp3OCL8Y0RCRugxuk9sA9xc0ZP11KXGn9XNn5Btq8r0lYpDxpiigrFD_sv0yLkYRflTY8MEA4ZEtCAY8P7UtmoqZ3Za6i_xUyoxWA9K_DDkWVgtNAbaIj9qm2pk50KhN9buVvDYABhhn-K',
            url: '<wrapped url>',
            optOutUrl: '<wrapped url>',
            buttonUrl: '<wrapped url>',
            surfaceUrl: '<wrapped url>',
            warning: undefined,
            profitBadgeText: {
                value: '960 руб.',
                prefix: 'Экономия',
            },
            constants: {
                buttonText: 'В магазин',
                shopInfoTooltip: 'Перейти в магазин',
                shopRatingText: 'Рейтинг %s из 5 на основе',
            },
        },
        {
            name: 'Apple iPhone X 256GB Silver (A1902)',
            warning: undefined,
            price: {
                value: 80990,
                currencyCode: 'RUR',
                currencyName: 'руб.',
            },
            category: {
                id: 91491,
                name: 'Мобильные телефоны',
                fullName: 'Мобильные телефоны',
                type: 'GURU',
                childCount: 0,
                advertisingModel: 'CPA',
                viewType: 'GRID',
            },
            target: 'price-list',
            shopInfo: {
                name: '1CLICK',
                id: 262,
                rating: 5,
                gradeTotal: 5004,
                url: '<wrapped url>',
            },
            delivery: {
                free: true,
                pickup: true,
                brief: 'в Москву — бесплатно, возможен самовывоз',
                delivery: true,
                daysFrom: 2,
                daysTo: 2,
                cityFrom: 'Москвы',
                cityTo: 'Москву',
            },
            photo: 'https://avatars.mds.yandex.net/get-marketpic/362766/market_C4QeB98Ex-PKPnOV4sBfAg/orig',
            source: 'Market',
            bigPhoto: {
                width: 183,
                height: 350,
                url: 'https://avatars.mds.yandex.net/get-marketpic/362766/market_C4QeB98Ex-PKPnOV4sBfAg/orig',
            },
            id:
                'yDpJekrrgZHKK5VJLcLldAwa23oMqFsh5yChP7WCs0v5A2-WiSXd2jBBIm1cNSb72YYhPxrX9rMPpp238EFButKDEemH45VDN8hsmkZNLNNumgNNqlARyTsCTHZt4YM8aSLm8WPyLzynjNuSAmZk9Bldw3aUrX3tBRk62PYINIvy8pp5JnhDRHKZx8xPOS2HxT7_dzLEQfPO6QUVzf_fWnTnn2GHceXO0MDEeqTz0pYtMoo-be8H2oIIG7vluF8EUZ5UpvZHjNhVheQ4nbfxkT_Fh8yha2EgRy_vzMggDU3EnpxHHuEm_gsmv4qnNP6G',
            url: '<wrapped url>',
            buttonUrl: '<wrapped url>',
            constants: {
                buttonText: 'В магазин',
                shopInfoTooltip: 'Перейти в магазин',
                freeDelivery: 'Бесплатно',
                shopRatingText: 'Рейтинг %s из 5 на основе',
            },
        },
        {
            name: 'Смартфон Apple iPhone X 256GB Серый космос',
            warning: undefined,
            price: {
                value: 91990,
                currencyCode: 'RUR',
                currencyName: 'руб.',
            },
            category: {
                id: 91491,
                name: 'Мобильные телефоны',
                fullName: 'Мобильные телефоны',
                type: 'GURU',
                childCount: 0,
                advertisingModel: 'CPA',
                viewType: 'GRID',
            },
            target: 'price-list',
            shopInfo: {
                name: 'Phonempire.ru',
                id: 74832,
                rating: 5,
                gradeTotal: 2770,
                url: '<wrapped url>',
            },
            delivery: {
                free: false,
                pickup: true,
                brief: 'в Москву — 390 руб., возможен самовывоз',
                price: {
                    value: '390',
                    currencyCode: 'RUR',
                    currencyName: 'руб.',
                },
                delivery: true,
                daysFrom: 1,
                daysTo: 1,
                cityFrom: 'Москвы',
                cityTo: 'Москву',
            },
            photo: 'https://avatars.mds.yandex.net/get-marketpic/362398/market_8Z-xXYZnPnt5y8-6CVy39Q/orig',
            source: 'Market',
            bigPhoto: {
                width: 744,
                height: 744,
                url: 'https://avatars.mds.yandex.net/get-marketpic/362398/market_8Z-xXYZnPnt5y8-6CVy39Q/orig',
            },
            id:
                'yDpJekrrgZGaVr2CEwdjUlFkNCcGnuZRm5DUJarextK7_iwY3L0eDvaWAaU8xTlZZ9mQ68Xg7pr05-BxFidCtNkH-UKlHkHcdHsRpX5AE4TMzS22XJ-_4PpuEjUpUbf_gJNVgjiCi67drP7gE0wjpVD26MuVK862RJ0GPTkAK8LGzATiyOcxTCaGcIjsX7Y3IPuvPF3kn5OM6sGP_ZsZzz598VMf9dQI_nooxLbuV5MyxD-8BBidPFvSCJDrnOk2IWP3MLpAQxqqq7rRoZA2rrCTgHpd8FihI4QtK7Rt3lkkT6_yHnFpbx9FVwCx5mlf',
            url: '<wrapped url>',
            buttonUrl: '<wrapped url>',
            constants: {
                buttonText: 'В магазин',
                shopInfoTooltip: 'Перейти в магазин',
                shopRatingText: 'Рейтинг %s из 5 на основе',
            },
        },
        {
            name: 'Смартфон Apple iPhone X 256GB Серебристый',
            warning: undefined,
            price: {
                value: 91990,
                currencyCode: 'RUR',
                currencyName: 'руб.',
            },
            category: {
                id: 91491,
                name: 'Мобильные телефоны',
                fullName: 'Мобильные телефоны',
                type: 'GURU',
                childCount: 0,
                advertisingModel: 'CPA',
                viewType: 'GRID',
            },
            target: 'price-list',
            shopInfo: {
                name: 'Phonempire.ru',
                id: 74832,
                rating: 5,
                gradeTotal: 2770,
                url: '<wrapped url>',
            },
            delivery: {
                free: false,
                pickup: true,
                brief: 'в Москву — 390 руб., возможен самовывоз',
                price: {
                    value: '390',
                    currencyCode: 'RUR',
                    currencyName: 'руб.',
                },
                delivery: true,
                daysFrom: 1,
                daysTo: 1,
                cityFrom: 'Москвы',
                cityTo: 'Москву',
            },
            photo: 'https://avatars.mds.yandex.net/get-marketpic/165430/market_j8dSDt6hFZn4QuaIXWC2wQ/orig',
            source: 'Market',
            bigPhoto: {
                width: 800,
                height: 800,
                url: 'https://avatars.mds.yandex.net/get-marketpic/165430/market_j8dSDt6hFZn4QuaIXWC2wQ/orig',
            },
            id:
                'yDpJekrrgZFNpj2jvJaEeRgJzTcGbfRBfjxoWpHVBHh_wgaEJAeh-EZX1rShZiyP_oNJlH8AGv4xnImuweW58dFRnGe2Gp94P42kHQRnbYEgKdhYdiL4rCc3x6MsN6NTZjJLYBWWzEE-U0zfdnVkR1YjUiXVEkLKW7OcRvEKTDr0hHpqG6znoDcuXULBhUrCg_lCRmn0uO_bcKQfFiskf71ofTIk7MPZm8UQSNQrfKTNcmpQ2KqBjxyfi-8UfcBRdBNp_ChNdBKaT47Ih_oE9s5iCsyVrWD-ztWQcp-OD8DBy2ZQg-wwSZOHrxmfYENk',
            url: '<wrapped url>',
            buttonUrl: '<wrapped url>',
            constants: {
                buttonText: 'В магазин',
                shopInfoTooltip: 'Перейти в магазин',
                shopRatingText: 'Рейтинг %s из 5 на основе',
            },
        },
        {
            name: 'Apple iPhone X 256GB Space Gray (Серый космос)',
            warning: undefined,
            price: {
                value: 89290,
                currencyCode: 'RUR',
                currencyName: 'руб.',
            },
            category: {
                id: 91491,
                name: 'Мобильные телефоны',
                fullName: 'Мобильные телефоны',
                type: 'GURU',
                childCount: 0,
                advertisingModel: 'CPA',
                viewType: 'GRID',
            },
            target: 'price-list',
            shopInfo: {
                name: 'МегаФон',
                id: 37758,
                rating: 4,
                gradeTotal: 4105,
                url: '<wrapped url>',
            },
            delivery: {
                free: true,
                pickup: true,
                brief: 'в Москву — бесплатно, возможен самовывоз',
                delivery: true,
                daysFrom: 1,
                daysTo: 1,
                cityFrom: 'Москвы',
                cityTo: 'Москву',
            },
            photo: 'https://avatars.mds.yandex.net/get-marketpic/219360/market_TU_cHtGUlloDMxeK1MkHVg/orig',
            source: 'Market',
            bigPhoto: {
                width: 400,
                height: 675,
                url: 'https://avatars.mds.yandex.net/get-marketpic/219360/market_TU_cHtGUlloDMxeK1MkHVg/orig',
            },
            id:
                'yDpJekrrgZHS7ITIm-pb6kMjFMVC5y7ZX-CoSupKeH_9xkPNz69kXaRb0L1vUOZtghOc5A-D507_tHQr-B3Zqqmu6kAnXAbS8dqrRvH003kXNQwyjR2__kL_UREwcVENRDGmk1qG0Llm6EjynD0HSPMBFlapY7Z-w8grv-Z_E4hEyhUxkXf-kBsSvXr00NTgApEOG7gdojvcSBUKctnJzy_K91zWTPxFcxokLh8YCJTPdqsyDM4idv0yihRxIzZE5fVngyVldfhnoPYAhbbmA1jpkCn-OtEOnhPdwVhqPdFncR9cvhgUf4cP0hSNFCEq',
            url: '<wrapped url>',
            buttonUrl: '<wrapped url>',
            constants: {
                buttonText: 'В магазин',
                shopInfoTooltip: 'Перейти в магазин',
                freeDelivery: 'Бесплатно',
                shopRatingText: 'Рейтинг %s из 5 на основе',
            },
        },
        {
            name: 'Apple iPhone X 256GB Silver (Серебристый)',
            warning: undefined,
            price: {
                value: 89290,
                currencyCode: 'RUR',
                currencyName: 'руб.',
            },
            category: {
                id: 91491,
                name: 'Мобильные телефоны',
                fullName: 'Мобильные телефоны',
                type: 'GURU',
                childCount: 0,
                advertisingModel: 'CPA',
                viewType: 'GRID',
            },
            target: 'price-list',
            shopInfo: {
                name: 'МегаФон',
                id: 37758,
                rating: 4,
                gradeTotal: 4105,
                url: '<wrapped url>',
            },
            delivery: {
                free: true,
                pickup: true,
                brief: 'в Москву — бесплатно, возможен самовывоз',
                delivery: true,
                daysFrom: 1,
                daysTo: 1,
                cityFrom: 'Москвы',
                cityTo: 'Москву',
            },
            photo: 'https://avatars.mds.yandex.net/get-marketpic/248830/market_96gwsN0vC0tIqVfxZEwaow/orig',
            source: 'Market',
            bigPhoto: {
                width: 400,
                height: 675,
                url: 'https://avatars.mds.yandex.net/get-marketpic/248830/market_96gwsN0vC0tIqVfxZEwaow/orig',
            },
            id:
                'yDpJekrrgZH8u0VSgcOzD1YuQQRO6hRg3Zpni_JCPRmtdBh6Z5jg9WDN9AsaJlxEmPK_tVibDmcuKqBnh0gAVF0UhWnu7Zng6bJuOSCZuWRJt6-y6NthUt9JwgRvB_h9uMDDyE4UDK0jxHtslEPI18T2hUXv_11tsNvzupwBla_P95IVY6oy-ic-XrxhbRs2oyyY65bo9VLUIbaKjkiH2WHjSMgFOzBYB802McmiRUHRuax7txW2b_EnqCoTr_9_sjtnwXFaUSYOKc82ZmN4_q1qs228DMDxNfeiSmGNuCz0JQqOaMZkSa2e-g0zr7C7',
            url: '<wrapped url>',
            buttonUrl: '<wrapped url>',
            constants: {
                buttonText: 'В магазин',
                shopInfoTooltip: 'Перейти в магазин',
                freeDelivery: 'Бесплатно',
                shopRatingText: 'Рейтинг %s из 5 на основе',
            },
        },
        {
            name: 'Мобильный телефон Apple iPhone X 256GB A1901 black',
            warning: undefined,
            price: {
                value: 79990,
                currencyCode: 'RUR',
                currencyName: 'руб.',
            },
            category: {
                id: 91491,
                name: 'Мобильные телефоны',
                fullName: 'Мобильные телефоны',
                type: 'GURU',
                childCount: 0,
                advertisingModel: 'CPA',
                viewType: 'GRID',
            },
            target: 'price-list',
            shopInfo: {
                name: 'Video-shoper.ru',
                id: 58825,
                rating: 5,
                gradeTotal: 10876,
                url: '<wrapped url>',
            },
            delivery: {
                free: false,
                pickup: true,
                brief: 'в Москву — 400 руб., возможен самовывоз',
                price: {
                    value: '400',
                    currencyCode: 'RUR',
                    currencyName: 'руб.',
                },
                delivery: true,
                daysFrom: 1,
                daysTo: 1,
                cityFrom: 'Москвы',
                cityTo: 'Москву',
            },
            photo: 'https://avatars.mds.yandex.net/get-marketpic/207337/market_ULfbbkMTv41Lu1DJf9IxQg/orig',
            source: 'Market',
            bigPhoto: {
                width: 175,
                height: 350,
                url: 'https://avatars.mds.yandex.net/get-marketpic/207337/market_ULfbbkMTv41Lu1DJf9IxQg/orig',
            },
            id:
                'yDpJekrrgZEgj5XdRwrVTQsR1FWEAtwxHfjRiNpcQzFOJXKWYsF_fNQLDnfVBnNJcjAmdp66o0PuyzcKx1CYK1Kv-hOP-93dmHv3lW5S154QPyXRpV9-RHK_0porEoDeDJu_Yv3oUp38rs7OpdSojpwXuqULpMaOyAonbeiREJuXvB3gQaOp3OCL8Y0RCRugxuk9sA9xc0ZP11KXGn9XNn5Btq8r0lYpDxpiigrFD_sv0yLkYRflTY8MEA4ZEtCAY8P7UtmoqZ3Za6i_xUyoxWA9K_DDkWVgtNAbaIj9qm2pk50KhN9buVvDYABhhn-K',
            url: '<wrapped url>',
            buttonUrl: '<wrapped url>',
            constants: {
                buttonText: 'В магазин',
                shopInfoTooltip: 'Перейти в магазин',
                shopRatingText: 'Рейтинг %s из 5 на основе',
            },
        },
    ],
    searchResult: undefined,
    searchResultCaption: undefined,
    optOutInfo: undefined,
    rules: undefined,
    bucketInfo: {},
    doNotSearchReason: undefined,
    notification: {
        title: 'Более выгодная цена - 79 990 руб.',
        text: 'на Apple iPhone X 256GB\nв магазине Video-shoper.ru',
        link: '%3Cwrapped%20url%3E?target=notification&click_type=paid',
        photo: 'https://avatars.mds.yandex.net/get-marketpic/207337/market_ULfbbkMTv41Lu1DJf9IxQg/orig',
        contextMessage: 'Доставка 400 руб.',
        buttons: [
            {
                title: 'Посмотреть',
                link: '%3Cwrapped%20url%3E?target=notification-button&click_type=paid',
            },
            {
                title: 'Еще предложения',
                link: '%3Cwrapped%20url%3E?target=notification-market-button&click_type=market',
            },
        ],
        showWhen: [
            'parent',
            'display',
            'position',
            'text-change',
            'size',
            'zindex',
            'zindexframe',
            'opacity',
            'transform',
            'node-remove',
            'inline-styles',
            'external-styles',
            'stylesheets',
        ],
        requireInteraction: true,
        duration: 30000,
    },
    shopInfo: undefined,
    searchInfo: {
        originalQuery: 'Мобильный телефон Apple iPhone X 256GB',
        filteredQuery: 'Мобильный телефон Apple iPhone X 256GB',
        category: undefined,
        doNotComparePrice: undefined,
        convertedPrice: {
            value: 80950,
            currencyCode: 'RUR',
        },
        offersCount: 190,
        urls: {
            shopsInfo: '<wrapped url>',
            market: '<wrapped url>',
            search:
                'https://market.yandex.ru/search.xml?text=%D0%9C%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D1%8B%D0%B9%20%D1%82%D0%B5%D0%BB%D0%B5%D1%84%D0%BE%D0%BD%20Apple%20iPhone%20X%20256GB&clid=2210590&distr_type=4&utm_source=sovetnik&utm_medium=cpc&utm_campaign=offer-title&cvredirect=2&req_id=jblcn9wys7oq5sqzjga4a6jn9j5bsgew',
            searchButton: '<wrapped url>',
            prices: '<wrapped url>',
            eula: '<wrapped url>',
            feedback: '<wrapped url>',
            help: '<wrapped url>',
            helpPhone: '<wrapped url>',
            helpTablet: '<wrapped url>',
            disable: '<wrapped url>',
            features: '<wrapped url>',
            userHelp: '<wrapped url>',
        },
        categories: [
            {
                id: 91491,
                name: 'Мобильные телефоны',
                rank: 3.1096057605980807,
                url: '<wrapped url>',
            },
            {
                id: 91498,
                name: 'Чехлы',
                rank: -1.5426012138071545,
                url: '<wrapped url>',
            },
            {
                id: 91499,
                name: 'Аккумуляторы',
                rank: -3.7627227252201205,
                url: '<wrapped url>',
            },
        ],
    },
    feedback: {
        constants: {
            closeButtonText: 'Закрыть',
            error: 'Комментарий не может быть пустым.',
            placeholder:
                'Пожалуйста, расскажите, что именно случилось. Ваш комментарий поможет нам исправить проблему быстрее.',
            submitButtonText: 'Отправить',
            text: 'Ваше сообщение поможет улучшить Советника',
            thanks: 'Спасибо!',
            title: 'Спасибо, мы получили ваш отчёт об ошибке',
        },
    },
    pricebar: {
        constants: {
            infoButtonTooltip: 'О программе',
            settingsButtonTooltip: 'Настройки',
            closeButtonTooltip: 'Закрыть',
            prevText: 'Более выгодная цена на',
            inShopText: 'в магазине',
            goButtonText: 'Посмотреть',
            goButtonTooltip: 'Посмотреть',
            moreButtonText: 'Еще предложения',
            moreButtonTooltip: 'Предложения других магазинов',
        },
    },
    tabs: {
        constants: {
            offers: 'Предложения магазинов',
        },
    },
    settings: {
        autoShowShopList: true,
        applicationName: 'Яндекс.Советник',
        isMbrApplication: true,
        constants: {
            yourRegion: 'Ваш регион:',
            changeRegion: 'Изменить регион',
            changeSettings: 'Изменить настройки',
            disable: 'Выключить на этом сайте',
        },
        items: [
            {
                title: 'Показывать предложения из других регионов',
                enabled: true,
            },
            {
                title: 'Показывать список предложений при наведении мыши',
                enabled: true,
            },
        ],
        region: 'Автоматически',
        needShowNotifications: true,
        showProductNotifications: true,
        showAviaNotifications: true,
        showAutoNotifications: true,
    },
    info: {
        constants: {
            text: 'Это приложение подсказывает вам более выгодные цены на товары, на которые вы смотрите прямо сейчас.',
            helpText: 'Помощь',
            feedbackText: 'Обратная связь',
            yandexLLC: '© %s ООО «Яндекс.Маркет»',
            licenseText: 'Лицензионное соглашение',
            disableText: 'Как отключить Советника',
            featuresText: 'Что ещё умеет Советник',
            upperLine: 'Яндекс.Советник',
            prefix: 'для ',
        },
    },
    footer: {
        constants: {
            changeRegion: 'Изменить регион',
            changeCurrentRegion: 'Изменить текущий регион',
            autoDetectedRegion: 'Автоматически',
            infoAboutShop: 'Информация о продавцах',
            infoAboutShopLegal: 'Юридическая информация о продавцах',
            feedback: 'Сообщить об ошибке',
            gotoMarket: 'Перейти на Яндекс.Маркет',
            wrongProductDetect: 'Неверно определен товар',
            data: {
                prefix: 'Данные',
                letter: 'Я',
                suffix: 'ндекс.Маркета',
            },
        },
    },
};
