/* eslint-disable max-len */

'use strict';

module.exports = {
    model: undefined,
    searchResult: undefined,
    offers: [
        {
            name:
                'Комплект детского постельного белья Letto "Игрушки", 1,5 спальный, наволочка 50 x 70 см, цвет: голубой',
            price: {
                value: 1019,
                currencyCode: 'RUR',
                currencyName: 'руб.',
            },
            warning: undefined,
            category: {
                id: 12894020,
                name: 'Комплекты',
                fullName: 'Комплекты постельного белья',
                type: 'VISUAL',
                childCount: 0,
                advertisingModel: 'HYBRID',
                viewType: 'LIST',
            },
            constants: {
                shopRatingText: 'Рейтинг %s из 5 на основе',
            },
            target: 'pricebar',
            bigPhoto: {
                width: 900,
                height: 900,
                url: 'https://avatars.mds.yandex.net/get-marketpic/171655/market_pIaIvCtkP9dcm1O6zgRilA/orig',
            },
            shopInfo: {
                name: 'OZON.ru',
                id: 155,
                rating: 2,
                gradeTotal: 34108,
                url: '<wrapped url>',
            },
            delivery: {
                free: false,
                pickup: true,
                brief: 'в Москву — 299 руб., возможен самовывоз',
                price: {
                    value: '299',
                    currencyCode: 'RUR',
                    currencyName: 'руб.',
                },
                delivery: true,
                daysFrom: 1,
                daysTo: 1,
                cityFrom: 'Москвы',
                cityTo: 'Москву',
            },
            photo: 'https://avatars.mds.yandex.net/get-marketpic/171655/market_pIaIvCtkP9dcm1O6zgRilA/orig',
            source: 'Market',
            id:
                'yDpJekrrgZFQ7RzJB4YYNA6FUUqSQkWw8bplEtCRkjWO58jOFDL7Wm6-EFkULXTT6ivuRBDNnS8ypi7dEcsm-nB4MVuGXn7txhhVD9aQk43jKIB-bxyZX366crhQn60HXKIngYNNQvfkucjZOFR2vyMBEMG6QU6QurN4F6GRXL2k_u8fA1gLaDmnd3rfSZUhy-7CJcxfNzT6vPn-iirFJJjwkkz2zBdusUFwn09VyMjZkEF47lDIZDw-1UCxNbJUwMHhn5COSGj19MHcUKEEHX1W3n9tvVVBrhv1wfOU-2k',
            url: '<wrapped url>',
            optOutUrl: '<wrapped url>',
            buttonUrl: '<wrapped url>',
            surfaceUrl: '<wrapped url>',
            profitBadgeText: {
                value: '−5%',
                prefix: 'до',
            },
        },
        {
            name: 'Комплект детского постельного белья Letto "Сова", 1,5 спальный, наволочка 50 x 70 см, цвет: желтый',
            price: {
                value: 1269,
                currencyCode: 'RUR',
                currencyName: 'руб.',
            },
            warning: undefined,
            mostRelevant: true,
            category: {
                id: 12894020,
                name: 'Комплекты',
                fullName: 'Комплекты постельного белья',
                type: 'VISUAL',
                childCount: 0,
                advertisingModel: 'HYBRID',
                viewType: 'LIST',
            },
            constants: {
                shopRatingText: 'Рейтинг %s из 5 на основе',
            },
            target: 'price-list',
            bigPhoto: {
                width: 1000,
                height: 1000,
                url: 'https://avatars.mds.yandex.net/get-marketpic/480326/market_9Ruo369FbCeib2p_4yez1w/orig',
            },
            shopInfo: {
                name: 'OZON.ru',
                id: 155,
                rating: 2,
                gradeTotal: 34108,
                url: '<wrapped url>',
            },
            delivery: {
                free: false,
                pickup: true,
                brief: 'в Москву — 299 руб., возможен самовывоз',
                price: {
                    value: '299',
                    currencyCode: 'RUR',
                    currencyName: 'руб.',
                },
                delivery: true,
                daysFrom: 1,
                daysTo: 1,
                cityFrom: 'Москвы',
                cityTo: 'Москву',
            },
            photo: 'https://avatars.mds.yandex.net/get-marketpic/480326/market_9Ruo369FbCeib2p_4yez1w/orig',
            source: 'Market',
            id:
                'yDpJekrrgZH_BSjjQ2iblEIl3iZImtzttNShxn7U9XuWvjx7Y-2ooaXMeHdNccSH67yI3A4fbTRPIsUn34h9aH3ZVUMUSa0psRCzaE8RPsZ9Vwg8lvYT_zlNAoubl_1O6DC-HkFd_TQBhnNfZ7lAzXZX2W5xWRZRWXEBMDDb09IxT7Rom5c2HKB0B70BKaw7CAKAglOr_Nq29nPu2eGCYaJihQBz04u5qlI75oYW5_w1AJxhnnEkmD4Ez6i2hAIK6iPXZM2_jz5j2DXuqG7rztJltwqkIy5RdoRB8y0_LYI',
            url: '<wrapped url>',
            buttonUrl: '<wrapped url>',
        },
        {
            name:
                'Комплект детского постельного белья Letto "Игрушки", 1,5 спальный, наволочка 50 x 70 см, цвет: голубой',
            price: {
                value: 1019,
                currencyCode: 'RUR',
                currencyName: 'руб.',
            },
            warning: undefined,
            category: {
                id: 12894020,
                name: 'Комплекты',
                fullName: 'Комплекты постельного белья',
                type: 'VISUAL',
                childCount: 0,
                advertisingModel: 'HYBRID',
                viewType: 'LIST',
            },
            constants: {
                shopRatingText: 'Рейтинг %s из 5 на основе',
            },
            target: 'price-list',
            bigPhoto: {
                width: 900,
                height: 900,
                url: 'https://avatars.mds.yandex.net/get-marketpic/171655/market_pIaIvCtkP9dcm1O6zgRilA/orig',
            },
            shopInfo: {
                name: 'OZON.ru',
                id: 155,
                rating: 2,
                gradeTotal: 34108,
                url: '<wrapped url>',
            },
            delivery: {
                free: false,
                pickup: true,
                brief: 'в Москву — 299 руб., возможен самовывоз',
                price: {
                    value: '299',
                    currencyCode: 'RUR',
                    currencyName: 'руб.',
                },
                delivery: true,
                daysFrom: 1,
                daysTo: 1,
                cityFrom: 'Москвы',
                cityTo: 'Москву',
            },
            photo: 'https://avatars.mds.yandex.net/get-marketpic/171655/market_pIaIvCtkP9dcm1O6zgRilA/orig',
            source: 'Market',
            id:
                'yDpJekrrgZFQ7RzJB4YYNA6FUUqSQkWw8bplEtCRkjWO58jOFDL7Wm6-EFkULXTT6ivuRBDNnS8ypi7dEcsm-nB4MVuGXn7txhhVD9aQk43jKIB-bxyZX366crhQn60HXKIngYNNQvfkucjZOFR2vyMBEMG6QU6QurN4F6GRXL2k_u8fA1gLaDmnd3rfSZUhy-7CJcxfNzT6vPn-iirFJJjwkkz2zBdusUFwn09VyMjZkEF47lDIZDw-1UCxNbJUwMHhn5COSGj19MHcUKEEHX1W3n9tvVVBrhv1wfOU-2k',
            url: '<wrapped url>',
            buttonUrl: '<wrapped url>',
        },
        {
            name: 'Комплект детского постельного белья Letto "Каляка", 1,5-спальный, наволочка 50x70, цвет: желтый',
            price: {
                value: 1259,
                currencyCode: 'RUR',
                currencyName: 'руб.',
            },
            warning: undefined,
            category: {
                id: 12894020,
                name: 'Комплекты',
                fullName: 'Комплекты постельного белья',
                type: 'VISUAL',
                childCount: 0,
                advertisingModel: 'HYBRID',
                viewType: 'LIST',
            },
            constants: {
                shopRatingText: 'Рейтинг %s из 5 на основе',
            },
            target: 'price-list',
            bigPhoto: {
                width: 1200,
                height: 1200,
                url: 'https://avatars.mds.yandex.net/get-marketpic/247229/market_iH3-KsChwDjOVSQtvMooaA/orig',
            },
            shopInfo: {
                name: 'OZON.ru',
                id: 155,
                rating: 2,
                gradeTotal: 34108,
                url: '<wrapped url>',
            },
            delivery: {
                free: false,
                pickup: true,
                brief: 'в Москву — 299 руб., возможен самовывоз',
                price: {
                    value: '299',
                    currencyCode: 'RUR',
                    currencyName: 'руб.',
                },
                delivery: true,
                daysFrom: 1,
                daysTo: 1,
                cityFrom: 'Москвы',
                cityTo: 'Москву',
            },
            photo: 'https://avatars.mds.yandex.net/get-marketpic/247229/market_iH3-KsChwDjOVSQtvMooaA/orig',
            source: 'Market',
            id:
                'yDpJekrrgZFtEBbm4u7wGeewizXw6y5b0Tw-iVKE5GIe0mWfESvAo-RPXJllvHeFhJAKXbccDAK5qXkVkdyNPCgahzD3VFKgqi_oMsBF70TIPEPGz5bXKjgnmgTCRQmPu6XpFAw1ysf0d67C6eC_xnapkWuXrUj8GS5TGzvZNZtRdOhRR0G5cC-FTC8rEKPswiDhN_D1g4mDMxFcB5qYN4bMzP2lB3D29GVO4Rq99l7WSP0bS2d3qGkZQyzOM9NsGJQGtl2zJ_whaXQR_J7Q4U2pmZthNfGYZ6RyOT3N8TQ',
            url: '<wrapped url>',
            buttonUrl: '<wrapped url>',
        },
        {
            name: 'Комплект детского постельного белья Letto "Шрифт", 1,5-спальный, наволочка 50х70',
            price: {
                value: 1249,
                currencyCode: 'RUR',
                currencyName: 'руб.',
            },
            warning: undefined,
            category: {
                id: 12894020,
                name: 'Комплекты',
                fullName: 'Комплекты постельного белья',
                type: 'VISUAL',
                childCount: 0,
                advertisingModel: 'HYBRID',
                viewType: 'LIST',
            },
            constants: {
                shopRatingText: 'Рейтинг %s из 5 на основе',
            },
            target: 'price-list',
            bigPhoto: {
                width: 1200,
                height: 1200,
                url: 'https://avatars.mds.yandex.net/get-marketpic/165151/market_QgKuOP6XmM8V-zinmM5wdw/orig',
            },
            shopInfo: {
                name: 'OZON.ru',
                id: 155,
                rating: 2,
                gradeTotal: 34108,
                url: '<wrapped url>',
            },
            delivery: {
                free: false,
                pickup: true,
                brief: 'в Москву — 299 руб., возможен самовывоз',
                price: {
                    value: '299',
                    currencyCode: 'RUR',
                    currencyName: 'руб.',
                },
                delivery: true,
                daysFrom: 1,
                daysTo: 1,
                cityFrom: 'Москвы',
                cityTo: 'Москву',
            },
            photo: 'https://avatars.mds.yandex.net/get-marketpic/165151/market_QgKuOP6XmM8V-zinmM5wdw/orig',
            source: 'Market',
            id:
                'yDpJekrrgZFsQJgfR0WrNOZLET3hrhJHB-Sw_IRBzwnNEZgzDKXEMoTsyKcjsrWXpiw_wzPBleSjCXVU9Flcgx1eZ9wAyu8PLnK3OQwCAyvO0KxQ-McXZuxRCBg3pcOa9zg8nhEAGeNuIMZ2DRgw1BDbZatMzm28YCSLx4lgT3-b0H_OqTsX08Ch4inOt72pnfKkHWEJZ3FN6d0lrPUd7aMcuJHFEi1UOLYVC82Ywhxs-9SJMesF7xqdQ1ks-lozLDEzt27V-UeXKPyFsp9ejM1zOTH2BVDHGDl8hpTMctY',
            url: '<wrapped url>',
            buttonUrl: '<wrapped url>',
        },
        {
            name: 'Детское постельное белье Letto "Мишки" (1,5 спальный КПБ, бязь, наволочка 50х70), цвет: розовый',
            price: {
                value: 1119,
                currencyCode: 'RUR',
                currencyName: 'руб.',
            },
            warning: undefined,
            category: {
                id: 12894020,
                name: 'Комплекты',
                fullName: 'Комплекты постельного белья',
                type: 'VISUAL',
                childCount: 0,
                advertisingModel: 'HYBRID',
                viewType: 'LIST',
            },
            constants: {
                shopRatingText: 'Рейтинг %s из 5 на основе',
            },
            target: 'price-list',
            bigPhoto: {
                width: 900,
                height: 900,
                url: 'https://avatars.mds.yandex.net/get-marketpic/234366/market_CZNEklNVKLYBF3TZzLUXrg/orig',
            },
            shopInfo: {
                name: 'OZON.ru',
                id: 155,
                rating: 2,
                gradeTotal: 34108,
                url: '<wrapped url>',
            },
            delivery: {
                free: false,
                pickup: true,
                brief: 'в Москву — 299 руб., возможен самовывоз',
                price: {
                    value: '299',
                    currencyCode: 'RUR',
                    currencyName: 'руб.',
                },
                delivery: true,
                daysFrom: 1,
                daysTo: 1,
                cityFrom: 'Москвы',
                cityTo: 'Москву',
            },
            photo: 'https://avatars.mds.yandex.net/get-marketpic/234366/market_CZNEklNVKLYBF3TZzLUXrg/orig',
            source: 'Market',
            id:
                'yDpJekrrgZHnMqOHOt7QGQvG_FHWCF0dqVdzR7oiUwwfR23GtPM23Yr2wIIuqcAmAAcOiUpfYJ46YOFrXzJpkDeuT3D2J1uB-7Sp7E6PvAtGI4aG3AZYwwh_jTTkJzELGARrU3TKtbIRlPS5qElbQ8MZcg2cshtqTQmJUGiOCWL9ZdhAKJVsyc-8uKwq45Ox-Kp6gTTI-j8G86F6y6gEeqBpZbiA4OhOJvM5mgDyX_BN9TZfSN09zeKJwaQo0Og9JojpmGE0E8pjiRXCaiby0o7jYBClZ3fcW-3m0hPhb3o',
            url: '<wrapped url>',
            buttonUrl: '<wrapped url>',
        },
        {
            name:
                'Комплект постельного белья Самойловский текстиль Капучино, 1,5 спальный с наволочками 50х70 (713563)',
            price: {
                value: 1060,
                currencyCode: 'RUR',
                currencyName: 'руб.',
            },
            warning: undefined,
            category: {
                id: 12894020,
                name: 'Комплекты',
                fullName: 'Комплекты постельного белья',
                type: 'VISUAL',
                childCount: 0,
                advertisingModel: 'HYBRID',
                viewType: 'LIST',
            },
            constants: {
                shopRatingText: 'Рейтинг %s из 5 на основе',
            },
            target: 'price-list',
            bigPhoto: {
                width: 800,
                height: 680,
                url: 'https://avatars.mds.yandex.net/get-marketpic/205766/market_bW_rUkg_A9Zf4ewyUUuchw/orig',
            },
            shopInfo: {
                name: 'ОНЛАЙН ТРЕЙД.РУ',
                id: 255,
                rating: 5,
                gradeTotal: 68651,
                url: '<wrapped url>',
            },
            delivery: {
                free: false,
                pickup: true,
                brief: 'в Москву — 300 руб., возможен самовывоз',
                price: {
                    value: '300',
                    currencyCode: 'RUR',
                    currencyName: 'руб.',
                },
                delivery: true,
                daysFrom: 1,
                daysTo: 2,
                cityFrom: 'Москвы',
                cityTo: 'Москву',
            },
            photo: 'https://avatars.mds.yandex.net/get-marketpic/205766/market_bW_rUkg_A9Zf4ewyUUuchw/orig',
            source: 'Market',
            id: 'yDpJekrrgZFhQsX7HyuBbZuBelHAlAiEh3o3hjQhWld_A_TKlxbFfw',
            url: '<wrapped url>',
            buttonUrl: '<wrapped url>',
        },
        {
            name: 'Комплект постельного белья Самойловский текстиль Утро, 1,5 спальный с наволочками 50х70 (714289)',
            price: {
                value: 1060,
                currencyCode: 'RUR',
                currencyName: 'руб.',
            },
            warning: undefined,
            category: {
                id: 12894020,
                name: 'Комплекты',
                fullName: 'Комплекты постельного белья',
                type: 'VISUAL',
                childCount: 0,
                advertisingModel: 'HYBRID',
                viewType: 'LIST',
            },
            constants: {
                shopRatingText: 'Рейтинг %s из 5 на основе',
            },
            target: 'price-list',
            bigPhoto: {
                width: 800,
                height: 680,
                url: 'https://avatars.mds.yandex.net/get-marketpic/231668/market_ehvhK6p8qza92tmjjo2tMA/orig',
            },
            shopInfo: {
                name: 'ОНЛАЙН ТРЕЙД.РУ',
                id: 255,
                rating: 5,
                gradeTotal: 68651,
                url: '<wrapped url>',
            },
            delivery: {
                free: false,
                pickup: true,
                brief: 'в Москву — 300 руб., возможен самовывоз',
                price: {
                    value: '300',
                    currencyCode: 'RUR',
                    currencyName: 'руб.',
                },
                delivery: true,
                daysFrom: 1,
                daysTo: 2,
                cityFrom: 'Москвы',
                cityTo: 'Москву',
            },
            photo: 'https://avatars.mds.yandex.net/get-marketpic/231668/market_ehvhK6p8qza92tmjjo2tMA/orig',
            source: 'Market',
            id: 'yDpJekrrgZGzksmCTOi9dXG4o0yVYwTiU8b0DM8QPYewZ16VmRfdqw',
            url: '<wrapped url>',
            buttonUrl: '<wrapped url>',
        },
        {
            name: 'Комплект постельного белья Кокетка с наволочками 50*70 см (1,5 сп.)',
            price: {
                value: 1875,
                currencyCode: 'RUR',
                currencyName: 'руб.',
            },
            warning: undefined,
            category: {
                id: 12894020,
                name: 'Комплекты',
                fullName: 'Комплекты постельного белья',
                type: 'VISUAL',
                childCount: 0,
                advertisingModel: 'HYBRID',
                viewType: 'LIST',
            },
            target: 'price-list',
            bigPhoto: {
                width: 500,
                height: 500,
                url: 'https://avatars.mds.yandex.net/get-marketpic/204557/market_jYVpdErrWMUtMKYUBLqRQQ/orig',
            },
            shopInfo: {
                name: 'Sova&Javoronok',
                id: 443496,
                rating: 3,
                gradeTotal: 1,
                url: '<wrapped url>',
            },
            constants: {
                freeDelivery: 'Бесплатно',
                shopRatingText: 'Рейтинг %s из 5 на основе',
            },
            delivery: {
                free: true,
                pickup: false,
                brief: 'в Москву — бесплатно',
                price: {
                    value: '0',
                    currencyCode: 'RUR',
                    currencyName: 'руб.',
                },
                delivery: true,
                daysFrom: 1,
                daysTo: 3,
                cityFrom: 'Москвы',
                cityTo: 'Москву',
            },
            photo: 'https://avatars.mds.yandex.net/get-marketpic/204557/market_jYVpdErrWMUtMKYUBLqRQQ/orig',
            source: 'Market',
            id:
                'yDpJekrrgZHBxIgfZ9pVBxncaZViSMSkzVh7dfSfReomCFeXvmmAXMeOnJmU-vnscZ6BT5KzRS9XzIa97rsyg0e_635IZirVZZvTcKihgSSuvRpXN7rm31X4S69IDBNYCHtJV4B6VUU8k4ktCcnwLXjB3qTcZCQUnJ7DIa9E7AvsZVn1Hj3jAztY_7IuIcEpfcOxSHqVVn9gmjz5bsSJgWz0IKM7C7SvaROQ1N0vA66wUFzf4gnXCsNgMno_x3P6FLSo9n9vYddjR1kgj3u1UCR5McjbkDb1F45-ypUOJh0',
            url: '<wrapped url>',
            buttonUrl: '<wrapped url>',
        },
        {
            name: 'Комплект постельного белья 1,5-спальный "Minnie", с наволочкой 50х70 см',
            price: {
                value: 1981,
                currencyCode: 'RUR',
                currencyName: 'руб.',
            },
            warning: undefined,
            category: {
                id: 12894020,
                name: 'Комплекты',
                fullName: 'Комплекты постельного белья',
                type: 'VISUAL',
                childCount: 0,
                advertisingModel: 'HYBRID',
                viewType: 'LIST',
            },
            constants: {
                shopRatingText: 'Рейтинг %s из 5 на основе',
            },
            target: 'price-list',
            bigPhoto: {
                width: 135,
                height: 202,
                url: 'https://avatars.mds.yandex.net/get-marketpic/246786/market_zqQ7hm5fQx6MViMxM3mUyg/orig',
            },
            shopInfo: {
                name: 'My-shop.ru',
                id: 582,
                rating: 3,
                gradeTotal: 2212,
                url: '<wrapped url>',
            },
            delivery: {
                free: false,
                pickup: true,
                brief: 'в Москву — 180 руб., возможен самовывоз',
                price: {
                    value: '180',
                    currencyCode: 'RUR',
                    currencyName: 'руб.',
                },
                delivery: true,
                daysFrom: 5,
                daysTo: 8,
                cityFrom: 'Москвы',
                cityTo: 'Москву',
            },
            photo: 'https://avatars.mds.yandex.net/get-marketpic/246786/market_zqQ7hm5fQx6MViMxM3mUyg/orig',
            source: 'Market',
            id:
                'yDpJekrrgZENY_RXGgrvIpCRGVORe-v8ER__JXuxdE3kV0gQ7w076Ho06tnkS77ozvXtOPeOeqOoXBXaM6GB3Uy7NNjXSJR4zz0XpxZJzChBSO9siUaQYxduQKFfeh4ZPXpiBFKRfMqzlL6tJxE2svUbcnmI8CqMo_bhDk4Snbni-J8bJVW4nyBJNZU1OrVZ_ehKQ2AEg3LGKmc75DTUx0jiK3wgrK7j0A9vaedekAoDev6uNIdaxKSPAFoqvfSNL00_SXgHIWzkV0rNuAVCC67Ypk34c2zxXA16xCgDSLo',
            url: '<wrapped url>',
            buttonUrl: '<wrapped url>',
        },
        {
            name:
                'Комплект постельного белья Самойловский текстиль Рейкьявик 1,5 спальный с наволочками 50х70 (714216)',
            price: {
                value: 1060,
                currencyCode: 'RUR',
                currencyName: 'руб.',
            },
            warning: undefined,
            category: {
                id: 12894020,
                name: 'Комплекты',
                fullName: 'Комплекты постельного белья',
                type: 'VISUAL',
                childCount: 0,
                advertisingModel: 'HYBRID',
                viewType: 'LIST',
            },
            constants: {
                shopRatingText: 'Рейтинг %s из 5 на основе',
            },
            target: 'price-list',
            bigPhoto: {
                width: 800,
                height: 680,
                url: 'https://avatars.mds.yandex.net/get-marketpic/205766/market_j9gHO_5ZIH3vV_9YF5QNtA/orig',
            },
            shopInfo: {
                name: 'ОНЛАЙН ТРЕЙД.РУ',
                id: 255,
                rating: 5,
                gradeTotal: 68651,
                url: '<wrapped url>',
            },
            delivery: {
                free: false,
                pickup: true,
                brief: 'в Москву — 300 руб., возможен самовывоз',
                price: {
                    value: '300',
                    currencyCode: 'RUR',
                    currencyName: 'руб.',
                },
                delivery: true,
                daysFrom: 1,
                daysTo: 2,
                cityFrom: 'Москвы',
                cityTo: 'Москву',
            },
            photo: 'https://avatars.mds.yandex.net/get-marketpic/205766/market_j9gHO_5ZIH3vV_9YF5QNtA/orig',
            source: 'Market',
            id: 'yDpJekrrgZG6WenwXxmvQ8tgfsALZgmAONb05HbL329YAlhkm1_ReA',
            url: '<wrapped url>',
            buttonUrl: '<wrapped url>',
        },
        {
            name: 'Комплект постельного белья Самойловский текстиль Бриз, 1,5 спальный с наволочками 50х70 (713564)',
            price: {
                value: 1060,
                currencyCode: 'RUR',
                currencyName: 'руб.',
            },
            warning: undefined,
            category: {
                id: 12894020,
                name: 'Комплекты',
                fullName: 'Комплекты постельного белья',
                type: 'VISUAL',
                childCount: 0,
                advertisingModel: 'HYBRID',
                viewType: 'LIST',
            },
            constants: {
                shopRatingText: 'Рейтинг %s из 5 на основе',
            },
            target: 'price-list',
            bigPhoto: {
                width: 800,
                height: 680,
                url: 'https://avatars.mds.yandex.net/get-marketpic/167181/market_1mch1BuEpQ1A7kV7lnRGTg/orig',
            },
            shopInfo: {
                name: 'ОНЛАЙН ТРЕЙД.РУ',
                id: 255,
                rating: 5,
                gradeTotal: 68651,
                url: '<wrapped url>',
            },
            delivery: {
                free: false,
                pickup: true,
                brief: 'в Москву — 300 руб., возможен самовывоз',
                price: {
                    value: '300',
                    currencyCode: 'RUR',
                    currencyName: 'руб.',
                },
                delivery: true,
                daysFrom: 1,
                daysTo: 2,
                cityFrom: 'Москвы',
                cityTo: 'Москву',
            },
            photo: 'https://avatars.mds.yandex.net/get-marketpic/167181/market_1mch1BuEpQ1A7kV7lnRGTg/orig',
            source: 'Market',
            id: 'yDpJekrrgZF6vUFnGR9H3bXvqdYsb9GUF07mZnX1y2VIPfevvxq1Mw',
            url: '<wrapped url>',
            buttonUrl: '<wrapped url>',
        },
        {
            name:
                'Комплект постельного белья Самойловский текстиль Легкость, 1,5 спальный с наволочками 50х70 (714278)',
            price: {
                value: 1060,
                currencyCode: 'RUR',
                currencyName: 'руб.',
            },
            warning: undefined,
            category: {
                id: 12894020,
                name: 'Комплекты',
                fullName: 'Комплекты постельного белья',
                type: 'VISUAL',
                childCount: 0,
                advertisingModel: 'HYBRID',
                viewType: 'LIST',
            },
            constants: {
                shopRatingText: 'Рейтинг %s из 5 на основе',
            },
            target: 'price-list',
            bigPhoto: {
                width: 800,
                height: 680,
                url: 'https://avatars.mds.yandex.net/get-marketpic/165839/market_Lhr3O-9MfmCmmqM1mVOGLg/orig',
            },
            shopInfo: {
                name: 'ОНЛАЙН ТРЕЙД.РУ',
                id: 255,
                rating: 5,
                gradeTotal: 68651,
                url: '<wrapped url>',
            },
            delivery: {
                free: false,
                pickup: true,
                brief: 'в Москву — 300 руб., возможен самовывоз',
                price: {
                    value: '300',
                    currencyCode: 'RUR',
                    currencyName: 'руб.',
                },
                delivery: true,
                daysFrom: 1,
                daysTo: 2,
                cityFrom: 'Москвы',
                cityTo: 'Москву',
            },
            photo: 'https://avatars.mds.yandex.net/get-marketpic/165839/market_Lhr3O-9MfmCmmqM1mVOGLg/orig',
            source: 'Market',
            id: 'yDpJekrrgZEeSNlKvqEifv8EPct46Ad65zs0-PTaLDS4YxK3cy0UnA',
            url: '<wrapped url>',
            buttonUrl: '<wrapped url>',
        },
        {
            name: 'Комплект постельного белья Disney «Олаф Зима», 1,5-спальное, наволочка 70х70 см',
            price: {
                value: 1749,
                currencyCode: 'RUR',
                currencyName: 'руб.',
            },
            warning: undefined,
            category: {
                id: 12894020,
                name: 'Комплекты',
                fullName: 'Комплекты постельного белья',
                type: 'VISUAL',
                childCount: 0,
                advertisingModel: 'HYBRID',
                viewType: 'LIST',
            },
            constants: {
                shopRatingText: 'Рейтинг %s из 5 на основе',
            },
            target: 'price-list',
            bigPhoto: {
                width: 1345,
                height: 1200,
                url: 'https://avatars.mds.yandex.net/get-marketpic/165839/market_AQNKRF5cVU3lF1LPwzlfNQ/orig',
            },
            shopInfo: {
                name: 'Ашан',
                id: 175488,
                rating: 1,
                gradeTotal: 175,
                url: '<wrapped url>',
            },
            delivery: {
                free: false,
                pickup: true,
                brief: 'в Москву — 249 руб., возможен самовывоз',
                price: {
                    value: '249',
                    currencyCode: 'RUR',
                    currencyName: 'руб.',
                },
                delivery: true,
                daysFrom: 2,
                daysTo: 2,
                cityFrom: 'Москвы',
                cityTo: 'Москву',
            },
            photo: 'https://avatars.mds.yandex.net/get-marketpic/165839/market_AQNKRF5cVU3lF1LPwzlfNQ/orig',
            source: 'Market',
            id:
                'yDpJekrrgZHDBDIeuKdQueRT44BmabSQ_bGehY5AL_WafkSGrc75wDCKDFu9424tN4qQK6KBl_sZo2wkAKWjnj2OhnxeOFuextbiKjiaaROoqGqBZyZFLfBOlolvU4LvoyG4QWWXbIvm44sXtjbmqv6oifsqSyQ2xGC3NgmvLjQ0z8i1Tk8PuMoVlkCzue-vRigm8jl9aeJ_1uYe4x3jRONudQlqlHHtzPKjEV0JD7aZkGd1nqzTVOS4PvJE5HnwI3dUjBtBWaHsdK2HpZEwXoBtkuE6OqhNnhP5PH2YHSE',
            url: '<wrapped url>',
            buttonUrl: '<wrapped url>',
        },
        {
            name: 'Комплект постельного белья Sova-&-Javoronok Индира 1,5 спальное 50-70, 100% хлопок',
            price: {
                value: 2215,
                currencyCode: 'RUR',
                currencyName: 'руб.',
            },
            warning: undefined,
            category: {
                id: 12894020,
                name: 'Комплекты',
                fullName: 'Комплекты постельного белья',
                type: 'VISUAL',
                childCount: 0,
                advertisingModel: 'HYBRID',
                viewType: 'LIST',
            },
            constants: {
                shopRatingText: 'Рейтинг %s из 5 на основе',
            },
            target: 'price-list',
            bigPhoto: {
                width: 500,
                height: 375,
                url: 'https://avatars.mds.yandex.net/get-marketpic/247921/market_YDpmP-hCaxz1Fhis9JzrPQ/orig',
            },
            shopInfo: {
                name: 'CompYou',
                id: 25017,
                rating: 5,
                gradeTotal: 4593,
                url: '<wrapped url>',
            },
            delivery: {
                free: false,
                pickup: true,
                brief: 'в Москву — 350 руб., возможен самовывоз',
                price: {
                    value: '350',
                    currencyCode: 'RUR',
                    currencyName: 'руб.',
                },
                delivery: true,
                daysFrom: 3,
                daysTo: 4,
                cityFrom: 'Москвы',
                cityTo: 'Москву',
            },
            photo: 'https://avatars.mds.yandex.net/get-marketpic/247921/market_YDpmP-hCaxz1Fhis9JzrPQ/orig',
            source: 'Market',
            id: 'yDpJekrrgZEH7siuJLb8rBpEque5QybHuUSaj9jczj9FngM-PbZ46g',
            url: '<wrapped url>',
            buttonUrl: '<wrapped url>',
        },
        {
            name: 'Комплект постельного белья Palermo 1.5-спальный Черника со сливками поплин, хлопок, 1.5-спальный',
            price: {
                value: 1063,
                currencyCode: 'RUR',
                currencyName: 'руб.',
            },
            warning: undefined,
            category: {
                id: 12894020,
                name: 'Комплекты',
                fullName: 'Комплекты постельного белья',
                type: 'VISUAL',
                childCount: 0,
                advertisingModel: 'HYBRID',
                viewType: 'LIST',
            },
            constants: {
                shopRatingText: 'Рейтинг %s из 5 на основе',
            },
            target: 'price-list',
            bigPhoto: {
                width: 518,
                height: 388,
                url: 'https://avatars.mds.yandex.net/get-marketpic/222975/market_Oucp0_EsJRJO_WJoqZfioQ/orig',
            },
            shopInfo: {
                name: 'Оксар.ру',
                id: 252831,
                rating: 5,
                gradeTotal: 1469,
                url: '<wrapped url>',
            },
            delivery: {
                free: false,
                pickup: true,
                brief: 'в Москву — 250 руб., возможен самовывоз',
                price: {
                    value: '250',
                    currencyCode: 'RUR',
                    currencyName: 'руб.',
                },
                delivery: true,
                daysFrom: 3,
                daysTo: 4,
                cityFrom: 'Москвы',
                cityTo: 'Москву',
            },
            photo: 'https://avatars.mds.yandex.net/get-marketpic/222975/market_Oucp0_EsJRJO_WJoqZfioQ/orig',
            source: 'Market',
            id: 'yDpJekrrgZGspS72Fj-n3-sow-ZGGqBOdAqWmqW8HkQXI6L0_Dko6w',
            url: '<wrapped url>',
            buttonUrl: '<wrapped url>',
        },
        {
            name: 'Комплект постельного белья Elite Gold (Milan) (1,5 спальный, наволочки 50*70)',
            price: {
                value: 4240,
                currencyCode: 'RUR',
                currencyName: 'руб.',
            },
            warning: undefined,
            category: {
                id: 12894020,
                name: 'Комплекты',
                fullName: 'Комплекты постельного белья',
                type: 'VISUAL',
                childCount: 0,
                advertisingModel: 'HYBRID',
                viewType: 'LIST',
            },
            constants: {
                shopRatingText: 'Рейтинг %s из 5 на основе',
            },
            target: 'price-list',
            bigPhoto: {
                width: 585,
                height: 564,
                url: 'https://avatars.mds.yandex.net/get-marketpic/168221/market_P9Rgg0z8L4y7h8W_r9QMSQ/orig',
            },
            shopInfo: {
                name: 'www.gite-line.ru',
                id: 305787,
                rating: 4,
                gradeTotal: 0,
                url: '<wrapped url>',
            },
            delivery: {
                free: false,
                pickup: true,
                brief: 'в Москву — 300 руб., возможен самовывоз',
                price: {
                    value: '300',
                    currencyCode: 'RUR',
                    currencyName: 'руб.',
                },
                delivery: true,
                daysFrom: 0,
                daysTo: 4,
                cityFrom: 'Москвы',
                cityTo: 'Москву',
            },
            photo: 'https://avatars.mds.yandex.net/get-marketpic/168221/market_P9Rgg0z8L4y7h8W_r9QMSQ/orig',
            source: 'Market',
            id:
                'yDpJekrrgZGt9e7iKyFOFNyqgld8pm1gH4OX74dOmKi1BYaos_jI5WdBcUXxSzZyfZeGx8voTEJvNiNX9nQ3ZbXqSmR5bys2-GlDvKrFOhlHoQlDBSkjBsoEq2LMaYX83Y3Ys_a_8RUV2MNvuxs2qGlqnOc1hqE95zaXwop4KCXNPZ8X6-K8ILhh7LWJcqOlEEb5BBdcOUHyLEHtKTDYnBwt0E2YaA9wNEkdEU-1nMBq_IG4lcJCNz0wJFaaeTDHGgUBiuWoXullk5oZ8VppQJF-XQTNXYa_koMglT211c4',
            url: '<wrapped url>',
            buttonUrl: '<wrapped url>',
        },
        {
            name: 'Комплект постельного белья 1,5-спальный "Disney", с наволочкой 50х70 см',
            price: {
                value: 1981,
                currencyCode: 'RUR',
                currencyName: 'руб.',
            },
            warning: undefined,
            category: {
                id: 12894020,
                name: 'Комплекты',
                fullName: 'Комплекты постельного белья',
                type: 'VISUAL',
                childCount: 0,
                advertisingModel: 'HYBRID',
                viewType: 'LIST',
            },
            constants: {
                shopRatingText: 'Рейтинг %s из 5 на основе',
            },
            target: 'price-list',
            bigPhoto: {
                width: 368,
                height: 517,
                url: 'https://avatars.mds.yandex.net/get-marketpic/173412/market_BwMD_rr2nqLmGUl-TeuxEw/orig',
            },
            shopInfo: {
                name: 'My-shop.ru',
                id: 582,
                rating: 3,
                gradeTotal: 2212,
                url: '<wrapped url>',
            },
            delivery: {
                free: false,
                pickup: true,
                brief: 'в Москву — 180 руб., возможен самовывоз',
                price: {
                    value: '180',
                    currencyCode: 'RUR',
                    currencyName: 'руб.',
                },
                delivery: true,
                daysFrom: 5,
                daysTo: 8,
                cityFrom: 'Москвы',
                cityTo: 'Москву',
            },
            photo: 'https://avatars.mds.yandex.net/get-marketpic/173412/market_BwMD_rr2nqLmGUl-TeuxEw/orig',
            source: 'Market',
            id:
                'yDpJekrrgZFF7TYsFFLKHTwaeJ1UPtaw3VSf4Wo3ssnAL2bqBn136ptlD-qI10RTaVp841RVQK3Cj6mi501O5ArKgHRfDBsNTsbR2h9jaVylLWuF0x0mJT2cky3JG6IieK-amgOCvfwumovu7dmqImDZG0Kh9toBtUsBcRw21VKcxrytzqwxZj97TUTkGbsNGPvFO_FNTSAcmdpzCZEQN8F5QCUWuhEifaZPJz7EUtR3nFtTnyJ_DB3yRq1aHLmGpP3lbFBSzkdDcfJfXnpIaLfRiZOpZi_UfUiM_7TbJYE',
            url: '<wrapped url>',
            buttonUrl: '<wrapped url>',
        },
        {
            name: 'Комплект постельного белья Byblos (Валенсия) (1,5 спальный, наволочки 50*70)',
            price: {
                value: 2700,
                currencyCode: 'RUR',
                currencyName: 'руб.',
            },
            warning: undefined,
            category: {
                id: 12894020,
                name: 'Комплекты',
                fullName: 'Комплекты постельного белья',
                type: 'VISUAL',
                childCount: 0,
                advertisingModel: 'HYBRID',
                viewType: 'LIST',
            },
            constants: {
                shopRatingText: 'Рейтинг %s из 5 на основе',
            },
            target: 'price-list',
            bigPhoto: {
                width: 704,
                height: 662,
                url: 'https://avatars.mds.yandex.net/get-marketpic/168221/market_w_tx5KYZ9K878Yx0aK2A-w/orig',
            },
            shopInfo: {
                name: 'www.gite-line.ru',
                id: 305787,
                rating: 4,
                gradeTotal: 0,
                url: '<wrapped url>',
            },
            delivery: {
                free: false,
                pickup: true,
                brief: 'в Москву — 300 руб., возможен самовывоз',
                price: {
                    value: '300',
                    currencyCode: 'RUR',
                    currencyName: 'руб.',
                },
                delivery: true,
                daysFrom: 0,
                daysTo: 4,
                cityFrom: 'Москвы',
                cityTo: 'Москву',
            },
            photo: 'https://avatars.mds.yandex.net/get-marketpic/168221/market_w_tx5KYZ9K878Yx0aK2A-w/orig',
            source: 'Market',
            id:
                'yDpJekrrgZHxOi1qDGohRJrC4a9wBkqgB1HSFh0ZsrfznwO1pCPYTIAFJjxzKYt0_pS62ducRwOehhVHZPFdJAVnBZs3CZTxO8tGltHv7vZZhr0VgLNttTW6S4rCA5p1_FxIEwfdUAm23BgpXOgp_mCRcsXkizrIsfxi7IUfZtT9a9YT1aYJtTPEAbLpc20x6UnMa_-kvbcIkdJIbCYrxqGdPOg6tsvuzdJcBeDoI556QeLS0K3_8EcCVqwf3WNmnR_86D2SXLRLv3m4znvHwHcqa5nOXrJdypFuHUdROLU',
            url: '<wrapped url>',
            buttonUrl: '<wrapped url>',
        },
        {
            name: 'Комплект постельного белья 1,5-спальный "Волшебная ночь", с наволочками 50х70 см',
            price: {
                value: 1645,
                currencyCode: 'RUR',
                currencyName: 'руб.',
            },
            warning: undefined,
            category: {
                id: 12894020,
                name: 'Комплекты',
                fullName: 'Комплекты постельного белья',
                type: 'VISUAL',
                childCount: 0,
                advertisingModel: 'HYBRID',
                viewType: 'LIST',
            },
            constants: {
                shopRatingText: 'Рейтинг %s из 5 на основе',
            },
            target: 'price-list',
            bigPhoto: {
                width: 200,
                height: 197,
                url: 'https://avatars.mds.yandex.net/get-marketpic/102460/market_LtljtTaBzHPLluOuKbRMAA/orig',
            },
            shopInfo: {
                name: 'My-shop.ru',
                id: 582,
                rating: 3,
                gradeTotal: 2212,
                url: '<wrapped url>',
            },
            delivery: {
                free: false,
                pickup: true,
                brief: 'в Москву — 180 руб., возможен самовывоз',
                price: {
                    value: '180',
                    currencyCode: 'RUR',
                    currencyName: 'руб.',
                },
                delivery: true,
                daysFrom: 5,
                daysTo: 8,
                cityFrom: 'Москвы',
                cityTo: 'Москву',
            },
            photo: 'https://avatars.mds.yandex.net/get-marketpic/102460/market_LtljtTaBzHPLluOuKbRMAA/orig',
            source: 'Market',
            id:
                'yDpJekrrgZFhJZXtJi0FpLY8jfXtggMRbP-LKM8dUhXn7vgabAVqkW1rWLqKsdkMqJeCoYfef9yT0LewkHy8jz-VCrQS0Xgi0S3TlN2XBF-d1I-vb8bAPG4hjn0FoJlselT6l4Ow-tPkYas8yVP4io2sVGFSKvlqIGviM0HuX8lbE6qerrL2-ATGPzqw2YCYNLysG1BrXnStCwhytv-p4ve2A7ct4C5UV_ryKDCb59-8tveMXNpISQ6ak9Mg_fG98GcMuYcGTEbbyaUg4dtxsokqTQGpyL8YKCG8iEA2SAQ',
            url: '<wrapped url>',
            buttonUrl: '<wrapped url>',
        },
        {
            name: 'Комплект постельного белья Botticielli (Milan) (1,5 спальный, наволочки 50*70)',
            price: {
                value: 4240,
                currencyCode: 'RUR',
                currencyName: 'руб.',
            },
            warning: undefined,
            category: {
                id: 12894020,
                name: 'Комплекты',
                fullName: 'Комплекты постельного белья',
                type: 'VISUAL',
                childCount: 0,
                advertisingModel: 'HYBRID',
                viewType: 'LIST',
            },
            constants: {
                shopRatingText: 'Рейтинг %s из 5 на основе',
            },
            target: 'price-list',
            bigPhoto: {
                width: 592,
                height: 571,
                url: 'https://avatars.mds.yandex.net/get-marketpic/169660/market_r7ahaF2ViCLO_RUTfUuZvg/orig',
            },
            shopInfo: {
                name: 'www.gite-line.ru',
                id: 305787,
                rating: 4,
                gradeTotal: 0,
                url: '<wrapped url>',
            },
            delivery: {
                free: false,
                pickup: true,
                brief: 'в Москву — 300 руб., возможен самовывоз',
                price: {
                    value: '300',
                    currencyCode: 'RUR',
                    currencyName: 'руб.',
                },
                delivery: true,
                daysFrom: 0,
                daysTo: 4,
                cityFrom: 'Москвы',
                cityTo: 'Москву',
            },
            photo: 'https://avatars.mds.yandex.net/get-marketpic/169660/market_r7ahaF2ViCLO_RUTfUuZvg/orig',
            source: 'Market',
            id:
                'yDpJekrrgZEdk7CeaCEhnnpkXMfjqPfJohEOgLBrg72UFB8InowM7tWz8DCORUdLNRqmXfr6DKi2xyZ_59qHI24DY1Yfz1iYWxzBs9oQMc9oqhQiuOPxKAaHXbnmrPylDXwhWPK4X6Jj1GVH-ZnYjAlTMXDowqRculjDEN01ap06zaxC_wWH0BURkXGvHzrevpzgkmUsYgGmgKBGCiGMAr6nSUhzju1CEBjOvlgC5BE2Dvwfixzv9xyJyZg-uH-Mi7uiIjqNNrqtsQTDeNrYy9cPZZqxKP0YG8NdifJr1-g',
            url: '<wrapped url>',
            buttonUrl: '<wrapped url>',
        },
        {
            name: 'Комплект постельного белья Lou, 1.5-спальное, сатин, наволочки 50 х 70 (2шт)',
            price: {
                value: 2936,
                currencyCode: 'RUR',
                currencyName: 'руб.',
            },
            warning: undefined,
            category: {
                id: 12894020,
                name: 'Комплекты',
                fullName: 'Комплекты постельного белья',
                type: 'VISUAL',
                childCount: 0,
                advertisingModel: 'HYBRID',
                viewType: 'LIST',
            },
            constants: {
                shopRatingText: 'Рейтинг %s из 5 на основе',
            },
            target: 'price-list',
            bigPhoto: {
                width: 840,
                height: 624,
                url: 'https://avatars.mds.yandex.net/get-marketpic/169403/market_k5bbKmSGr4Ej7cPLG05AmA/orig',
            },
            shopInfo: {
                name: 'Ашан',
                id: 175488,
                rating: 1,
                gradeTotal: 175,
                url: '<wrapped url>',
            },
            delivery: {
                free: false,
                pickup: true,
                brief: 'в Москву — 249 руб., возможен самовывоз',
                price: {
                    value: '249',
                    currencyCode: 'RUR',
                    currencyName: 'руб.',
                },
                delivery: true,
                daysFrom: 2,
                daysTo: 2,
                cityFrom: 'Москвы',
                cityTo: 'Москву',
            },
            photo: 'https://avatars.mds.yandex.net/get-marketpic/169403/market_k5bbKmSGr4Ej7cPLG05AmA/orig',
            source: 'Market',
            id:
                'yDpJekrrgZFWMia7BiQe0AEw-o9c7YApueI43r0oBnQZVUKAmPv-_Q8wl6qT5mlsQTkwC40DLgR9lKBF8zByfUtmxue2CA-Xo2zhO3Tp-u7tZsYw1aQAAbUHx-vZdD4n-yscO-aWkm9Nm9hzZT1NWqgNizUpVbcNdtvnei41x7HPKPO_hnO7TcClf-3W9xm5a25RgSy_clZHtT-F7DqJGBrJfy_gu75iVKlZdakoWWjdnA9pbFrVx6221WZToY5ru9PPmpLe1GS1PrjyzCaafS9PdHsHOUPCTBKvmxIm_tE',
            url: '<wrapped url>',
            buttonUrl: '<wrapped url>',
        },
        {
            name: 'Комплект постельного белья 1,5-спальный "Волшебная ночь", с наволочками 50х70 см',
            price: {
                value: 1957,
                currencyCode: 'RUR',
                currencyName: 'руб.',
            },
            warning: undefined,
            category: {
                id: 12894020,
                name: 'Комплекты',
                fullName: 'Комплекты постельного белья',
                type: 'VISUAL',
                childCount: 0,
                advertisingModel: 'HYBRID',
                viewType: 'LIST',
            },
            constants: {
                shopRatingText: 'Рейтинг %s из 5 на основе',
            },
            target: 'price-list',
            bigPhoto: {
                width: 341,
                height: 349,
                url: 'https://avatars.mds.yandex.net/get-marketpic/365133/market_NH1CWPUDCrnPQlvfnuoPKg/orig',
            },
            shopInfo: {
                name: 'My-shop.ru',
                id: 582,
                rating: 3,
                gradeTotal: 2212,
                url: '<wrapped url>',
            },
            delivery: {
                free: false,
                pickup: true,
                brief: 'в Москву — 180 руб., возможен самовывоз',
                price: {
                    value: '180',
                    currencyCode: 'RUR',
                    currencyName: 'руб.',
                },
                delivery: true,
                daysFrom: 5,
                daysTo: 8,
                cityFrom: 'Москвы',
                cityTo: 'Москву',
            },
            photo: 'https://avatars.mds.yandex.net/get-marketpic/365133/market_NH1CWPUDCrnPQlvfnuoPKg/orig',
            source: 'Market',
            id:
                'yDpJekrrgZFgi6Of88RSUeVI3ZJyNevhkU74Zd68zMqY5OQs4-MDEsjh12P1RQ-9Tpw5egeI4eT5TnV-UO0bE5LZ19Vha5p4ZwoP9DbT6m7lcsy-yM02a_b66dRb9JS5zQpa74UYwPQBcGMqVhEg9dszvg1J5g0m3HfBPzkOcgPpiFg3slNHDms01-YWmi0BWv3sJeFUM4ka8CeOecMd-1pps1qLFsaPAesqqezA8IjnzEivfnw95Qcecm_BeoAS_XWtXrKlvB_5bjuX7TRlEJ-pDpYn4GFRGA4dF2YCSxc',
            url: '<wrapped url>',
            buttonUrl: '<wrapped url>',
        },
        {
            name: 'Комплект постельного белья HelloKitty, 1,5 - спальное, наволочка 70х70 см',
            price: {
                value: 2092,
                currencyCode: 'RUR',
                currencyName: 'руб.',
            },
            warning: undefined,
            category: {
                id: 12894020,
                name: 'Комплекты',
                fullName: 'Комплекты постельного белья',
                type: 'VISUAL',
                childCount: 0,
                advertisingModel: 'HYBRID',
                viewType: 'LIST',
            },
            constants: {
                shopRatingText: 'Рейтинг %s из 5 на основе',
            },
            target: 'price-list',
            bigPhoto: {
                width: 1314,
                height: 1200,
                url: 'https://avatars.mds.yandex.net/get-marketpic/169403/market_hhNl6L--SLAwpRqe1CvTug/orig',
            },
            shopInfo: {
                name: 'Ашан',
                id: 175488,
                rating: 1,
                gradeTotal: 175,
                url: '<wrapped url>',
            },
            delivery: {
                free: false,
                pickup: true,
                brief: 'в Москву — 249 руб., возможен самовывоз',
                price: {
                    value: '249',
                    currencyCode: 'RUR',
                    currencyName: 'руб.',
                },
                delivery: true,
                daysFrom: 2,
                daysTo: 2,
                cityFrom: 'Москвы',
                cityTo: 'Москву',
            },
            photo: 'https://avatars.mds.yandex.net/get-marketpic/169403/market_hhNl6L--SLAwpRqe1CvTug/orig',
            source: 'Market',
            id:
                'yDpJekrrgZG5O-YxOFOW2Anuu-loc78Wi-Rwnldsht8Rk9bKLVBRtBSG7NSVX5mKBMkWGaiBcFezIYU8HHNX2XpGnt-y6NPtSO852eSQK9HJUdvmiH6XmQmnX3Me3fVHdE4VE-FmQOMovHS5mEmu0363vLJtOK1jtDbg0eUjXg4hxZ-MXvy2OFgCVTD-CXKxT4aWwI0uoo5Ya6akH26_iizwSGtpfezVsqWGpR2KBEaAHL25l48zx4oEVrp1h9NmZHV1YcgCL1herDZjjkQys368hFA6RIZHoWkTORwE5cc',
            url: '<wrapped url>',
            buttonUrl: '<wrapped url>',
        },
        {
            name: 'Комплект постельного белья Quelle Sova&Javoronok 1010792 1,5сп, 50х70*2',
            price: {
                value: 1718,
                discount: '25',
                base: 2290,
                currencyCode: 'RUR',
                currencyName: 'руб.',
            },
            warning: undefined,
            category: {
                id: 12894020,
                name: 'Комплекты',
                fullName: 'Комплекты постельного белья',
                type: 'VISUAL',
                childCount: 0,
                advertisingModel: 'HYBRID',
                viewType: 'LIST',
            },
            target: 'price-list',
            bigPhoto: {
                width: 450,
                height: 640,
                url: 'https://avatars.mds.yandex.net/get-marketpic/236356/market_K_NqjYyG03c1wUeBUfP9Fg/orig',
            },
            shopInfo: {
                name: 'QUELLE',
                id: 105713,
                rating: 5,
                gradeTotal: 8920,
                url: '<wrapped url>',
            },
            delivery: {
                free: false,
                pickup: true,
                brief: 'в Москву — 479 руб., возможен самовывоз',
                daysFrom: undefined,
                daysTo: undefined,
                price: {
                    value: '479',
                    currencyCode: 'RUR',
                    currencyName: 'руб.',
                },
                delivery: true,
                cityFrom: 'Москвы',
                cityTo: 'Москву',
            },
            photo: 'https://avatars.mds.yandex.net/get-marketpic/236356/market_K_NqjYyG03c1wUeBUfP9Fg/orig',
            source: 'Market',
            id: 'yDpJekrrgZF_Hdd8g6x9CkegZLTgw2014FZK3RvrmAxESAK-QvLgwA',
            url: '<wrapped url>',
            buttonUrl: '<wrapped url>',
            constants: {
                discount: 'Скидка',
                shopRatingText: 'Рейтинг %s из 5 на основе',
            },
        },
        {
            name: 'Комплект постельного белья «Коллекция», 1.5-спальный, поплин, наволочки 50 х 70 (2шт)',
            price: {
                value: 2134,
                currencyCode: 'RUR',
                currencyName: 'руб.',
            },
            warning: undefined,
            category: {
                id: 12894020,
                name: 'Комплекты',
                fullName: 'Комплекты постельного белья',
                type: 'VISUAL',
                childCount: 0,
                advertisingModel: 'HYBRID',
                viewType: 'LIST',
            },
            constants: {
                shopRatingText: 'Рейтинг %s из 5 на основе',
            },
            target: 'price-list',
            bigPhoto: {
                width: 788,
                height: 630,
                url: 'https://avatars.mds.yandex.net/get-marketpic/218908/market__vfllzI5wnQU8HFOuNmnVA/orig',
            },
            shopInfo: {
                name: 'Ашан',
                id: 175488,
                rating: 1,
                gradeTotal: 175,
                url: '<wrapped url>',
            },
            delivery: {
                free: false,
                pickup: true,
                brief: 'в Москву — 249 руб., возможен самовывоз',
                price: {
                    value: '249',
                    currencyCode: 'RUR',
                    currencyName: 'руб.',
                },
                delivery: true,
                daysFrom: 2,
                daysTo: 2,
                cityFrom: 'Москвы',
                cityTo: 'Москву',
            },
            photo: 'https://avatars.mds.yandex.net/get-marketpic/218908/market__vfllzI5wnQU8HFOuNmnVA/orig',
            source: 'Market',
            id:
                'yDpJekrrgZERoRiNuGA2AfQUFgeR1jWuh9v4487SMphrNP69kKZ5kdSj0dyEDC_jq2k7H8-3_O8cKumR2VEVnBbUSngKDyFPjmjQrU22-z0urHQ9JqkwEJmckR8_ut-aSbNazYrtEt8fn4sSxcakAx4GDw7aM33iP2Rglx_YeseCJpeO1e-0c67SF2CtKsuWQ36DUoI6NoeTkvOxIDCSzuee1vQMUlBTNP4hNkWhdpqtnlBSrMfETjpvcksYLGt7aRu5sfGwGFjJ9ckakz8dBU8VaiydfB70IZL10AC6Q9A',
            url: '<wrapped url>',
            buttonUrl: '<wrapped url>',
        },
        {
            name: 'Комплект постельного белья Sova & Javoronok Зеленый чай 1,5 спальное 50-70',
            price: {
                value: 2105,
                currencyCode: 'RUR',
                currencyName: 'руб.',
            },
            warning: undefined,
            category: {
                id: 12894020,
                name: 'Комплекты',
                fullName: 'Комплекты постельного белья',
                type: 'VISUAL',
                childCount: 0,
                advertisingModel: 'HYBRID',
                viewType: 'LIST',
            },
            constants: {
                shopRatingText: 'Рейтинг %s из 5 на основе',
            },
            target: 'price-list',
            bigPhoto: {
                width: 674,
                height: 668,
                url: 'https://avatars.mds.yandex.net/get-marketpic/245020/market_s5v4fEXxV9-IGR4_pSxMgg/orig',
            },
            shopInfo: {
                name: 'TopComputer.RU',
                id: 5205,
                rating: 5,
                gradeTotal: 10788,
                url: '<wrapped url>',
            },
            delivery: {
                free: false,
                pickup: true,
                brief: 'в Москву — 490 руб., возможен самовывоз',
                price: {
                    value: '490',
                    currencyCode: 'RUR',
                    currencyName: 'руб.',
                },
                delivery: true,
                daysFrom: 4,
                daysTo: 6,
                cityFrom: 'Москвы',
                cityTo: 'Москву',
            },
            photo: 'https://avatars.mds.yandex.net/get-marketpic/245020/market_s5v4fEXxV9-IGR4_pSxMgg/orig',
            source: 'Market',
            id: 'yDpJekrrgZEgVKPKYpVobuDAr0Ncq3aT3T9e_VpG3SQ7zDlABINg5w',
            url: '<wrapped url>',
            buttonUrl: '<wrapped url>',
        },
        {
            name: 'Комплект постельного белья Fillippi (Валенсия) (1,5 спальный, наволочки 50*70)',
            price: {
                value: 2700,
                currencyCode: 'RUR',
                currencyName: 'руб.',
            },
            warning: undefined,
            category: {
                id: 12894020,
                name: 'Комплекты',
                fullName: 'Комплекты постельного белья',
                type: 'VISUAL',
                childCount: 0,
                advertisingModel: 'HYBRID',
                viewType: 'LIST',
            },
            constants: {
                shopRatingText: 'Рейтинг %s из 5 на основе',
            },
            target: 'price-list',
            bigPhoto: {
                width: 707,
                height: 666,
                url: 'https://avatars.mds.yandex.net/get-marketpic/175127/market_ALmuLanrJq1fuf2HDl0MVg/orig',
            },
            shopInfo: {
                name: 'www.gite-line.ru',
                id: 305787,
                rating: 4,
                gradeTotal: 0,
                url: '<wrapped url>',
            },
            delivery: {
                free: false,
                pickup: true,
                brief: 'в Москву — 300 руб., возможен самовывоз',
                price: {
                    value: '300',
                    currencyCode: 'RUR',
                    currencyName: 'руб.',
                },
                delivery: true,
                daysFrom: 0,
                daysTo: 4,
                cityFrom: 'Москвы',
                cityTo: 'Москву',
            },
            photo: 'https://avatars.mds.yandex.net/get-marketpic/175127/market_ALmuLanrJq1fuf2HDl0MVg/orig',
            source: 'Market',
            id:
                'yDpJekrrgZFLrEAoEEkG8J0iCY23mqGN6YhEDrB7OhZxLEXnOUkSpm3O_OY_pXxnsRlvewOG-4JZilj8xbuxeCDodzwavmuvKk3Pcccr2pP7OUWDeqIQWNiz6NgylPRTtNw2T5JvrTAaIY07h-j0RoSAxCD6aqjBbHl9PjYqR5_SzMCpo53EXG46I6DECk7NzWD-2zYyK5eLnDiesiJayG_TKgHlbfmlXm-j8GaSj5L0VlRXxQhVP_Vd4GCyziyc1RBPEY8M1S4a5gF-WyJtseIA9eBjjF9Y5UxdXO-5ZwY',
            url: '<wrapped url>',
            buttonUrl: '<wrapped url>',
        },
        {
            name:
                'Комплект постельного белья 1,5-спальный "Самойловский текстиль. Утро в саду", с наволочками 50х70 см',
            price: {
                value: 1187,
                currencyCode: 'RUR',
                currencyName: 'руб.',
            },
            warning: undefined,
            category: {
                id: 12894020,
                name: 'Комплекты',
                fullName: 'Комплекты постельного белья',
                type: 'VISUAL',
                childCount: 0,
                advertisingModel: 'HYBRID',
                viewType: 'LIST',
            },
            constants: {
                shopRatingText: 'Рейтинг %s из 5 на основе',
            },
            target: 'price-list',
            bigPhoto: {
                width: 571,
                height: 485,
                url: 'https://avatars.mds.yandex.net/get-marketpic/247272/market_ZqT6wKIw63vGMMSIDj_tZw/orig',
            },
            shopInfo: {
                name: 'My-shop.ru',
                id: 582,
                rating: 3,
                gradeTotal: 2212,
                url: '<wrapped url>',
            },
            delivery: {
                free: false,
                pickup: true,
                brief: 'в Москву — 180 руб., возможен самовывоз',
                price: {
                    value: '180',
                    currencyCode: 'RUR',
                    currencyName: 'руб.',
                },
                delivery: true,
                daysFrom: 5,
                daysTo: 8,
                cityFrom: 'Москвы',
                cityTo: 'Москву',
            },
            photo: 'https://avatars.mds.yandex.net/get-marketpic/364755/market_UK3k1NNerXQrRxiEBEjxKQ/orig',
            source: 'Market',
            id:
                'yDpJekrrgZG73a8iSBaea6_WL5HmyY74jGkuOiT_5ZmiZ1Ywby7hLB4YwLp0rzDGCGu4-MbqRoULKb8xqAykgk3ETaNHTXSxqmRsraBnMqleTYR63ZO3n4aE9-QQC_RN-JikwLBYaHIwlogONLc-PpLT4n38ZaH2J4JDd85MJ-qDU2afbglfXO-9juqD7jrAAk_Vv0wFZHxdyiMUm0vu5dFEmq3BerD7rBUnlCg2Pgk4oNn-RMr_MZLnLjvIwNqTdYAnCQSmOSlZmH3Hc37pTOJtOBUU3vpikR_peuWRNcY',
            url: '<wrapped url>',
            buttonUrl: '<wrapped url>',
        },
        {
            name: 'Комплект постельного белья Ginza (Валенсия) (1,5 спальный, наволочки 50*70)',
            price: {
                value: 2700,
                currencyCode: 'RUR',
                currencyName: 'руб.',
            },
            warning: undefined,
            category: {
                id: 12894020,
                name: 'Комплекты',
                fullName: 'Комплекты постельного белья',
                type: 'VISUAL',
                childCount: 0,
                advertisingModel: 'HYBRID',
                viewType: 'LIST',
            },
            constants: {
                shopRatingText: 'Рейтинг %s из 5 на основе',
            },
            target: 'price-list',
            bigPhoto: {
                width: 706,
                height: 679,
                url: 'https://avatars.mds.yandex.net/get-marketpic/175127/market_c0aIQDzrTcNlEJewLyXAFg/orig',
            },
            shopInfo: {
                name: 'www.gite-line.ru',
                id: 305787,
                rating: 4,
                gradeTotal: 0,
                url: '<wrapped url>',
            },
            delivery: {
                free: false,
                pickup: true,
                brief: 'в Москву — 300 руб., возможен самовывоз',
                price: {
                    value: '300',
                    currencyCode: 'RUR',
                    currencyName: 'руб.',
                },
                delivery: true,
                daysFrom: 0,
                daysTo: 4,
                cityFrom: 'Москвы',
                cityTo: 'Москву',
            },
            photo: 'https://avatars.mds.yandex.net/get-marketpic/175127/market_c0aIQDzrTcNlEJewLyXAFg/orig',
            source: 'Market',
            id:
                'yDpJekrrgZGVfbCe9d0RB4F_Cs-nzOW2dbtxrdvdmmykOSc0N9N79qi3HBJxiup3rzUbt1yDBLHjhVmoWf_4WLz8xuZhLstmI3qe153Es5iVRT61Drkcf_UIBePvC-aK90JIi_Hv2tfkdOIpLLK-IyDAdrgk0bekjtEHMJQZfnZ5C6gl1xOCm9Ygm6hAtBaKlg7cvEM-eJy8cZbNxVYchEHwKWyWmuKUZdj5O_5XpmRh9Ro_wbR7pnJ_tpqXF1wCb-MFCzRrnNZpV6dFbDKnwqGeWxnSio2GiLz8A7HoOoI',
            url: '<wrapped url>',
            buttonUrl: '<wrapped url>',
        },
        {
            name: 'Комплект постельного белья Palermo 1.5-спальный Персик в шоколаде поплин, хлопок, 1.5-спальный',
            price: {
                value: 956,
                currencyCode: 'RUR',
                currencyName: 'руб.',
            },
            warning: undefined,
            category: {
                id: 12894020,
                name: 'Комплекты',
                fullName: 'Комплекты постельного белья',
                type: 'VISUAL',
                childCount: 0,
                advertisingModel: 'HYBRID',
                viewType: 'LIST',
            },
            constants: {
                shopRatingText: 'Рейтинг %s из 5 на основе',
            },
            target: 'price-list',
            bigPhoto: {
                width: 640,
                height: 488,
                url: 'https://avatars.mds.yandex.net/get-marketpic/174398/market_PxTUUGfiUqMvKd_krrsOmQ/orig',
            },
            shopInfo: {
                name: 'Оксар.ру',
                id: 252831,
                rating: 5,
                gradeTotal: 1469,
                url: '<wrapped url>',
            },
            delivery: {
                free: false,
                pickup: true,
                brief: 'в Москву — 250 руб., возможен самовывоз',
                price: {
                    value: '250',
                    currencyCode: 'RUR',
                    currencyName: 'руб.',
                },
                delivery: true,
                daysFrom: 3,
                daysTo: 4,
                cityFrom: 'Москвы',
                cityTo: 'Москву',
            },
            photo: 'https://avatars.mds.yandex.net/get-marketpic/174398/market_PxTUUGfiUqMvKd_krrsOmQ/orig',
            source: 'Market',
            id: 'yDpJekrrgZFGUUq4mFI9HlSJGhZvBlDzBl4Cs8izf41m7fuDb_alIA',
            url: '<wrapped url>',
            buttonUrl: '<wrapped url>',
        },
    ],
    searchResultCaption: 'Комплекты постельного белья',
    bucketInfo: {},
    doNotSearchReason: undefined,
    shopInfo: {
        shopName: 'WILDBERRIES.RU',
        rating: 5,
        url: '<wrapped url>',
        gradeTotal: 32489,
    },
    notification: {
        title: 'Более выгодная цена - 1 019 руб.',
        text:
            'на Комплект детского постельного белья Letto "Игрушки", 1,5 спальный, наволочка 50 x 70 см, цвет: голубой\nв магазине OZON.ru',
        link: '%3Cwrapped%20url%3E?target=notification&click_type=paid',
        contextMessage: 'Доставка 299 руб.',
        buttons: [
            {
                title: 'Посмотреть',
                link: '%3Cwrapped%20url%3E?target=notification-button&click_type=paid',
            },
            {
                title: 'Еще предложения',
                link: '%3Cwrapped%20url%3E?target=notification-market-button&click_type=market',
            },
        ],
        showWhen: [
            'parent',
            'display',
            'position',
            'text-change',
            'size',
            'zindex',
            'zindexframe',
            'opacity',
            'transform',
            'node-remove',
            'inline-styles',
            'external-styles',
            'stylesheets',
        ],
        requireInteraction: true,
        duration: 30000,
    },
    rules: undefined,
    optOutInfo: undefined,
    searchInfo: {
        originalQuery: 'Комплект постельного Лисички, 1,5-спальный, наволочка 50*70, хлопок, Letto',
        filteredQuery: 'Комплект постельного Лисички, 1,5-спальный, наволочка 50*70, хлопок, Letto',
        convertedPrice: {
            value: 1071,
            currencyCode: 'RUR',
        },
        doNotComparePrice: undefined,
        category: undefined,
        offersCount: 30,
        urls: {
            shopsInfo: '<wrapped url>',
            market: '<wrapped url>',
            search:
                'https://market.yandex.ru/search.xml?text=%D0%9A%D0%BE%D0%BC%D0%BF%D0%BB%D0%B5%D0%BA%D1%82%20%D0%BF%D0%BE%D1%81%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D0%BE%D0%B3%D0%BE%20%D0%9B%D0%B8%D1%81%D0%B8%D1%87%D0%BA%D0%B8%2C%201%2C5-%D1%81%D0%BF%D0%B0%D0%BB%D1%8C%D0%BD%D1%8B%D0%B9%2C%20%D0%BD%D0%B0%D0%B2%D0%BE%D0%BB%D0%BE%D1%87%D0%BA%D0%B0%2050*70%2C%20%D1%85%D0%BB%D0%BE%D0%BF%D0%BE%D0%BA%2C%20Letto&clid=2210590&distr_type=4&utm_source=sovetnik&utm_medium=cpc&utm_campaign=offer-title&cvredirect=2&req_id=jdecnnvohg3sg9gyjaw7fs0ey2fmi79j&hid=12894020&fesh=-258283,-145985,-174503,-397505,-310140,-156493,-397053,-111387,-17493,-296374,-120350,-192472,-284077,-431828,-397233,-258150,-397506,-165579,-112422,-117318,-431834,-154433,-149780,-397525,-397523,-119236,-284125,-296376,-216743,-169247,-258260,-397512,-129755,-431904,-232465,-397500,-431831,-397514,-258140,-431896,-397088,-143409,-123491,-114202,-431906,-296339,-115706,-397128,-431902,-296361,-431818,-161597,-225477,-431910,-174505,-169243,-130669,-139995,-139872,-111836,-114871,-284123,-296363,-397115,-256021,-397516,-397240,-284120,-235023,-237642,-256050,-256060,-3678',
            searchButton: '<wrapped url>',
            prices: '<wrapped url>',
            eula: '<wrapped url>',
            feedback: '<wrapped url>',
            help: '<wrapped url>',
            helpPhone: '<wrapped url>',
            helpTablet: '<wrapped url>',
            disable: '<wrapped url>',
            features: '<wrapped url>',
            userHelp: '<wrapped url>',
        },
        categories: [
            {
                id: 12894020,
                name: 'Комплекты',
                rank: 0.638723867913658,
                url: '<wrapped url>',
            },
            {
                id: 10752690,
                name: 'Постельное белье и комплекты',
                rank: -2.9257784604739348,
                url: '<wrapped url>',
            },
            {
                id: 12894026,
                name: 'Наволочки',
                rank: -4.888531513742836,
                url: '<wrapped url>',
            },
        ],
    },
    feedback: {
        constants: {
            closeButtonText: 'Закрыть',
            error: 'Комментарий не может быть пустым.',
            placeholder:
                'Пожалуйста, расскажите, что именно случилось. Ваш комментарий поможет нам исправить проблему быстрее.',
            submitButtonText: 'Отправить',
            text: 'Ваше сообщение поможет улучшить Советника',
            thanks: 'Спасибо!',
            title: 'Спасибо, мы получили ваш отчёт об ошибке',
        },
    },
    pricebar: {
        constants: {
            infoButtonTooltip: 'О программе',
            settingsButtonTooltip: 'Настройки',
            closeButtonTooltip: 'Закрыть',
            prevText: 'Более выгодная цена на',
            inShopText: 'в магазине',
            goButtonText: 'Посмотреть',
            goButtonTooltip: 'Посмотреть',
            moreButtonText: 'Еще предложения',
            moreButtonTooltip: 'Предложения других магазинов',
        },
    },
    tabs: { constants: { offers: 'Предложения магазинов' } },
    settings: {
        autoShowShopList: true,
        applicationName: 'Яндекс.Советник',
        isMbrApplication: true,
        constants: {
            yourRegion: 'Ваш регион:',
            changeRegion: 'Изменить регион',
            changeSettings: 'Изменить настройки',
            disable: 'Выключить на этом сайте',
        },
        items: [
            {
                title: 'Показывать предложения из других регионов',
                enabled: true,
            },
            {
                title: 'Показывать список предложений при наведении мыши',
                enabled: true,
            },
        ],
        region: 'Автоматически',
        needShowNotifications: true,
        showProductNotifications: true,
        showAviaNotifications: true,
        showAutoNotifications: true,
    },
    info: {
        constants: {
            text: 'Это приложение подсказывает вам более выгодные цены на товары, на которые вы смотрите прямо сейчас.',
            helpText: 'Помощь',
            feedbackText: 'Обратная связь',
            yandexLLC: '© %s ООО «Яндекс.Маркет»',
            licenseText: 'Лицензионное соглашение',
            disableText: 'Как отключить Советника',
            featuresText: 'Что ещё умеет Советник',
            upperLine: 'Яндекс.Советник',
            prefix: 'для ',
        },
    },
    footer: {
        constants: {
            changeRegion: 'Изменить регион',
            changeCurrentRegion: 'Изменить текущий регион',
            autoDetectedRegion: 'Автоматически',
            infoAboutShop: 'Информация о продавцах',
            infoAboutShopLegal: 'Юридическая информация о продавцах',
            feedback: 'Сообщить об ошибке',
            gotoMarket: 'Перейти на Яндекс.Маркет',
            wrongProductDetect: 'Неверно определен товар',
            data: {
                prefix: 'Данные',
                letter: 'Я',
                suffix: 'ндекс.Маркета',
            },
        },
    },
};
