/* eslint-disable max-len */

'use strict';

module.exports = {
    model: {
        name: 'Apple iPhone SE 64GB',
        vendor: 'Apple',
        reviewsCount: 95,

        rating: 4.5,
        gradeCount: 163,
        prices: {
            max: 33990,
            min: 24450,
            avg: 26790,
            curCode: 'RUR',
            curName: 'руб.',
        },
        offersCount: 19,
        mainPhoto: {
            url: 'https://avatars.mds.yandex.net/get-mpic/96484/img_id4712451804472673330/orig',
            width: 354,
            height: 701,
        },
        isNew: 0,
        photo: 'https://avatars.mds.yandex.net/get-mpic/96484/img_id4712451804472673330/4hq',
        urls: {
            model: '<wrapped url>',
            modelPicture: '<wrapped url>',
            offers: '<wrapped url>',
            map: '<wrapped url>',
            price: '<wrapped url>',
            reviews: '<wrapped url>',
            reviewsBadge: '<wrapped url>',
        },
    },
    notification: undefined,
    offers: [
        {
            name: 'Apple iPhone SE 64Gb Rose Gold',
            price: {
                value: 24870,
                currencyName: 'руб.',
                currencyCode: 'RUR',
            },
            category: {
                id: 91491,
                type: 'GURU',
                advertisingModel: 'CPA',
                name: 'Мобильные телефоны',
            },
            target: 'pricebar',
            bigPhoto: {
                url: 'https://avatars.mds.yandex.net/get-marketpic/364498/market_2pdfxuJ82BXGpqDQPVzApA/orig',
                width: 484,
                height: 484,
            },
            shopInfo: {
                name: 'Цифроцентр',
                rating: 3,
                id: 141122,
                gradeTotal: 285,
                url: '<wrapped url>',
            },
            warning: undefined,
            delivery: {
                free: false,
                brief: 'в Москву — 400 руб., возможен самовывоз',
                price: {
                    value: '400',
                    currencyName: 'руб.',
                    currencyCode: 'RUR',
                },
                delivery: true,
            },
            photo: 'https://avatars.mds.yandex.net/get-marketpic/364498/market_2pdfxuJ82BXGpqDQPVzApA/orig',
            source: 'Market',
            id:
                'yDpJekrrgZFztD6WyzUvHlunueMn-6Sa7O4BtaDo1tB5b6t08UmMWfcdpi8DiYfj647w6UTbQCPe3vm-HF05L0BpkjhZ2lkDkpNZnrinv5T16P_2I-rvM0QzZzYgzWjo-yBNOEK5UyXhGxmeqXiwLWIoHNpsiIkCjNryDoRsuKjLaWs98mVr5Zik3yDJwryzkh8uLoiUjyRUqL-5zNvcEKOkoEtu72H0puN9CRRz-tO8Q2ZVCCULE-yZV9EvMRIxJWVUw3VoTDKFC57AeTS2SXPXdc9b8WZH7yAez55mBgY',
            url: '<wrapped url>',
            optOutUrl: '<wrapped url>',
            buttonUrl: '<wrapped url>',
            surfaceUrl: '<wrapped url>',
        },
        {
            name: 'Сотовый телефон Apple iPhone SE 64Gb (A1723) Silver',
            price: {
                value: 25989,
                currencyName: 'руб.',
                currencyCode: 'RUR',
                discount: '13',
                base: 29990,
            },
            category: {
                id: 91491,
                type: 'GURU',
                advertisingModel: 'CPA',
                name: 'Мобильные телефоны',
            },
            target: 'price-list',
            bigPhoto: {
                url: 'https://avatars.mds.yandex.net/get-marketpic/167181/market_LtMPbl0BIpQ8y-Ckyur9SQ/orig',
                width: 246,
                height: 373,
            },
            shopInfo: {
                name: 'БОЛТУН.РУ',
                rating: 5,
                id: 6537,
                gradeTotal: 6073,
                url: '<wrapped url>',
            },
            warning: undefined,
            delivery: {
                free: false,
                brief: 'в Москву — 399 руб., возможен самовывоз',
                price: {
                    value: '399',
                    currencyName: 'руб.',
                    currencyCode: 'RUR',
                },
                delivery: true,
            },
            photo: 'https://avatars.mds.yandex.net/get-marketpic/167181/market_LtMPbl0BIpQ8y-Ckyur9SQ/orig',
            source: 'Market',
            id:
                'yDpJekrrgZE_ZPb9iynT9eQYjZxb9LzWyaE-N7qVDN5iuL1VSkVIXFCycRGFYhSznhbhC77Bkqw3Q2sfikKAgC0_8jMCjqodZorXk0XQfxWTpHEZYZur9tHD8-wsX-LUrKkX940BchDbCUAr2f_wf67dT_jciVRTYT5SYydCbbVYOnAWsMJxiC5DsIDuOPIs0EMAx_fvwheWtn-CX0u9ZPmXWoN2eR2ddiYUBhMMwrT3rRarquxldCl-XOz7Zd-p2QoOBNhiuAOzOwahG7oAPdzYijoDqIH4VDzufUJadF0',
            url: '<wrapped url>',
            buttonUrl: '<wrapped url>',
        },
        {
            name: 'Мобильный телефон Apple iPhone SE 64Gb Gold',
            price: {
                value: 25600,
                currencyName: 'руб.',
                currencyCode: 'RUR',
            },
            category: {
                id: 91491,
                type: 'GURU',
                advertisingModel: 'CPA',
                name: 'Мобильные телефоны',
            },
            target: 'price-list',
            bigPhoto: {
                url: 'https://avatars.mds.yandex.net/get-marketpic/331110/market_X1iWnCeN6lBRRnRoxyb-sw/orig',
                width: 320,
                height: 320,
            },
            shopInfo: {
                name: 'Mobilfunk.ru',
                rating: 5,
                id: 38615,
                gradeTotal: 3861,
                url: '<wrapped url>',
            },
            warning: undefined,
            delivery: {
                free: false,
                brief: 'в Москву — 390 руб., возможен самовывоз',
                price: {
                    value: '390',
                    currencyName: 'руб.',
                    currencyCode: 'RUR',
                },
                delivery: true,
            },
            photo: 'https://avatars.mds.yandex.net/get-marketpic/331110/market_X1iWnCeN6lBRRnRoxyb-sw/orig',
            source: 'Market',
            id:
                'yDpJekrrgZHhpLQrPyL817Y7bVCuPkC-pnxnPrx7uZfjmHhHvhA79PtYqkp4J6rWK_IzauKFwA75_mO7T32-Mt3fxYiu4nXiOcTW9zQeIkJ6y79zmVKZCu0Fwpqxq9uyBB0KUpy70trUoDFzSppsTq2W08P91ZB_xXTt0LkxaiW1h0oNNmEnnyLWYOoK5uTPgnQC8VUJxMdNnHLzZ6T2T41weVwyZMrxIcqEEclbcjkTFAqLgOCOnEMBaJTTq2vtp3Y6Ntvn6x3lpMIuDgim50oS8TweRl6hyyeL8ldv8Xo',
            url: '<wrapped url>',
            buttonUrl: '<wrapped url>',
        },
        {
            name: 'Apple iPhone SE 64Gb Gold',
            price: {
                value: 33990,
                currencyName: 'руб.',
                currencyCode: 'RUR',
            },
            category: {
                id: 91491,
                type: 'GURU',
                advertisingModel: 'CPA',
                name: 'Мобильные телефоны',
            },
            target: 'price-list',
            bigPhoto: {
                url: 'https://avatars.mds.yandex.net/get-marketpic/209514/market_Hpins67UX0M-6XZGr3SKzw/orig',
                width: 246,
                height: 300,
            },
            shopInfo: {
                name: 'ФОТОТЕХНИКА',
                rating: 5,
                id: 955,
                gradeTotal: 2716,
                url: '<wrapped url>',
            },
            warning: undefined,
            delivery: {
                free: false,
                brief: 'в Москву — 399 руб., возможен самовывоз',
                price: {
                    value: '399',
                    currencyName: 'руб.',
                    currencyCode: 'RUR',
                },
                delivery: true,
            },
            photo: 'https://avatars.mds.yandex.net/get-marketpic/209514/market_Hpins67UX0M-6XZGr3SKzw/orig',
            source: 'Market',
            id: 'yDpJekrrgZFhEeS4pWsCcLBEkLNFGMaPDbVR9JmyldRWEY5nEUA1Lg',
            url: '<wrapped url>',
            buttonUrl: '<wrapped url>',
        },
        {
            name: 'Apple iPhone SE 64Gb Silver',
            price: {
                value: 27799,
                currencyName: 'руб.',
                currencyCode: 'RUR',
            },
            category: {
                id: 91491,
                type: 'GURU',
                advertisingModel: 'CPA',
                name: 'Мобильные телефоны',
            },
            target: 'price-list',
            bigPhoto: {
                url: 'https://avatars.mds.yandex.net/get-marketpic/219743/market_Q_GPlcDIDgCNd8XvasWZug/orig',
                width: 470,
                height: 545,
            },
            shopInfo: {
                name: 'TEHNIKALUX',
                rating: 4,
                id: 32902,
                gradeTotal: 1771,
                url: '<wrapped url>',
            },
            warning: undefined,
            delivery: {
                free: false,
                brief: 'в Москву — 390 руб., возможен самовывоз',
                price: {
                    value: '390',
                    currencyName: 'руб.',
                    currencyCode: 'RUR',
                },
                delivery: true,
            },
            photo: 'https://avatars.mds.yandex.net/get-marketpic/219743/market_Q_GPlcDIDgCNd8XvasWZug/orig',
            source: 'Market',
            id:
                'yDpJekrrgZGeiJg8l1_Qna6q2QdpKoTHDJvvPv_1jKXCs0CBJDYFMCL5BEhS2B7DtZEkdmqn10zLTAZXWFhtxVRkstn2BLHMOFsh-8rACnLdUr-cpPJgr5af-7Rp83xBPuX1T-f6i4xjMah2NwNV3rcTcKhS-mLdw57bCqcO8BUcD1bnGRbbRkblwndvbJciy1qiqBAiWP_uDg3Cv7hL3qBgFMylDIrI9Nx63PjnR0F3Nb79JjDepJWEYg0XWyv1Y2jZUs4fa3fqX9hpsOlwOOfDQ078oGbUvtd5nUXfXX4',
            url: '<wrapped url>',
            buttonUrl: '<wrapped url>',
        },
        {
            name: 'Apple iPhone SE 64Gb Gold (A1723)',
            price: {
                value: 25990,
                currencyName: 'руб.',
                currencyCode: 'RUR',
            },
            category: {
                id: 91491,
                type: 'GURU',
                advertisingModel: 'CPA',
                name: 'Мобильные телефоны',
            },
            target: 'price-list',
            bigPhoto: {
                url: 'https://avatars.mds.yandex.net/get-marketpic/230492/market_sHz7wlGGYko3PmuDKCY3hA/orig',
                width: 295,
                height: 350,
            },
            shopInfo: {
                name: '1CLICK',
                rating: 5,
                id: 262,
                gradeTotal: 4950,
                url: '<wrapped url>',
            },
            warning: undefined,
            delivery: {
                free: true,
                brief: 'в Москву — бесплатно, возможен самовывоз',
                delivery: true,
            },
            photo: 'https://avatars.mds.yandex.net/get-marketpic/230492/market_sHz7wlGGYko3PmuDKCY3hA/orig',
            source: 'Market',
            id:
                'yDpJekrrgZEoohSPJiZjFaTELJQD6bVN8wGQSHV9qEOV_p5w3qGu86cSim5M5O9ACe9d7A231UooJwAs1oj1DUj6a4DCohBroOaexVwIo2jJ1_le1RPkn-D3l4HfGOdlVTdHu4NlPv3XS8-2W4o1FTagngRzuTniIXNUodTNWBMcCaSSvkJFafvuh2gXZV-qfLWPtsfvwFH5ew_UxcJ4O7EIpWJDKLG9y8oUZciIfhD5PAVL20qWeQhuHzuMFZx2wdcvwjQBaB4zD6M8wrstyAOsey_uG6PyvqCutLaPJ6c',
            url: '<wrapped url>',
            buttonUrl: '<wrapped url>',
        },
        {
            name: 'Apple iPhone SE 64Gb Rose Gold',
            price: {
                value: 24870,
                currencyName: 'руб.',
                currencyCode: 'RUR',
            },
            category: {
                id: 91491,
                type: 'GURU',
                advertisingModel: 'CPA',
                name: 'Мобильные телефоны',
            },
            target: 'price-list',
            bigPhoto: {
                url: 'https://avatars.mds.yandex.net/get-marketpic/364498/market_2pdfxuJ82BXGpqDQPVzApA/orig',
                width: 484,
                height: 484,
            },
            shopInfo: {
                name: 'Цифроцентр',
                rating: 3,
                id: 141122,
                gradeTotal: 285,
                url: '<wrapped url>',
            },
            warning: undefined,
            delivery: {
                free: false,
                brief: 'в Москву — 400 руб., возможен самовывоз',
                price: {
                    value: '400',
                    currencyName: 'руб.',
                    currencyCode: 'RUR',
                },
                delivery: true,
            },
            photo: 'https://avatars.mds.yandex.net/get-marketpic/364498/market_2pdfxuJ82BXGpqDQPVzApA/orig',
            source: 'Market',
            id:
                'yDpJekrrgZFztD6WyzUvHlunueMn-6Sa7O4BtaDo1tB5b6t08UmMWfcdpi8DiYfj647w6UTbQCPe3vm-HF05L0BpkjhZ2lkDkpNZnrinv5T16P_2I-rvM0QzZzYgzWjo-yBNOEK5UyXhGxmeqXiwLWIoHNpsiIkCjNryDoRsuKjLaWs98mVr5Zik3yDJwryzkh8uLoiUjyRUqL-5zNvcEKOkoEtu72H0puN9CRRz-tO8Q2ZVCCULE-yZV9EvMRIxJWVUw3VoTDKFC57AeTS2SXPXdc9b8WZH7yAez55mBgY',
            url: '<wrapped url>',
            buttonUrl: '<wrapped url>',
        },
    ],
    bucketInfo: {},
    doNotSearchReason: undefined,
    shopInfo: {
        shopName: 'www.CULTGOODS.com',
        rating: 5,
        url: '<wrapped url>',
        gradeTotal: 639,
    },
    optOutInfo: undefined,
    rules: undefined,
    searchInfo: {
        originalQuery: 'Смартфон Apple iPhone SE 64Gb Silver A1662',
        filteredQuery: 'Смартфон Apple iPhone SE 64Gb Silver A1662',
        category: undefined,
        doNotComparePrice: undefined,
        convertedPrice: {
            value: 24450,
            currencyCode: 'RUR',
        },
        offersCount: 19,
        urls: {
            shopsInfo: '<wrapped url>',
            market: '<wrapped url>',
            search:
                'https://market.yandex.ru/search.xml?text=%D0%A1%D0%BC%D0%B0%D1%80%D1%82%D1%84%D0%BE%D0%BD%20Apple%20iPhone%20SE%2064Gb%20Silver%20A1662&clid=2210590&distr_type=4&utm_source=sovetnik&utm_medium=cpc&utm_campaign=offer-title&cvredirect=2&req_id=jbr1dm5pf3qyrqv1s3onqjxlss1o0au7',
            searchButton: '<wrapped url>',
            prices: '<wrapped url>',
            eula: '<wrapped url>',
            feedback: '<wrapped url>',
            help: '<wrapped url>',
            helpPhone: '<wrapped url>',
            helpTablet: '<wrapped url>',
            disable: '<wrapped url>',
            features: '<wrapped url>',
        },
        categories: [
            {
                id: 91491,
                name: 'Мобильные телефоны',
                rank: 0.8214808737111632,
                url: '<wrapped url>',
            },
            {
                id: 10834023,
                name: 'Чехлы-аккумуляторы',
                rank: -1.2889164355594547,
                url: '<wrapped url>',
            },
            {
                id: 91498,
                name: 'Чехлы',
                rank: -1.5030274759601436,
                url: '<wrapped url>',
            },
        ],
    },
    searchResult: undefined,
    searchResultCaption: undefined,
    settings: {
        autoShowShopList: true,
        applicationName: 'Яндекс.Советник',
        isMbrApplication: true,
        items: [
            {
                title: 'Показывать предложения из других регионов',
                enabled: true,
            },
            {
                title: 'Показывать список предложений при наведении мыши',
                enabled: true,
            },
        ],
        region: 'Автоматически',
        needShowNotifications: true,
        showProductNotifications: true,
        showAviaNotifications: true,
        showAutoNotifications: true,
    },
};
