/* eslint-disable max-len */

'use strict';

module.exports = {
    model: {
        name: 'Apple iPhone X 256GB',
        vendor: 'Apple',
        reviewsCount: 21,

        rating: 3.5,
        gradeCount: 88,
        prices: {
            max: 123990,
            min: 80720,
            avg: 85000,
            curCode: 'RUR',
            curName: 'руб.',
        },
        offersCount: 190,
        mainPhoto: {
            url: 'https://avatars.mds.yandex.net/get-mpic/397397/img_id7051974271832358544.png/orig',
            width: 321,
            height: 620,
        },
        isNew: 1,
        photo: 'https://avatars.mds.yandex.net/get-mpic/397397/img_id7051974271832358544.png/4hq',
        urls: {
            model: '<wrapped url>',
            modelPicture: '<wrapped url>',
            offers: '<wrapped url>',
            map: '<wrapped url>',
            price: '<wrapped url>',
            reviews: '<wrapped url>',
            reviewsBadge: '<wrapped url>',
        },
    },
    offers: [
        {
            name: 'Apple iPhone X 256 Gb Space Gray',
            price: {
                value: 80750,
                currencyName: 'руб.',
                currencyCode: 'RUR',
            },
            category: {
                id: 91491,
                type: 'GURU',
                advertisingModel: 'CPA',
                name: 'Мобильные телефоны',
            },
            target: 'pricebar',
            bigPhoto: {
                url: 'https://avatars.mds.yandex.net/get-marketpic/245136/market_7kKYlH6P7GUnbsM9HxPnlw/orig',
                width: 704,
                height: 942,
            },
            shopInfo: {
                name: 'iMoscow.Store',
                rating: 4,
                id: 423057,
                gradeTotal: 11,
                url: '<wrapped url>',
            },
            warning: undefined,
            delivery: {
                free: false,
                brief: 'в Москву — 290 руб., возможен самовывоз',
                price: {
                    value: '290',
                    currencyName: 'руб.',
                    currencyCode: 'RUR',
                },
                delivery: true,
            },
            photo: 'https://avatars.mds.yandex.net/get-marketpic/245913/market_LHLGRK7jlexVgafBgZMDsQ/orig',
            source: 'Market',
            id:
                'yDpJekrrgZGCXzGrW_b92BZB180fphqAK54KgLlK2cJfcBb163DOZCILONfAKtG7uFx1MGqGF3SFsTUZC9oDIDpCbM0QJsW36ySbFBRTh3nxS2S2zL-IcG3F2SCGgyVMJ9xccMWKc0hNy4WfbluolT8uYwq3QDeI323R44crdFITG-Z4aDuJLBWgVD6vhGQwJsueEq5dXDYKS_o71__OQFAwucFz9JUbQ-l3o8dwBs3nGV8s2eEx5zOfHOGwKklyqeVDMOZGDqom2YsqqulY4bZgdwQRpfTjnHKEJjUtdkI',
            url: '<wrapped url>',
            optOutUrl: '<wrapped url>',
            buttonUrl: '<wrapped url>',
            surfaceUrl: '<wrapped url>',
        },
        {
            name: 'Телефон Apple iPhone X 256Gb Space Gray',
            price: {
                value: 80849,
                currencyName: 'руб.',
                currencyCode: 'RUR',
            },
            category: {
                id: 91491,
                type: 'GURU',
                advertisingModel: 'CPA',
                name: 'Мобильные телефоны',
            },
            target: 'price-list',
            bigPhoto: {
                url: 'https://avatars.mds.yandex.net/get-marketpic/208469/market_1Of259utTIiVnWqja7GFtA/orig',
                width: 600,
                height: 600,
            },
            shopInfo: {
                name: 'TechFast',
                rating: 5,
                id: 368738,
                gradeTotal: 262,
                url: '<wrapped url>',
            },
            warning: undefined,
            delivery: {
                free: false,
                brief: 'не производится (самовывоз)',
                delivery: false,
            },
            photo: 'https://avatars.mds.yandex.net/get-marketpic/208469/market_1Of259utTIiVnWqja7GFtA/orig',
            source: 'Market',
            id:
                'yDpJekrrgZHhWq-Wp6qRdvNfa4PxPDXc2hLK1jAygZrFUHEzWA6JaOyiJlHF4z36VHeM56UoFWifGS8BAEkp7U2o7BUJvyHmmoBMtgUmKwWPdXTdVq1YJPD7woAMJdon-O8B3QWahswXA6llQc-6Ec6U4ZeyrkGt1xWWWbi9mRyKy4See-GyLZw6IGlvLv92my-HpXFH9sFBzlVGHqXfbPKqYdA5oq5ZZhG6RNwDF6SfaAyITMOSAeWji3Kp3tjTKchsDJo16H0nb8NVkGA99HBUdG3XxA5hVgCnIQVD62c',
            url: '<wrapped url>',
            buttonUrl: '<wrapped url>',
        },
        {
            name: 'Apple iPhone X 256Gb Space Gray (Серый Космос)',
            price: {
                value: 80790,
                currencyName: 'руб.',
                currencyCode: 'RUR',
            },
            category: {
                id: 91491,
                type: 'GURU',
                advertisingModel: 'CPA',
                name: 'Мобильные телефоны',
            },
            target: 'price-list',
            bigPhoto: {
                url: 'https://avatars.mds.yandex.net/get-marketpic/221955/market_Pg8GjbGu-5heSHRBtBWAaQ/orig',
                width: 99,
                height: 200,
            },
            shopInfo: {
                name: 'PRO Mobile',
                rating: 4,
                id: 397212,
                gradeTotal: 9,
                url: '<wrapped url>',
            },
            warning: undefined,
            delivery: {
                free: false,
                brief: 'в Москву — 400 руб., возможен самовывоз',
                price: {
                    value: '400',
                    currencyName: 'руб.',
                    currencyCode: 'RUR',
                },
                delivery: true,
            },
            photo: 'https://avatars.mds.yandex.net/get-marketpic/221955/market_Pg8GjbGu-5heSHRBtBWAaQ/orig',
            source: 'Market',
            id:
                'yDpJekrrgZGO6jM06K0EC4pmFYuCAXZ8ixPg2_bgKJBENn7vaDsUBtjGzFV-eX9cYAsgammCzsZDdaJrOrOU5fYFaaR9vqRrpq1un3W2Uocsrug0dn0w2Z4imSzJiH_9EXMSWV51vLeLj4F1MLEF5Mow3GFJtNpJDWvYH7qrkm8n1_vz2a0xe-SrDiBj2fR391zZeLcJeRf3xDygyQ7Ta6QJjo1qNEmerkF93kTR24Gg6aLXQanjGeliiQP1_4gkqcl0Rf3xORGuazjlxfSkTU09sLOc8ZIpYeayk6sxM7Q',
            url: '<wrapped url>',
            buttonUrl: '<wrapped url>',
        },
        {
            name: 'Apple iPhone X 256 Gb Space Gray',
            price: {
                value: 80750,
                currencyName: 'руб.',
                currencyCode: 'RUR',
            },
            category: {
                id: 91491,
                type: 'GURU',
                advertisingModel: 'CPA',
                name: 'Мобильные телефоны',
            },
            target: 'price-list',
            bigPhoto: {
                url: 'https://avatars.mds.yandex.net/get-marketpic/245136/market_7kKYlH6P7GUnbsM9HxPnlw/orig',
                width: 704,
                height: 942,
            },
            shopInfo: {
                name: 'iMoscow.Store',
                rating: 4,
                id: 423057,
                gradeTotal: 11,
                url: '<wrapped url>',
            },
            warning: undefined,
            delivery: {
                free: false,
                brief: 'в Москву — 290 руб., возможен самовывоз',
                price: {
                    value: '290',
                    currencyName: 'руб.',
                    currencyCode: 'RUR',
                },
                delivery: true,
            },
            photo: 'https://avatars.mds.yandex.net/get-marketpic/245913/market_LHLGRK7jlexVgafBgZMDsQ/orig',
            source: 'Market',
            id:
                'yDpJekrrgZGCXzGrW_b92BZB180fphqAK54KgLlK2cJfcBb163DOZCILONfAKtG7uFx1MGqGF3SFsTUZC9oDIDpCbM0QJsW36ySbFBRTh3nxS2S2zL-IcG3F2SCGgyVMJ9xccMWKc0hNy4WfbluolT8uYwq3QDeI323R44crdFITG-Z4aDuJLBWgVD6vhGQwJsueEq5dXDYKS_o71__OQFAwucFz9JUbQ-l3o8dwBs3nGV8s2eEx5zOfHOGwKklyqeVDMOZGDqom2YsqqulY4bZgdwQRpfTjnHKEJjUtdkI',
            url: '<wrapped url>',
            buttonUrl: '<wrapped url>',
        },
    ],
    shopInfo: undefined,
    bucketInfo: {},
    doNotSearchReason: undefined,
    notification: {
        title: 'Более выгодная цена - 80 750 руб.',
        text: 'на Apple iPhone X 256GB\nв магазине iMoscow.Store',
        link: '%3Cwrapped%20url%3E?target=notification&click_type=paid',
        photo: 'https://avatars.mds.yandex.net/get-marketpic/245913/market_LHLGRK7jlexVgafBgZMDsQ/orig',
        contextMessage: 'Доставка 290 руб.',
        buttons: [
            {
                title: 'Посмотреть',
                link: '%3Cwrapped%20url%3E?target=notification-button&click_type=paid',
            },
            {
                title: 'Еще предложения',
                link: '%3Cwrapped%20url%3E?target=notification-market-button&click_type=market',
            },
        ],
        showWhen: [
            'parent',
            'display',
            'position',
            'text-change',
            'size',
            'zindex',
            'zindexframe',
            'opacity',
            'transform',
            'node-remove',
            'inline-styles',
            'external-styles',
            'stylesheets',
        ],
        requireInteraction: true,
        duration: 30000,
    },
    optOutInfo: undefined,
    rules: undefined,
    searchInfo: {
        category: undefined,
        doNotComparePrice: undefined,
        originalQuery: 'Мобильный телефон Apple iPhone X 256GB',
        filteredQuery: 'Мобильный телефон Apple iPhone X 256GB',
        convertedPrice: {
            value: 80950,
            currencyCode: 'RUR',
        },
        offersCount: 190,
        urls: {
            shopsInfo: '<wrapped url>',
            market: '<wrapped url>',
            search:
                'https://market.yandex.ru/search.xml?text=%D0%9C%D0%BE%D0%B1%D0%B8%D0%BB%D1%8C%D0%BD%D1%8B%D0%B9%20%D1%82%D0%B5%D0%BB%D0%B5%D1%84%D0%BE%D0%BD%20Apple%20iPhone%20X%20256GB&clid=2210590&distr_type=4&utm_source=sovetnik&utm_medium=cpc&utm_campaign=offer-title&cvredirect=2&req_id=jblcn9wys7oq5sqzjga4a6jn9j5bsgew',
            searchButton: '<wrapped url>',
            prices: '<wrapped url>',
            eula: '<wrapped url>',
            feedback: '<wrapped url>',
            help: '<wrapped url>',
            helpPhone: '<wrapped url>',
            helpTablet: '<wrapped url>',
            disable: '<wrapped url>',
            features: '<wrapped url>',
        },
        categories: [
            {
                id: 91491,
                name: 'Мобильные телефоны',
                rank: 2.073835906607096,
                url: '<wrapped url>',
            },
            {
                id: 91498,
                name: 'Чехлы',
                rank: -2.413292280467597,
                url: '<wrapped url>',
            },
            {
                id: 10834023,
                name: 'Чехлы-аккумуляторы',
                rank: -2.453011833347297,
                url: '<wrapped url>',
            },
        ],
    },
    searchResult: undefined,
    searchResultCaption: undefined,
    settings: {
        autoShowShopList: true,
        applicationName: 'Яндекс.Советник',
        isMbrApplication: true,
        items: [
            {
                title: 'Показывать предложения из других регионов',
                enabled: true,
            },
            {
                title: 'Показывать список предложений при наведении мыши',
                enabled: true,
            },
        ],
        region: 'Автоматически',
        needShowNotifications: true,
        showProductNotifications: true,
        showAviaNotifications: true,
        showAutoNotifications: true,
    },
};
