/* eslint-disable max-len */

'use strict';

module.exports = {
    model: {
        name: 'Настольная игра Hasbro games Monopoly С банковскими картами (обновленная)',
        reviewsCount: 1,
        rating: 0,
        gradeCount: 0,
        info: {
            constants: {
                atMarket: 'на Яндекс.Маркете',
                avgPrice: 'Средняя цена',
                avgPriceGraph: 'График средней цены на',
                ratingTooltipText: 'Рейтинг товара %s из 5',
            },
        },
        isNew: false,
        links: {
            constants: {
                allPrices: 'Все цены',
                allPricesMarket: 'Все цены на Яндекс.Маркете',
                closestShops: 'Магазины рядом',
                reviews: 'Отзывы',
                reviewsMarket: 'Отзывы на Яндекс.Маркете',
                shopsOnMap: 'Предложения магазинов на карте',
            },
        },
        prices: {
            max: 4687,
            min: 2194,
            avg: 2799,
            curCode: 'RUR',
            curName: 'руб.',
        },
        offersCount: 39,
        mainPhoto: {
            width: 701,
            height: 542,
            url: 'https://avatars.mds.yandex.net/get-mpic/372220/img_id8335316585521998506.jpeg/orig',
        },
        photo: 'https://avatars.mds.yandex.net/get-mpic/372220/img_id8335316585521998506.jpeg/orig',

        urls: {
            model: '<wrapped url>',
            modelPicture: '<wrapped url>',
            offers: '<wrapped url>',
            map: '<wrapped url>',
            price: '<wrapped url>',
            reviews: '<wrapped url>',
            reviewsBadge: '<wrapped url>',
        },
    },
    offers: [
        {
            name: 'Настольная игра Monopoly с банковскими картами (обновленная)',
            price: {
                value: 2199,
                discount: '37',
                base: 3480,
                currencyCode: 'RUR',
                currencyName: 'руб.',
            },
            constants: {
                buttonText: 'В магазин',
                shopInfoTooltip: 'Перейти в магазин',
                discount: 'Скидка',
                shopRatingText: 'Рейтинг %s из 5 на основе',
            },
            category: {
                id: 10682647,
                name: 'Настольные игры',
                fullName: 'Настольные игры',
                type: 'GURU',
                childCount: 0,
                advertisingModel: 'HYBRID',
                viewType: 'GRID',
            },
            target: 'pricebar',
            shopInfo: {
                name: 'Дочки и Сыночки',
                id: 179876,
                rating: 5,
                gradeTotal: 9370,
                url: '<wrapped url>',
            },
            delivery: {
                free: false,
                pickup: true,
                brief: 'в Москву — 150 руб., возможен самовывоз',
                price: {
                    value: '150',
                    currencyCode: 'RUR',
                    currencyName: 'руб.',
                },
                delivery: true,
                daysFrom: 1,
                daysTo: 1,
                cityFrom: 'Москвы',
                cityTo: 'Москву',
            },
            warning: undefined,
            photo: 'https://avatars.mds.yandex.net/get-marketpic/208616/market_YafVySBIwd6V7E_RcwvRaA/orig',
            source: 'Market',
            bigPhoto: {
                width: 1000,
                height: 1076,
                url: 'https://avatars.mds.yandex.net/get-marketpic/208616/market_YafVySBIwd6V7E_RcwvRaA/orig',
            },
            id:
                'yDpJekrrgZGvdSG4WBl3Zva7m0gZ8RDohljZnpNWsyLmg94V7m7XXoO6sX5_36d9MVse8-_wqT3EELF5LtCjtA_yM9q8WXuEIFfjaH8yd6JJ-yADjQkOi1ZSyzYLoQ2cN83WNQBgMwWcOrws9Q0XTFCwFlbbp-C38eCSY8LJVCvbF9HaeWQAoxiOxMoJNuLJQBkNCYx6fo1MeHpEcnqySeWvcpP4eT4RGS6hRprrfLnPIag-zxqXCo3MpE7IM3amruOvjk-R3Ba_i6pcH-5MuGSywEFuRcBSj7UiYzgKiRE',
            url: '<wrapped url>',
            optOutUrl: '<wrapped url>',
            buttonUrl: '<wrapped url>',
            surfaceUrl: '<wrapped url>',
            profitBadgeText: {
                prefix: 'до',
                value: '−4%',
            },
        },
        {
            name: 'Monopoly Настольная игра Банк без границ',
            price: {
                value: 2329,
                currencyCode: 'RUR',
                currencyName: 'руб.',
            },
            constants: {
                buttonText: 'В магазин',
                shopInfoTooltip: 'Перейти в магазин',
                shopRatingText: 'Рейтинг %s из 5 на основе',
            },
            category: {
                id: 10682647,
                name: 'Настольные игры',
                fullName: 'Настольные игры',
                type: 'GURU',
                childCount: 0,
                advertisingModel: 'HYBRID',
                viewType: 'GRID',
            },
            target: 'price-list',
            shopInfo: {
                name: 'OZON.ru',
                id: 155,
                rating: 2,
                gradeTotal: 34087,
                url: '<wrapped url>',
            },
            delivery: {
                free: false,
                pickup: true,
                brief: 'в Москву — 299 руб., возможен самовывоз',
                price: {
                    value: '299',
                    currencyCode: 'RUR',
                    currencyName: 'руб.',
                },
                delivery: true,
                daysFrom: 1,
                daysTo: 1,
                cityFrom: 'Москвы',
                cityTo: 'Москву',
            },
            warning: undefined,
            photo: 'https://avatars.mds.yandex.net/get-marketpic/204557/market_UMbKLSBLDhvKWzmv7q_YuQ/orig',
            source: 'Market',
            bigPhoto: {
                width: 1200,
                height: 853,
                url: 'https://avatars.mds.yandex.net/get-marketpic/230492/market_QJHCBCVG2MIDr3EPqfs_kA/orig',
            },
            id:
                'yDpJekrrgZGMMVoVIEAtd-i7j73Wn8W6MmbTNmpGIiUBu858JJsDxGK4sqba1k1XdF2yDQ_PCuXnZJlZ9mvSCJDtRqzzSCvnJhwGC3Oj9nXvOradZpSb6rXQZwGEGC2luYnmSxavUIAGNjJtinsq49Vi0riOeVcYx5Xqe_Z0pVGQy0D7jlwGtUGR9sOA-_Kyk390hd3mAVyQdTesAP7ty1A1xJVfCvUFx4cT7zW0f1SuMuEAxTyWfJqSDTAK6QDPO6h-Tr9YLMtJgu5mIIAreCmawPKAJgQo53CdMrgGlwI',
            url: '<wrapped url>',
            buttonUrl: '<wrapped url>',
        },
        {
            name: 'Игра настольная "Монополия с банковскими карточками", MONOPOLY Hasbro, в коробке, B6677',
            price: {
                value: 4278,
                currencyCode: 'RUR',
                currencyName: 'руб.',
            },
            constants: {
                buttonText: 'В магазин',
                shopInfoTooltip: 'Перейти в магазин',
                shopRatingText: 'Рейтинг %s из 5 на основе',
            },
            category: {
                id: 10682647,
                name: 'Настольные игры',
                fullName: 'Настольные игры',
                type: 'GURU',
                childCount: 0,
                advertisingModel: 'HYBRID',
                viewType: 'GRID',
            },
            target: 'price-list',
            shopInfo: {
                name: 'Kit-Hobby.ru - Офис. Школа. Творчество',
                id: 394515,
                rating: 5,
                gradeTotal: 87,
                url: '<wrapped url>',
            },
            delivery: {
                free: false,
                pickup: true,
                brief: 'в Москву — 249 руб., возможен самовывоз',
                price: {
                    value: '249',
                    currencyCode: 'RUR',
                    currencyName: 'руб.',
                },
                delivery: true,
                daysFrom: 7,
                daysTo: 7,
                cityFrom: 'Москвы',
                cityTo: 'Москву',
            },
            warning: undefined,
            photo: 'https://avatars.mds.yandex.net/get-marketpic/209514/market_lHCX-HMrpLdZu35tGnsPVw/orig',
            source: 'Market',
            bigPhoto: {
                width: 160,
                height: 160,
                url: 'https://avatars.mds.yandex.net/get-marketpic/209514/market_lHCX-HMrpLdZu35tGnsPVw/orig',
            },
            id:
                'yDpJekrrgZFYw3UKTkjyqz0_dF0BB_eYP59qIixf2rAvZwqD31FFitJftxfivbxCXaDGymPTLdt8BHZXLEDPUm_8d5UZtKnYyRx0UoAGOf3IxcmEYJOW27UIhX0s3oe9vSsS-UgK1Qdn734ZoFL_IC6Mlhqv4pggI1lKWx5bD-PX-hA4W7KZtzA1Olvc7vrEweqleq5M20NRJt6dEO99JraqEkOP--J-LCDAxGHH-887w7r_RjEw_0Ovd4E17IUiAuOToQgWXIJZh696iVGUJGCNvwbnuyOcqhlL6twNpBQ',
            url: '<wrapped url>',
            buttonUrl: '<wrapped url>',
        },
        {
            name: 'Настольная игра Hasbro Monopoly B6677 Монополия с банковскими картами (обновленная)',
            price: {
                value: 2799,
                currencyCode: 'RUR',
                currencyName: 'руб.',
            },
            constants: {
                buttonText: 'В магазин',
                shopInfoTooltip: 'Перейти в магазин',
                shopRatingText: 'Рейтинг %s из 5 на основе',
            },
            category: {
                id: 10682647,
                name: 'Настольные игры',
                fullName: 'Настольные игры',
                type: 'GURU',
                childCount: 0,
                advertisingModel: 'HYBRID',
                viewType: 'GRID',
            },
            target: 'price-list',
            shopInfo: {
                name: 'TOY.RU',
                id: 56564,
                rating: 4,
                gradeTotal: 5494,
                url: '<wrapped url>',
            },
            delivery: {
                free: false,
                pickup: true,
                brief: 'в Москву — 99 руб., возможен самовывоз',
                price: {
                    value: '99',
                    currencyCode: 'RUR',
                    currencyName: 'руб.',
                },
                delivery: true,
                daysFrom: 2,
                daysTo: 2,
                cityFrom: 'Москвы',
                cityTo: 'Москву',
            },
            warning: undefined,
            photo: 'https://avatars.mds.yandex.net/get-marketpic/174581/market_W8f3HiEC3gNz0zdMup3wDA/orig',
            source: 'Market',
            bigPhoto: {
                width: 600,
                height: 600,
                url: 'https://avatars.mds.yandex.net/get-marketpic/174581/market_W8f3HiEC3gNz0zdMup3wDA/orig',
            },
            id: 'yDpJekrrgZEGqvpvMGyhJsOY3lroaO4xOzk2g1PKSc5xit7Oqre4kg',
            url: '<wrapped url>',
            buttonUrl: '<wrapped url>',
        },
        {
            name: 'Настольная игра Monopoly с банковскими картами (обновленная)',
            price: {
                value: 2199,
                discount: '37',
                base: 3480,
                currencyCode: 'RUR',
                currencyName: 'руб.',
            },
            constants: {
                buttonText: 'В магазин',
                shopInfoTooltip: 'Перейти в магазин',
                discount: 'Скидка',
                shopRatingText: 'Рейтинг %s из 5 на основе',
            },
            category: {
                id: 10682647,
                name: 'Настольные игры',
                fullName: 'Настольные игры',
                type: 'GURU',
                childCount: 0,
                advertisingModel: 'HYBRID',
                viewType: 'GRID',
            },
            target: 'price-list',
            shopInfo: {
                name: 'Дочки и Сыночки',
                id: 179876,
                rating: 5,
                gradeTotal: 9370,
                url: '<wrapped url>',
            },
            delivery: {
                free: false,
                pickup: true,
                brief: 'в Москву — 150 руб., возможен самовывоз',
                price: {
                    value: '150',
                    currencyCode: 'RUR',
                    currencyName: 'руб.',
                },
                delivery: true,
                daysFrom: 1,
                daysTo: 1,
                cityFrom: 'Москвы',
                cityTo: 'Москву',
            },
            warning: undefined,
            photo: 'https://avatars.mds.yandex.net/get-marketpic/208616/market_YafVySBIwd6V7E_RcwvRaA/orig',
            source: 'Market',
            bigPhoto: {
                width: 1000,
                height: 1076,
                url: 'https://avatars.mds.yandex.net/get-marketpic/208616/market_YafVySBIwd6V7E_RcwvRaA/orig',
            },
            id:
                'yDpJekrrgZGvdSG4WBl3Zva7m0gZ8RDohljZnpNWsyLmg94V7m7XXoO6sX5_36d9MVse8-_wqT3EELF5LtCjtA_yM9q8WXuEIFfjaH8yd6JJ-yADjQkOi1ZSyzYLoQ2cN83WNQBgMwWcOrws9Q0XTFCwFlbbp-C38eCSY8LJVCvbF9HaeWQAoxiOxMoJNuLJQBkNCYx6fo1MeHpEcnqySeWvcpP4eT4RGS6hRprrfLnPIag-zxqXCo3MpE7IM3amruOvjk-R3Ba_i6pcH-5MuGSywEFuRcBSj7UiYzgKiRE',
            url: '<wrapped url>',
            buttonUrl: '<wrapped url>',
        },
        {
            name: 'Настольная игра HASBRO B6677 Монополия с банковскими картами (обновленная)',
            price: {
                value: 3010,
                currencyCode: 'RUR',
                currencyName: 'руб.',
            },
            constants: {
                buttonText: 'В магазин',
                shopInfoTooltip: 'Перейти в магазин',
                shopRatingText: 'Рейтинг %s из 5 на основе',
            },
            category: {
                id: 10682647,
                name: 'Настольные игры',
                fullName: 'Настольные игры',
                type: 'GURU',
                childCount: 0,
                advertisingModel: 'HYBRID',
                viewType: 'GRID',
            },
            target: 'price-list',
            shopInfo: {
                name: 'ОНЛАЙН ТРЕЙД.РУ',
                id: 255,
                rating: 5,
                gradeTotal: 68301,
                url: '<wrapped url>',
            },
            delivery: {
                free: false,
                pickup: true,
                brief: 'в Москву — 300 руб., возможен самовывоз',
                price: {
                    value: '300',
                    currencyCode: 'RUR',
                    currencyName: 'руб.',
                },
                delivery: true,
                daysFrom: 2,
                daysTo: 3,
                cityFrom: 'Москвы',
                cityTo: 'Москву',
            },
            warning: undefined,
            photo: 'https://avatars.mds.yandex.net/get-marketpic/363663/market_HIW8w4hgdebgMRkbfIcDXg/orig',
            source: 'Market',
            bigPhoto: {
                width: 600,
                height: 600,
                url: 'https://avatars.mds.yandex.net/get-marketpic/363663/market_HIW8w4hgdebgMRkbfIcDXg/orig',
            },
            id: 'yDpJekrrgZE32ctA1t3XK9flbhihsL5dtYtPziiGsKv9fAAUqRxqXg',
            url: '<wrapped url>',
            buttonUrl: '<wrapped url>',
        },
        {
            name: 'Настольная игра Hasbro Монополия Банк без границ B6677121',
            price: {
                value: 3090,
                currencyCode: 'RUR',
                currencyName: 'руб.',
            },
            constants: {
                buttonText: 'В магазин',
                shopInfoTooltip: 'Перейти в магазин',
                freeDelivery: 'Бесплатно',
                shopRatingText: 'Рейтинг %s из 5 на основе',
            },
            category: {
                id: 10682647,
                name: 'Настольные игры',
                fullName: 'Настольные игры',
                type: 'GURU',
                childCount: 0,
                advertisingModel: 'HYBRID',
                viewType: 'GRID',
            },
            target: 'price-list',
            shopInfo: {
                name: 'Подари игру',
                id: 395204,
                rating: 5,
                gradeTotal: 41,
                url: '<wrapped url>',
            },
            delivery: {
                free: true,
                pickup: true,
                brief: 'в Москву — бесплатно, возможен самовывоз',
                price: {
                    value: '0',
                    currencyCode: 'RUR',
                    currencyName: 'руб.',
                },
                delivery: true,
                daysFrom: 1,
                daysTo: 1,
                cityFrom: 'Москвы',
                cityTo: 'Москву',
            },
            warning: undefined,
            photo: 'https://avatars.mds.yandex.net/get-marketpic/175315/market_51_kG6rRLVBVrIUe2CsQhg/orig',
            source: 'Market',
            bigPhoto: {
                width: 650,
                height: 650,
                url: 'https://avatars.mds.yandex.net/get-marketpic/175315/market_51_kG6rRLVBVrIUe2CsQhg/orig',
            },
            id:
                'yDpJekrrgZEwDUdLttSr-OZElwUS4nxUbvj4bbUbr6bFtDMhnH34cJLCE92pjwa9qjmg2_vXgWXIwuuA5bwDwbwmN6c1Qx8KwkspZlCWd9v9HfW-IuJVjIbPN_83GyYsPPj1A8CcjR3A6v8pXHHcWNvNEvvjthGDTuU5uVLmlqCiSXSQYfkaTc1HS06GHf8s_iiRE8gW0d6Hjce3BjXhO3JDV3p9J8bekPUSTwMt71nr96DPAXievKYZrN-nsLYYPwGKJuWHGwwl_DdSSfslgd0KuJoqvGRm4f3S4Q3afd4',
            url: '<wrapped url>',
            buttonUrl: '<wrapped url>',
        },
    ],
    feedback: {
        constants: {
            closeButtonText: 'Закрыть',
            error: 'Комментарий не может быть пустым.',
            placeholder:
                'Пожалуйста, расскажите, что именно случилось. Ваш комментарий поможет нам исправить проблему быстрее.',
            submitButtonText: 'Отправить',
            text: 'Ваше сообщение поможет улучшить Советника',
            thanks: 'Спасибо!',
            title: 'Спасибо, мы получили ваш отчёт об ошибке',
        },
    },
    pricebar: {
        constants: {
            closeButtonTooltip: 'Закрыть',
            goButtonText: 'Посмотреть',
            goButtonTooltip: 'Посмотреть',
            inShopText: 'в магазине',
            infoButtonTooltip: 'О программе',
            moreButtonText: 'Еще предложения',
            moreButtonTooltip: 'Предложения других магазинов',
            prevText: 'Более выгодная цена на',
            settingsButtonTooltip: 'Настройки',
        },
    },
    searchResult: undefined,
    searchResultCaption: undefined,
    bucketInfo: {},
    shopInfo: {
        shopName: 'ЭЛЬДОРАДО',
        url: '<wrapped url>',
    },
    notification: {
        title: 'Более выгодная цена - 2 199 руб.',
        text:
            'на Настольная игра Hasbro games Monopoly С банковскими картами (обновленная)\nв магазине Дочки и Сыночки',
        link: '%3Cwrapped%20url%3E?target=notification&click_type=paid',
        photo: 'https://avatars.mds.yandex.net/get-marketpic/208616/market_YafVySBIwd6V7E_RcwvRaA/orig',
        contextMessage: 'Доставка 150 руб.',
        buttons: [
            {
                title: 'Посмотреть',
                link: '%3Cwrapped%20url%3E?target=notification-button&click_type=paid',
            },
            {
                title: 'Еще предложения',
                link: '%3Cwrapped%20url%3E?target=notification-market-button&click_type=market',
            },
        ],
        showWhen: [
            'parent',
            'display',
            'position',
            'text-change',
            'size',
            'zindex',
            'zindexframe',
            'opacity',
            'transform',
            'node-remove',
            'inline-styles',
            'external-styles',
            'stylesheets',
        ],
        requireInteraction: true,
        duration: 30000,
    },
    searchInfo: {
        originalQuery: 'Настольная игра MONOPOLY Монополия с банковскими картами, обновленная (B6677)',
        filteredQuery: 'Настольная игра MONOPOLY Монополия с банковскими картами, обновленная (B6677)',
        convertedPrice: {
            value: 2299,
            currencyCode: 'RUR',
        },
        offersCount: 39,
        urls: {
            shopsInfo: '<wrapped url>',
            market: '<wrapped url>',
            search:
                'https://market.yandex.ru/search.xml?text=%D0%9D%D0%B0%D1%81%D1%82%D0%BE%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F%20%D0%B8%D0%B3%D1%80%D0%B0%20MONOPOLY%20%D0%9C%D0%BE%D0%BD%D0%BE%D0%BF%D0%BE%D0%BB%D0%B8%D1%8F%20%D1%81%20%D0%B1%D0%B0%D0%BD%D0%BA%D0%BE%D0%B2%D1%81%D0%BA%D0%B8%D0%BC%D0%B8%20%D0%BA%D0%B0%D1%80%D1%82%D0%B0%D0%BC%D0%B8%2C%20%D0%BE%D0%B1%D0%BD%D0%BE%D0%B2%D0%BB%D0%B5%D0%BD%D0%BD%D0%B0%D1%8F%20(B6677)&clid=2210590&distr_type=4&utm_source=sovetnik&utm_medium=cpc&utm_campaign=offer-title&cvredirect=2&req_id=jd1oocot8isgyf4in7rek5cta8ad5zmn',
            searchButton: '<wrapped url>',
            prices: '<wrapped url>',
            eula: '<wrapped url>',
            feedback: '<wrapped url>',
            help: '<wrapped url>',
            helpPhone: '<wrapped url>',
            helpTablet: '<wrapped url>',
            disable: '<wrapped url>',
            features: '<wrapped url>',
            userHelp: '<wrapped url>',
        },
        category: undefined,
        categories: [
            {
                id: 10682647,
                name: 'Настольные игры',
                rank: 2.7774426934268526,
                url: '<wrapped url>',
            },
            {
                id: 13887809,
                name: 'Шахматы, шашки, нарды',
                rank: -6.456194007568087,
                url: '<wrapped url>',
            },
            {
                id: 10682659,
                name: 'Детские компьютеры',
                rank: -6.4796440107369815,
                url: '<wrapped url>',
            },
        ],
        doNotComparePrice: undefined,
    },
    rules: undefined,
    optOutInfo: undefined,
    settings: {
        constants: {
            changeRegion: 'Изменить регион',
            changeSettings: 'Изменить настройки',
            disable: 'Выключить на этом сайте',
            yourRegion: 'Ваш регион:',
        },
        autoShowShopList: true,
        applicationName: 'Яндекс.Советник',
        isMbrApplication: true,
        items: [
            {
                title: 'Показывать предложения из других регионов',
                enabled: true,
            },
            {
                title: 'Показывать список предложений при наведении мыши',
                enabled: true,
            },
        ],
        region: 'Автоматически',
        needShowNotifications: true,
        showProductNotifications: true,
        showAviaNotifications: true,
        showAutoNotifications: true,
    },
    doNotSearchReason: undefined,
    footer: {
        constants: {
            autoDetectedRegion: 'Автоматически',
            changeCurrentRegion: 'Изменить текущий регион',
            changeRegion: 'Изменить регион',
            data: {
                letter: 'Я',
                prefix: 'Данные',
                suffix: 'ндекс.Маркета',
            },
            infoAboutShop: 'Информация о продавцах',
            infoAboutShopLegal: 'Юридическая информация о продавцах',
            feedback: 'Сообщить об ошибке',
            gotoMarket: 'Перейти на Яндекс.Маркет',
            wrongProductDetect: 'Неверно определен товар',
        },
    },
    info: {
        constants: {
            disableText: 'Как отключить Советника',
            featuresText: 'Что ещё умеет Советник',
            feedbackText: 'Обратная связь',
            helpText: 'Помощь',
            licenseText: 'Лицензионное соглашение',
            prefix: 'для ',
            text: 'Это приложение подсказывает вам более выгодные цены на товары, на которые вы смотрите прямо сейчас.',
            upperLine: 'Яндекс.Советник',
            yandexLLC: '© %s ООО «Яндекс.Маркет»',
        },
    },
    tabs: {
        constants: {
            offers: 'Предложения магазинов',
        },
    },
};
