/* eslint-disable max-len */

'use strict';

module.exports = {
    model: {
        name: 'LG 43LJ510V',
        vendor: 'LG',
        reviewsCount: 5,

        rating: 3.5,
        gradeCount: 6,
        prices: {
            max: 26014,
            min: 20450,
            avg: 23849,
            curCode: 'RUR',
            curName: 'руб.',
        },
        offersCount: 67,
        mainPhoto: {
            url: 'https://avatars.mds.yandex.net/get-mpic/200316/img_id1791511517718709854/orig',
            width: 701,
            height: 466,
        },
        isNew: 0,
        photo: 'https://avatars.mds.yandex.net/get-mpic/200316/img_id1791511517718709854/4hq',
        urls: {
            model: '<wrapped url>',
            modelPicture: '<wrapped url>',
            offers: '<wrapped url>',
            map: '<wrapped url>',
            price: '<wrapped url>',
            reviews: '<wrapped url>',
            reviewsBadge: '<wrapped url>',
        },
    },
    offers: [
        {
            name: "Телевизор LED LG 43' 43LJ510V",
            price: {
                value: 23178,
                currencyName: 'руб.',
                currencyCode: 'RUR',
            },
            category: {
                id: 90639,
                type: 'GURU',
                advertisingModel: 'CPA',
                name: 'Телевизоры',
            },
            target: 'pricebar',
            bigPhoto: {
                url: 'https://avatars.mds.yandex.net/get-marketpic/163900/market_lQ_fiPrRgh-A69VqpyOlmg/orig',
                width: 800,
                height: 528,
            },
            shopInfo: {
                name: 'Techmela',
                rating: 4,
                id: 425757,
                gradeTotal: 10,
                url: '<wrapped url>',
            },
            delivery: {
                free: false,
                brief: 'в Москву — 500 руб., возможен самовывоз',
                price: {
                    value: '500',
                    currencyName: 'руб.',
                    currencyCode: 'RUR',
                },
                delivery: true,
            },
            photo: 'https://avatars.mds.yandex.net/get-marketpic/163900/market_lQ_fiPrRgh-A69VqpyOlmg/orig',
            source: 'Market',
            id:
                'yDpJekrrgZH4O72wbGXvLbh5vYByPiHBSXQUC8voI2F5b_8TSgRWgMo1mv2VEYtV4lntjTvdxQiRPTeq_D8qyJ7F0XvNWa7b8LJ-S1UWfnKbLldvAQSbm6NMnHFr-NzQBk8k_N6qDawZXxob8r5s_T_BagOpjpGka1iuH6S0uhoUJ6fAm92X6uQK3JvtjGZ_VOcTKd6Ow84OFCVrq30ZHFiSzoJWypKmYk6AR68Hh1zhpRdA6b2nezPookIthqRhPoJSXlwpG6wpVewwi9qKP1uAKoJkQ5et9nqG4eVY74M',
            url: '<wrapped url>',
            optOutUrl: '<wrapped url>',
            buttonUrl: '<wrapped url>',
            surfaceUrl: '<wrapped url>',
            warning: undefined,
        },
        {
            name: "Телевизор LED LG 43' 43LJ510V",
            price: {
                value: 23178,
                currencyName: 'руб.',
                currencyCode: 'RUR',
            },
            category: {
                id: 90639,
                type: 'GURU',
                advertisingModel: 'CPA',
                name: 'Телевизоры',
            },
            target: 'price-list',
            bigPhoto: {
                url: 'https://avatars.mds.yandex.net/get-marketpic/163900/market_lQ_fiPrRgh-A69VqpyOlmg/orig',
                width: 800,
                height: 528,
            },
            shopInfo: {
                name: 'Techmela',
                rating: 4,
                id: 425757,
                gradeTotal: 10,
                url: '<wrapped url>',
            },
            delivery: {
                free: false,
                brief: 'в Москву — 500 руб., возможен самовывоз',
                price: {
                    value: '500',
                    currencyName: 'руб.',
                    currencyCode: 'RUR',
                },
                delivery: true,
            },
            photo: 'https://avatars.mds.yandex.net/get-marketpic/163900/market_lQ_fiPrRgh-A69VqpyOlmg/orig',
            source: 'Market',
            id:
                'yDpJekrrgZH4O72wbGXvLbh5vYByPiHBSXQUC8voI2F5b_8TSgRWgMo1mv2VEYtV4lntjTvdxQiRPTeq_D8qyJ7F0XvNWa7b8LJ-S1UWfnKbLldvAQSbm6NMnHFr-NzQBk8k_N6qDawZXxob8r5s_T_BagOpjpGka1iuH6S0uhoUJ6fAm92X6uQK3JvtjGZ_VOcTKd6Ow84OFCVrq30ZHFiSzoJWypKmYk6AR68Hh1zhpRdA6b2nezPookIthqRhPoJSXlwpG6wpVewwi9qKP1uAKoJkQ5et9nqG4eVY74M',
            url: '<wrapped url>',
            buttonUrl: '<wrapped url>',
            warning: undefined,
        },
        {
            name: 'Телевизор LG 43LJ510V',
            price: {
                value: 23410,
                currencyName: 'руб.',
                currencyCode: 'RUR',
            },
            category: {
                id: 90639,
                type: 'GURU',
                advertisingModel: 'CPA',
                name: 'Телевизоры',
            },
            target: 'price-list',
            shopInfo: {
                name: 'Assortiment-BT.ru',
                rating: 5,
                id: 197695,
                gradeTotal: 4556,
                url: '<wrapped url>',
            },
            delivery: {
                free: false,
                brief: 'в Москву — 450 руб.',
                price: {
                    value: '450',
                    currencyName: 'руб.',
                    currencyCode: 'RUR',
                },
                delivery: true,
            },
            source: 'Market',
            id:
                'yDpJekrrgZHyXZWnWVyppX1pD7ROqZxtC8EudWLIrgc3z8cRaVwB9v1Mctw-9WnTnQjbi547hD-NYDUumHb5TlFHHkyH091gJzCdneIdTy5k2x0haJ-rkrXmWiZ6Gk_8wciWgHlbTupgyk1REtU7oHCLXgB52Nw91U6NtQiRn6Kibe2zDJYZmx6tmixaBPBg0widqk23OWuzl0DgQh9J-JUII4WK0YyfvgkydFiScI0lTdL1SZUupkKMw1jczu2YtdhdFHgvImqzKigHZXMWFv0aNk77H3csAIF2ln5XxvU',
            url: '<wrapped url>',
            buttonUrl: '<wrapped url>',
            warning: undefined,
        },
        {
            name: 'LED Телевизор LG 43LJ510V',
            price: {
                value: 25180,
                currencyName: 'руб.',
                currencyCode: 'RUR',
            },
            category: {
                id: 90639,
                type: 'GURU',
                advertisingModel: 'CPA',
                name: 'Телевизоры',
            },
            target: 'price-list',
            bigPhoto: {
                url: 'https://avatars.mds.yandex.net/get-marketpic/206654/market_myG4UW7srrHrPHywu3JIHQ/orig',
                width: 300,
                height: 300,
            },
            shopInfo: {
                name: 'TechPort.ru',
                rating: 5,
                id: 1672,
                gradeTotal: 52893,
                url: '<wrapped url>',
            },
            delivery: {
                free: false,
                brief: 'в Москву — 500 руб., возможен самовывоз',
                price: {
                    value: '500',
                    currencyName: 'руб.',
                    currencyCode: 'RUR',
                },
                delivery: true,
            },
            photo: 'https://avatars.mds.yandex.net/get-marketpic/206654/market_myG4UW7srrHrPHywu3JIHQ/orig',
            source: 'Market',
            id:
                'yDpJekrrgZH673vrypnRFH5nNUQRhvsuTGdxg8l7pNET0e8wf8ZwUo1xqTJXJaGwWAyE-t9QJ5UvKivVf7_hlOQYKRkU5IsB9qF8ZCh9UMtqGtKvUumLpLJQTK0zp7d34pe1NZay_H3FMGylOdFBkMGsEF_R7lIFPLyJQd3r2jbAluYFqhYON-8qaLgkKw7a50_3meB5moohuzAxH5aarYunXNHXOKBPjqh00fmqaCAzsdwMDjlSf1jxA9O0Ctemnyn2sr9WZZAbii0CN-Sef4KJJSBzymjUL6Hfi67jzPE',
            url: '<wrapped url>',
            buttonUrl: '<wrapped url>',
            warning: undefined,
        },
        {
            name: "Телевизор LG 43LJ510V 43' Black, 16:9, 1920x1080, USB, 2xHDMI, AV, DVB-T2, C, S2",
            price: {
                value: 25990,
                currencyName: 'руб.',
                currencyCode: 'RUR',
            },
            category: {
                id: 90639,
                type: 'GURU',
                advertisingModel: 'CPA',
                name: 'Телевизоры',
            },
            target: 'price-list',
            bigPhoto: {
                url: 'https://avatars.mds.yandex.net/get-marketpic/163651/market_3ckrTop2mTduBU_DPJ8faw/orig',
                width: 900,
                height: 594,
            },
            shopInfo: {
                name: 'OLDI.RU',
                rating: 5,
                id: 12138,
                gradeTotal: 8543,
                url: '<wrapped url>',
            },
            delivery: {
                free: false,
                brief: 'в Москву — 290 руб., возможен самовывоз',
                price: {
                    value: '290',
                    currencyName: 'руб.',
                    currencyCode: 'RUR',
                },
                delivery: true,
            },
            photo: 'https://avatars.mds.yandex.net/get-marketpic/163651/market_3ckrTop2mTduBU_DPJ8faw/orig',
            source: 'Market',
            id:
                'yDpJekrrgZGSqhn4PcDKkq4xgMwp3EeH7-5k6XUxwd0K_yFqXTxxxAlFizCTJQ-deln16titBse72WqPanD91Cg1-T-WFYvGAjaQGqWX5xOUj4dGCuu3F9DtBvApGs3wKtyCmQ5Ju9e8uFOZZeUMwkQSkZdSLwPGrY3DsCzsDBKrzhY6C3Ftw6jf9N2wDtGsVyl894tWuqldRa3kNlK_S2mQ2GD9gmMBZ1Q4aOECNqQIfV2ljVyGszcmIcsGpaduLdYpK8lFlEShhnSOcPN6dLdK0iItu205U-vi-ItiR_0',
            url: '<wrapped url>',
            buttonUrl: '<wrapped url>',
            warning: undefined,
        },
        {
            name: "Телевизор lg 43' 43lj510v черный full hd/50hz/dvb-t2/dvb-c/dvb-s2/usb rus",
            price: {
                value: 23608,
                currencyName: 'руб.',
                currencyCode: 'RUR',
            },
            category: {
                id: 90639,
                type: 'GURU',
                advertisingModel: 'CPA',
                name: 'Телевизоры',
            },
            target: 'price-list',
            bigPhoto: {
                url: 'https://avatars.mds.yandex.net/get-marketpic/202108/market_kqLSBLdtNn0yXjnnB6N_ZQ/orig',
                width: 250,
                height: 250,
            },
            shopInfo: {
                name: 'ТехноГид',
                rating: 5,
                id: 108546,
                gradeTotal: 2725,
                url: '<wrapped url>',
            },
            delivery: {
                free: false,
                brief: 'в Москву — 300 руб., возможен самовывоз',
                price: {
                    value: '300',
                    currencyName: 'руб.',
                    currencyCode: 'RUR',
                },
                delivery: true,
            },
            photo: 'https://avatars.mds.yandex.net/get-marketpic/202108/market_kqLSBLdtNn0yXjnnB6N_ZQ/orig',
            source: 'Market',
            id: 'yDpJekrrgZGyHez37GLfcz0J8eu7H3XoH-P5NRrxIaEzIUwK1dYhZw',
            url: '<wrapped url>',
            buttonUrl: '<wrapped url>',
            warning: undefined,
        },
        {
            name: 'LED телевизор LG 43LJ510V',
            price: {
                value: 24000,
                currencyName: 'руб.',
                currencyCode: 'RUR',
            },
            category: {
                id: 90639,
                type: 'GURU',
                advertisingModel: 'CPA',
                name: 'Телевизоры',
            },
            target: 'price-list',
            bigPhoto: {
                url: 'https://avatars.mds.yandex.net/get-marketpic/175315/market_q7yYIghjG3MtxiiLtZyuBg/orig',
                width: 300,
                height: 199,
            },
            shopInfo: {
                name: 'Техника Быта',
                rating: 5,
                id: 23824,
                gradeTotal: 1661,
                url: '<wrapped url>',
            },
            delivery: {
                free: false,
                brief: 'в Москву — 600 руб.',
                price: {
                    value: '600',
                    currencyName: 'руб.',
                    currencyCode: 'RUR',
                },
                delivery: true,
            },
            photo: 'https://avatars.mds.yandex.net/get-marketpic/175315/market_q7yYIghjG3MtxiiLtZyuBg/orig',
            source: 'Market',
            id: 'yDpJekrrgZHta7MFbcmVMUXN-TCoiZGyU_B8339JW3ooSZaRfnPL6Q',
            url: '<wrapped url>',
            buttonUrl: '<wrapped url>',
            warning: undefined,
        },
    ],
    notification: undefined,
    bucketInfo: {},
    shopInfo: {
        shopName: 'ЭЛЬДОРАДО',
        rating: 5,
        url: '<wrapped url>',
        gradeTotal: 126436,
    },
    doNotSearchReason: undefined,
    optOutInfo: undefined,
    rules: undefined,
    searchInfo: {
        originalQuery: 'LED телевизор LG 43LJ510V',
        filteredQuery: 'LED телевизор LG 43LJ510V',
        doNotComparePrice: undefined,
        convertedPrice: {
            value: 25999,
            currencyCode: 'RUR',
        },
        category: undefined,
        offersCount: 67,
        urls: {
            shopsInfo: '<wrapped url>',
            market: '<wrapped url>',
            search:
                'https://market.yandex.ru/search.xml?text=LED%20%D1%82%D0%B5%D0%BB%D0%B5%D0%B2%D0%B8%D0%B7%D0%BE%D1%80%20LG%2043LJ510V&clid=2270459&distr_type=4&utm_source=sovetnik&utm_medium=cpc&utm_campaign=offer-title&cvredirect=2&req_id=jbow18xiiwmgiumhdpsntuwd0rxvty2l&lr=213',
            searchButton: '<wrapped url>',
            prices: '<wrapped url>',
            eula: '<wrapped url>',
            feedback: '<wrapped url>',
            help: '<wrapped url>',
            helpPhone: '<wrapped url>',
            helpTablet: '<wrapped url>',
            disable: '<wrapped url>',
            features: '<wrapped url>',
        },
        categories: [
            {
                id: 90639,
                name: 'Телевизоры',
                rank: 0.7319687003523168,
                url: '<wrapped url>',
            },
            {
                id: 10469630,
                name: 'Рекламные дисплеи и интерактивные панели',
                rank: -2.0509925072575053,
                url: '<wrapped url>',
            },
            {
                id: 90417,
                name: 'Автомобильные телевизоры',
                rank: -2.6996986050235723,
                url: '<wrapped url>',
            },
        ],
    },
    searchResult: undefined,
    searchResultCaption: undefined,
    settings: {
        autoShowShopList: true,
        applicationName: 'Советник Яндекс.Маркета',
        isMbrApplication: true,
        items: [
            {
                title: 'Показывать предложения из других регионов',
                enabled: true,
            },
            {
                title: 'Показывать список предложений при наведении мыши',
                enabled: true,
            },
        ],
        region: 'Москва',
        needShowNotifications: true,
        showProductNotifications: true,
        showAviaNotifications: true,
        showAutoNotifications: true,
    },
};
