"""
    Package with test for gencfg API and module,
    in this file we define test responses and other simulation data
"""

CARD_JSON = {'access': {'sshers': [], 'sudo_commands': [], 'sudoers': []},
             'audit': {'cpu': {'class_name': 'normal',
                               'extra_cpu': 0.0,
                               'greedy_limit': None,
                               'last_modified': '2017-08-14 10:35:43',
                               'min_cpu': 0.0,
                               'service_coeff': 1.1333,
                               'service_groups': [],
                               'suggest': {
                                   'at': 'Jun 25, 2018',
                                   'cpu': 1.0,
                                   'msg': 'Modify power: <6.00> => <0.28> for group with instance power already set'},
                               'traffic_coeff': 1.5},
                       'instances': {'min_instances': None},
                       'memory': {'last_modified': None}},
             'balancer': {'balancer_type': 'hashing', 'dnsname': None, 'enabled': False},
             'configs': {'balancer': {'module_name': None,
                                      'output_file': None,
                                      'params': None,
                                      'sub_module_name': None},
                         'basesearch': {'custom_name': None, 'jinja_params': [], 'template': None},
                         'enabled': False,
                         'intmetasearch': {'config_power': None}},
             'description': 'no description',
             'guest': {'hbf_project_id': 0,
                       'owners': [],
                       'port': 8041,
                       'tags': {'ctype': 'none', 'itype': 'none', 'metaprj': 'unknown', 'prj': []}},
             'host_donor': None,
             'host_donors': [],
             'intlookups': [],
             'legacy': {'funcs': {'instanceCount': 'default',
                                  'instanceMemory': None,
                                  'instancePort': 'old9010',
                                  'instancePower': 'exactly6'}},
             'master': 'ALL_HEAD_COMPILATION',
             'name': 'TICKENATOR',
             'nanny': {'services': [{'last_modified': '2018-06-18 13:23:28',
                                     'name': 'tickenator',
                                     'status': 'ONLINE',
                                     'tag': 'tags/stable-101-r88'}]},
             'on_update_trigger': None,
             'owners': [],
             'owners_abc_roles': [],
             'properties': {'allow_background_groups': True,
                            'allow_fast_download_queue': False,
                            'background_group': False,
                            'cpu_guarantee_set': True,
                            'created_at': 'May 30, 2017',
                            'created_from_portovm_group': None,
                            'expires': None,
                            'export_to_cauth': True,
                            'extra_disk_shards': 2,
                            'extra_disk_size': 0,
                            'extra_disk_size_per_instance': 0,
                            'fake_group': False,
                            'full_host_group': False,
                            'hbf_old_project_ids': [],
                            'hbf_parent_macros': '_GENCFG_TICKENATOR_',
                            'hbf_project_id': 17466607,
                            'hbf_range': '_GENCFG_SEARCHPRODNETS_ROOT_',
                            'hbf_resolv_conf': 'default',
                            'ignore_cpu_audit': False,
                            'internet_tunnel': False,
                            'ipip6_ext_tunnel': False,
                            'ipip6_ext_tunnel_pool_name': 'default',
                            'ipip6_ext_tunnel_v2': False,
                            'monitoring_golovan_port': 30997,
                            'monitoring_juggler_port': 30998,
                            'monitoring_ports_ready': True,
                            'mtn': {'export_mtn_to_cauth': False,
                                    'port': None,
                                    'portovm_mtn_addrs': False,
                                    'tunnels': {'hbf_decapsulator_anycast_address': '2a02:6b8:0:3400::aaaa',
                                                'hbf_slb_ipv4_mtu': 1450,
                                                'hbf_slb_ipv6_mtu': 1450,
                                                'hbf_slb_name': []},
                                    'use_mtn_in_config': False},
                            'mtn_fqdn_domain': None,
                            'mtn_fqdn_version': 0,
                            'nidx_for_group': None,
                            'nonsearch': True,
                            'security_segment': 'normal',
                            'unraisable_group': False,
                            'untouchable': False,
                            'yasmagent_prestable_group': False,
                            'yasmagent_production_group': True},
             'recluster': {'alloc_hosts': [],
                           'cleanup': [],
                           'generate_intlookups': [],
                           'next_stage': None},
             'reminders': [],
             'reqs': {'hosts': {'cpu_models': [],
                                'except_cpu_models': [],
                                'location': {'dc': [], 'location': []},
                                'max_per_switch': 0,
                                'memory': 0.0,
                                'ndisks': 0,
                                'netcard_regexp': None},
                      'instances': {'affinity_category': None,
                                    'disk': 3758096384.0,
                                    'max_per_host': 0,
                                    'memory_guarantee': 2147483648.0,
                                    'memory_overcommit': 104857600.0,
                                    'min_instances': 0,
                                    'min_per_host': 0,
                                    'net_guarantee': 0.0,
                                    'net_limit': 0.0,
                                    'port': 8041,
                                    'power': 0,
                                    'ssd': 0.0},
                      'shards': {'equal_instances_power': False,
                                 'max_replicas': 1000,
                                 'min_power': 6,
                                 'min_replicas': 1},
                      'volumes': [{'generate_deprecated_uuid': False,
                                   'guest_mp': '/',
                                   'host_mp_root': '/place',
                                   'mount_point_workdir': False,
                                   'quota': 1610612736.0,
                                   'shared': False,
                                   'symlinks': [],
                                   'uuid_generator_version': 2},
                                  {'generate_deprecated_uuid': False,
                                   'guest_mp': '',
                                   'host_mp_root': '/place',
                                   'mount_point_workdir': True,
                                   'quota': 1073741824.0,
                                   'shared': False,
                                   'symlinks': [],
                                   'uuid_generator_version': 2},
                                  {'generate_deprecated_uuid': False,
                                   'guest_mp': '/logs',
                                   'host_mp_root': '/place',
                                   'mount_point_workdir': False,
                                   'quota': 1073741824.0,
                                   'shared': False,
                                   'symlinks': ['/usr/local/www/logs'],
                                   'uuid_generator_version': 2}]},
             'resolved_owners': [],
             'resources': {'ninstances': 3},
             'searcherlookup_postactions': {'aline_tag': {'enabled': False},
                                            'conditional_tags': [],
                                            'copy_on_ssd_tag': {'enabled': False},
                                            'custom_tier': {'enabled': False, 'tier_name': ''},
                                            'fixed_hosts_tags': [],
                                            'gen_by_code_tags': [],
                                            'host_memory_tag': {'enabled': False},
                                            'int_with_snippet_reqs_tag': {'enabled': False},
                                            'pre_in_pre_tags': [],
                                            'replica_tags': {'enabled': False,
                                                             'first_replica_tag': None,
                                                             'tag_format': None},
                                            'shardid_tag': {'enabled': False,
                                                            'tag_format': None,
                                                            'tag_prefix': 'a_shard_',
                                                            'tags_format': [],
                                                            'write_primus_name': False}},
             'slaves': [],
             'tags': {'ctype': 'none',
                      'itag': [],
                      'itype': 'none',
                      'metaprj': 'other',
                      'prj': ['none']},
             'triggers': {'on_add_host': {'method': 'default'},
                          'on_rename_group': {'method': 'default'}},
             'walle': {'reinstall': {'max_reinstall_count': 0,
                                     'max_reinstall_percent': 0}},
             'watchers': [],
             'yp': {'endpointset': None}}

INSTANCES_JSON = {'instances': [{'dc': 'sas',
                                 'domain': '.search.yandex.net',
                                 'hbf': {'hbf_project_id': '10a84ef',
                                         'interfaces': {
                                             'backbone': {'hostname': 'sentinel-tickenator-9010.gencfg-c.yandex.net',
                                                          'ipv6addr': '2a02:6b8:c08:49e:10a:84ef:0:2332'},
                                             'fastbone': {'hostname': 'fb-sentinel-tickenator-9010.gencfg-c.yandex.net',
                                                          'ipv6addr': '2a02:6b8:fc00:49e:10a:84ef:0:2332'}},
                                         'mtn_ready': True,
                                         'resolv.conf': 'default'},
                                 'host_resources': {'disk': 1717,
                                                    'memory': 64,
                                                    'model': 'E5-2660',
                                                    'n_disks': 2,
                                                    'ncpu': 32,
                                                    'ssd': 440},
                                 'hostname': 'sentinel.search.yandex.net',
                                 'ipv4addr': None,
                                 'ipv6addr': '2a02:6b8:b000:108:225:90ff:fe88:ce16',
                                 'iss': {'allow_fast_download_queue': False},
                                 'location': 'sas',
                                 'monitoring': {'juggler': {'agent': {'port': 30998}},
                                                'yasm': {'agent': {'port': 30997}}},
                                 'port': 9010,
                                 'porto_limits': {'cpu_cores_guarantee': 0,
                                                  'cpu_cores_limit': 1.6991150442477876,
                                                  'cpu_guarantee': 0,
                                                  'cpu_limit': 5.3097345132743365,
                                                  'memory_guarantee': 2147483648,
                                                  'memory_limit': 2252341248,
                                                  'net_guarantee': 0,
                                                  'net_limit': 0},
                                 'power': 6.0,
                                 'queue': 'sas-1.3.3',
                                 'rack': '31',
                                 'secondary_ports': [],
                                 'security_segment': 'normal',
                                 'shard_name': 'none',
                                 'storages': {'rootfs': {'partition': 'hdd', 'size': 3.5}},
                                 'tags': ['TICKENATOR',
                                          'a_ctype_none',
                                          'a_dc_sas',
                                          'a_geo_sas',
                                          'a_itype_none',
                                          'a_line_sas-1.3.3',
                                          'a_metaprj_other',
                                          'a_prj_none',
                                          'a_tier_none',
                                          'a_topology_cgset-memory.limit_in_bytes=2252341248',
                                          'a_topology_cgset-memory.low_limit_in_bytes=2147483648',
                                          'a_topology_group-TICKENATOR',
                                          'a_topology_stable-126-r854',
                                          'a_topology_version-stable-126-r854',
                                          'cgset_memory_recharge_on_pgfault_1'],
                                 'volumes': [{'dom0_mount_point_root': '/place',
                                              'guest_mount_point': '/',
                                              'mount_point_workdir': False,
                                              'quota': 1610612736,
                                              'symlinks': [],
                                              'uuid': '0dcdc842b771'},
                                             {'dom0_mount_point_root': '/place',
                                              'guest_mount_point': '',
                                              'mount_point_workdir': True,
                                              'quota': 1073741824,
                                              'symlinks': [],
                                              'uuid': 'a8db4acaeaf6'},
                                             {'dom0_mount_point_root': '/place',
                                              'guest_mount_point': '/logs',
                                              'mount_point_workdir': False,
                                              'quota': 1073741824,
                                              'symlinks': ['/usr/local/www/logs'],
                                              'uuid': '908c1146c27e'}]},
                                {'dc': 'man',
                                 'domain': '.search.yandex.net',
                                 'hbf': {'hbf_project_id': '10a84ef',
                                         'interfaces': {
                                             'backbone': {'hostname': 'guardian-tickenator-9010.gencfg-c.yandex.net',
                                                          'ipv6addr': '2a02:6b8:c09:de3:10a:84ef:0:2332'},
                                             'fastbone': {'hostname': 'fb-guardian-tickenator-9010.gencfg-c.yandex.net',
                                                          'ipv6addr': '2a02:6b8:fc11:e63:10a:84ef:0:2332'}},
                                         'mtn_ready': True,
                                         'resolv.conf': 'default'},
                                 'host_resources': {'disk': 3458,
                                                    'memory': 256,
                                                    'model': 'E5-2650v2',
                                                    'n_disks': 3,
                                                    'ncpu': 32,
                                                    'ssd': 1759},
                                 'hostname': 'guardian.search.yandex.net',
                                 'ipv4addr': None,
                                 'ipv6addr': '2a02:6b8:b000:651e:e61d:2dff:fe6d:2030',
                                 'iss': {'allow_fast_download_queue': False},
                                 'location': 'man',
                                 'monitoring': {'juggler': {'agent': {'port': 30998}},
                                                'yasm': {'agent': {'port': 30997}}},
                                 'port': 9010,
                                 'porto_limits': {'cpu_cores_guarantee': 0,
                                                  'cpu_cores_limit': 1.4849187935034802,
                                                  'cpu_guarantee': 0,
                                                  'cpu_limit': 4.640371229698376,
                                                  'memory_guarantee': 2147483648,
                                                  'memory_limit': 2252341248,
                                                  'net_guarantee': 0,
                                                  'net_limit': 0},
                                 'power': 6.0,
                                 'queue': 'man-4_b.1.09',
                                 'rack': '4C4',
                                 'secondary_ports': [],
                                 'security_segment': 'normal',
                                 'shard_name': 'none',
                                 'storages': {'rootfs': {'partition': 'hdd', 'size': 3.5}},
                                 'tags': ['TICKENATOR',
                                          'a_ctype_none',
                                          'a_dc_man',
                                          'a_geo_man',
                                          'a_itype_none',
                                          'a_line_man-4_b.1.09',
                                          'a_metaprj_other',
                                          'a_prj_none',
                                          'a_tier_none',
                                          'a_topology_cgset-memory.limit_in_bytes=2252341248',
                                          'a_topology_cgset-memory.low_limit_in_bytes=2147483648',
                                          'a_topology_group-TICKENATOR',
                                          'a_topology_stable-126-r854',
                                          'a_topology_version-stable-126-r854',
                                          'cgset_memory_recharge_on_pgfault_1'],
                                 'volumes': [{'dom0_mount_point_root': '/place',
                                              'guest_mount_point': '/',
                                              'mount_point_workdir': False,
                                              'quota': 1610612736,
                                              'symlinks': [],
                                              'uuid': '56bf928e8183'},
                                             {'dom0_mount_point_root': '/place',
                                              'guest_mount_point': '',
                                              'mount_point_workdir': True,
                                              'quota': 1073741824,
                                              'symlinks': [],
                                              'uuid': '750e835c018c'},
                                             {'dom0_mount_point_root': '/place',
                                              'guest_mount_point': '/logs',
                                              'mount_point_workdir': False,
                                              'quota': 1073741824,
                                              'symlinks': ['/usr/local/www/logs'],
                                              'uuid': '9a389ee4da41'}]},
                                {'dc': 'myt',
                                 'domain': '.search.yandex.net',
                                 'hbf': {'hbf_project_id': '10a84ef',
                                         'interfaces': {
                                             'backbone': {'hostname': 'watchman-tickenator-9010.gencfg-c.yandex.net',
                                                          'ipv6addr': '2a02:6b8:c00:47d:10a:84ef:0:2332'},
                                             'fastbone': {'hostname': 'fb-watchman-tickenator-9010.gencfg-c.yandex.net',
                                                          'ipv6addr': '2a02:6b8:fc10:47d:10a:84ef:0:2332'}},
                                         'mtn_ready': True,
                                         'resolv.conf': 'default'},
                                 'host_resources': {'disk': 3458,
                                                    'memory': 256,
                                                    'model': 'E5-2650v2',
                                                    'n_disks': 3,
                                                    'ncpu': 32,
                                                    'ssd': 1649},
                                 'hostname': 'watchman.search.yandex.net',
                                 'ipv4addr': None,
                                 'ipv6addr': '2a02:6b8:b000:a037:92e2:baff:fea3:73e8',
                                 'iss': {'allow_fast_download_queue': False},
                                 'location': 'msk',
                                 'monitoring': {'juggler': {'agent': {'port': 30998}},
                                                'yasm': {'agent': {'port': 30997}}},
                                 'port': 9010,
                                 'porto_limits': {'cpu_cores_guarantee': 0,
                                                  'cpu_cores_limit': 1.4849187935034802,
                                                  'cpu_guarantee': 0,
                                                  'cpu_limit': 4.640371229698376,
                                                  'memory_guarantee': 2147483648,
                                                  'memory_limit': 2252341248,
                                                  'net_guarantee': 0,
                                                  'net_limit': 0},
                                 'power': 6.0,
                                 'queue': 'myt-3',
                                 'rack': '34',
                                 'secondary_ports': [],
                                 'security_segment': 'normal',
                                 'shard_name': 'none',
                                 'storages': {'rootfs': {'partition': 'hdd', 'size': 3.5}},
                                 'tags': ['TICKENATOR',
                                          'a_ctype_none',
                                          'a_dc_myt',
                                          'a_geo_msk',
                                          'a_itype_none',
                                          'a_line_myt-3',
                                          'a_metaprj_other',
                                          'a_prj_none',
                                          'a_tier_none',
                                          'a_topology_cgset-memory.limit_in_bytes=2252341248',
                                          'a_topology_cgset-memory.low_limit_in_bytes=2147483648',
                                          'a_topology_group-TICKENATOR',
                                          'a_topology_stable-126-r854',
                                          'a_topology_version-stable-126-r854',
                                          'cgset_memory_recharge_on_pgfault_1'],
                                 'volumes': [{'dom0_mount_point_root': '/place',
                                              'guest_mount_point': '/',
                                              'mount_point_workdir': False,
                                              'quota': 1610612736,
                                              'symlinks': [],
                                              'uuid': '673162e794fe'},
                                             {'dom0_mount_point_root': '/place',
                                              'guest_mount_point': '',
                                              'mount_point_workdir': True,
                                              'quota': 1073741824,
                                              'symlinks': [],
                                              'uuid': 'aaed7203344c'},
                                             {'dom0_mount_point_root': '/place',
                                              'guest_mount_point': '/logs',
                                              'mount_point_workdir': False,
                                              'quota': 1073741824,
                                              'symlinks': ['/usr/local/www/logs'],
                                              'uuid': 'd7062b98fe65'}]}]}
