--liquibase formatted sql
--changeset vsubhuman:VNDMARKET-419_create_billing_view_test_metrics_table
CREATE TABLE CS_BILLING_TMS.FAST_BILLING_VIEW_TEST
(
  OP_DATE DATE DEFAULT SYSDATE NOT NULL,
  CS_ID NUMBER NOT NULL,
  OLD_VIEW_MILLIS NUMBER NOT NULL,
  NEW_VIEW_MILLIS NUMBER NOT NULL,
  IS_EQUAL NUMBER(1) NOT NULL,
  CONSTRAINT PK_FAST_BILLING_VIEW_TEST PRIMARY KEY (OP_DATE, CS_ID),
  CONSTRAINT FAST_BILLING_VIEW_TEST_FLAG CHECK (IS_EQUAL IN (0,1))
)
TABLESPACE CSB_DTS;

GRANT SELECT, INSERT, UPDATE, DELETE ON CS_BILLING_TMS.FAST_BILLING_VIEW_TEST TO CS_BILLING;

--rollback DROP TABLE CS_BILLING_TMS.FAST_BILLING_VIEW_TEST;